# GENERATED by dev/conditions-census-gen.R in the frmtmb
# repository, from dev/conditions-census-template.R.
# Edit the template, not this file.
#
# Every error, warning and message that this package raises itself goes
# through frmtmb::frm_stop(), frm_warning() or frm_message(), so that it
# carries the classed condition brms keeps as `brms_error`
# (?frmtmb::frmtmb-conditions).
# This census parses every R source file under R/ and inst/ and fails on
# a bare stop(), warning() or message(), on the same functions called
# through `base::`, on one passed as a value (`error = stop`), named to
# do.call(), get() or match.fun(), or built into a call or into code
# text, and on the base functions that raise a condition themselves
# (.Deprecated(), .signalSimpleWarning()), unless the site is in the
# exemption list below with its reason in the generator. An exemption
# excuses one site each time it is listed, and a stale exemption fails
# too, so the list cannot outlive the code it excuses.

census_exempt <- c(
  character(0))

census_kinds <- c("stop", "warning", "message")
# base functions that signal a base condition of their own
census_raisers <- c(".Deprecated", ".Defunct", ".signalSimpleWarning",
                    ".dfltStop", ".dfltWarn")
# functions that find a function from its name
census_lookups <- c("get", "get0", "mget", "match.fun",
                    "getExportedValue", "dynGet")
# functions that build a call, or code, from a name or from text.
# as.name() and as.symbol() are not here: a symbol alone raises nothing,
# and `identical(h, as.name("stop"))` is an ordinary test of a call head.
# They are caught where they become a call, inside as.call().
census_builders <- c("call", "as.call", "str2lang", "str2expression",
                     "parse")
# a call of one of the three in code text; `frm_stop(` does not match
census_code_rx <- "(^|[^A-Za-z0-9._])(stop|warning|message)[[:space:]]*[(]"

# Known false positives, which fail loudly and take an exemption:
# `get("warning", envir = e)` for an object named `warning` in `e`, since
# with the default `inherits = TRUE` it can reach base's function, and a
# string of code text such as `"message(x)"` that is never evaluated.

# The name of the function a call head refers to, through `::` and `:::`.
census_fname <- function(h) {
  if (is.name(h)) return(as.character(h))
  if (is.call(h) && length(h) == 3L &&
      (identical(h[[1L]], as.name("::")) ||
       identical(h[[1L]], as.name(":::")))) {
    return(as.character(h[[3L]]))
  }
  ""
}

# The names a top-level expression binds for itself: the left side of an
# assignment, a formal argument and a `for` variable. Inside that
# expression such a name is a local object, not base's function, so it
# is not flagged as a value, a lookup or a builder. A CALL of one of the
# three condition functions is flagged whatever is bound.
census_locals <- function(e) {
  out <- character(0)
  rec <- function(x) {
    if (!is.call(x) && !is.pairlist(x)) return(invisible(NULL))
    if (is.call(x) && is.name(x[[1L]])) {
      hd <- as.character(x[[1L]])
      if (hd %in% c("<-", "=", "<<-") && length(x) == 3L &&
          is.name(x[[2L]])) {
        out <<- c(out, as.character(x[[2L]]))
      }
      if (hd == "function" && is.pairlist(x[[2L]])) {
        out <<- c(out, names(x[[2L]]))
      }
      if (hd == "for" && is.name(x[[2L]])) {
        out <<- c(out, as.character(x[[2L]]))
      }
    }
    xs <- as.list(x)
    for (i in seq_along(xs)) {
      if (identical(xs[[i]], quote(expr = ))) next
      a <- xs[[i]]
      if (is.call(a) || is.pairlist(a)) rec(a)
    }
    invisible(NULL)
  }
  rec(e)
  unique(out)
}

# Whether code text parses to formulas only, which are data and are not
# evaluated as calls.
census_formula_text <- function(a) {
  p <- tryCatch(parse(text = a, keep.source = FALSE),
                error = function(err) NULL)
  length(p) > 0L &&
    all(vapply(p, function(x) {
      is.call(x) && identical(x[[1L]], as.name("~"))
    }, NA))
}

# Whether a call names a condition function by symbol, as in
# as.name("stop"), as.symbol("warning") or quote(message).
census_names_kind <- function(e) {
  if (!is.call(e)) return(FALSE)
  fn <- census_fname(e[[1L]])
  if (fn %in% c("as.name", "as.symbol") && length(e) >= 2L &&
      is.character(e[[2L]]) && any(e[[2L]] %in% census_kinds)) {
    return(TRUE)
  }
  if (fn == "quote" && length(e) == 2L && is.name(e[[2L]]) &&
      as.character(e[[2L]]) %in% census_kinds) {
    return(TRUE)
  }
  xs <- as.list(e)[-1L]
  for (i in seq_along(xs)) {
    if (identical(xs[[i]], quote(expr = ))) next
    if (census_names_kind(xs[[i]])) return(TRUE)
  }
  FALSE
}

# One record per site: "file | enclosing top-level name | call". The
# enclosing name is the object a top-level `<-` assigns, which is how a
# site is named in the exemption list without a line number to drift.
census_sites <- function(exprs, file) {
  out <- character(0)
  owner <- ""
  locals <- character(0)
  add <- function(what) {
    out <<- c(out, paste(file, owner, what, sep = " | "))
  }
  walk <- function(e) {
    if (!is.call(e)) return(invisible(NULL))
    h <- e[[1L]]
    fn <- census_fname(h)
    bare <- fn %in% c(census_kinds, census_raisers)
    if (bare) {
      add(paste(deparse(e, width.cutoff = 500L), collapse = " "))
    }
    args <- as.list(e)[-1L]
    nms <- names(args)
    if (is.null(nms)) nms <- rep("", length(args))
    local_head <- is.name(h) && fn %in% locals
    # do.call() matches `what` by name first, so it can sit anywhere;
    # unnamed, it is the first positional argument
    if (fn == "do.call" && !local_head && length(args)) {
      w <- if ("what" %in% nms) which(nms == "what")[1L] else
        which(nms == "")[1L]
      a <- if (!is.na(w)) args[[w]]
      if (is.character(a) && length(a) == 1L && a %in% census_kinds) {
        add(paste0("<do.call> ", a))
      }
    }
    if (fn == "as.call" && !local_head && census_names_kind(e)) {
      add("<as.call> a condition function by name")
    }
    for (i in seq_along(args)) {
      if (identical(args[[i]], quote(expr = ))) next
      a <- args[[i]]
      if (!is.character(a) || local_head) next
      if (fn %in% census_lookups && any(a %in% census_kinds)) {
        add(paste0("<", fn, "> ", a[a %in% census_kinds][1L]))
      }
      if (fn %in% census_builders &&
          (any(a %in% census_kinds) ||
           (any(grepl(census_code_rx, a)) && !census_formula_text(a)))) {
        add(paste0("<", fn, "> ", a[1L]))
      }
    }
    # the right-hand side of `$` and `@` is a slot name, not a function
    skip_rhs <- is.name(h) && as.character(h) %in% c("$", "@")
    # the left-hand side of an assignment is the name being bound
    skip_lhs <- is.name(h) && as.character(h) %in% c("<-", "=", "<<-")
    args <- as.list(e)
    for (i in seq_along(args)[-1L]) {
      if (skip_rhs && i == 3L) next
      if (skip_lhs && i == 2L && is.name(args[[i]])) next
      # an empty argument (`x[, 1]`, a formal with no default) errors
      # once it is bound to a name, so it is tested before binding
      if (identical(args[[i]], quote(expr = ))) next
      a <- args[[i]]
      # the formals of `function`, whose defaults are code too
      if (is.pairlist(a) && length(a)) {
        walk(as.call(c(list(as.name("list")), as.list(a))))
        next
      }
      if (is.name(a) && as.character(a) %in%
          c(census_kinds, census_raisers) &&
          !as.character(a) %in% locals) {
        add(paste0("<value> ", as.character(a)))
      } else if (is.call(a)) {
        walk(a)
      }
    }
    if (is.call(h) && !bare) walk(h)
    invisible(NULL)
  }
  for (e in exprs) {
    owner <- if (is.call(e) && as.character(e[[1L]])[1L] %in%
                 c("<-", "=") && is.name(e[[2L]])) {
      as.character(e[[2L]])
    } else ""
    # the top-level name itself is a binding of the file, not a local
    locals <- setdiff(census_locals(e), owner)
    walk(e)
  }
  out
}

# Sites the exemptions do not excuse, and exemptions no site uses. Each
# listing of an exemption excuses one site, so a second site with the
# same key is caught rather than merged into the first.
census_compare <- function(sites, exempt) {
  keys <- union(sites, exempt)
  n_site <- vapply(keys, function(k) sum(sites == k), 0L)
  n_ex <- vapply(keys, function(k) sum(exempt == k), 0L)
  list(bare = rep(keys, pmax(n_site - n_ex, 0L)),
       stale = rep(keys, pmax(n_ex - n_site, 0L)))
}

# R CMD INSTALL reads R code from these extensions, and from R/unix and
# R/windows as well as R/ itself
census_file_rx <- "[.]([RrSsq])$"

test_that("the census finds what it is looking for", {
  # the absent case, built rather than hoped for: every shape the census
  # claims to catch is caught, and the shapes it must not flag are not
  planted <- parse(text = c(
    "f <- function(x) { if (x) stop(\"a\"); x }",
    "g <- function() base::warning(\"b\")",
    "h <- function() tryCatch(1, error = stop)",
    "k <- function() do.call(\"message\", list(\"c\"))",
    "m <- function(on_error = warning) on_error(\"e\")",
    "n <- function() do.call(args = list(\"p\"), what = \"stop\")",
    "o <- function() get(\"warning\")(\"p\")",
    "p <- function() match.fun(\"stop\")(\"p\")",
    "q <- function() eval(call(\"stop\", \"p\"))",
    "r <- function() eval(str2lang(\"warning('p')\"))",
    "s <- function() eval(parse(text = \"base::stop('p')\"))",
    "t <- function() .Deprecated(\"new_fn\")",
    "u <- function() .signalSimpleWarning(\"p\", NULL)",
    "v <- function() Map(message, \"p\")",
    "w <- function() eval(as.call(list(as.name(\"stop\"), \"p\")))",
    "x <- function(message) { stop(message) }",
    paste0("ok <- function(e) { frm_stop(\"d\"); e$message; ",
           "list(message = 1); get(\"x\"); call(\"frm_stop\", 1); ",
           "parse(text = \"frm_warning('a')\"); do.call(what = \"sum\", ",
           "args = list(\"stop\")) }")),
    keep.source = FALSE)
  got <- census_sites(planted, "planted.R")
  expect_identical(
    sub(" [|] .*$", "", sub("^planted[.]R [|] ", "", got)),
    c("f", "g", "h", "k", "m", "n", "o", "p", "q", "r", "s", "t", "u",
      "v", "w", "x"))
  # legitimate shapes the census used to flag: a local object or formal
  # with a condition function's name, a local function named like a
  # lookup or a builder, a symbol compared with a call head, and code
  # text that is a formula
  clean <- parse(text = c(
    "a <- function(x) { message <- paste(\"a\", x); frm_stop(message) }",
    "b <- function(message) list(message = message)",
    "c1 <- function(k) { get <- function(k) k; get(\"message\") }",
    "d <- function(h) identical(h, as.name(\"stop\"))",
    "e <- function() { call <- function(x) x; call(\"stop\") }",
    "f <- function() str2lang(\"y ~ message(x)\")"),
    keep.source = FALSE)
  expect_identical(census_sites(clean, "clean.R"), character(0))
  # one exemption excuses one site: the second of two identical sites is
  # reported, and an exemption with no site is stale
  twice <- c("R/a.R | f | stop(e)", "R/a.R | f | stop(e)")
  cmp <- census_compare(twice, "R/a.R | f | stop(e)")
  expect_identical(cmp$bare, "R/a.R | f | stop(e)")
  expect_identical(cmp$stale, character(0))
  cmp <- census_compare(character(0), "R/a.R | f | stop(e)")
  expect_identical(cmp$stale, "R/a.R | f | stop(e)")
  expect_identical(census_compare(twice, rep("R/a.R | f | stop(e)", 2L)),
                   list(bare = character(0), stale = character(0)))
  # the file pattern takes every extension R CMD INSTALL reads as R code
  expect_identical(grepl(census_file_rx, c("a.R", "a.r", "a.S", "a.s",
                                           "a.q", "a.Rd", "a.rda")),
                   c(TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE))
})

test_that("frmtmb.spline raises no bare stop(), warning() or message()", {
  # An installed package has a DESCRIPTION and an R/ directory too, and
  # its Meta/ directory is what tells it apart; under R CMD check the
  # tests run where neither exists. Both skip. A SOURCE tree is
  # recognised without the anchor file, and the anchor is then asserted,
  # so renaming it fails the census instead of skipping it.
  root <- testthat::test_path("..", "..")
  rdir <- file.path(root, "R")
  desc <- file.path(root, "DESCRIPTION")
  is_src <- file.exists(desc) && dir.exists(rdir) &&
    !dir.exists(file.path(root, "Meta")) &&
    identical(unname(read.dcf(desc, fields = "Package")[1L, 1L]), "frmtmb.spline")
  skip_if_not(is_src,
              "package sources are not available (installed-package run)")
  expect_true(file.exists(file.path(rdir, "frmtmb.spline-package.R")),
              label = "the anchor file R/frmtmb.spline-package.R exists")

  files <- sort(list.files(rdir, pattern = census_file_rx,
                           recursive = TRUE))
  expect_gt(length(files), 0L)
  sites <- character(0)
  for (f in files) {
    sites <- c(sites, census_sites(
      parse(file.path(rdir, f), keep.source = FALSE, encoding = "UTF-8"),
      file.path("R", f)))
  }
  # R code shipped in inst/, such as the worked-example families the
  # vignettes source, raises refusals a user meets just the same
  idir <- file.path(root, "inst")
  for (f in sort(list.files(idir, pattern = census_file_rx,
                            recursive = TRUE))) {
    sites <- c(sites, census_sites(
      parse(file.path(idir, f), keep.source = FALSE, encoding = "UTF-8"),
      file.path("inst", f)))
  }
  cmp <- census_compare(sites, census_exempt)
  expect_identical(cmp$bare, character(0),
                   info = paste0("Raise through frm_stop(), frm_warning() ",
                                 "or frm_message(); see ",
                                 "?frmtmb::frm_stop.\n",
                                 paste(cmp$bare, collapse = "\n")))
  expect_identical(cmp$stale, character(0),
                   info = paste(cmp$stale, collapse = "\n"))
})
