# Route 3: an exact first-passage density for THREE alternatives, by the
# method of images.
#
# Geometry (see common.R). Three accumulators, only relative evidence
# decides, so the reduced process is isotropic 2-D Brownian motion with
# drift a = U'mu, absorbed on the boundary of the EQUILATERAL triangle
# T = {z : <n_k, z> < r}, inradius r = c*sqrt(3/2), side L = 2*sqrt(3)*r.
#
# WHY THIS CLOSES. The group generated by reflections in the three sides of
# an equilateral triangle is the affine Weyl group of A2. It tiles the plane
# and T is its fundamental domain, so the Dirichlet heat kernel on T is the
# ALTERNATING sum of free heat kernels over the orbit of the source:
#
#   q(z, t | z0) = sum_g det(g) G_t(z - g z0),   G_t(w) = e^{-|w|^2/2t}/2 pi t
#
# Drift is a Girsanov tilt, p = exp(<a, z - z0> - |a|^2 t / 2) q, exact
# because q vanishes on the boundary. The defective density for choice k is
# the outward flux through side k, -1/2 int_side d_n p, and the integral
# along the side is Gaussian, so it is a difference of two normal
# distribution functions. Everything is elementary.
#
# WHY IT STOPS AT THREE. The continuation region for n alternatives is a
# regular (n-1)-simplex. Only for n = 3 is that a reflection-group alcove:
# the regular tetrahedron does not tile 3-space by reflections, and its
# Dirichlet spectrum is not known in closed form either. So this route is
# exactly three alternatives and nothing else.
#
# WHY THE GROUP ELEMENTS ARE DATA. R_k(z) = (I - 2 n_k n_k') z + 2 r n_k, so
# every group element is g(z) = A_g z + r w_g with A_g and w_g independent
# of every parameter. The boundary r, the start z0 and the drift a all enter
# the closed form smoothly. That is what makes it tapeable.

# Unit normals and tangents of the base triangle, from the reduced geometry.
gd_tri_geom <- function() {
  V <- gd_normals(3L)$V              # 2 x 3, columns v_k
  nk <- V / sqrt(sum(V[, 1L]^2))     # unit normals
  mk <- rbind(-nk[2L, ], nk[1L, ])   # tangents, n rotated by +90 degrees
  list(n = nk, m = mk, scale = sqrt(sum(V[, 1L]^2)))  # r = c / scale
}

# Breadth-first unfolding of the reflection group. Returns one row per tile:
# the 2x2 linear part flattened, the translation direction, and the sign.
# Ordered by |w|, so truncating the table truncates by distance.
gd_tiles <- function(max_tiles = 400L) {
  g <- gd_tri_geom()
  M <- lapply(1:3, function(k) diag(2) - 2 * outer(g$n[, k], g$n[, k]))
  A <- list(diag(2)); w <- list(c(0, 0)); s <- 1
  key <- function(v) paste(round(v, 8), collapse = ",")
  seen <- new.env(parent = emptyenv()); assign(key(c(0, 0)), TRUE, seen)
  head <- 1L
  while (head <= length(A) && length(A) < max_tiles) {
    Ah <- A[[head]]; wh <- w[[head]]; sh <- s[head]
    for (k in 1:3) {
      # (g o R_k)(z) = A(M_k z + 2 r n_k) + r w = (A M_k) z + r (w + 2 A n_k)
      A2 <- Ah %*% M[[k]]
      w2 <- wh + 2 * as.numeric(Ah %*% g$n[, k])
      kk <- key(w2)
      if (!is.null(seen[[kk]])) next
      assign(kk, TRUE, seen)
      A <- c(A, list(A2)); w <- c(w, list(w2)); s <- c(s, -sh)
    }
    head <- head + 1L
  }
  ord <- order(vapply(w, function(v) sum(v^2), numeric(1)))
  list(A = A[ord], w = do.call(rbind, w)[ord, , drop = FALSE], sgn = s[ord],
       geom = g)
}

# Defective first-passage density for choice k, on a vector of DECISION
# times t (already net of any non-decision time). Works on plain numbers and
# on RTMB advectors alike.
#
#   a   drift in reduced coordinates, length 2
#   z0  start in reduced coordinates, length 2
#   r   inradius of the triangle
#   tl  a gd_tiles() table, or a prefix of one
gd_img_density <- function(t, a, z0, r, tl, k) {
  gg <- tl$geom
  nk <- gg$n[, k]; mk <- gg$m[, k]
  L <- 2 * sqrt(3) * r
  beta <- a[1L] * nk[1L] + a[2L] * nk[2L]
  alph <- a[1L] * mk[1L] + a[2L] * mk[2L]
  az0 <- a[1L] * z0[1L] + a[2L] * z0[2L]
  st <- sqrt(t)
  acc <- t * 0
  for (i in seq_along(tl$sgn)) {
    Ai <- tl$A[[i]]; wi <- tl$w[i, ]
    y1 <- Ai[1L, 1L] * z0[1L] + Ai[1L, 2L] * z0[2L] + r * wi[1L]
    y2 <- Ai[2L, 1L] * z0[1L] + Ai[2L, 2L] * z0[2L] + r * wi[2L]
    h <- y1 * nk[1L] + y2 * nk[2L]
    b <- y1 * mk[1L] + y2 * mk[2L]
    gap <- r - h
    acc <- acc + tl$sgn[i] * gap *
      exp(-gap * gap / (2 * t) + alph * b) *
      (RTMB::pnorm((L / 2 - b - alph * t) / st) -
       RTMB::pnorm((-L / 2 - b - alph * t) / st))
  }
  # Outer factor: the Girsanov tilt, the flux prefactor 1/2t, the 1/2 pi t
  # of the free kernel and the sqrt(2 pi t) the Gaussian integral along the
  # side leaves behind, which together are 1 / (2 t sqrt(2 pi t)). The
  # -|a|^2 t/2 of the tilt and the +alpha^2 t/2 of that integral combine to
  # -beta^2 t/2, because beta and alpha are the normal and tangential parts
  # of the same drift.
  exp(-az0 + r * beta - beta * beta * t / 2) / (2 * t * sqrt(2 * pi * t)) * acc
}

# All three, as a list.
gd_img_all <- function(t, a, z0, r, tl) {
  lapply(1:3, function(k) gd_img_density(t, a, z0, r, tl, k))
}
