.libPaths(c('C:/Users/adf44/source/r/rellib-r3', 'C:/Users/adf44/source/r/pinlib', 'C:/Users/adf44/AppData/Local/R/win-library/4.6'))
suppressPackageStartupMessages(library(frmtmb))

f <- function() message("note")
zz <- textConnection("cap", "w")
sink(zz, type = "message")
f()
sink(type = "message")
close(zz)
print(cap)
