# GENERATED by dev/brmsport-gen.R from brms 2.23.0
# tests/testthat/tests.brmsfit-helpers.R. Do not edit by hand: change
# dev/brmsport-verdicts.tsv or the generator, then regenerate.
# helper-brms-suite.R says what brms_port() asserts.

skip_unless_brms_suite()
epilepsy <- brms::epilepsy

test_that("probit and probit_approx produce similar results", {
  brms_port_not_run("brmsfit-helpers:17", "cannot transfer",
    paste0(
      "compares brms:::inv_link() with itself on two link names; ",
      "frmtmb has no inv_link()"),
    "reaches brms's own namespace"
  )
  # expect_equal(brms:::inv_link(-10:10, "probit"),
  #                brms:::inv_link(-10:10, "probit_approx"),
  #                tolerance = 1e-3)
})

test_that("make_conditions works correctly", {
  brms_setup("brmsfit-helpers:93",
    conds <- make_conditions(epilepsy, c("zBase", "zAge"))
  )
  brms_port("brmsfit-helpers:94", "cannot transfer",
    "frmtmb exports no make_conditions()",
    expect_equal(dim(conds), c(9, 3))
  )
  brms_port("brmsfit-helpers:95", "cannot transfer",
    "frmtmb exports no make_conditions()",
    expect_equal(conds$cond__[3], "zBase = -1 & zAge = 1")
  )
})
