# Paste the generated ledger summary into dev/brmsport-findings.md,
# verbatim, between its markers.
#
#   Rscript dev/adefects-paste-ledger.R
#
# WHY A SCRIPT. dev/lane-rules.md: emit counts from the summariser into
# a marked block and paste that block verbatim, never type them. The
# figures in that record are the ported tier's, and this lane moved
# eight of them.
f <- "dev/brmsport-findings.md"
ln <- readLines(f, warn = FALSE)
b <- grep("^<!-- BEGIN GENERATED: dev/brmsport-ledger.R -->$", ln)
e <- grep("^<!-- END GENERATED -->$", ln)
stopifnot(length(b) == 1L, length(e) >= 1L)
e <- e[e > b][1L]
sm <- readLines("dev/brmsport-log/ledger-summary.md", warn = FALSE)
# the summariser's own header line is a comment about itself, not part
# of the block
sm <- sm[!grepl("^<!-- generated by", sm)]
out <- c(ln[seq_len(b)], sm, ln[e:length(ln)])
writeLines(out, f)
cat("pasted", length(sm), "lines into", f, "\n")
