## Render every Rd this lane touched and grep the OUTPUT, because `%`
## starts a comment in Rd even inside verbatim macros and reading the
## source does not show what was dropped (dev/lane-rules.md).
##
## roxygen2 writes two `%` comment lines at the top of every file it
## generates, so a raw count of unescaped signs is 2 on a clean file and
## a summary line that fires on "greater than zero" is UNCONDITIONAL and
## says nothing. Those two header lines are excluded and the per-file
## count is the instrument: it moves to 1 on the first author `%`.
.libPaths(c("C:/Users/adf44/source/r/brmsmatch-lib",
            "C:/Users/adf44/source/r/rellib-r3",
            "C:/Users/adf44/source/r/pinlib",
            "C:/Users/adf44/AppData/Local/R/win-library/4.6"))
man <- file.path("C:/Users/adf44/source/r/frmtmb-wt-brmsmatch",
                 "extensions/frmtmb.sample/man")
files <- c("draws-diagnostics.Rd", "posterior_epred.Rd",
           "sample-posterior_summary.Rd", "pp_mixture.Rd",
           "log_lik.Rd", "sample-as_draws.Rd", "sample-loo.Rd")

## An author writes a percent sign ESCAPED, as `\%`; an unescaped one
## starts a comment and silently swallows the rest of its line. So two
## numbers matter per file, and roxygen's own `%` header lines are not
## either of them.
counts <- function(src) {
  body <- src[!grepl("^%", src)]
  n <- function(re) sum(vapply(gregexpr(re, body, perl = TRUE),
                               function(m) sum(m > 0), 0L))
  c(escaped = n("\\\\%"), unescaped = n("(?<!\\\\)%"))
}
rendered_pct <- function(txt) {
  sum(vapply(gregexpr("%", txt, fixed = TRUE),
             function(m) sum(m > 0), 0L))
}

bad <- 0L
for (f in files) {
  p <- file.path(man, f)
  src <- readLines(p, warn = FALSE)
  out <- tempfile()
  tools::Rd2txt(p, out = out)
  txt <- readLines(out, warn = FALSE)
  k <- counts(src)
  got <- rendered_pct(txt)
  ok <- k[["unescaped"]] == 0L && got == k[["escaped"]]
  cat(sprintf("%-30s escaped=%d unescaped=%d rendered=%d  %s\n",
              f, k[["escaped"]], k[["unescaped"]], got,
              if (ok) "ok" else "DEFECT"))
  if (!ok) bad <- bad + 1L
}
cat("files with a dropped or unescaped percent sign: ", bad, "\n")

## Both inverse cases, so neither branch is unreachable. An UNESCAPED
## sign must be counted as such and must vanish from the render; an
## ESCAPED one must be counted as such and must survive it.
probe <- function(line) {
  tmp <- tempfile(fileext = ".Rd")
  writeLines(c("% Generated by roxygen2: do not edit by hand",
               "\\name{zz}", "\\alias{zz}", "\\title{zz}",
               paste0("\\description{", line, "}"),
               "\\keyword{internal}"), tmp)
  out <- tempfile()
  tools::Rd2txt(tmp, out = out)
  c(counts(readLines(tmp)),
    rendered = rendered_pct(readLines(out, warn = FALSE)))
}
u <- probe("a 50% drop.")
e <- probe("a 50\\% drop.")
cat(sprintf("control UNESCAPED: escaped=%d unescaped=%d rendered=%d\n",
            u[["escaped"]], u[["unescaped"]], u[["rendered"]]))
cat(sprintf("control ESCAPED:   escaped=%d unescaped=%d rendered=%d\n",
            e[["escaped"]], e[["unescaped"]], e[["rendered"]]))
cat("fires on an unescaped sign:      ",
    u[["unescaped"]] > 0L && u[["rendered"]] < 1L, "\n")
cat("does not fire on an escaped one: ",
    e[["unescaped"]] == 0L && e[["rendered"]] == e[["escaped"]], "\n")
cat("DONE\n")
