.libPaths("C:/Users/adf44/AppData/Local/R/win-library/4.6")
suppressMessages(library(brms))
print(args(brms::mm))
set.seed(45)
d <- data.frame(x = rnorm(300), g1 = factor(sample(1:10, 300, TRUE)), g2 = factor(sample(1:10, 300, TRUE)))
fl <- rep(c("a", "b"), each = 5); d$f1 <- factor(fl[d$g1]); d$f2 <- factor(fl[d$g2]); d$y <- rnorm(300)
sd <- standata(y ~ x + (1 | mm(g1, g2, by = cbind(f1, f2))), data = d)
str(sd[grep("_1", names(sd))])
cat(grep("sd_1|z_1|r_1", strsplit(stancode(y ~ x + (1 | mm(g1, g2, by = cbind(f1, f2))), data = d), "\n")[[1]], value = TRUE), sep = "\n")