# Lane wt-conditions: write tests/testthat/test-conditions.R into each
# extension, one representative refusal per package, from one template.
#   Rscript dev/conditions-ext-tests.R
reps <- list(
  frmtmb.coupling = c(
    setup = "",
    expr = "frm_cross_spectrum(rnorm(20), rnorm(10))",
    regex = "must have the same length"),
  frmtmb.eam = c(
    setup = "",
    expr = "wiener()$links[[\"ndt\"]]$linkinv(0)",
    regex = "bound is not set yet"),
  frmtmb.latent = c(
    setup = "",
    expr = "hmm(1)",
    regex = "number of hidden states"),
  frmtmb.learn = c(
    setup = "",
    expr = "bandit4arm2_kalman_filter(subject = 1, sigma_o = -1)",
    regex = "observation noise"),
  frmtmb.ode = c(
    setup = paste0(
      "  ev <- data.frame(time = 2, state = \"depot\", value = 100,\n",
      "                   method = \"replace\")\n"),
    expr = paste0("frm_lincmt(parms = list(ka = 1.1, ke = 0.2, V = 10),\n",
                  "               times = c(0, 1, 2, 4), ncmt = 1,\n",
                  "               depot = TRUE, events = ev)"),
    regex = "replace rows"),
  frmtmb.sample = c(
    setup = "  d <- data.frame(y = c(1, 2, 3))\n",
    expr = "frm_sample(y ~ 1, data = d, priors = NULL)",
    regex = "takes `prior`, not `priors`"),
  frmtmb.spline = c(
    setup = "",
    expr = "frm_curve(data.frame(), newdata = data.frame())",
    regex = "must be a frmtmb fit"))

template <- '# GENERATED by dev/conditions-ext-tests.R in the frmtmb repository.
#
# brms raises every refusal as a `brms_error`; frmtmb keeps the same
# contract with `frmtmb_error` (?frmtmb::frmtmb-conditions). A refusal
# that this package raises also carries its own subclass,
# `@SUB@_error`, so a caller can catch every frmtmb refusal or
# only the refusals of this package. The census in
# test-conditions-census.R keeps every call site on the helpers; this
# asserts that a real refusal arrives with the classes.

test_that("a @PKG@ refusal is caught as a frmtmb_error", {
@SETUP@  refuse <- function() {
    @EXPR@
  }
  e <- tryCatch(refuse(), frmtmb_error = function(e) e)
  expect_identical(class(e), c("@SUB@_error", "frmtmb_error", "error",
                               "condition"))
  expect_match(conditionMessage(e), "@REGEX@", fixed = TRUE)
  # and by its own subclass alone
  expect_s3_class(tryCatch(refuse(), @SUB@_error = function(e) e),
                  "@SUB@_error")
})

test_that("the refusals classed in punch round 1 carry the subclass", {
  # an argument refused by frm_match_arg(), and a refusal this package
  # wrote that another package raises, which is the case the subclass
  # used to miss
  cases <- list(
@CASES@)
  n <- 0L
  for (nm in names(cases)) {
    e <- tryCatch(eval(cases[[nm]]), error = identity)
    expect_identical(class(e)[1:3], c("@SUB@_error", "frmtmb_error",
                                      "error"), label = nm)
    n <- n + 1L
  }
  # the loop asserted once per case, not over nothing
  expect_identical(n, @N@L)
})
'

# Punch round 1: refusals that must carry the package's subclass. Each
# is cheap: a match.arg()-style argument or a refusal the package wrote
# that frmtmb or frmtmb.eam raises.
more <- list(
  frmtmb.coupling = c(
    window = 'frm_cross_spectrum(rnorm(64), rnorm(64), window = "bogus")'),
  frmtmb.eam = c(
    tridiagonal = 'gddm_control(tridiagonal = "bogus")',
    lapse = 'gddm(lapse = "bogus")',
    lapse_simulate = 'gddm_simulate(10, lapse = "bogus")',
    dec_needed = paste0(
      'frm(bf(rt ~ 1, bias = 0.5), family = wiener(),\n',
      '        data = data.frame(rt = c(0.4, 0.5, 0.6)))')),
  frmtmb.latent = c(
    init = 'hmm(2, init = "bogus")',
    starts_nonfit = 'hmm_starts(1)'),
  frmtmb.learn = c(
    task = 'frm_task_design(task = "bogus")',
    split = 'bandit2arm_dual(subject = id, split = "bogus")',
    task_simulate_nonfamily = 'frm_task_simulate(1, data.frame(x = 1))',
    rlddm_pending_bound = 'rlddm(subject = id)$links$ndt$linkinv(0)'),
  frmtmb.ode = c(
    output = paste0('frm_lincmt(parms = list(ke = 0.2, V = 10), ',
                    'times = 1:5,\n               output = "bogus")'),
    on_error = paste0('frm_ode(function(t, y, p) list(-y[[1]]), ',
                      'init = list(1),\n            times = 1:3, ',
                      'on_error = "bogus")')),
  frmtmb.sample = c(
    criterion = paste0('loo_compare(structure(list(), class = ',
                       '"frmtmb_draws"),\n', strrep(' ', 18),
                       'structure(list(), class = "frmtmb_draws"),\n',
                       strrep(' ', 18), 'criterion = "bogus")'),
    prefix = paste0('pp_check(structure(list(), class = "frmtmb_draws"),',
                    '\n', strrep(' ', 15), 'prefix = "bogus")')),
  frmtmb.spline = c(
    scale = 'royston_parmar(scale = "bogus")'))

for (pkg in names(reps)) {
  r <- reps[[pkg]]
  sub_ <- gsub(".", "_", pkg, fixed = TRUE)
  txt <- template
  m <- more[[pkg]]
  cases <- paste0("    ", names(m), " = quote(", m, ")", collapse = ",\n")
  for (k in c("PKG", "SUB", "SETUP", "EXPR", "REGEX", "CASES", "N")) {
    val <- switch(k, PKG = pkg, SUB = sub_, SETUP = r[["setup"]],
                  EXPR = r[["expr"]], REGEX = r[["regex"]],
                  CASES = cases, N = as.character(length(m)))
    txt <- gsub(paste0("@", k, "@"), val, txt, fixed = TRUE)
  }
  out <- file.path("extensions", pkg, "tests", "testthat",
                   "test-conditions.R")
  con <- file(out, open = "wb")
  writeLines(txt, con, sep = "\n")
  close(con)
  cat("wrote", out, "\n")
}
