# The tier counts of lane wt-correct, emitted as a block to paste into
# dev/correct-findings.md rather than typed: a count taken from a
# sentence has been wrong in this project before.
#   Rscript dev/correct-runs.R
root <- "C:/Users/adf44/source/r/frmtmb-wt-correct"
log_dir <- file.path(root, "dev/correct-log")

tier <- function(file, label) {
  if (!file.exists(file)) {
    cat(sprintf("%-8s MISSING %s\n", label, file))
    return(invisible(NULL))
  }
  x <- readLines(file, warn = FALSE)
  r <- grep("^RESULT ", x, value = TRUE)
  num <- function(key) {
    v <- regmatches(r, regexpr(paste0(key, "=[0-9]+"), r))
    sum(as.integer(sub(".*=", "", v)))
  }
  ran <- grep("^(SUITE|GATED) ran ", x, value = TRUE)
  bad <- grep("NO RESULT LINE", x, value = TRUE)
  cat(sprintf("%-8s files %d  pass %d  fail %d  error %d  skip %d  %s\n",
              label, length(r), num("pass"), num("fail"), num("err"),
              num("skip"),
              if (length(ran)) ran[length(ran)] else "no ran line"))
  if (length(bad)) cat("  ", length(bad), "files produced no RESULT\n")
  invisible(NULL)
}

cat("```\n")
cat("== generated by dev/correct-runs.R ==\n")
tier(file.path(log_dir, "suite.log"), "suite")
tier(file.path(log_dir, "gated.log"), "gated")

# R CMD check: one status line per package
chk <- file.path(log_dir, "check.log")
if (file.exists(chk)) {
  x <- readLines(chk, warn = FALSE)
  pkg <- sub("^===== CHECK .*/", "", grep("^===== CHECK", x, value = TRUE))
  st <- grep("^Status: ", x, value = TRUE)
  cat(sprintf("check    %s\n", paste(sub(" =====$", "", pkg), st,
                                     sep = ": ", collapse = " | ")))
} else {
  cat("check    MISSING\n")
}

# the ported ledger, before and after
led <- function(f, label) {
  if (!file.exists(f)) return(cat(sprintf("%-8s MISSING\n", label)))
  x <- readLines(f, warn = FALSE)
  tot <- grep("^\\| \\*\\*total\\*\\*", x, value = TRUE)[1L]
  cat(sprintf("%-8s %s\n", label, trimws(tot)))
}
led(file.path(log_dir, "ledger-summary-before.md"), "ledger0")
led(file.path(root, "dev/brmsport-log/ledger-summary.md"), "ledger1")

# nothing else moved
cmp <- file.path(log_dir, "bitwise-compare.txt")
if (file.exists(cmp)) {
  x <- readLines(cmp, warn = FALSE)
  cat("bitwise ", grep("^identical:", x, value = TRUE),
      " differing:", length(grep("DIFFERS", x)), "\n")
}
cat("```\n")
