# The verdict moves lane wt-defects makes to the ported brms tier
# (dev/brmsport-ledger.tsv), applied idempotently, after the precedent
# of dev/adefects-verdicts.R: the verdict files are data, and a hand
# edit to a 200-line TSV cannot be re-read or re-applied.
#
#   Rscript dev/defects-verdicts.R
#   Rscript dev/brmsport-ledger.R
#   Rscript dev/brmsport-gen.R
#
# Every move names the row and what the lane build now reports; the
# record behind each is dev/brmsport-log/rec-*.tsv as regenerated by
# dev/defects-record.sh against C:/Users/adf44/source/r/wt-defects-lib,
# and dev/defects-findings.md section 2 has the table.
man_f <- "dev/brmsport-verdicts-manual.tsv"
fit_f <- "dev/brmsport-verdicts-manual-fit.tsv"
own_f <- "dev/brmsport-verdicts-own.tsv"

rd <- function(f) utils::read.delim(f, quote = "", colClasses = "character",
                                    na.strings = NULL)
wr <- function(x, f) utils::write.table(x, f, sep = "\t", quote = FALSE,
                                        row.names = FALSE)
man <- rd(man_f)
fit <- rd(fit_f)
own <- rd(own_f)

# Rows that now HOLD on brms's own assertion, so their manual verdict is
# stale. The ledger builder stops on a stale verdict; these are the 28
# rows (29 runs: families:102 holds in both packages) it named
# (dev/defects-findings.md section 2 says what fixed each).
to_pass <- c(
  "brm:102", "standata:83", "standata:85", "standata:142", "priors:55",
  "priors:59", "priors:101", "families:102",
  "brmsfit-methods:82", "brmsfit-methods:83", "brmsfit-methods:94",
  "brmsfit-methods:96", "brmsfit-methods:284", "brmsfit-methods:285",
  "brmsfit-methods:301", "brmsfit-methods:305", "brmsfit-methods:352",
  "brmsfit-methods:737", "brmsfit-methods:741", "brmsfit-methods:772",
  "brmsfit-methods:817",
  "brmsfit-methods:828", "brmsfit-methods:832", "brmsfit-methods:840",
  "brmsfit-methods:841", "brmsfit-methods:904", "brmsfit-methods:924",
  "data-helpers:7")

# Rows whose refusal is now brms's refusal of the same case in frmtmb's
# words (rule 1 of 2026-09-17): an own-words pass.
to_own <- data.frame(
  id = c("brm:81", "brm:116", "brmsfit-methods:938"),
  pkg = "frmtmb",
  pattern = c(
    "se[(][)] carries a known standard deviation.*'weibull' does not declare",
    "cs[(][)] needs an sratio, cratio, or acat family; the group-level term",
    "The model uses .wrong_var., which is not a column of .data."),
  note = c(
    paste0("brms: Argument 'se' is not supported for family. The same ",
           "refusal from the formula alone: frmtmb checks whether the ",
           "family reads se() before it reads the data now (lane ",
           "wt-defects), where it named the missing column sei first"),
    paste0("brms: Category specific effects are not supported for this ",
           "family. The same refusal of cs() on categorical(); frmtmb ",
           "read the integer response as having fewer than two categories ",
           "before, and then died on R's could not find function cs"),
    paste0("brms: New variables found: 'wrong_var'. The same refusal of ",
           "the same update in frmtmb's words: the variable is in neither ",
           "the data nor the formula environment")),
  stringsAsFactors = FALSE)

# Rows that still do not hold, with the verdict, class and reason the
# lane build now supports.
recl <- list(
  list(id = "brmsfit-methods:283", verdict = "divergence", class = "class",
       reason = paste0(
         "family(fit6, resp = 'count') answers now, with that response's ",
         "family, as brms's does; the object's class is frmtmb_family, ",
         "not brmsfamily (user decision, 2026-09-17, rule 2)")),
  list(id = "brmsfit-methods:314", verdict = "defect", class = "argument",
       reason = paste0(
         "fitted() takes sample_new_levels = 'gaussian' now; this call ",
         "asks 'old_levels', which resamples the posterior draws of the ",
         "seen levels and is refused by name, and ndraws, which a ",
         "maximum-likelihood fit has no draws to thin (D3's reason). The ",
         "setup dies on ndraws, so the assertion reads a stale object")),
  list(id = "brmsfit-methods:317", verdict = "divergence",
       class = "no-draws",
       reason = paste0(
         "fitted() takes sample_new_levels = 'gaussian' now, as brms's ",
         "does; ndraws = 1 is refused by name, since fitted() on a ",
         "maximum-likelihood fit is a Wald summary with no draws to thin ",
         "(D3's reason). The setup dies on it, so the assertion reads a ",
         "stale object")),
  list(id = "brmsfit-methods:391", verdict = "defect", class = "argument",
       reason = paste0(
         "plot() of a hypothesis refuses brms's plot = FALSE by name: ",
         "frmtmb draws the densities with base graphics and returns the ",
         "object, where brms returns a list of ggplot objects that ",
         "plot = FALSE hands back undrawn. frmtmb does not depend on ",
         "ggplot2 (dev/brms-vignette-audit.md, break 2)")),
  list(id = "brmsfit-methods:396", verdict = "defect", class = "argument",
       reason = paste0(
         "plot() of a hypothesis refuses brms's ignore_prior and plot by ",
         "name, as brmsfit-methods:391; a fit has no prior draws, so ",
         "ignore_prior would change nothing")),
  list(id = "brmsfit-methods:747", verdict = "defect",
       class = "refuses-accepted",
       reason = paste0(
         "fixture 1 is brms's own model now, arma() with cov = FALSE ",
         "(lane wt-defects). predict(newdata = ) with the response NA in ",
         "rows 8 to 10 is refused by name: under cov = FALSE a row's mean ",
         "reads the residuals of the rows before it. brms fills a missing ",
         "response with its predicted draws and runs the recursion over ",
         "them; simulate(newdata = ) does that here and predict() does ",
         "not yet")),
  list(id = "brmsfit-methods:814", verdict = "divergence", class = "policy",
       reason = paste0(
         "ranef(pars = 'Trt1') answers now and keeps the Trt1 column of ",
         "visit; the value is levels x coefficients, the policy of ",
         "brmsfit-methods:811 (dev/brms-api-diff.md (b)), so dimnames() ",
         "has no third element to read")),
  list(id = "brmsfit-methods:927", verdict = "divergence", class = "policy",
       reason = paste0(
         "update(fit, data = new_data) refits on the new data, as ",
         "stats::update(), lme4 and glmmTMB read it; brms refuses the ",
         "spelling and asks for newdata, which frmtmb also takes. ",
         "Refusing a spelling that means one thing would only break the ",
         "lme4 idiom (lane wt-defects)")),
  list(id = "brmsfit-methods:995", verdict = "defect", class = "spelling",
       reason = paste0(
         "parnames() is brms's deprecated spelling of variables(). ",
         "frmtmb.sample answers it on draws, with brms's warning; core ",
         "has none for a fit, and adding one moves the generic from ",
         "frmtmb.sample's owner table to core's (R/generic-owners.R)")),
  list(id = "data-helpers:12", verdict = "divergence", class = "policy",
       reason = paste0(
         "brms refuses the integer codes of `fac`, a factor column of the ",
         "data that no term of the model reads; frmtmb never checks such a ",
         "column, since no value in it can change the prediction, and ",
         "refuses this call for the new `visit` level set the line ",
         "before")),
  list(id = "priors:74", verdict = "divergence", class = "policy",
       reason = paste0(
         "default_prior() answers brms's Beta() model on an rnorm() ",
         "response now, as brms does (lane wt-defects); its 5 phi rows ",
         "against brms's 6 lack the per-coefficient sd row (sd, g, ",
         "Intercept), which frmtmb does not list because its class sd ",
         "addresses a block and refuses coef (priorform ledger P1, P26)")),
  list(id = "standata:75", verdict = "defect", class = "refuses-accepted",
       reason = paste0(
         "bernoulli refuses a response with the two values -1 and -2 ",
         "('response must be 0/1'); brms codes them 1 and 0 by level ",
         "order. Filed by lane wt-defects: the recoding has to be stored ",
         "with the fit and applied on every refit (influence(), ",
         "frm_bootstrap()) and every response read from newdata ",
         "(pp_check(), residuals(newdata = ), predictive_error()), or a ",
         "subset holding one of the two values is coded wrong in silence"))
)

drop_ids <- c(to_pass, to_own$id)
man <- man[!(man$id %in% drop_ids), , drop = FALSE]
fit <- fit[!(fit$id %in% drop_ids), , drop = FALSE]
for (r in recl) {
  for (nm in c("man", "fit")) {
    x <- get(nm)
    i <- which(x$id == r$id)
    if (!length(i)) next
    x$verdict[i] <- r$verdict
    x$class[i] <- r$class
    x$reason[i] <- r$reason
    assign(nm, x)
  }
  stopifnot(sum(man$id == r$id) + sum(fit$id == r$id) >= 1L)
}
own <- own[!(own$id %in% to_own$id), , drop = FALSE]
own <- rbind(own, to_own)
wr(man, man_f)
wr(fit, fit_f)
wr(own, own_f)
cat("removed", length(drop_ids), "manual ids; reclassified", length(recl),
    "; own-words rows now", nrow(own), "\n")
