# Turn the 104 hand-written meta-refresh files in docs/reference/ into a
# pkgdown `redirects:` block for the core _pkgdown.yml, and say which of
# their targets a clean build actually produces.
#
# WHY. Those files are not pkgdown output. Nothing regenerates them, so a
# build that cleans its destination loses all 104 and the old URLs start
# answering 404. pkgdown's own `redirects:` key writes exactly the same
# meta-refresh page from config, on every build. build_redirect() forms
# the target as sprintf("%s/%s%s", url, prefix, new), with prefix empty
# for a released site, so `new` has to be relative to the core site root
# and a subsite target spells itself frmtmb.sample/reference/x.html.
#
#   Rscript dev/docsci-gen-redirects.R
#
# It writes dev/docsci-core-redirects.yml itself rather than being
# redirected into it, because PowerShell's Out-File puts a UTF-8 BOM on
# the front and R chokes on one.
#
# Nothing here edits _pkgdown.yml. The block is for the owner to read,
# prune and paste, because 17 of the targets are subsite pages and 87
# point back inside the core site, and some of THOSE point at pages a
# clean build does not produce.

site_url <- "https://aforren1.github.io/frmtmb/"
# Only the pages a clean build does NOT produce. pkgdown writes its own
# meta-refresh page for every Rd alias that used to have one, 308 of them
# in the core site, and those need no config: the new build has them all.
# What is left is the set whose alias no longer exists in core, which is
# the set nothing regenerates.
have <- basename(Sys.glob("dev/docsci-site/reference/*.html"))
files <- sort(Sys.glob("docs/reference/*.html"))
files <- files[!basename(files) %in% have]
target_of <- function(f) {
  txt <- paste(readLines(f, warn = FALSE), collapse = " ")
  if (!grepl("http-equiv=\"refresh\"", txt, fixed = TRUE)) {
    return(NA_character_)
  }
  m <- regmatches(txt, regexpr("URL=[^\"]+", txt))
  if (!length(m)) return(NA_character_)
  sub("^URL=", "", m)
}
tgt <- vapply(files, target_of, character(1))
keep <- !is.na(tgt)
files <- files[keep]
tgt <- tgt[keep]
rel <- sub(paste0("^", gsub("[.]", "[.]", site_url)), "", tgt)
from <- paste0("reference/", basename(files))

# 51 targets are themselves one of these hand-written pages: a chain
# that a clean build breaks, because its middle link is not rebuilt.
# Each chain is one hop to a frmtmb.sample page, so following it is a
# lookup, not a choice. Follow it, and refuse a cycle.
hops <- integer(length(rel))
for (i in seq_along(rel)) {
  seen <- from[i]
  while (rel[i] %in% from) {
    if (rel[i] %in% seen) stop("redirect cycle through ", rel[i])
    seen <- c(seen, rel[i])
    rel[i] <- rel[match(rel[i], from)]
    hops[i] <- hops[i] + 1L
  }
}

# Where a clean build already produces the page, the redirect is live.
# Where it does not, the redirect points at nothing and the entry is a
# question for the owner rather than a line to paste.
built <- file.exists(file.path("dev/docsci-site", rel))

out <- file("dev/docsci-core-redirects.yml", open = "wt", encoding = "UTF-8")
sink(out)
cat("# Generated by dev/docsci-gen-redirects.R. Do not hand-edit.\n")
cat("#\n# ", sum(built), " of ", length(built),
    " targets exist in a clean build; ", sum(hops > 0L),
    " of them were reached\n",
    "# by following a chain through another hand-written page. Any\n",
    "# target a clean build lacks is listed at the bottom, commented out.\n",
    sep = "")
cat("redirects:\n")
for (i in which(built)) {
  cat("  - [\"", from[i], "\", \"", rel[i], "\"]\n", sep = "")
}
cat("\n# TARGET DOES NOT EXIST IN A CLEAN BUILD (", sum(!built),
    " entries):\n", sep = "")
for (i in which(!built)) {
  cat("#  - [\"", from[i], "\", \"", rel[i], "\"]\n", sep = "")
}
sink()
close(out)
cat("wrote dev/docsci-core-redirects.yml: ", length(built),
    " redirects, ", sum(built), " with a live target\n", sep = "")
