#!/usr/bin/env Rscript
#
# Summarize a built site tree into a block that dev/docsci-findings.md
# pastes verbatim. Counts in a document that were typed rather than
# generated have been wrong in this project before, so the document gets
# its numbers from the tree.
#
#   Rscript dev/docsci-verify.R <site-dir> [<reference-dir>]
#
# With a reference directory it also compares, per article, the number of
# rendered output lines, which is how a silently gated-off article shows
# up: the page still builds and its `#>` lines go to zero.

args <- commandArgs(trailingOnly = TRUE)
site <- normalizePath(args[1], winslash = "/", mustWork = TRUE)
ref <- if (length(args) > 1) {
  normalizePath(args[2], winslash = "/", mustWork = TRUE)
} else {
  NA_character_
}

roots <- c("", basename(list.dirs(site, recursive = FALSE)))
roots <- roots[roots == "" | grepl("^frmtmb[.]", roots)]
at <- function(r, ...) {
  if (nzchar(r)) file.path(site, r, ...) else file.path(site, ...)
}

cat("<!-- generated by dev/docsci-verify.R; do not edit by hand -->\n")
cat("```\n")
cat("site ", site, "\n", sep = "")
cat(sprintf("%-18s %8s %6s %6s %7s\n",
            "site", "index", "refpg", "artcl", "outlines"))
n_ok <- 0L
for (r in roots) {
  idx <- at(r, "index.html")
  refi <- at(r, "reference", "index.html")
  arts <- Sys.glob(at(r, "articles", "*.html"))
  arts <- arts[basename(arts) != "index.html"]
  md <- Sys.glob(at(r, "articles", "*.md"))
  md <- md[basename(md) != "index.md"]
  outlines <- sum(vapply(md, function(f) {
    sum(grepl("^#>", readLines(f, warn = FALSE)))
  }, numeric(1)))
  ok <- file.exists(idx) && file.size(idx) > 0 && file.exists(refi)
  if (ok) n_ok <- n_ok + 1L
  cat(sprintf("%-18s %8s %6s %6d %7d\n",
              if (nzchar(r)) r else "frmtmb (root)",
              if (file.exists(idx)) "yes" else "NO",
              if (file.exists(refi)) "yes" else "NO",
              length(arts), outlines))
}
cat("site roots with index.html and reference/index.html: ", n_ok, "\n",
    sep = "")
cat("search.json at the root: ",
    if (file.exists(file.path(site, "search.json"))) "yes" else "NO",
    " (", format(file.size(file.path(site, "search.json"))), " bytes)\n",
    sep = "")
cat("reference pages, all sites: ",
    length(Sys.glob(file.path(site, "reference", "*.html"))) +
      length(Sys.glob(file.path(site, "frmtmb.*", "reference", "*.html"))),
    "\n", sep = "")
cat("files, all sites: ",
    length(list.files(site, recursive = TRUE, all.files = TRUE)), "\n",
    sep = "")

# The core navbar is the only route a reader has to an extension site.
# Run this script from the repository root.
cfg <- yaml::read_yaml("_pkgdown.yml")
menu <- cfg$navbar$components$extensions$menu
cat("\ncore navbar Extensions menu against the built tree:\n")
for (m in menu) {
  seg <- basename(sub("/+$", "", m$href))
  cat(sprintf("  %-18s %s\n", seg,
              if (file.exists(file.path(site, seg, "index.html"))) {
                "built"
              } else {
                "MISSING"
              }))
}

if (!is.na(ref)) {
  cat("\nrendered output lines, this build against ", ref, ":\n", sep = "")
  cat(sprintf("  %-46s %7s %7s\n", "article", "ref", "new"))
  drop <- 0L
  for (r in roots) {
    md <- Sys.glob(at(r, "articles", "*.md"))
    for (f in md) {
      rel <- substring(f, nchar(site) + 2)
      g <- file.path(ref, rel)
      cnt <- function(p) {
        if (!file.exists(p)) return(NA_integer_)
        sum(grepl("^#>", readLines(p, warn = FALSE)))
      }
      a <- cnt(g)
      b <- cnt(f)
      if (identical(a, b)) next
      if (!is.na(a) && !is.na(b) && b < a) drop <- drop + 1L
      cat(sprintf("  %-46s %7s %7s\n", rel,
                  if (is.na(a)) "-" else a, if (is.na(b)) "-" else b))
    }
  }
  cat("articles with FEWER output lines than the reference: ", drop, "\n",
      sep = "")
}
cat("```\n")
