.libPaths(c("C:/Users/adf44/source/r/pinlib",
             "C:/Users/adf44/AppData/Local/R/win-library/4.6"))
suppressPackageStartupMessages(library(brms))
cat("brms", format(packageVersion("brms")), "\n")
str(unclass(brms::student()), max.level = 1)
str(unclass(brms::zero_inflated_binomial()), max.level = 1)
str(unclass(brms::brmsfamily("gaussian")), max.level = 1)
print(brms::brmsfamily)
print(brms:::.family_bernoulli)
print(brms:::.family_beta_binomial)
print(brms:::validate_family)
print(brms:::check_family)
print(brms:::family_info)
print(brms:::mixture)
print(names(brms:::.family_student()))
