# Generate R/links-brms.R: the links brms allows for each family's mean.
#
# The sets are READ from brms, never typed: brms:::.family_<name>()$links
# is the list .brmsfamily() validates `link` against, and its first entry
# is brms's default. Rerun after a brms upgrade and diff the result;
# tests/testthat/test-brms-families.R recomputes the same table from the
# installed brms and fails if the committed file has drifted.
#
# Run: Rscript dev/famlink-gen-links.R
.libPaths(c("C:/Users/adf44/source/r/pinlib",
            "C:/Users/adf44/AppData/Local/R/win-library/4.6"))
stopifnot(requireNamespace("brms", quietly = TRUE))
ver <- format(utils::packageVersion("brms"))

# frmtmb family name (fam$family) -> the brms family whose set it takes.
# Three frmtmb families have no brms counterpart and take the set of the
# brms family they are closest to: nbinom1 is a negative binomial mean,
# tweedie a positive continuous mean (compound Poisson-gamma), huber a
# location on the whole line.
src <- c(
  gaussian = "gaussian", poisson = "poisson", binomial = "binomial",
  Gamma = "gamma", lognormal = "lognormal", student = "student",
  negbinomial = "negbinomial", nbinom1 = "negbinomial", beta = "beta",
  tweedie = "gamma", compois = "com_poisson",
  zero_inflated_poisson = "zero_inflated_poisson",
  zero_inflated_negbinomial = "zero_inflated_negbinomial",
  hurdle_poisson = "hurdle_poisson",
  hurdle_negbinomial = "hurdle_negbinomial", multinomial = "multinomial",
  cumulative = "cumulative", beta_binomial = "beta_binomial",
  skew_normal = "skew_normal", inverse.gaussian = "inverse.gaussian",
  exgaussian = "exgaussian", bernoulli = "bernoulli",
  geometric = "geometric", exponential = "exponential",
  weibull = "weibull", shifted_lognormal = "shifted_lognormal",
  hurdle_gamma = "hurdle_gamma", hurdle_lognormal = "hurdle_lognormal",
  zero_inflated_binomial = "zero_inflated_binomial",
  zero_inflated_beta = "zero_inflated_beta",
  zero_one_inflated_beta = "zero_one_inflated_beta",
  asym_laplace = "asym_laplace",
  zero_inflated_asym_laplace = "zero_inflated_asym_laplace",
  huber = "gaussian", sratio = "sratio", cratio = "cratio", acat = "acat",
  von_mises = "von_mises", cox = "cox", categorical = "categorical"
)
analog <- c("nbinom1", "tweedie", "huber")

ns <- asNamespace("brms")
sets <- lapply(src, function(b) get(paste0(".family_", b), envir = ns)()$links)

q <- function(x) paste0("\"", x, "\"")
lines <- c(
  "# GENERATED by dev/famlink-gen-links.R from brms %s. Do not edit by",
  "# hand: rerun the script, which reads brms:::.family_<name>()$links.",
  "#",
  "# The links brms allows for each family's MEAN, keyed by the frmtmb",
  "# family name. The first entry is brms's default. nbinom1, tweedie and",
  "# huber have no brms family and take the set of the analog named in",
  "# `brms_mu_link_source`.",
  "",
  "brms_mu_link_source <- c("
)
lines[1] <- sprintf(lines[1], ver)
body <- paste0("  ", ifelse(make.names(names(src)) == names(src), names(src),
                            paste0("`", names(src), "`")),
               " = ", q(src))
lines <- c(lines, paste0(body, c(rep(",", length(body) - 1L), "")), ")", "",
           paste0("brms_mu_link_analogs <- c(", paste(q(analog), collapse = ", "),
                  ")"), "", "brms_mu_links <- list(")
ent <- vapply(names(sets), function(nm) {
  key <- if (make.names(nm) == nm) nm else paste0("`", nm, "`")
  paste(strwrap(paste0(key, " = c(", paste(q(sets[[nm]]), collapse = ", "), ")"),
                width = 74, prefix = "      ", initial = "  "),
        collapse = "\n")
}, "")
lines <- c(lines, paste0(ent, c(rep(",", length(ent) - 1L), "")), ")")

# The families brms refuses as mixture components: brms:::no_mixture()
# applied to each brms family an frmtmb family maps to. An analog takes
# no verdict from its analog: whether a density can be a mixture
# component is a property of that density, and the analog's is another.
barred <- names(src)[vapply(names(src), function(nm) {
  if (nm %in% analog) return(FALSE)
  isTRUE(brms:::no_mixture(brms::brmsfamily(src[[nm]])))
}, NA)]
lines <- c(lines, "",
  "# The families brms:::no_mixture() bars as mixture components, by",
  "# frmtmb family name. The analogs above take no verdict.",
  paste(strwrap(paste0("brms_no_mixture <- c(",
                       paste(q(barred), collapse = ", "), ")"),
                width = 74, prefix = "  ", initial = ""),
        collapse = "\n"))
writeLines(lines, "R/links-brms.R", useBytes = TRUE)
cat("wrote R/links-brms.R from brms", ver, "with", length(sets), "families,",
    sum(lengths(sets)), "(family, link) pairs\n")
cat("brms_no_mixture:", barred, "\n")
