# Reviewer: the gradient (not only higher derivatives) at x == a / (a + b)
.libPaths(c("C:/Users/adf44/source/r/wt-fams2-lib", "C:/Users/adf44/source/r/rellib-r3", "C:/Users/adf44/AppData/Local/R/win-library/4.6"))
suppressPackageStartupMessages({ library(RTMB); library(frmtmb) })
F <- MakeTape(function(p) frmtmb:::log_ibeta_half(p[1], p[2], p[3]), c(0.1, 1, 2))
J <- F$jacfun()
cat("log_ibeta_half(0.3, 300, 700) gradient:", J(c(0.3, 300, 700)), "\n")
fam <- frmtmb:::as_frmtmb_family(xbeta())
lp0 <- MakeTape(function(p) sum(fam$lpdf(c(0, 0.3), list(mu = p[1], phi = p[2], kappa = p[3]), list())), c(0.2, 100, 0.1))
cat("xbeta rows (0, 0.3) at mu = q = 1/6, phi 3000, kappa 0.25: gradient", lp0$jacfun()(c(1/6, 3000, 0.25)), "\n")
cat("the same through MakeADFun with mu on the logit scale, at mu = plogis(qlogis(1/6)):", plogis(qlogis(1/6)) == 1/6, "\n")
