# Put the generated counts block into dev/formrobust-findings.md in
# place of the GENERATED-COUNTS marker. Kept as the record.
wt <- "C:/Users/adf44/source/r/frmtmb-wt-formrobust/dev/"
f <- readLines(paste0(wt, "formrobust-findings.md"))
cnt <- readLines(paste0(wt, "formrobust-log/counts.md"))
st <- function(p) {
  x <- readLines(p, warn = FALSE)
  x[grepl("^Status", x)][1]
}
core_st <- st(paste0(wt, "formrobust-check/frmtmb/check.log"))
samp_st <- st(paste0(wt, "formrobust-check/frmtmb.sample/check.log"))
pre <- c(
  "Every test file ran in its own R process with `library(<pkg>)`",
  "attached (`dev/formrobust-run-tests.R`, driven by",
  "`dev/formrobust-run-par.sh`). The seven unchanged extensions loaded",
  "from `rellib-r4` behind the lane's core, as the library lines below",
  "show. The block below is generated by `dev/formrobust-counts.R` and",
  "`dev/formrobust-counts-new.sh` from the per-file logs; the per-file",
  "RESULT lines are in `dev/formrobust-log/suite2.log` and",
  "`dev/formrobust-log/gated1.log`.",
  "",
  "The eight gated failures are the stale \"now HOLDS\" rows of section",
  "7, and nothing else (`dev/formrobust-log/dbg-gated-*.txt`). The gated",
  "tier ran before the last edit, which changed only the reason text of",
  "two `R/compat.R` rows and a vignette paragraph; the ungated suite and",
  "the checks ran on the final code.",
  "")
post <- c(
  "`R CMD check --as-cran` (built and checked in",
  "`dev/formrobust-check/<pkg>/`, `_R_CHECK_CRAN_INCOMING_REMOTE_=FALSE`):",
  "",
  paste0("- frmtmb: ", core_st, ". The NOTE is the V8 math-rendering note on the HTML manual, which lane-rules.md expects."),
  paste0("- frmtmb.sample: ", samp_st, "."),
  "- No other extension changed, so none was checked.")
i <- which(f == "GENERATED-COUNTS")
stopifnot(length(i) == 1L)
f <- c(f[seq_len(i - 1L)], pre, cnt, post, f[(i + 1L):length(f)])
writeLines(f, paste0(wt, "formrobust-findings.md"))
