# Punch round 1: put the generated counts and the check Status lines of
# the round into section 8 of dev/formrobust-findings.md. Record.
wt <- "C:/Users/adf44/source/r/frmtmb-wt-formrobust/dev/"
f <- readLines(paste0(wt, "formrobust-findings.md"))
cnt <- readLines(paste0(wt, "formrobust-log/counts-p1.md"))
st <- function(p) {
  x <- readLines(p, warn = FALSE)
  x[grepl("^Status", x)][1]
}
core_st <- st(paste0(wt, "formrobust-check/frmtmb/check.log"))
samp_st <- st(paste0(wt, "formrobust-check/frmtmb.sample/check.log"))
mut <- readLines(paste0(wt, "formrobust-log/p1-mut.log"))
block <- c(
  "### Punch round 1",
  "",
  "The final runs of the round, on the final code. The blocks below are",
  "generated by `dev/formrobust-counts.R` from the per-file logs",
  "(`suite3.log`, `gated2.log`). The gated tier now includes",
  "`test-offset-grid.R`, whose brms comparison needs Stan. Its eight",
  "failures are the same stale \"now HOLDS\" rows as round 0 (section 7).",
  "",
  cnt,
  "Mutation runs (`dev/formrobust-log/p1-mut.log`, verbatim):",
  "",
  "```",
  mut,
  "```",
  "",
  "`R CMD check --as-cran` of the round:",
  "",
  paste0("- frmtmb: ", core_st, ". The NOTE is the V8 math-rendering"),
  "  note on the HTML manual, which lane-rules.md expects.",
  paste0("- frmtmb.sample: ", samp_st, "."),
  "")
i <- which(f == "## 9. Decided not to do, and why")
stopifnot(length(i) == 1L)
f <- c(f[seq_len(i - 1L)], block, f[i:length(f)])
writeLines(f, paste0(wt, "formrobust-findings.md"))
