.libPaths(c("C:/Users/adf44/source/r/wt-formrobust-lib", "C:/Users/adf44/source/r/rellib-r4", "C:/Users/adf44/AppData/Local/R/win-library/4.6"))
suppressMessages(library(frmtmb))
f <- frmtmb:::as_frmtmb_family(gaussian())
str(f[c("family", "link")], max.level = 1)
print(names(f)); print(vapply(f$links, function(l) if (is.list(l)) l$name %||% NA_character_ else as.character(l), ""))
g <- frmtmb:::as_frmtmb_family(student(link_sigma = "identity"))
print(vapply(g$links, function(l) if (is.list(l)) l$name %||% NA_character_ else as.character(l), ""))
print(formals(student))
print(class(f)); print(f$call)
