source("C:/Users/adf44/source/r/frmtmb-wt-generics/dev/generics-sub.R")
root <- "C:/Users/adf44/source/r/frmtmb-wt-generics"
p <- "tests/testthat/test-scale-contract.R"

# N7. The ">5" is not measuring the separation it looked like it was
# measuring, and the page should not say it is.
sub1(p,
paste0("  # then the discrimination. The prediction's own standard error\n",
       "  # cannot do it: measured on this design the mean and the median\n",
       "  # sit 0.9 of one apart. The quantity that separates them is the\n",
       "  # RATIO, exp(sigma^2 / 2), whose standard error follows by the\n",
       "  # delta method from the standard error of log(sigma) that\n",
       "  # summary() reports.\n"),
paste0("  # then the discrimination. The prediction's own standard error\n",
       "  # cannot do it: measured on this design the mean and the median\n",
       "  # sit 0.9134 of one apart. The quantity that separates them is\n",
       "  # the RATIO, exp(sigma^2 / 2), whose standard error follows by\n",
       "  # the delta method from the standard error of log(sigma) that\n",
       "  # summary() reports.\n",
       "  #\n",
       "  # Read what this statistic IS before trusting it. Substituting\n",
       "  # the identity, `ratio - 1` is about sigma^2/2 and `se_ratio`\n",
       "  # about sigma^2 * se(log sigma), so the whole thing reduces to\n",
       "  # 1 / (2 * se(log sigma)), which is about sqrt(n/2) and does NOT\n",
       "  # depend on sigma. So `> 5` is, to first order, an assertion\n",
       "  # that n is over 50: it is a sanity bound, not a measurement of\n",
       "  # the size of the discrepancy. It still discriminates, which is\n",
       "  # the job: under mutant M1 the ratio is exactly 1 and the\n",
       "  # statistic is 0.\n"))

extra <- paste0(
'\n',
'test_that("conditional_effects() is on the RESPONSE scale", {\n',
'  # The row that matters most and was missing from the page: it is\n',
'  # the one method whose scale is the OPPOSITE of predict()\'s\n',
'  # default, so a porter who plots both sees three orders of\n',
'  # magnitude between them and no document explaining it.\n',
'  f <- scale_fits()$ln\n',
'  ce <- conditional_effects(f)[[1]]\n',
'  est <- ce$estimate__\n',
'  expect_true(all(est > 0))\n',
'  # it lives inside the range fitted() covers, not near the linear\n',
'  # predictor, and the yardstick is the fit\'s own fitted values\n',
'  fv <- fitted(f)\n',
'  expect_gt(min(est), min(fv) / 2)\n',
'  expect_lt(max(est), max(fv) * 2)\n',
'  # the inverse: it is nowhere near the link scale\n',
'  expect_gt(stats::median(est) / stats::median(predict(f)), 100)\n',
'})\n',
'\n',
'test_that("the lognormal identity holds only for a constant sigma", {\n',
'  # The page used to state exp(mu + sigma^2/2) flatly. With a\n',
'  # distributional sigma there is no scalar to put in it, and\n',
'  # sigma() says so by returning NA rather than by inventing one.\n',
'  fits <- scale_fits()\n',
'  dd <- fits$dd\n',
'  f2 <- frm(bf(y ~ x + (1 | g), sigma ~ x) + lognormal(), data = dd)\n',
'  expect_warning(s <- sigma(f2), "varies by observation")\n',
'  expect_true(is.na(s))\n',
'  mu <- predict(f2, type = "link")\n',
'  sv <- predict(f2, dpar = "sigma", type = "response")\n',
'  # the per-row sigma reproduces fitted() exactly; the scalar cannot\n',
'  expect_identical(fitted(f2), exp(mu + sv^2 / 2))\n',
'  expect_true(all(is.na(exp(mu + s^2 / 2))))\n',
'})\n',
'\n',
'test_that("the lognormal identity fails under truncation", {\n',
'  # fitted() is the TRUNCATED mean there, so the naive formula is not\n',
'  # merely imprecise, it is answering a different question. The\n',
'  # assertion is two-sided: the error has to be far above the\n',
'  # machine precision the untruncated identity holds to, and the\n',
'  # truncated mean has to stay above the truncation bound.\n',
'  fits <- scale_fits()\n',
'  dd <- fits$dd\n',
'  lb <- 2000\n',
'  d3 <- dd[dd$y > lb, ]\n',
'  f3 <- frm(bf(y | trunc(lb = lb) ~ x + (1 | g)) + lognormal(),\n',
'            data = d3)\n',
'  mu <- predict(f3, type = "link")\n',
'  naive <- exp(mu + sigma(f3)^2 / 2)\n',
'  rel <- max(abs(fitted(f3) - naive)) / max(abs(fitted(f3)))\n',
'  expect_gt(rel, 1e4 * .Machine$double.eps)\n',
'  expect_true(all(fitted(f3) > lb))\n',
'  # and the untruncated fit on the same design still holds it exactly\n',
'  ln <- fits$ln\n',
'  expect_identical(fitted(ln),\n',
'                   exp(predict(ln, type = "link") + sigma(ln)^2 / 2))\n',
'})\n')
f <- file.path(root, p)
txt <- rawToChar(readBin(f, "raw", file.info(f)$size))
writeBin(charToRaw(paste0(txt, extra)), f)
cat("appended 3 scale blocks\n")
cat("DONE\n")
