source("C:/Users/adf44/source/r/frmtmb-wt-generics/dev/generics-sub.R")

# Measured before this change (dev/generics-adoptcost.R): the adopted
# path cost 8.89 us per ACCESS, which is 0.80 of one fixef() call, and
# the two-owner path cost 49.13 us because frm_adopt_target() ran
# sub() over every entry of search() on every access. Neither is fatal
# for a once-per-user-action accessor, but the source comment claimed
# the cost was "small next to any call it gates", and at 0.80 of a
# fixef() that was not true. Two changes rather than a weaker claim:
# the memo moves into each binding's own closure, so there is no key to
# build and no environment to search, and the search-path scan becomes
# two vector operations.

sub1("R/generic-owners.R",
paste0("#' Which owner of `gen` would the user have reached without frmtmb?\n",
       "#'\n",
       "#' Attachment order decides that, so the search path is consulted\n",
       "#' first. The `owners` order is the tie-break for owners that are\n",
       "#' loaded but not attached. Only `ngrps` and `refit` reach this; a\n",
       "#' single-owner name takes the cheap path in `frm_owner_generic()`.\n",
       "#'\n",
       "#' @noRd\n",
       "frm_adopt_target <- function(gen, owners) {\n",
       "  for (nm in search()) {\n",
       "    p <- sub(\"^package:\", \"\", nm)\n",
       "    if (!(p %in% owners)) next\n",
       "    if (exists(gen, envir = as.environment(nm), inherits = FALSE)) {\n",
       "      return(p)\n",
       "    }\n",
       "  }\n",
       "  for (p in owners) {\n",
       "    if (!isNamespaceLoaded(p)) next\n",
       "    g <- tryCatch(getExportedValue(p, gen), error = function(e) NULL)\n",
       "    if (is.function(g)) return(p)\n",
       "  }\n",
       "  NULL\n",
       "}\n"),
paste0("#' Which owner of `gen` would the user have reached without frmtmb?\n",
       "#'\n",
       "#' Attachment order decides that, so the search path is consulted\n",
       "#' first, and the owner nearest the front of it wins. The `owners`\n",
       "#' order is the tie-break for owners that are loaded but not\n",
       "#' attached.\n",
       "#'\n",
       "#' Only `ngrps` and `refit` reach this, and it runs on every ACCESS\n",
       "#' of those two names, so it is two vector operations rather than a\n",
       "#' loop with a `sub()` in it: the loop spelling measured 49.13 us\n",
       "#' per access against 1.70 us for a single-owner name.\n",
       "#'\n",
       "#' @noRd\n",
       "frm_adopt_target <- function(gen, owners) {\n",
       "  pos <- match(paste0(\"package:\", owners), search())\n",
       "  if (any(!is.na(pos))) {\n",
       "    p <- owners[which.min(ifelse(is.na(pos), Inf, pos))]\n",
       "    e <- as.environment(paste0(\"package:\", p))\n",
       "    if (exists(gen, envir = e, inherits = FALSE)) return(p)\n",
       "  }\n",
       "  for (p in owners) {\n",
       "    if (!isNamespaceLoaded(p)) next\n",
       "    g <- tryCatch(getExportedValue(p, gen), error = function(e) NULL)\n",
       "    if (is.function(g)) return(p)\n",
       "  }\n",
       "  NULL\n",
       "}\n"))

sub1("R/generic-owners.R",
paste0("#' The owner's generic for `gen`, or NULL when no owner is loaded.\n",
       "#'\n",
       "#' @noRd\n",
       "frm_owner_generic <- function(gen, owners) {\n",
       "  own <- if (length(owners) == 1L) {\n",
       "    if (isNamespaceLoaded(owners)) owners else NULL\n",
       "  } else {\n",
       "    frm_adopt_target(gen, owners)\n",
       "  }\n",
       "  if (is.null(own)) return(NULL)\n",
       "  ns <- tryCatch(asNamespace(own), error = function(e) NULL)\n",
       "  if (is.null(ns)) return(NULL)\n",
       "  key <- paste0(own, \"::\", gen)\n",
       "  memo <- frm_generic_memo[[key]]\n",
       "  if (!is.null(memo) && identical(memo$ns, ns)) return(memo$fn)\n",
       "  g <- tryCatch(getExportedValue(own, gen), error = function(e) NULL)\n",
       "  if (!frm_is_generic(g)) g <- NULL\n",
       "  assign(key, list(ns = ns, fn = g), envir = frm_generic_memo)\n",
       "  g\n",
       "}\n",
       "\n",
       "#' The value the active binding hands back.\n",
       "#'\n",
       "#' @noRd\n",
       "frm_live_generic <- function(gen, owners, fallback) {\n",
       "  g <- frm_owner_generic(gen, owners)\n",
       "  if (is.null(g)) fallback else g\n",
       "}\n",
       "\n",
       "#' Install one active binding. A function of its own, so that the loop\n",
       "#' variable is captured by value rather than by reference.\n",
       "#'\n",
       "#' @noRd\n",
       "frm_bind_generic <- function(ns, gen, owners, fallback) {\n",
       "  force(gen)\n",
       "  force(owners)\n",
       "  force(fallback)\n",
       "  makeActiveBinding(gen,\n",
       "                    function() frm_live_generic(gen, owners, fallback),\n",
       "                    ns)\n",
       "  invisible(TRUE)\n",
       "}\n"),
paste0("#' Install one active binding.\n",
       "#'\n",
       "#' A function of its own for two reasons. The loop variable is\n",
       "#' captured by value rather than by reference, and the memo lives in\n",
       "#' THIS closure rather than in a shared environment, so resolving a\n",
       "#' name costs no key to build and no environment to search. The memo\n",
       "#' holds the owner's NAMESPACE ENVIRONMENT beside the function, and\n",
       "#' validating it is an environment identity test: a namespace that\n",
       "#' was unloaded and reloaded is a different environment, so a stale\n",
       "#' instance cannot be served. That is the failure the round-1\n",
       "#' binding swap had, and it is closed here by construction rather\n",
       "#' than by a hook.\n",
       "#'\n",
       "#' @noRd\n",
       "frm_bind_generic <- function(ns, gen, owners, fallback) {\n",
       "  force(gen)\n",
       "  force(fallback)\n",
       "  single <- length(owners) == 1L\n",
       "  one <- if (single) owners[[1L]] else NULL\n",
       "  memo_ns <- NULL\n",
       "  memo_fn <- NULL\n",
       "  makeActiveBinding(gen, function() {\n",
       "    own <- if (single) {\n",
       "      if (isNamespaceLoaded(one)) one else NULL\n",
       "    } else {\n",
       "      frm_adopt_target(gen, owners)\n",
       "    }\n",
       "    if (is.null(own)) return(fallback)\n",
       "    ons <- tryCatch(asNamespace(own), error = function(e) NULL)\n",
       "    if (is.null(ons)) return(fallback)\n",
       "    if (!identical(ons, memo_ns)) {\n",
       "      g <- tryCatch(getExportedValue(own, gen),\n",
       "                    error = function(e) NULL)\n",
       "      # a name an owner exports need not be a GENERIC; if it is not,\n",
       "      # frmtmb keeps its own or its method for its own class goes\n",
       "      # unreachable with nothing said\n",
       "      if (!frm_is_generic(g)) g <- NULL\n",
       "      memo_ns <<- ons\n",
       "      memo_fn <<- g\n",
       "    }\n",
       "    if (is.null(memo_fn)) fallback else memo_fn\n",
       "  }, ns)\n",
       "  invisible(TRUE)\n",
       "}\n"))

# the shared memo environment is gone with it
sub1("R/generic-owners.R",
paste0("#' Memo for the resolved owner generics, keyed `owner::generic`.\n",
       "#'\n",
       "#' Each entry holds the owner's NAMESPACE ENVIRONMENT beside the\n",
       "#' function. Validating the memo is then an environment identity test,\n",
       "#' which is a pointer comparison, and a namespace that was unloaded and\n",
       "#' reloaded is a different environment, so the memo cannot serve a\n",
       "#' stale instance. That is the failure the swapped-binding version had.\n",
       "#'\n",
       "#' @noRd\n",
       "frm_generic_memo <- new.env(parent = emptyenv())\n",
       "\n"),
"")

# and the cost claim in the header stops being an adjective
sub1("R/generic-owners.R",
paste0("# The cost is one closure call per ACCESS of the name instead of one\n",
       "# per session. It is measured in dev/generics-adoptcost.R, and it is\n",
       "# small next to any call it gates, because the memo below reduces the\n",
       "# steady state to an `isNamespaceLoaded()` and an environment identity\n",
       "# test.\n"),
paste0("# The cost is one closure call per ACCESS of the name instead of one\n",
       "# per session, and it is a real cost rather than a rounding error:\n",
       "# see dev/generics-adoptcost.R for the number on this box, measured\n",
       "# against an ordinary binding lookup and against one `fixef()` call.\n",
       "# These names are reached once per user action, not in a loop, so\n",
       "# the trade is the right one; it is stated rather than waved away\n",
       "# because the first spelling of this file called it small and the\n",
       "# measurement did not agree.\n"))
cat("DONE\n")
