source("C:/Users/adf44/source/r/frmtmb-wt-generics/dev/generics-sub.R")
p <- "tests/testthat/test-generic-collision.R"

# The header now describes the mechanism that shipped, and the probe
# stops reading error strings.
sub1(p,
paste0("# Measured against the 0.55.2 code this replaces (dev/generics-out,\n",
       "# dev/generics-summary.R): `library(brms); library(frmtmb)` cost brms 25\n",
       "# of the 27 shared generics its own dispatch and all 27 of\n",
       "# `getS3method()`, and `library(lme4); library(frmtmb)` cost lme4 all 5\n",
       "# of the names they share.\n"),
paste0("# Measured against the 0.55.2 code this replaces (dev/generics-out2,\n",
       "# dev/generics-summary.R): `library(brms); library(frmtmb)` cost brms\n",
       "# ALL 27 of the generics the two share, two of them SILENTLY by\n",
       "# falling into frmtmb's own `.default`, and all 27 of\n",
       "# `getS3method()`; `library(lme4); library(frmtmb)` cost lme4 all 5 of\n",
       "# the names they share.\n",
       "#\n",
       "# The probe below asks whether the CLASS method is reachable, not\n",
       "# whether the call errors. An earlier version matched the string \"no\n",
       "# applicable method\", and that scored the two silent cases as healthy\n",
       "# and scored a REGRESSION on `frmtmb_fit` as an improvement, because\n",
       "# the replacement error did not contain the string it tested for.\n"))

sub1(p,
paste0("    \"bad <- character(); nom <- character()\",\n",
       "    \"for (g in gens) {\",\n",
       "    \"  m <- tryCatch(getS3method(g, class(obj), optional = TRUE),\",\n",
       "    \"                error = function(e) NULL)\",\n",
       "    \"  if (is.null(m)) nom <- c(nom, g)\",\n",
       "    \"  r <- tryCatch({ do.call(g, list(obj)); TRUE },\",\n",
       "    \"    error = function(e) !grepl(paste0(\\\"no applicable method for '\\\",\",\n",
       "    \"      g, \\\"'\\\"), conditionMessage(e), fixed = TRUE))\",\n",
       "    \"  if (!isTRUE(r)) bad <- c(bad, g)\",\n",
       "    \"}\",\n"),
paste0("    \"bad <- character(); nom <- character()\",\n",
       "    \"# UseMethod()'s own lookup: the method table of the namespace\",\n",
       "    \"# where the generic that was REACHED is defined.\",\n",
       "    \"reach <- function(gen, k) {\",\n",
       "    \"  f <- tryCatch(get(gen), error = function(e) NULL)\",\n",
       "    \"  if (!is.function(f)) return(NA_character_)\",\n",
       "    \"  e <- environment(f)\",\n",
       "    \"  if (is.null(e)) e <- baseenv()\",\n",
       "    \"  if (!exists('.__S3MethodsTable__.', envir = e,\",\n",
       "    \"              inherits = FALSE)) return(NA_character_)\",\n",
       "    \"  tb <- get('.__S3MethodsTable__.', envir = e, inherits = FALSE)\",\n",
       "    \"  nm <- paste0(gen, '.', k)\",\n",
       "    \"  if (exists(nm, envir = tb, inherits = FALSE)) 'yes' else NA\",\n",
       "    \"}\",\n",
       "    \"for (g in gens) {\",\n",
       "    \"  m <- tryCatch(getS3method(g, class(obj), optional = TRUE),\",\n",
       "    \"                error = function(e) NULL)\",\n",
       "    \"  if (is.null(m)) nom <- c(nom, g)\",\n",
       "    \"  if (is.na(reach(g, class(obj)))) bad <- c(bad, g)\",\n",
       "    \"}\",\n"))

# ---- the load orders review built that this file did not run --------
extra <- paste0(
'\n',
'test_that("an owner unloaded and reloaded does not leave a stale generic", {\n',
'  # The construction that broke the round-1 mechanism. A binding\n',
'  # SWAPPED once is a hard reference to one namespace instance, so\n',
'  # unloading loo and letting something else pull a fresh one left\n',
'  # frmtmb dispatching into a dead method table with nothing said.\n',
'  # An active binding re-resolves on every access; this pins that.\n',
'  skip_on_cran()\n',
'  skip_if_not_installed("loo")\n',
'  skip_if_not_installed("brms")\n',
'  out <- run_child(c(\n',
'    "suppressMessages(library(loo))",\n',
'    "suppressMessages(library(frmtmb))",\n',
'    "detach(\'package:loo\'); unloadNamespace(\'loo\')",\n',
'    "suppressMessages(loadNamespace(\'brms\'))",\n',
'    "g <- get(\'loo\')",\n',
'    "cat(\'ENV:\', environmentName(topenv(environment(g))), \'\\\\n\')",\n',
'    "cat(\'STALE:\', !identical(g, loo::loo), \'\\\\n\')",\n',
'    "cat(\'BRMSFIT:\', !is.null(getS3method(\'loo\', \'brmsfit\',",\n',
'    "                                    optional = TRUE)), \'\\\\n\')",\n',
'    "cat(\'CHILDOK\\\\n\')"))\n',
'  expect_match(out, "CHILDOK", fixed = TRUE)\n',
'  expect_equal(parse_field(out, "ENV"), "loo")\n',
'  expect_equal(parse_field(out, "STALE"), "FALSE")\n',
'  expect_equal(parse_field(out, "BRMSFIT"), "TRUE")\n',
'})\n',
'\n',
'test_that("the repair survives detach and reattach in both packages", {\n',
'  skip_on_cran()\n',
'  skip_if_not_installed("brms")\n',
'  out <- run_child(c(\n',
'    "suppressMessages(library(brms)); suppressMessages(library(frmtmb))",\n',
'    "detach(\'package:frmtmb\'); suppressMessages(library(frmtmb))",\n',
'    "detach(\'package:brms\'); suppressMessages(library(brms))",\n',
'    "cat(\'LOO:\', environmentName(topenv(environment(get(\'loo\')))), \'\\\\n\')",\n',
'    "cat(\'CE:\', environmentName(topenv(environment(",\n',
'    "      get(\'conditional_effects\')))), \'\\\\n\')",\n',
'    "cat(\'M:\', !is.null(getS3method(\'conditional_effects\', \'brmsfit\',",\n',
'    "                              optional = TRUE)), \'\\\\n\')",\n',
'    "cat(\'CHILDOK\\\\n\')"))\n',
'  expect_match(out, "CHILDOK", fixed = TRUE)\n',
'  expect_equal(parse_field(out, "LOO"), "loo")\n',
'  expect_equal(parse_field(out, "CE"), "brms")\n',
'  expect_equal(parse_field(out, "M"), "TRUE")\n',
'})\n',
'\n',
'test_that("the binding is ACTIVE, and stays active through a re-export", {\n',
'  # The mechanism, stated where it can fail. Active-ness propagating\n',
'  # through importIntoEnv() is what carries the repair into a package\n',
'  # that re-exports the name from frmtmb, which a swapped binding\n',
'  # could not do. If this stops being an active binding, the\n',
'  # re-export residue comes back and only this assertion says so.\n',
'  skip_on_cran()\n',
'  out <- run_child(c(\n',
'    "suppressMessages(library(frmtmb))",\n',
'    "ns <- asNamespace(\'frmtmb\')",\n',
'    "cat(\'NS:\', bindingIsActive(\'loo\', ns), \'\\\\n\')",\n',
'    "cat(\'ATT:\', bindingIsActive(\'loo\',",\n',
'    "      as.environment(\'package:frmtmb\')), \'\\\\n\')",\n',
'    "cat(\'UNLOCKED:\', any(grepl(\'unlockBinding\',",\n',
'    "      unlist(lapply(ls(ns), function(n) {",\n',
'    "        f <- get0(n, envir = ns); if (is.function(f))",\n',
'    "          paste(deparse(body(f)), collapse = \' \') else \'\' })),",\n',
'    "      fixed = TRUE)), \'\\\\n\')",\n',
'    "cat(\'CHILDOK\\\\n\')"))\n',
'  expect_match(out, "CHILDOK", fixed = TRUE)\n',
'  expect_equal(parse_field(out, "NS"), "TRUE")\n',
'  expect_equal(parse_field(out, "ATT"), "TRUE")\n',
'  # and no unlockBinding() anywhere in the namespace, which is the\n',
'  # R CMD check NOTE this design exists to avoid\n',
'  expect_equal(parse_field(out, "UNLOCKED"), "FALSE")\n',
'})\n',
'\n',
'test_that("an owner that exports a NON-generic does not take the name", {\n',
'  # frm_owner_generic() checks that the owner\'s export is a GENERIC,\n',
'  # not merely a function. Built rather than assumed: a shadow\n',
'  # `posterior` whose `ndraws` is a plain function must NOT displace\n',
'  # frmtmb\'s, or frmtmb\'s own method for its own class would become\n',
'  # unreachable with nothing said.\n',
'  skip_on_cran()\n',
'  lib <- file.path(tempdir(), "frmtmb-nongeneric-owner")\n',
'  dir.create(file.path(lib, "posterior", "R"), recursive = TRUE,\n',
'             showWarnings = FALSE)\n',
'  on.exit(unlink(lib, recursive = TRUE), add = TRUE)\n',
'  d <- file.path(lib, "posterior")\n',
'  writeLines(c("Package: posterior", "Version: 99.0",\n',
'               "Title: A deliberately non-generic ndraws",\n',
'               "Author: t", "Maintainer: t <t@t.tt>",\n',
'               "Description: t.", "License: GPL-2",\n',
'               "Built: R 4.6.1; ; ; windows"),\n',
'             file.path(d, "DESCRIPTION"))\n',
'  writeLines("export(ndraws)", file.path(d, "NAMESPACE"))\n',
'  code <- file.path(d, "R", "posterior")\n',
'  writeLines("ndraws <- function(x) 42", code)\n',
'  out <- run_child(c(\n',
'    sprintf(".libPaths(c(%s, .libPaths()))", deparse(lib)),\n',
'    "ok <- tryCatch({ loadNamespace(\'posterior\'); TRUE },",\n',
'    "               error = function(e) FALSE)",\n',
'    "cat(\'SHADOWLOADED:\', ok, \'\\\\n\')",\n',
'    "suppressMessages(library(frmtmb))",\n',
'    "cat(\'NDRAWS:\', environmentName(topenv(environment(",\n',
'    "      get(\'ndraws\')))), \'\\\\n\')",\n',
'    "cat(\'CHILDOK\\\\n\')"))\n',
'  expect_match(out, "CHILDOK", fixed = TRUE)\n',
'  if (identical(parse_field(out, "SHADOWLOADED"), "TRUE")) {\n',
'    # the shadow loaded and exports a plain function: frmtmb must\n',
'    # keep its own generic rather than adopt it\n',
'    expect_equal(parse_field(out, "NDRAWS"), "frmtmb")\n',
'  } else {\n',
'    skip("the shadow package would not load on this machine")\n',
'  }\n',
'})\n')
txt <- rawToChar(readBin(file.path(
  "C:/Users/adf44/source/r/frmtmb-wt-generics", p), "raw",
  file.info(file.path("C:/Users/adf44/source/r/frmtmb-wt-generics",
                      p))$size))
writeBin(charToRaw(paste0(txt, extra)),
         file.path("C:/Users/adf44/source/r/frmtmb-wt-generics", p))
cat("appended 4 load-order blocks\n")
cat("DONE\n")
