# Reads dev/generics-out2/*.txt and emits the counts as a block to be
# pasted verbatim into dev/generics-findings.md.  The lane rule is that
# a count is generated by the summarizer, never typed.
#
# Three traps this file was written around, all of which had already
# produced a wrong number here.
#
#  * Fields are read at FIXED WIDTHS, not by splitting on whitespace.
#    The first draft split on whitespace, the dispatch column held
#    "NO METHOD" with a space in it, and every broken row was dropped:
#    2 rows reported where 28 existed, which read as "no damage" on the
#    UNFIXED build.
#  * A generic the control does not have AT ALL is not damage.  With
#    brms alone, `refit` is not on the search path; rows whose control
#    column does not resolve a class method are dropped.
#  * DAMAGE IS NOT AN ERROR MESSAGE.  It is the loss of the class
#    method.  The second draft counted an error string, so the two
#    names where the call falls SILENTLY into frmtmb's own `.default`,
#    `posterior_summary` and `loo_compare`, scored as healthy and the
#    base damage came out 25 of 27 instead of 27 of 27.  The probe now
#    reports which package supplies the method and whether it matched
#    the class or `default`, and those two are counted and named.
root <- "C:/Users/adf44/source/r/frmtmb-wt-generics"
dir <- file.path(root, "dev", "generics-out2")
W <- c(1, 20, 22, 33, 35, 46, 48, 57, 59, 64)

rd <- function(f) {
  p <- file.path(dir, paste0(f, ".txt"))
  if (!file.exists(p)) return(NULL)
  ln <- readLines(p, warn = FALSE)
  i <- grep("^generic ", ln)[1]
  j <- grep("^$|^-- frmtmb_fit|^DONE", ln[-seq_len(i)])[1] + i
  body <- ln[(i + 1):(j - 1)]
  fld <- function(k) trimws(substr(body, W[2 * k - 1], W[2 * k]))
  out <- data.frame(gen = fld(1), gfrom = fld(2), mfrom = fld(3),
                    how = fld(4), getS3 = fld(5),
                    stringsAsFactors = FALSE)
  out <- out[nzchar(out$gen), , drop = FALSE]
  attr(out, "tail") <- ln[grepl(
    "^FITMETHOD_NOT_OURS|^FITMETHOD_LIST|^REFIT_OK|^NGRPS|^POSTSUMMARY",
    ln)]
  attr(out, "msg") <- ln[grepl("^MSG ", ln)]
  out
}

cmp <- function(ctrl, test, label, k) {
  a <- rd(ctrl); b <- rd(test)
  if (is.null(a) || is.null(b)) {
    cat(sprintf("%-26s MISSING\n", label)); return(invisible())
  }
  m <- merge(a, b, by = "gen", suffixes = c(".c", ".t"))
  m <- m[m$how.c == k, , drop = FALSE]
  lost <- m$how.t != k
  silent <- m$how.t == "default"
  gs <- m$getS3.c == "TRUE" & m$getS3.t == "FALSE"
  cat(sprintf("%-26s class-method lost %2d/%d  getS3method lost %2d/%d\n",
              label, sum(lost), nrow(m), sum(gs), nrow(m)))
  if (any(silent)) {
    cat("    SILENTLY answered by a .default instead: ",
        paste(m$gen[silent], collapse = ", "), "\n")
  }
  if (any(lost & !silent)) {
    cat("    no method at all:  ",
        paste(m$gen[lost & !silent], collapse = ", "), "\n")
  }
  invisible()
}

cat("```\n")
cat("== Phase 2.5 generic-collision measurement ==\n")
cat("dev/generics-check.R + dev/generics-summary.R; ONE PROCESS PER ROW\n")
cat("seed 20260915, R 4.6.1, brms 2.23.0, lme4 2.0.6\n")
cat("DAMAGE is the loss of the CLASS method, found by reproducing\n")
cat("UseMethod()'s lookup in the method table of environment(generic),\n")
cat("not by reading an error message. The denominator is the generics\n")
cat("for which the control resolves a class method.\n\n")
cat("BASE = base commit, SWAP = round 1, FIX = the active binding\n\n")
cmp("base-X", "base-A", "BASE  brms then frmtmb", "brmsfit")
cmp("base-X", "swap-A", "SWAP  brms then frmtmb", "brmsfit")
cmp("base-X", "fix-A",  "FIX   brms then frmtmb", "brmsfit")
cmp("base-X", "base-B", "BASE  frmtmb then brms", "brmsfit")
cmp("base-X", "swap-B", "SWAP  frmtmb then brms", "brmsfit")
cmp("base-X", "fix-B",  "FIX   frmtmb then brms", "brmsfit")
cmp("base-X", "base-D", "BASE  brms loaded only", "brmsfit")
cmp("base-X", "swap-D", "SWAP  brms loaded only", "brmsfit")
cmp("base-X", "fix-D",  "FIX   brms loaded only", "brmsfit")
cmp("base-M", "base-L", "BASE  lme4 then frmtmb", "merMod")
cmp("base-M", "swap-L", "SWAP  lme4 then frmtmb", "merMod")
cmp("base-M", "fix-L",  "FIX   lme4 then frmtmb", "merMod")
cat("\nfrmtmb's OWN methods on a frmtmb_fit: does the method that\n")
cat("would run belong to frmtmb? A foreign .default is a FAILURE.\n")
for (f in c("base-A", "swap-A", "fix-A", "base-C", "swap-C",
            "fix-C", "base-D", "swap-D", "fix-D", "base-L",
            "swap-L", "fix-L")) {
  x <- rd(f)
  if (is.null(x)) next
  cat(sprintf("  %-8s %s\n", f, paste(attr(x, "tail"), collapse = " | ")))
}
cat("\nthe message a frmtmb_fit gets from two of the six that regressed:\n")
for (f in c("base-A", "swap-A", "fix-A")) {
  x <- rd(f)
  if (is.null(x)) next
  for (m in attr(x, "msg")) cat(sprintf("  %-8s %s\n", f, m))
}
cat("\nwhich namespace each generic resolves to:\n")
for (f in c("base-A", "fix-A", "fix-B", "fix-C", "fix-D", "fix-L")) {
  x <- rd(f)
  if (is.null(x)) next
  tb <- table(x$gfrom)
  cat(sprintf("  %-8s %s\n", f,
              paste(sprintf("%s=%d", names(tb), as.integer(tb)),
                    collapse = " ")))
}
cat("```\n")
