# Lane `learnhier`: every COUNT in the findings, derived from files and
# written into the document mechanically.
#
#   Rscript dev/learnhier-counts.R
#
# WHY THIS EXISTS. This lane caught itself writing "24 of 24 settled"
# into the findings when 9 files existed: the number came from the
# planned count rather than from the results. The lane's verifier could
# not catch it, because the verifier checks FILES and that was a
# SENTENCE. A number typed by hand is a number with no provenance.
#
# So no count is typed into dev/learnhier-findings.md any more. This
# script derives them all from the result directories and replaces the
# block between the two markers below. Re-run it and the document is
# correct by construction; forget to re-run it and the block still says
# when it was generated and from how many files.
source("dev/learnhier-env.R")

BEGIN <- "<!-- COUNTS:BEGIN -->"
END <- "<!-- COUNTS:END -->"
DOC <- "dev/learnhier-findings.md"

rd <- function(dir, pat) {
  fs <- list.files(dir, pattern = pat, full.names = TRUE)
  lapply(fs, readRDS)
}

out <- c(BEGIN,
         paste0("<!-- generated by dev/learnhier-counts.R at ",
                format(Sys.time(), "%Y-%m-%d %H:%M"),
                "; do not edit by hand -->"),
         "",
         "| arm | design | files | distinct seeds | gaps | notes |",
         "|---|---|---|---|---|---|")

arm_row <- function(label, dir, design, extra = "") {
  R <- rd(dir, paste0("^", design, "-[0-9]+[.]rds$"))
  if (!length(R)) {
    return(paste0("| ", label, " | `", design, "` | 0 | 0 | n/a | not ",
                  "run |"))
  }
  sd_all <- vapply(R, function(r) r$seed, numeric(1))
  grid <- seq(min(sd_all), max(sd_all), by = 10)
  gaps <- length(setdiff(grid, sd_all))
  ok <- vapply(R, function(r) isTRUE(r$ok), TRUE)
  conv <- sum(vapply(R[ok], function(r) r$conv == 0L, TRUE))
  pdh <- sum(vapply(R[ok], function(r) isTRUE(r$pdHess), TRUE))
  nan <- sum(vapply(R[ok], function(r) r$n_bad_se, numeric(1)))
  nt <- unique(vapply(R, function(r) r$nt, numeric(1)))
  paste0("| ", label, " | `", design, "`, ", paste(nt, collapse = "/"),
         " trials | ", length(R), " | ", length(unique(sd_all)), " | ",
         if (gaps) paste0("**", gaps, "**") else "none",
         " | convergence code 0 on ", conv, ", positive definite ",
         "Hessian on ", pdh, ", NaN standard errors ", nan, extra, " |")
}

out <- c(out,
         arm_row("main, correlated truth", "dev/learnhier-rec", "bandit"),
         arm_row("main, diagonal truth", "dev/learnhier-rec", "bandit0"),
         arm_row("main", "dev/learnhier-rec", "rlddm"),
         arm_row("Test 2, 100 trials", "dev/learnhier-rec-nt100",
                 "rlddm"),
         arm_row("five-parameter probe", "dev/learnhier-rec5", "rlddm5"))

I <- rd("dev/learnhier-imp", "^imp-.*[.]rds$")
if (length(I)) {
  oc <- vapply(I, function(r) r$outcome %||% "NA", character(1))
  n <- length(oc)
  nset <- sum(oc == "settled")
  bound <- if (nset == n) {
    paste0(round(100 * (1 - 0.05^(1 / n)), 1), " percent")
  } else {
    paste0("n/a, ", n - nset, " not settled")
  }
  sp <- vapply(I, function(r) r$spread %||% NA_real_, numeric(1))
  # wrapped to 72 columns: this block is pasted into a markdown file
  # that the house style holds to 80
  para <- function(...) strwrap(paste0(...), width = 72)
  out <- c(out, "",
           para("The importance correction: **", nset, " of ", n,
                " settled**, counted with `frmtmb:::imp_stalled()`."),
           "",
           para("Rule-of-three upper bound on the failure rate at this ",
                "count: **", bound, "** at 95 percent confidence."),
           "",
           para("Round-to-round spreads ",
                format(min(sp, na.rm = TRUE), digits = 3), " to ",
                format(max(sp, na.rm = TRUE), digits = 3), ", which is ",
                format(min(sp, na.rm = TRUE) / 1e-2, digits = 3),
                "x the `imp_stall_tol` threshold and ",
                format(min(sp, na.rm = TRUE) / 2.10e-2, digits = 3),
                "x the narrowest still-moving spread the 184-fit ",
                "review measured."))
}
out <- c(out, END)

doc <- readLines(DOC, warn = FALSE)
b <- match(BEGIN, doc)
e <- match(END, doc)
if (is.na(b) || is.na(e)) {
  stop("markers not found in ", DOC, "; add ", BEGIN, " and ", END)
}
writeLines(c(doc[seq_len(b - 1L)], out, doc[seq.int(e + 1L, length(doc))]),
           DOC)
cat("rewrote the counts block in ", DOC, "\n", sep = "")
cat(paste(out, collapse = "\n"), "\n")
