SP="C:/Users/adf44/AppData/Local/Temp/1/claude/c--Users-adf44-source-r-frmtmb/529b6e73-d28f-46aa-a279-7dbeeb58fd4f/scratchpad"
LKLIB="$SP/lk-lib"
ULIB="C:/Users/adf44/AppData/Local/R/win-library/4.6"
RS="C:/Program Files/R/R-4.6.1/bin/Rscript.exe"
WT="C:/Users/adf44/source/r/frmtmb-wt-links"
export R_LIBS="$LKLIB;$ULIB"
export R_LIBS_USER="$LKLIB"
export FRMTMB_BRMS_FIT_TESTS=true
export NOT_CRAN=true
export FRMTMB_STAN_CACHE="$SP/lk-stan-cache"
export R_MAKEVARS_USER="$SP/lk-makevars-cxx17.mk"
