# dev/pdi-guard.R -- can frmtmb detect a miscompiled tmbstan cheaply?
#
# Two candidate guards, tested against the broken container tmbstan:
#   (1) static: count the std_normal placeholder left in the model.hpp that
#       tmbstan installs beside itself. No sampling, no side effects.
#   (2) numeric: compare rstan::grad_log_prob() on the returned stanfit with
#       -obj$gr(). The reverse-mode path is the one that loses the objective,
#       so the GRADIENT is the discriminating quantity; log_prob() alone is
#       not, because the double-precision overload IS patched.
#
#   Rscript dev/pdi-guard.R

options(warn = 1, digits = 12)
suppressPackageStartupMessages({
  library(RTMB)
  library(tmbstan)
})

hpp <- system.file("model.hpp", package = "tmbstan")
src <- readLines(hpp, warn = FALSE)
left <- sum(grepl("std_normal_lpdf<propto__>(y)", src, fixed = TRUE))
cat("### static guard\n")
cat("tmbstan model.hpp: ", hpp, "\n", sep = "")
cat("stanc line: ", grep("generated by stanc", src, value = TRUE)[1], "\n",
    sep = "")
cat("unpatched std_normal placeholders left: ", left, "  -> ",
    if (left > 0) "MISCOMPILED" else "ok", "\n", sep = "")

set.seed(7)
y <- rnorm(20, mean = 3, sd = 1)
f <- function(pars) -sum(RTMB::dnorm(y, pars$mu, 1, log = TRUE))
o <- RTMB::MakeADFun(f, list(mu = 0), silent = TRUE)
o$fn(o$par)

s <- tmbstan::tmbstan(o, chains = 1, iter = 20, warmup = 10, seed = 1,
                      init = "0", refresh = 0)

cat("\n### numeric guard\n")
for (v in c(0, 1, 2)) {
  lp <- rstan::log_prob(s, v)
  gr <- rstan::grad_log_prob(s, v)
  cat(sprintf("mu=%4.1f  stan_lp=%14.8f  tmb_lp=%14.8f | stan_gr=%14.8f  tmb_gr=%14.8f\n",
              v, lp, -o$fn(v), gr, -o$gr(v)))
}
cat("\n##### done\n")
