# Nothing else moved: the base test files on the base build (arm A)
# against the same files on the lane build (arm B), one row per
# test_that() block, compared on assertion counts, failures, errors and
# skips. Also the totals of arm C (lane files, lane build).
lg <- "C:/Users/adf44/source/r/frmtmb-wt-phase3a/dev/phase3a-log/"
rd <- function(lab) {
  f <- paste0(lg, "suite-", lab, ".tsv")
  # a test name can span lines; a record starts with its arm
  l <- readLines(f)
  start <- grepl("^(arm|base|lane)	", l)
  l <- vapply(split(l, cumsum(start)), paste, "", collapse = " ")
  x <- utils::read.delim(text = l, stringsAsFactors = FALSE, quote = "")
  x$key <- paste(x$file, x$test, sep = " :: ")
  x
}
cat("<!-- generated by dev/phase3a-compare.R -->\n")
for (p in c("frmtmb.ode", "frmtmb.coupling", "frmtmb.spline")) {
  a <- rd(paste0("base-", p)); b <- rd(paste0("lanebasetests-", p))
  cc <- tryCatch(rd(paste0("lane-", p)), error = function(e) NULL)
  m <- merge(a, b, by = "key", all = TRUE, suffixes = c(".a", ".b"))
  cols <- c("nb", "passed", "failed", "error", "skipped", "warning")
  diff <- m[Reduce(`|`, lapply(cols, function(k) {
    !(m[[paste0(k, ".a")]] %in% m[[paste0(k, ".b")]] &
        m[[paste0(k, ".b")]] %in% m[[paste0(k, ".a")]]) |
      xor(is.na(m[[paste0(k, ".a")]]), is.na(m[[paste0(k, ".b")]])) |
      (m[[paste0(k, ".a")]] != m[[paste0(k, ".b")]]) %in% TRUE
  })), , drop = FALSE]
  tot <- function(x) sprintf("files %d, blocks %d, pass %d, fail %d, error %d, skip %d, warn %d",
                             length(unique(x$file)), nrow(x), sum(x$passed),
                             sum(x$failed), sum(as.logical(x$error)),
                             sum(as.logical(x$skipped)), sum(x$warning))
  cat("\n##", p, "\n")
  cat("A base build, base tests: ", tot(a), "\n")
  cat("B lane build, base tests: ", tot(b), "\n")
  cat("C lane build, lane tests: ", tot(cc), "\n")
  cat("blocks that differ between A and B:", nrow(diff), "\n")
  if (nrow(diff)) {
    print(diff[, c("key", "passed.a", "failed.a", "passed.b", "failed.b",
                   "error.a", "error.b", "warning.a", "warning.b")],
          row.names = FALSE)
  }
}
cat("<!-- end generated -->\n")
