# Summarise the item 3.6 false-alarm runs into a block pasted verbatim
# into dev/phase3a-findings.md. Counts are read from the tsv rows, never
# from the launch grid.
.libPaths(c("C:/Users/adf44/AppData/Local/R/win-library/4.6"))
lg <- "C:/Users/adf44/source/r/frmtmb-wt-phase3a/dev/phase3a-log"
sim <- utils::read.delim(file.path(lg, "phase3a-fa36-sim.tsv"))
real <- utils::read.delim(file.path(lg, "phase3a-fa36-real.tsv"))
cp_upper <- function(k, n) stats::binom.test(k, n)$conf.int[2L]
block <- function(x, label) {
  ok <- x[x$status == "ok", ]
  cat(sprintf("%s: %d rows, %d fitted, %d fit errors\n", label, nrow(x),
              nrow(ok), sum(x$status != "ok")))
  cat(sprintf("  nlminb code 0 on %d of %d\n", sum(ok$conv == 0), nrow(ok)))
  cat(sprintf("  0.7.0 check fires (event rows): %d of %d\n", sum(ok$old),
              nrow(ok)))
  cat(sprintf("  widened check fires: %d of %d\n", sum(ok$new), nrow(ok)))
  cat(sprintf(paste0("  fires ONLY because of the widening: %d of %d, ",
                     "95%% upper bound %.4f\n"),
              sum(ok$new_only), nrow(ok), cp_upper(sum(ok$new_only),
                                                   nrow(ok))))
  cat(sprintf("  fit-end censored-row warning raised: %d of %d\n",
              sum(ok$fitend_warn_cens), nrow(ok)))
  if (!is.null(ok$gate)) {
    g <- table(factor(ok$gate, levels = c("refuse", "warn", "silent")))
    cat(sprintf("  rp_floored(): refuse %d, warn %d, silent %d of %d\n",
                g[["refuse"]], g[["warn"]], g[["silent"]], nrow(ok)))
  }
  cat(sprintf("  smallest d(eta)/d(log t) on any censored row: %.4g\n",
              min(ok$min_detadx_cens, na.rm = TRUE)))
  tab <- stats::aggregate(cbind(fits = 1, old = ok$old, new = ok$new,
                                new_only = ok$new_only) ~ df + form,
                          data = ok, FUN = sum)
  print(tab[order(tab$form, tab$df), ], row.names = FALSE)
  if (any(ok$new == 1)) {
    cat("  fits that fire:\n")
    print(ok[ok$new == 1, c("design", "seed", "n", "df", "scale", "form",
                            "conv", "n_nonmono", "n_nonmono_cens")],
          row.names = FALSE)
  }
  if (any(x$status != "ok")) {
    print(x[x$status != "ok", c("design", "seed", "df", "scale", "form",
                                "msg")], row.names = FALSE)
  }
  cat("\n")
}
cat("<!-- generated by dev/phase3a-fa36-report.R -->\n")
block(sim, "simulated")
cat("censoring fraction by design (simulated):\n")
print(stats::aggregate(cens_frac ~ design + n, data = sim, FUN = mean),
      row.names = FALSE, digits = 3)
cat("\n")
block(real, "real")
cat("rows and censoring fraction (real):\n")
print(unique(real[, c("design", "n", "cens_frac")]), row.names = FALSE)
cat("<!-- end generated -->\n")
