.libPaths(c("C:/Users/adf44/source/r/wt-postfit2-lib","C:/Users/adf44/source/r/rellib-r3","C:/Users/adf44/AppData/Local/R/win-library/4.6"))
suppressMessages({library(frmtmb); library(frmtmb.sample)})
set.seed(22)
db <- data.frame(x = rnorm(160), g = factor(rep(1:8, 20)), h = factor(rep(1:10, each = 16)))
db$y <- rnorm(160, 1 + 0.5 * db$x + rnorm(8, 0, 2)[db$g] + rnorm(10, 0, 0.5)[db$h], 1)
fb <- frm(bf(y ~ x + (1 | g) + (1 | h)), family = gaussian(), data = db)
print(brms_par_labels(fb)); print(fb$estimates$theta)
fs <- frm(bf(y ~ x + (1 | g), sigma ~ (1 | g)), family = gaussian(), data = db)
print(brms_par_labels(fs))
db$o <- cut(db$y, quantile(db$y, c(0, .3, .6, 1)), include.lowest = TRUE, ordered_result = TRUE)
fo <- frm(bf(o ~ x + (1 | g)), family = cumulative(), data = db)
print(brms_par_labels(fo)); print(fo$estimates)
