.libPaths(c("C:/Users/adf44/source/r/wt-postfit2-lib", "C:/Users/adf44/source/r/rellib-r3", "C:/Users/adf44/AppData/Local/R/win-library/4.6"))
suppressMessages(library(frmtmb))
set.seed(21)
d <- data.frame(x = stats::rnorm(80), g = factor(rep(1:8, 10)))
d$y <- stats::rnorm(80, 1 + 0.5 * d$x + stats::rnorm(8, 0, 2)[d$g], 1)
fit <- frm(bf(y ~ x + (1 | g)), family = gaussian(), data = d)
cond <- list(g = factor("1", levels = levels(d$g)))
pop <- conditional_effects(fit, "x", resolution = 3, conditions = cond, band = "boot", boot = 5, seed = 2)
obs <- conditional_effects(fit, "x", resolution = 3, re_formula = NULL, conditions = cond, band = "boot", boot = 5, seed = 2)
kp <- unserialize(attr(pop, "boot")$ce_key); ko <- unserialize(attr(obs, "boot")$ce_key)
for (nm in names(kp)) cat(nm, identical(kp[[nm]], ko[[nm]]), "\n")
str(kp$grids[[1]]$nd); str(ko$grids[[1]]$nd)
ns <- asNamespace("frmtmb")
fn <- get("ce_boot_key", envir = ns)
print(body(fn))
sb <- function(o) serialize(o, NULL, xdr = FALSE)
for (nm in names(kp)) cat("bytes", nm, identical(sb(kp[[nm]]), sb(ko[[nm]])), "\n")
g1 <- kp$grids[[1]]; g2 <- ko$grids[[1]]
for (nm in names(g1)) cat("grid part", nm, identical(sb(g1[[nm]]), sb(g2[[nm]])), "\n")
for (nm in names(g1$nd)) cat("nd col", nm, identical(sb(g1$nd[[nm]]), sb(g2$nd[[nm]])), "\n")
cat("levels bytes", identical(sb(levels(g1$nd$g)), sb(levels(g2$nd$g))), "\n")
cat("cset bytes", identical(sb(g1$cset), sb(g2$cset)), "\n")
