.libPaths(c("C:/Users/adf44/source/r/wt-postfit2-lib", "C:/Users/adf44/source/r/rellib-r3", "C:/Users/adf44/AppData/Local/R/win-library/4.6"))
suppressMessages(library(frmtmb))
set.seed(47)
d7 <- data.frame(x = runif(200), g = factor(rep(1:5, 40)))
d7$y <- sin(2 * pi * d7$x) + rnorm(5, 0, 0.5)[d7$g] + rnorm(200, 0, 0.3)
f7 <- frm(bf(y ~ s(x, g, bs = "fs", k = 5)), family = gaussian(), data = d7)
for (bk in f7$frame$re_blocks) str(bk[c("group_name", "covstruct", "term_label")])
str(f7$frame$linpreds[[1]]$smooths[[1]]$sm[c("fterm", "flev", "term", "by", "label")])
run <- function(e) { r <- tryCatch(e, error = function(e) e); if (inherits(r, "error")) cat("ERROR", conditionMessage(r), "\n") else print(r$x[, c("g", "estimate__", "se__")]) }
for (g in c("2", "99")) for (rf in list(NULL, NA)) run(conditional_effects(f7, "x", resolution = 3, re_formula = rf, conditions = list(g = g)))
run(conditional_effects(f7, "x", resolution = 3, re_formula = NULL))
nd <- data.frame(x = 0.5, g = factor("99", levels = c(1:5, "99")))
print(tryCatch(frm_linpred(f7, newdata = nd, allow_new_levels = TRUE, se.fit = TRUE), error = function(e) conditionMessage(e)))
print(tryCatch(frm_linpred(f7, newdata = nd, allow_new_levels = FALSE, se.fit = TRUE), error = function(e) conditionMessage(e)))
