# The gated tiers: brms fit tests, brms's own bin-1 suite, the BCM
# chapters, the RL identity, the fuzz grammar tier, and the sampler
# files. One R process per file. Reports how many files actually
# produced a RESULT line, because a driver that prints a completion
# marker over zero work has happened three times in this project.

# "Stop" only while checking preconditions. It must NOT be in force
# around the R calls: PowerShell 5.1 wraps every stderr line from a
# native command in an ErrorRecord, so an ordinary rstan message such
# as "the number of chains is less than 1" becomes terminating and
# kills the run 13 files in. See dev/lane-rules.md, shell traps.
$ErrorActionPreference = "Stop"
$ROOT = "C:/Users/adf44/source/r/frmtmb-wt-simnewdata"
$R    = "C:/Program Files/R/R-4.6.1/bin/Rscript.exe"
$S    = "$ROOT/dev/simnewdata-run-tests.R"
$LOG  = "$ROOT/dev/simnewdata-log/gated.log"

if (-not (Test-Path $S)) { throw "runner missing: $S" }
if (-not (Test-Path $R)) { throw "Rscript missing: $R" }

$env:NOT_CRAN = "true"
$env:FRMTMB_BRMS_FIT_TESTS = "true"
# The drmTMB agreement tier. Every test in it fits about 50 models in
# the two packages, so it is gated like the brms fit tier rather than
# run in every check job. It needs drmTMB installed.
$env:FRMTMB_DRMTMB_FIT_TESTS = "true"
$env:FRMTMB_FUZZ = "true"
$env:FRMTMB_STAN_CACHE = "$ROOT/dev/stan-cache"
# backslashes: a forward-slash PATH left `cmd` unresolvable once, and
# the driver ran nothing while still writing its completion marker
$env:PATH = "C:\rtools45\usr\bin;C:\rtools45\x86_64-w64-mingw32.static.posix\bin;" + $env:PATH

Remove-Item $LOG -ErrorAction SilentlyContinue
$core = "$ROOT/tests/testthat"

$jobs = New-Object System.Collections.ArrayList
foreach ($f in (Get-ChildItem -Path $core -Filter "test-bcm-*.R" | Sort-Object Name)) {
  [void]$jobs.Add(@{ n = "frmtmb"; f = $f.FullName })
}
foreach ($nm in @("test-brms-agreement.R", "test-brms-likelihood.R",
                  "test-brms-methods.R", "test-brms-priors.R",
                  "test-brms-port.R", "test-rl-example.R",
                  "test-drmtmb-agreement.R", "test-fuzz.R")) {
  [void]$jobs.Add(@{ n = "frmtmb"; f = "$core/$nm" })
}
# brms 2.23.0's own bin-1 suite, generated by dev/brmsport-gen.R (item
# 2.6b); dev/brmsport-ledger.tsv gives each assertion's verdict. A glob
# that matches nothing adds no job and the existence check below then
# passes on zero jobs, so an empty match throws.
$suite = @(
  @{ n = "frmtmb"; d = $core },
  @{ n = "frmtmb.sample"; d = "$ROOT/extensions/frmtmb.sample/tests/testthat" }
)
# PowerShell names are case-insensitive: a loop variable `$s` here was
# `$S`, the runner path, so every job after it ran Rscript on a hashtable,
# printed nothing, and the tier reported 0 of 38.
foreach ($suiteDir in $suite) {
  $hits = @(Get-ChildItem -Path $suiteDir.d -Filter "test-brms-suite-*.R" |
            Sort-Object Name)
  if ($hits.Count -eq 0) {
    throw ("no test-brms-suite-*.R files in " + $suiteDir.d)
  }
  foreach ($f in $hits) {
    [void]$jobs.Add(@{ n = $suiteDir.n; f = $f.FullName })
  }
}
[void]$jobs.Add(@{ n = "frmtmb.learn"; f = "$ROOT/extensions/frmtmb.learn/tests/testthat/test-stan-identity.R" })
[void]$jobs.Add(@{ n = "frmtmb.sample"; f = "$ROOT/extensions/frmtmb.sample/tests/testthat/test-loo.R" })
[void]$jobs.Add(@{ n = "frmtmb.sample"; f = "$ROOT/extensions/frmtmb.sample/tests/testthat/test-sampling-ported.R" })

foreach ($j in $jobs) {
  if (-not (Test-Path $j.f)) { throw ("test file missing: " + $j.f) }
}

Add-Content -Path $LOG -Value ("== gated " + $jobs.Count + " files ==")
$ErrorActionPreference = "Continue"
$ran = 0
foreach ($j in $jobs) {
  $out = & $R $S $j.n $j.f 2>&1
  $hit = $out | Select-String -Pattern "^RESULT"
  if ($hit) {
    $ran = $ran + 1
    Add-Content -Path $LOG -Value $hit.Line
  } else {
    Add-Content -Path $LOG -Value ("NO RESULT LINE for " + $j.f)
    Add-Content -Path $LOG -Value ($out | Select-Object -Last 5)
  }
}
Add-Content -Path $LOG -Value ("GATED ran " + $ran + " of " + $jobs.Count)
Write-Output ("GATED ran " + $ran + " of " + $jobs.Count)
