# Tier counts, generated from the logs rather than typed. Emits a block
# to paste verbatim into dev/skewinit-findings.md.
d <- "C:/Users/adf44/source/r/frmtmb-wt-skewinit/dev/skewinit-log"
parse_log <- function(f) {
  L <- readLines(f, warn = FALSE)
  r <- grep("RESULT ", L, value = TRUE, fixed = TRUE)
  m <- regmatches(r, regexec(
    "RESULT (\\S+) pass=(\\d+) fail=(\\d+) err=(\\d+) skip=(\\d+)", r))
  ok <- vapply(m, length, 0L) == 6L
  data.frame(
    file = vapply(m[ok], `[`, "", 2L),
    pass = as.integer(vapply(m[ok], `[`, "", 3L)),
    fail = as.integer(vapply(m[ok], `[`, "", 4L)),
    err  = as.integer(vapply(m[ok], `[`, "", 5L)),
    skip = as.integer(vapply(m[ok], `[`, "", 6L)),
    bad  = sum(!ok),
    stringsAsFactors = FALSE)
}
ung <- do.call(rbind, lapply(
  file.path(d, paste0("suite-", 0:3, ".log")), parse_log))
gat <- parse_log(file.path(d, "gated.log"))
noresult <- function(f) sum(grepl("NO RESULT|LOADERROR", readLines(f, warn = FALSE)))
nr_u <- sum(vapply(file.path(d, paste0("suite-", 0:3, ".log")), noresult, 0L))
nr_g <- noresult(file.path(d, "gated.log"))

cat("<!-- generated by dev/skewinit-tiers.R, do not type these -->\n")
cat(sprintf(
  "| tier | files | pass | fail | error | skip | no RESULT line |\n"))
cat("|---|---|---|---|---|---|---|\n")
cat(sprintf("| ungated, 1 process per file | %d | %d | %d | %d | %d | %d |\n",
            nrow(ung), sum(ung$pass), sum(ung$fail), sum(ung$err),
            sum(ung$skip), nr_u))
cat(sprintf("| gated, all env vars set | %d | %d | %d | %d | %d | %d |\n",
            nrow(gat), sum(gat$pass), sum(gat$fail), sum(gat$err),
            sum(gat$skip), nr_g))
cat("<!-- end generated -->\n\n")
cat("ungated files with any fail or error:",
    sum(ung$fail > 0 | ung$err > 0), "\n")
cat("gated files with any fail or error:",
    sum(gat$fail > 0 | gat$err > 0), "\n")
cat("ungated files reporting zero of everything (fully gated out):",
    sum(ung$pass == 0 & ung$fail == 0 & ung$err == 0 & ung$skip == 0), "\n")
cat("\nthe lane's own file:\n")
print(ung[ung$file == "test-skew-normal-start.R", 1:5], row.names = FALSE)
cat("\ngated top five by assertions:\n")
print(utils::head(gat[order(-gat$pass), 1:5], 5), row.names = FALSE)
