# Lane surface: read the shapes the pooled methods build on (scratch).
source("dev/surface-env.R")
surface_env("base")
suppressPackageStartupMessages(library(frmtmb))
data("nhanes", package = "mice")
imp <- mice::mice(nhanes, m = 3, print = FALSE, seed = 1)
fm <- frm_multiple(bmi ~ age * chl, data = imp)
f1 <- fm$fits[[1]]
print(frmtmb:::brms_coef_table(f1))
print(rownames(frmtmb:::vcov_estimated(f1)))
print(frmtmb:::estimated_coef_names(f1))
print(fixef(f1))
ce <- conditional_effects(f1, "age:chl")
str(ce[[1]])
print(attributes(ce)[setdiff(names(attributes(ce)), "names")])
print(args(frm_linpred))
s <- summary(f1)
print(names(s))
str(s$fixed); str(s$spec_pars)
