## Regenerate the "Tests run" block of dev/thresrefit-findings.md from
## the FINAL whole-suite logs, so the counts in the document come from the
## run and are not typed.
##
## The file list is READ OUT OF dev/thresrefit-suite.sh rather than
## repeated here. It was repeated here once, and the two drifted: the
## runner grew to 44 files while the block still listed 40, which the
## reviewer caught. A list in one place cannot drift.
root <- "C:/Users/adf44/source/r/frmtmb-wt-thresrefit"
sh <- readLines(file.path(root, "dev/thresrefit-suite.sh"), warn = FALSE)
files <- sort(unique(grep("^test-.*\\.R$", trimws(sh), value = TRUE)))
stopifnot(length(files) > 0L)

rows <- vapply(files, function(f) {
  p <- file.path(root, "dev/thresrefit-testlog-all", paste0(f, ".log"))
  if (!file.exists(p)) return(sprintf("    %-30s NO LOG", f))
  ln <- grep("^RESULT", readLines(p, warn = FALSE), value = TRUE)
  if (!length(ln)) return(sprintf("    %-30s NO RESULT LINE", f))
  sprintf("    %-30s %s", f, regmatches(ln, regexpr("pass=.*$", ln)))
}, "")
## a missing count must be loud in the document, not quietly absent
bad <- grep("NO LOG|NO RESULT LINE", rows, value = TRUE)
if (length(bad)) cat("WARNING, incomplete:\n", paste(bad, collapse = "\n"),
                     "\n", sep = "")

doc <- file.path(root, "dev/thresrefit-findings.md")
old <- sub("\r$", "", readLines(doc, warn = FALSE))
b <- grep("^<!-- generated by dev/thresrefit-block\\.R", old)
stopifnot(length(b) == 1L)
## the block runs from the marker to the first line that is not indented
## output, so it does not matter how many rows were there before
k <- b + 1L
while (k <= length(old) && grepl("^    ", old[k])) k <- k + 1L
writeLines(c(old[seq_len(b)], rows, old[k:length(old)]), doc)
cat("replaced", k - b - 1L, "rows with", length(rows), "from",
    length(files), "files named by the runner\n")
