# Reviewer check: does every generated region of each record equal the
# block of the same name in vigport-blocks.txt (regenerated by the
# reviewer into vigport-rev-blocks.txt)?
root <- "C:/Users/adf44/source/r/frmtmb-wt-vigport/dev"
src <- readLines(file.path(root, "vigport-rev-blocks.txt"), warn = FALSE)
beg <- grep("^<!-- BEGIN generated: ", src)
blocks <- list()
for (a in beg) {
  nm <- sub("^<!-- BEGIN generated: (.*) -->$", "\\1", src[a])
  b <- a + grep("^<!-- END generated -->$", src[(a + 1):length(src)])[1]
  blocks[[nm]] <- src[a:b]
}
cat("blocks generated:", length(blocks), "\n")
used <- character()
for (f in c("vigport-findings.md", "brms-vignette-port.md",
            "brms-vignette-audit.md")) {
  x <- readLines(file.path(root, f), warn = FALSE)
  bs <- grep("^<!-- BEGIN generated: ", x)
  for (i in bs) {
    nm <- sub("^<!-- BEGIN generated: (.*) -->$", "\\1", x[i])
    j <- i + grep("^<!-- END generated -->$", x[(i + 1):length(x)])[1]
    same <- identical(x[i:j], blocks[[nm]])
    used <- c(used, nm)
    cat(sprintf("%-24s %-28s %s\n", f, nm, if (same) "IDENTICAL" else
      "DIFFERS"))
  }
}
cat("blocks never used:", setdiff(names(blocks), used), "\n")
