# GENERATED by dev/brmsport-gen.R from brms 2.23.0
# tests/testthat/tests.brmsfit-methods.R. Do not edit by hand: change
# dev/brmsport-verdicts.tsv or the generator, then regenerate.
# helper-brms-suite.R says what brms_port() asserts.

skip_unless_brms_suite()
grDevices::pdf(NULL)
withr::defer(grDevices::dev.off(), teardown_env())
expect_range <- function(object, lower = -Inf, upper = Inf, ...) {
  testthat::expect_true(all(object >= lower & object <= upper), ...)
}
expect_ggplot <- function(object, ...) {
  testthat::expect_true(is(object, "ggplot"), ...)
}
SM <- suppressMessages
SW <- suppressWarnings
epilepsy <- brms::epilepsy
rename_pars <- brms_shim_rename_pars
update <- brms_shim_update
fit1 <- brms_fixture(1)
fit2 <- brms_fixture(2)
fit3 <- brms_fixture(3)
fit4 <- brms_fixture(4)
fit5 <- brms_fixture(5)
fit6 <- brms_fixture(6)
nobs <- 40
npatients <- 10
nsubjects <- 8
nvisits <- 4

test_that("autocor has reasonable ouputs", {
  brms_port("brmsfit-methods:112", "cannot transfer",
    paste0(
      "frmtmb has no autocor(), brms's deprecated accessor for ",
      "autocorrelation structures"),
    expect_true(is.null(SW(autocor(fit1))))
  )
  brms_port("brmsfit-methods:113", "cannot transfer",
    "frmtmb has no autocor()",
    expect_true(is.null(SW(autocor(fit6, resp = "count"))))
  )
})

test_that("conditional_effects has reasonable ouputs", {
  brms_setup("brmsfit-methods:150",
    me <- conditional_effects(fit1, resp = "count")
  )
  brms_port("brmsfit-methods:151", "pass",
    "",
    expect_equal(nrow(me[[2]]), 100)
  )
  brms_setup("brmsfit-methods:152",
    meplot <- plot(me, points = TRUE, rug = TRUE,
                   ask = FALSE, plot = FALSE)
  )
  brms_port("brmsfit-methods:154", "defect",
    paste0(
      "plot() of conditional effects refuses brms's rug and plot ",
      "arguments by name"),
    expect_ggplot(meplot[[1]])
  )
  brms_setup("brmsfit-methods:156",
    me <- conditional_effects(fit1, "Trt", select_points = 0.1)
  )
  brms_port("brmsfit-methods:157", "cannot transfer",
    paste0(
      "conditional_effects() has no select_points ",
      "(dev/brms-api-diff.md (c); on draws it is refused by name, ",
      "dev/brmsnames-findings.md not fixed 9)"),
    expect_lt(nrow(attr(me[[1]], "points")), nobs(fit1))
  )
  brms_setup("brmsfit-methods:159",
    me <- conditional_effects(fit1, "volume:Age", surface = TRUE,
                              resolution = 15, too_far = 0.2)
  )
  brms_setup("brmsfit-methods:161",
    meplot <- plot(me, plot = FALSE)
  )
  brms_port("brmsfit-methods:162", "cannot transfer",
    paste0(
      "conditional_effects() has no too_far, so the surface object ",
      "is never built; plot() also refuses brms's plot = FALSE by ",
      "name (dev/brms-api-diff.md (c))"),
    expect_ggplot(meplot[[1]])
  )
  brms_setup("brmsfit-methods:163",
    meplot <- plot(me, stype = "raster", plot = FALSE)
  )
  brms_port("brmsfit-methods:164", "cannot transfer",
    paste0(
      "conditional_effects() has no too_far; plot() also refuses ",
      "brms's stype and plot arguments by name"),
    expect_ggplot(meplot[[1]])
  )
  brms_setup("brmsfit-methods:166",
    me <- conditional_effects(fit1, "Age", spaghetti = TRUE, ndraws = 10)
  )
  brms_port("brmsfit-methods:167", "cannot transfer",
    paste0(
      "conditional_effects() has no spaghetti ",
      "(dev/brms-api-diff.md (c))"),
    expect_equal(nrow(attr(me$Age, "spaghetti")), 1000)
  )
  brms_setup("brmsfit-methods:168",
    meplot <- plot(me, plot = FALSE)
  )
  brms_port("brmsfit-methods:169", "cannot transfer",
    "conditional_effects() has no spaghetti",
    expect_ggplot(meplot[[1]])
  )
  brms_port("brmsfit-methods:170", "cannot transfer",
    paste0(
      "conditional_effects() has no spaghetti, so the ",
      "spaghetti-with-surface refusal brms asserts is never ",
      "reached"),
    expect_error(
      conditional_effects(fit1, "Age", spaghetti = TRUE, surface = TRUE),
      "Cannot use 'spaghetti' and 'surface' at the same time"
    )
  )
  brms_setup("brmsfit-methods:175",
    me <- conditional_effects(fit1, effects = c("Age", "Age:visit"),
                              re_formula = NULL)
  )
  brms_port("brmsfit-methods:177", "pass",
    "",
    expect_equal(nrow(me[[1]]), 100)
  )
  brms_setup("brmsfit-methods:178",
    exp_nrow <- 100 * length(unique(fit1$data$visit))
  )
  brms_port("brmsfit-methods:179", "pass",
    "",
    expect_equal(nrow(me[[2]]), exp_nrow)
  )
  brms_setup("brmsfit-methods:181", {
    mdata = data.frame(
      Age = c(-0.3, 0, 0.3),
      count = c(10, 20, 30),
      Exp = c(1, 3, 5)
    )
  })
  brms_setup("brmsfit-methods:186",
    exp_nrow <- nrow(mdata) * 100
  )
  brms_setup("brmsfit-methods:187",
    me <- conditional_effects(fit1, effects = "Age", conditions = mdata)
  )
  brms_port("brmsfit-methods:188", "pass",
    "",
    expect_equal(nrow(me[[1]]), exp_nrow)
  )
  brms_setup("brmsfit-methods:190",
    mdata$visit <- 1:3
  )
  brms_setup("brmsfit-methods:191",
    me <- conditional_effects(fit1, re_formula = NULL, conditions = mdata)
  )
  brms_port("brmsfit-methods:192", "pass",
    "",
    expect_equal(nrow(me$Age), exp_nrow)
  )
  brms_setup("brmsfit-methods:194",
    me <- conditional_effects(
      fit1, "Age:Trt", int_conditions = list(Age = rnorm(5))
    )
  )
  brms_port("brmsfit-methods:197", "pass",
    "",
    expect_equal(nrow(me[[1]]), 10)
  )
  brms_setup("brmsfit-methods:198",
    me <- conditional_effects(
      fit1, "Age:Trt", int_conditions = list(Age = quantile)
    )
  )
  brms_port("brmsfit-methods:201", "pass",
    "",
    expect_equal(nrow(me[[1]]), 10)
  )
  brms_port_own("brmsfit-methods:203",
    "Variable 'Trtc' is not stored in the model frame",
    paste0(
      "brms: All specified effects are invalid for this model. ",
      "CAVEAT: frmtmb gives this message for brmsfit-methods:205, ",
      "where brms warns and keeps the valid effects"),
    expect_error(conditional_effects(fit1, effects = "Trtc"),
                 "All specified effects are invalid for this model")
  )
  brms_port("brmsfit-methods:205", "defect",
    paste0(
      "one invalid effect among valid ones is an error; brms warns ",
      "'Some specified effects are invalid' and returns the valid ",
      "ones (dev/brmsport-probe4.R)"),
    expect_warning(conditional_effects(fit1, effects = c("Trtc", "Trt")),
                   "Some specified effects are invalid for this model")
  )
  brms_port_own("brmsfit-methods:207",
    "Effects support at most two variables: 'Trtc:a:b'",
    "brms: please use the 'conditions' argument",
    expect_error(conditional_effects(fit1, effects = "Trtc:a:b"),
                 "please use the 'conditions' argument")
  )
  brms_setup("brmsfit-methods:210",
    mdata$visit <- NULL
  )
  brms_setup("brmsfit-methods:211",
    mdata$Exp <- NULL
  )
  brms_setup("brmsfit-methods:212",
    mdata$patient <- 1
  )
  brms_port("brmsfit-methods:213", "defect",
    paste0(
      "conditional_effects() refuses its default Wald band on the ",
      "nonlinear fit2 and names band = 'boot'; brms answers. No ",
      "document records refusing the default band as a decision"),
    expect_equal(nrow(conditional_effects(fit2)[[2]]), 100)
  )
  brms_setup("brmsfit-methods:214",
    me <- conditional_effects(fit2, re_formula = NULL, conditions = mdata)
  )
  brms_port("brmsfit-methods:215", "defect",
    paste0(
      "conditional_effects() refuses its default Wald band on the ",
      "nonlinear fit2 and names band = 'boot'; brms answers. No ",
      "document records refusing the default band as a decision"),
    expect_equal(nrow(me$Age), exp_nrow)
  )
  brms_port("brmsfit-methods:217", "defect",
    paste0(
      "no 'Predictions are treated as continuous variables' ",
      "warning on the ordinal fit4; the brmsnames note cited ",
      "before is about draws, and the fit method was never audited ",
      "(brmsnames 'Found and NOT fixed' 11)"),
    expect_warning(
      me4 <- conditional_effects(fit4),
      "Predictions are treated as continuous variables"
    )
  )
  brms_port("brmsfit-methods:221", "divergence",
    paste0(
      "the object is not a brms_conditional_effects brms's class ",
      "name; frmtmb objects must NOT carry brms's class names ",
      "(user decision, 2026-09-17, rule 2)"),
    expect_true(is(me4, "brms_conditional_effects"))
  )
  brms_setup("brmsfit-methods:222",
    me4 <- conditional_effects(fit4, "x2", categorical = TRUE)
  )
  brms_port("brmsfit-methods:223", "divergence",
    paste0(
      "the object is not a brms_conditional_effects brms's class ",
      "name; frmtmb objects must NOT carry brms's class names ",
      "(user decision, 2026-09-17, rule 2)"),
    expect_true(is(me4, "brms_conditional_effects"))
  )
  brms_setup("brmsfit-methods:225",
    me5 <- conditional_effects(fit5)
  )
  brms_port("brmsfit-methods:226", "divergence",
    paste0(
      "the object is not a brms_conditional_effects brms's class ",
      "name; frmtmb objects must NOT carry brms's class names ",
      "(user decision, 2026-09-17, rule 2)"),
    expect_true(is(me5, "brms_conditional_effects"))
  )
  brms_setup("brmsfit-methods:228",
    me6 <- conditional_effects(fit6, ndraws = 20)
  )
  brms_port("brmsfit-methods:229", "divergence",
    paste0(
      "the object is not a brms_conditional_effects brms's class ",
      "name; frmtmb objects must NOT carry brms's class names ",
      "(user decision, 2026-09-17, rule 2)"),
    expect_true(is(me6, "brms_conditional_effects"))
  )
})

test_that("conditional_smooths has reasonable ouputs", {
  brms_setup("brmsfit-methods:268",
    ms <- conditional_smooths(fit1)
  )
  brms_port("brmsfit-methods:269", "defect",
    paste0(
      "conditional_smooths() is absent, though ",
      "R/conditional-effects.R says conditional_effects() 'also ",
      "covers what brms calls conditional_smooths()'"),
    expect_equal(nrow(ms[[1]]), 100)
  )
  brms_port("brmsfit-methods:270", "divergence",
    paste0(
      "is(ms, 'brms_conditional_effects'): brms's class name; ",
      "frmtmb objects must NOT carry brms's class names (user ",
      "decision, 2026-09-17, rule 2)"),
    expect_true(is(ms, "brms_conditional_effects"))
  )
  brms_setup("brmsfit-methods:272",
    ms <- conditional_smooths(fit1, spaghetti = TRUE, ndraws = 10)
  )
  brms_port("brmsfit-methods:273", "cannot transfer",
    "frmtmb has no conditional_smooths()",
    expect_equal(nrow(attr(ms[[1]], "spaghetti")), 1000)
  )
  brms_port("brmsfit-methods:275", "defect",
    paste0(
      "conditional_smooths() is absent, though ",
      "R/conditional-effects.R says conditional_effects() 'also ",
      "covers what brms calls conditional_smooths()'"),
    expect_error(conditional_smooths(fit1, smooths = "s3"),
                 "No valid smooth terms found in the model")
  )
  brms_port("brmsfit-methods:277", "defect",
    paste0(
      "conditional_smooths() is absent, though ",
      "R/conditional-effects.R says conditional_effects() 'also ",
      "covers what brms calls conditional_smooths()'"),
    expect_error(conditional_smooths(fit2),
                 "No valid smooth terms found in the model")
  )
})

test_that("family has reasonable ouputs", {
  brms_port("brmsfit-methods:282", "divergence",
    paste0(
      "family(fit) is a frmtmb_family, not a brmsfamily brms's ",
      "class name; frmtmb objects must NOT carry brms's class ",
      "names (user decision, 2026-09-17, rule 2)"),
    expect_is(family(fit1), "brmsfamily")
  )
  brms_port("brmsfit-methods:283", "defect",
    paste0(
      "family() refuses brms's resp argument by name and says to ",
      "index the returned list instead"),
    expect_is(family(fit6, resp = "count"), "brmsfamily")
  )
  brms_port("brmsfit-methods:284", "defect",
    "print() of a family refuses brms's links argument by name",
    expect_output(print(family(fit1), links = TRUE), "student.*log.*logm1")
  )
  brms_port("brmsfit-methods:285", "defect",
    paste0(
      "print(family(fit5)) reads 'Family: mixture(gaussian, ",
      "exponential)', not brms's 'Mixture' then one family per ",
      "component (user decision, 2026-09-17, rule 3; item 2.6f)"),
    expect_output(print(family(fit5)), "Mixture.*gaussian.*exponential")
  )
})

test_that("fitted has reasonable outputs", {
  skip_on_cran()
  brms_setup("brmsfit-methods:291",
    fi <- fitted(fit1)
  )
  brms_port("brmsfit-methods:292", "pass",
    "",
    expect_equal(dim(fi), c(nobs(fit1), 4))
  )
  brms_port("brmsfit-methods:293", "pass",
    "",
    expect_equal(colnames(fi), c("Estimate", "Est.Error", "Q2.5", "Q97.5"))
  )
  brms_setup("brmsfit-methods:295",
    newdata <- data.frame(
      Age = c(0, -0.2), visit = c(1, 4), Trt = c(0, 1),
      count = c(20, 13), patient = c(1, 42), Exp = c(2, 4),
      volume = 0
    )
  )
  brms_setup("brmsfit-methods:300",
    fi <- fitted(fit1, newdata = newdata)
  )
  brms_port("brmsfit-methods:301", "defect",
    paste0(
      "newdata carrying the numeric codes 0 and 1 of the factor ",
      "Trt dies with R's 'contrasts apply only to factors'; brms ",
      "matches them to the levels (dev/brmsport-probe4.R)"),
    expect_equal(dim(fi), c(2, 4))
  )
  brms_setup("brmsfit-methods:302",
    newdata$visit <- c(1, 6)
  )
  brms_setup("brmsfit-methods:303",
    fi <- fitted(fit1, newdata = newdata,
                 allow_new_levels = TRUE)
  )
  brms_port("brmsfit-methods:305", "defect",
    paste0(
      "fitted() refuses brms's allow_new_levels by name, though ",
      "predict() takes it"),
    expect_equal(dim(fi), c(2, 4))
  )
  brms_setup("brmsfit-methods:308",
    newdata <- data.frame(
      Age = 0, visit = paste0("a", 1:100), Trt = 0,
      count = 20, patient = 1, Exp = 2, volume = 0
    )
  )
  brms_setup("brmsfit-methods:312",
    fi <- fitted(fit1, newdata = newdata, allow_new_levels = TRUE,
                 sample_new_levels = "old_levels", ndraws = 10)
  )
  brms_port("brmsfit-methods:314", "defect",
    paste0(
      "fitted() is brms's four-column summary now (item 2.6f) and ",
      "still refuses ndraws BY NAME: a maximum-likelihood fit has ",
      "no draws to thin. The setup line dies on that refusal, so ",
      "the assertion reads a stale object"),
    expect_equal(dim(fi), c(100, 4))
  )
  brms_setup("brmsfit-methods:315",
    fi <- fitted(fit1, newdata = newdata, allow_new_levels = TRUE,
                 sample_new_levels = "gaussian", ndraws = 1)
  )
  brms_port("brmsfit-methods:317", "defect",
    paste0(
      "fitted() is brms's four-column summary now (item 2.6f) and ",
      "still refuses ndraws BY NAME: a maximum-likelihood fit has ",
      "no draws to thin. The setup line dies on that refusal, so ",
      "the assertion reads a stale object"),
    expect_equal(dim(fi), c(100, 4))
  )
  brms_setup("brmsfit-methods:320",
    newdata <- data.frame(
      Age = 0, visit = c("a", "b"), Trt = 0,
      count = 20, patient = 1, Exp = 2, volume = 0
    )
  )
  brms_setup("brmsfit-methods:324",
    fi <- fitted(fit1, dpar = "sigma")
  )
  brms_port("brmsfit-methods:325", "pass",
    "",
    expect_equal(dim(fi), c(nobs(fit1), 4))
  )
  brms_port("brmsfit-methods:326", "cannot transfer",
    paste0(
      "fitted(fit1, dpar = 'sigma') is brms's four-column summary ",
      "now, and FIXTURE 1 DOES NOT CONVERGE (nlminb code 1, NaN ",
      "standard errors), so the Est.Error and the two Q columns ",
      "are NA and all(fi > 0) is NA rather than TRUE. The Estimate ",
      "column is positive, which is what the assertion is about; ",
      "brms's fixture converged. A converged stand-in would ",
      "transfer it (dev/brmsport-findings.md section 3)"),
    expect_true(all(fi > 0))
  )
  brms_setup("brmsfit-methods:327",
    fi_lin <- fitted(fit1, dpar = "sigma", scale = "linear")
  )
  brms_port("brmsfit-methods:328", "pass",
    "",
    expect_equal(dim(fi_lin), c(nobs(fit1), 4))
  )
  brms_port("brmsfit-methods:329", "pass",
    "",
    expect_true(!isTRUE(all.equal(fi, fi_lin)))
  )
  brms_port_own("brmsfit-methods:330",
    "Unknown dpar: 'inv'",
    "brms: Invalid argument 'dpar'",
    expect_error(fitted(fit1, dpar = "inv"),
                 "Invalid argument 'dpar'")
  )
  brms_setup("brmsfit-methods:333",
    fi <- fitted(fit2)
  )
  brms_port("brmsfit-methods:334", "pass",
    "",
    expect_equal(dim(fi), c(nobs(fit2), 4))
  )
  brms_setup("brmsfit-methods:335",
    fi <- fitted(fit2, newdata = newdata,
                 allow_new_levels = TRUE)
  )
  brms_port("brmsfit-methods:337", "pass",
    "",
    expect_equal(dim(fi), c(2, 4))
  )
  brms_setup("brmsfit-methods:338",
    fi <- fitted(fit2, dpar = "shape")
  )
  brms_port("brmsfit-methods:339", "pass",
    "",
    expect_equal(dim(fi), c(nobs(fit2), 4))
  )
  brms_port("brmsfit-methods:340", "pass",
    paste0(
      "WEAKER than brms wrote it: fitted() is brms's n x 4 matrix ",
      "now, so fi[1, ] and fi[2, ] each carry Estimate plus three ",
      "NA cells on this non-converging fixture, and expect_equal ",
      "compares c(19.122, NA, NA, NA) with itself. Before the ",
      "shapes item this compared two numbers and errored on fi[1, ",
      "]. It moved from defect to pass on that weakening, not on a ",
      "fix (dev/reviews/20260918-shapes.md, m7)."),
    expect_equal(fi[1, ], fi[2, ])
  )
  brms_setup("brmsfit-methods:341",
    fi <- fitted(fit2, nlpar = "a")
  )
  brms_port("brmsfit-methods:342", "pass",
    "",
    expect_equal(dim(fi), c(nobs(fit2), 4))
  )
  brms_setup("brmsfit-methods:344",
    fi <- fitted(fit3, newdata = fit3$data[1:10, ])
  )
  brms_port("brmsfit-methods:345", "pass",
    "",
    expect_equal(dim(fi), c(10, 4))
  )
  brms_setup("brmsfit-methods:347",
    fi <- fitted(fit4)
  )
  brms_port("brmsfit-methods:348", "pass",
    "",
    expect_equal(dim(fi), c(nobs(fit4), 4, 4))
  )
  brms_setup("brmsfit-methods:349",
    fi <- fitted(fit4, newdata = fit4$data[1, ])
  )
  brms_port("brmsfit-methods:350", "pass",
    "",
    expect_equal(dim(fi), c(1, 4, 4))
  )
  brms_setup("brmsfit-methods:351",
    fi <- fitted(fit4, newdata = fit4$data[1, ], scale = "linear")
  )
  brms_port("brmsfit-methods:352", "defect",
    paste0(
      "dim(fitted(fit4, newdata = fit4$data[1, ], scale = ...)) is ",
      "NULL where brms gives 1 x 4 x 3. Rule 3, item 2.6f. Was ",
      "fit-data"),
    expect_equal(dim(fi), c(1, 4, 3))
  )
  brms_setup("brmsfit-methods:354",
    fi <- fitted(fit5)
  )
  brms_port("brmsfit-methods:355", "pass",
    "",
    expect_equal(dim(fi), c(nobs(fit5), 4))
  )
  brms_setup("brmsfit-methods:357",
    fi <- fitted(fit6)
  )
  brms_port("brmsfit-methods:358", "defect",
    paste0(
      "fitted() exists and refuses the multivariate fit6 as 'not ",
      "supported yet'; brms answers (user decision, 2026-09-17, ",
      "rule 3; item 2.6f)"),
    expect_equal(dim(fi), c(nobs(fit6), 4, 2))
  )
  brms_port("brmsfit-methods:359", "defect",
    paste0(
      "fitted() exists and refuses the multivariate fit6 as 'not ",
      "supported yet'; brms answers (user decision, 2026-09-17, ",
      "rule 3; item 2.6f)"),
    expect_equal(dimnames(fi)[[3]], c("volume", "count"))
  )
})

test_that("fixef has reasonable ouputs", {
  brms_setup("brmsfit-methods:363",
    fixef1 <- SM(fixef(fit1))
  )
  brms_port("brmsfit-methods:364", "pass",
    "",
    expect_equal(rownames(fixef1),
                 c("Intercept", "sigma_Intercept", "Trt1", "Age", "volume",
                   "Trt1:Age", "sigma_Trt1", "sAge_1", "moExp")
    )
  )
  brms_setup("brmsfit-methods:368",
    fixef1 <- SM(fixef(fit1, pars = c("Age", "sAge_1")))
  )
  brms_port("brmsfit-methods:369", "pass",
    "",
    expect_equal(rownames(fixef1), c("Age", "sAge_1"))
  )
})

test_that("formula has reasonable ouputs", {
  brms_port("brmsfit-methods:373", "divergence",
    paste0(
      "is.brmsformula(formula(fit1)): brms's class name; frmtmb ",
      "objects must NOT carry brms's class names (user decision, ",
      "2026-09-17, rule 2)"),
    expect_true(is.brmsformula(formula(fit1)))
  )
})

test_that("hypothesis has reasonable ouputs", {
  brms_setup("brmsfit-methods:388",
    hyp <- hypothesis(fit1, c("Age > Trt1", "Trt1:Age = -1"))
  )
  brms_port("brmsfit-methods:389", "pass",
    "",
    expect_equal(dim(hyp$hypothesis), c(2, 8))
  )
  brms_port("brmsfit-methods:390", "pass",
    "",
    expect_output(print(hyp), "(Age)-(Trt1) > 0", fixed = TRUE)
  )
  brms_port("brmsfit-methods:391", "defect",
    "plot() of a hypothesis refuses brms's plot = FALSE by name",
    expect_ggplot(plot(hyp, plot = FALSE)[[1]])
  )
  brms_setup("brmsfit-methods:393",
    hyp <- hypothesis(fit1, "Intercept = 0", class = "sd", group = "visit")
  )
  brms_port("brmsfit-methods:394", "hollow",
    paste0(
      "holds only as is.numeric(NA_real_): Evid.Ratio is NA on a ",
      "fit (D4, dev/brmsnames-findings.md 'The hypothesis() ",
      "object'), where brms reports a number. Marked by hand, ",
      "because a rule cannot tell this NA from an NA that is the ",
      "right answer"),
    expect_true(is.numeric(hyp$hypothesis$Evid.Ratio[1]))
  )
  brms_port("brmsfit-methods:395", "pass",
    "",
    expect_output(print(hyp), "class sd_visit:", fixed = TRUE)
  )
  brms_port("brmsfit-methods:396", "defect",
    paste0(
      "plot() of a hypothesis refuses brms's ignore_prior and plot ",
      "by name"),
    expect_ggplot(plot(hyp, ignore_prior = TRUE, plot = FALSE)[[1]])
  )
  brms_setup("brmsfit-methods:398",
    hyp <- hypothesis(fit1, "0 > r_visit[4,Intercept]", class = "", 
        alpha = 0.01)
  )
  brms_port("brmsfit-methods:399", "divergence",
    paste0(
      "r_visit[4,Intercept] is not a parameter of an ML fit: a ",
      "group-level coefficient needs draws, the reason scope = ",
      "'ranef' is refused on a fit (D4)"),
    expect_equal(dim(hyp$hypothesis), c(1, 8))
  )
  brms_port("brmsfit-methods:400", "divergence",
    "as brmsfit-methods:399 (D4)",
    expect_output(print(hyp, chars = NULL), "r_visit[4,Intercept]", 
        fixed = TRUE)
  )
  brms_port("brmsfit-methods:401", "divergence",
    "as brmsfit-methods:399 (D4)",
    expect_output(print(hyp), "99%-CI", fixed = TRUE)
  )
  brms_setup("brmsfit-methods:403",
    hyp <- hypothesis(
      fit1, c("Intercept = 0", "Intercept + exp(Trt1) = 0"),
      group = "visit", scope = "coef"
    )
  )
  brms_port("brmsfit-methods:407", "divergence",
    "hypothesis(scope = 'coef') is refused by name on a fit (D4)",
    expect_equal(dim(hyp$hypothesis), c(8, 9))
  )
  brms_port("brmsfit-methods:408", "divergence",
    "hypothesis(scope = 'coef') is refused by name on a fit (D4)",
    expect_equal(hyp$hypothesis$Group[1], factor(1, levels = 1:4))
  )
  brms_port("brmsfit-methods:410", "pass",
    "",
    expect_error(hypothesis(fit1, "Intercept > x"), fixed = TRUE,
                 "cannot be found in the model: \n'b_x'")
  )
  brms_port("brmsfit-methods:412", "pass",
    "",
    expect_error(hypothesis(fit1, 1),
                 "Argument 'hypothesis' must be a character vector")
  )
  brms_port_own("brmsfit-methods:414",
    "`alpha` must be a single number strictly between 0 and 1",
    "brms: Argument 'alpha' must be a single value in [0,1]",
    expect_error(hypothesis(fit2, "b_Age = 0", alpha = 2),
                 "Argument 'alpha' must be a single value in [0,1]",
                 fixed = TRUE)
  )
  brms_port("brmsfit-methods:417", "pass",
    "",
    expect_error(hypothesis(fit3, "b_Age x 0"), "Every hypothesis must be of the form 'left (= OR < OR >) right'", 
        fixed = TRUE)
  )
  brms_setup("brmsfit-methods:422",
    hyp <- hypothesis(as.data.frame(fit3), "bsp_meAgeAgeSD > sigma")
  )
  brms_port("brmsfit-methods:423", "cannot transfer",
    paste0(
      "hypothesis() on as.data.frame() of posterior draws: an ML ",
      "fit has no draws to coerce, and fit3's me() term is not in ",
      "the fixture (D8)"),
    expect_equal(dim(hyp$hypothesis), c(1, 8))
  )
  brms_setup("brmsfit-methods:424",
    hyp <- hypothesis(fit3$fit, "bsp_meAgeAgeSD > sigma")
  )
  brms_port("brmsfit-methods:425", "cannot transfer",
    paste0(
      "reads fit3$fit, the stanfit (D10), and fit3's me() term ",
      "(D8)"),
    expect_equal(dim(hyp$hypothesis), c(1, 8))
  )
})

test_that("model.frame has reasonable ouputs", {
  brms_port("brmsfit-methods:567", "pass",
    "",
    expect_equal(model.frame(fit1), fit1$data)
  )
})

test_that("ngrps has reasonable ouputs", {
  brms_port("brmsfit-methods:584", "pass",
    "",
    expect_equal(ngrps(fit1), list(visit = 4))
  )
  brms_port("brmsfit-methods:585", "pass",
    "",
    expect_equal(ngrps(fit2), list(patient = 10))
  )
})

test_that("nobs has reasonable ouputs", {
  brms_port("brmsfit-methods:589", "pass",
    "",
    expect_equal(nobs(fit1), nobs)
  )
})

test_that("plot has reasonable outputs", {
  brms_port("brmsfit-methods:604", "cannot transfer",
    paste0(
      "brms's plot() of a fit draws posterior trace and density ",
      "plots; an ML fit's plot() is a diagnostics plot and takes ",
      "neither plot nor variable"),
    expect_silent(p <- plot(fit1, plot = FALSE))
  )
  brms_port("brmsfit-methods:605", "cannot transfer",
    paste0(
      "brms's plot() of a fit plots posterior draws (see ",
      "brmsfit-methods:604)"),
    expect_silent(p <- plot(fit1, variable = "^b", regex = TRUE, plot = FALSE))
  )
  brms_port("brmsfit-methods:606", "cannot transfer",
    paste0(
      "brms's plot() of a fit plots posterior draws (see ",
      "brmsfit-methods:604)"),
    expect_silent(p <- plot(fit1, variable = "^sd", regex = TRUE, plot = FALSE))
  )
  brms_port("brmsfit-methods:607", "cannot transfer",
    paste0(
      "the expect_error is met only by plot() refusing the ",
      "argument name variable, not by the missing variable brms ",
      "refuses"),
    expect_error(plot(fit1, variable = "123"))
  )
})

test_that("pp_check has reasonable outputs", {
  brms_port("brmsfit-methods:674", "pass",
    "",
    expect_ggplot(pp_check(fit1))
  )
  brms_port("brmsfit-methods:675", "pass",
    "",
    expect_ggplot(pp_check(fit1, newdata = fit1$data[1:10, ]))
  )
  brms_port("brmsfit-methods:676", "pass",
    "",
    expect_ggplot(pp_check(fit1, "stat", ndraws = 5))
  )
  brms_port("brmsfit-methods:677", "pass",
    "",
    expect_ggplot(pp_check(fit1, "error_binned"))
  )
  brms_setup("brmsfit-methods:678",
    pp <- pp_check(fit1, "ribbon_grouped", group = "visit", x = "Age")
  )
  brms_port("brmsfit-methods:679", "pass",
    "",
    expect_ggplot(pp)
  )
  brms_setup("brmsfit-methods:680",
    pp <- pp_check(fit1, type = "violin_grouped",
                   group = "visit", newdata = fit1$data[1:10, ])
  )
  brms_port("brmsfit-methods:682", "pass",
    "",
    expect_ggplot(pp)
  )
  brms_setup("brmsfit-methods:684",
    pp <- SW(pp_check(fit1, type = "loo_pit_qq", cores = 1))
  )
  brms_port("brmsfit-methods:685", "defect",
    paste0(
      "pp_check(type = 'loo_pit_qq') is given no lw or psis_object ",
      "(dev/brmsnames-findings.md not fixed 8)"),
    expect_ggplot(pp)
  )
  brms_port("brmsfit-methods:688", "pass",
    "",
    expect_ggplot(pp_check(fit1, prefix = "ppd"))
  )
  skip_on_cran()
  brms_port("brmsfit-methods:693", "pass",
    "",
    expect_ggplot(pp_check(fit3))
  )
  brms_port("brmsfit-methods:694", "pass",
    "",
    expect_ggplot(pp_check(fit2, "ribbon", x = "Age"))
  )
  brms_port("brmsfit-methods:695", "pass",
    "",
    expect_error(pp_check(fit2, "ribbon", x = "x"),
                 "Variable 'x' could not be found in the data")
  )
  brms_port("brmsfit-methods:697", "pass",
    "",
    expect_error(pp_check(fit1, "wrong_type"))
  )
  brms_port("brmsfit-methods:698", "pass",
    "",
    expect_error(pp_check(fit2, "violin_grouped"), "group")
  )
  brms_port("brmsfit-methods:699", "pass",
    "",
    expect_error(pp_check(fit1, "stat_grouped", group = "g"),
                 "Variable 'g' could not be found in the data")
  )
  brms_port("brmsfit-methods:701", "pass",
    "",
    expect_ggplot(pp_check(fit4))
  )
  brms_port("brmsfit-methods:702", "pass",
    "",
    expect_ggplot(pp_check(fit5))
  )
  brms_port("brmsfit-methods:703", "pass",
    "",
    expect_error(pp_check(fit4, "error_binned"),
                 "Type 'error_binned' is not available")
  )
})

test_that("predict has reasonable outputs", {
  brms_setup("brmsfit-methods:725",
    pred <- predict(fit1)
  )
  brms_port("brmsfit-methods:726", "pass",
    "",
    expect_equal(dim(pred), c(nobs(fit1), 4))
  )
  brms_port("brmsfit-methods:727", "pass",
    "",
    expect_equal(colnames(pred), c("Estimate", "Est.Error", "Q2.5", "Q97.5"))
  )
  brms_setup("brmsfit-methods:728",
    pred <- predict(fit1, ndraws = 10, probs = c(0.2, 0.5, 0.8))
  )
  brms_port("brmsfit-methods:729", "pass",
    "",
    expect_equal(dim(pred), c(nobs(fit1), 5))
  )
  brms_setup("brmsfit-methods:731",
    newdata <- data.frame(
      Age = c(0, -0.2), visit = c(1, 4), Trt = c(1, 0),
      count = c(2, 10), patient = c(1, 42), Exp = c(1, 2),
      volume = 0
    )
  )
  brms_setup("brmsfit-methods:736",
    pred <- predict(fit1, newdata = newdata)
  )
  brms_port("brmsfit-methods:737", "defect",
    paste0(
      "newdata with the numeric codes of the factor Trt dies with ",
      "'contrasts apply only to factors' (as brmsfit-methods:301); ",
      "the shape after it is item 2.6d"),
    expect_equal(dim(pred), c(2, 4))
  )
  brms_setup("brmsfit-methods:739",
    newdata$visit <- c(1, 6)
  )
  brms_setup("brmsfit-methods:740",
    pred <- predict(fit1, newdata = newdata, allow_new_levels = TRUE)
  )
  brms_port("brmsfit-methods:741", "defect",
    paste0(
      "newdata with the numeric codes of the factor Trt dies with ",
      "'contrasts apply only to factors' (as brmsfit-methods:301)"),
    expect_equal(dim(pred), c(2, 4))
  )
  brms_setup("brmsfit-methods:744",
    df <- fit1$data[1:10, ]
  )
  brms_setup("brmsfit-methods:745",
    df$count[8:10] <- NA
  )
  brms_setup("brmsfit-methods:746",
    pred <- predict(fit1, newdata = df, ndraws = 1)
  )
  brms_port("brmsfit-methods:747", "defect",
    paste0(
      "predict(ndraws =) is answered now - the draws are ",
      "SIMULATED, so ndraws sets how many - and the setup still ",
      "dies earlier, on fit1$data, which partial-matches ",
      "fit1$data2 (the fit has no data element)"),
    expect_true(!anyNA(pred[, "Estimate"]))
  )
  brms_setup("brmsfit-methods:749",
    pred <- predict(fit2)
  )
  brms_port("brmsfit-methods:750", "pass",
    "",
    expect_equal(dim(pred), c(nobs(fit2), 4))
  )
  brms_setup("brmsfit-methods:752",
    pred <- predict(fit2, newdata = newdata, allow_new_levels = TRUE)
  )
  brms_port("brmsfit-methods:753", "pass",
    "",
    expect_equal(dim(pred), c(2, 4))
  )
  brms_setup("brmsfit-methods:756",
    newdata$patient <- factor(2)
  )
  brms_setup("brmsfit-methods:757",
    pred <- predict(fit2, newdata = newdata)
  )
  brms_port("brmsfit-methods:758", "pass",
    "",
    expect_equal(dim(pred), c(2, 4))
  )
  brms_setup("brmsfit-methods:760",
    pred <- predict(fit4)
  )
  brms_port("brmsfit-methods:761", "pass",
    "",
    expect_equal(dim(pred), c(nobs(fit4), 4))
  )
  brms_port("brmsfit-methods:762", "pass",
    "",
    expect_equal(colnames(pred), paste0("P(Y = ", 1:4, ")"))
  )
  brms_setup("brmsfit-methods:763",
    pred <- predict(fit4, newdata = fit4$data[1, ])
  )
  brms_port("brmsfit-methods:764", "pass",
    "",
    expect_equal(dim(pred), c(1, 4))
  )
  brms_setup("brmsfit-methods:766",
    pred <- predict(fit5)
  )
  brms_port("brmsfit-methods:767", "pass",
    "",
    expect_equal(dim(pred), c(nobs(fit5), 4))
  )
  brms_setup("brmsfit-methods:768",
    newdata <- fit5$data[1:5, ]
  )
  brms_setup("brmsfit-methods:769",
    newdata$patient <- "a"
  )
  brms_setup("brmsfit-methods:770",
    pred <- predict(fit5, newdata, allow_new_levels = TRUE,
                    sample_new_levels = "old_levels")
  )
  brms_port("brmsfit-methods:772", "defect",
    paste0(
      "predict() honors sample_new_levels = \"gaussian\", which is ",
      "what it does, and refuses \"old_levels\" BY NAME: that value ",
      "resamples the POSTERIOR draws of the levels the fit saw, ",
      "and a maximum-likelihood fit has no such draws. The setup ",
      "line dies, so this assertion reads a stale object"),
    expect_equal(dim(pred), c(5, 4))
  )
  brms_setup("brmsfit-methods:773",
    pred <- predict(fit5, newdata, allow_new_levels = TRUE,
                    sample_new_levels = "gaussian")
  )
  brms_port("brmsfit-methods:775", "pass",
    "",
    expect_equal(dim(pred), c(5, 4))
  )
})

test_that("print has reasonable outputs", {
  brms_port("brmsfit-methods:784", "pass",
    "",
    expect_output(SW(print(fit1)), "Multilevel Hyperparameters:")
  )
})

test_that("prior_summary has reasonable outputs", {
  brms_port("brmsfit-methods:806", "divergence",
    paste0(
      "prior_summary(fit) is frmtmb's prior table, not a brmsprior ",
      "brms's class name; frmtmb objects must NOT carry brms's ",
      "class names (user decision, 2026-09-17, rule 2)"),
    expect_true(is(prior_summary(fit1), "brmsprior"))
  )
})

test_that("ranef has reasonable outputs", {
  brms_setup("brmsfit-methods:810",
    ranef1 <- SM(ranef(fit1))
  )
  brms_port("brmsfit-methods:811", "divergence",
    paste0(
      "ranef() returns the conditional modes, levels x ",
      "coefficients, without brms's Est.Error and quantile layer; ",
      "ranef(condVar =) is the recorded fit-side analog ",
      "(dev/brms-api-diff.md (b))"),
    expect_equal(dim(ranef1$visit), c(nvisits, 4, 2))
  )
  brms_setup("brmsfit-methods:813",
    ranef1 <- SM(ranef(fit1, pars = "Trt1"))
  )
  brms_port("brmsfit-methods:814", "defect",
    "ranef() refuses brms's pars by name and says to subset",
    expect_equal(dimnames(ranef1$visit)[[3]], "Trt1")
  )
  brms_setup("brmsfit-methods:816",
    ranef1 <- SM(ranef(fit1, groups = "a"))
  )
  brms_port("brmsfit-methods:817", "defect",
    paste0(
      "ranef() refuses brms's groups by name and says to index the ",
      "list"),
    expect_equal(length(ranef1), 0L)
  )
  brms_setup("brmsfit-methods:819",
    ranef2 <- SM(ranef(fit2, summary = FALSE))
  )
  brms_port("brmsfit-methods:820", "divergence",
    "ranef(summary = FALSE) is refused by name on a fit (D3)",
    expect_equal(dim(ranef2$patient), c(ndraws(fit2), npatients, 2))
  )
})

test_that("residuals has reasonable outputs", {
  brms_setup("brmsfit-methods:824",
    res1 <- SW(residuals(fit1, type = "pearson", probs = c(0.65)))
  )
  brms_port("brmsfit-methods:825", "pass",
    "",
    expect_equal(dim(res1), c(nobs(fit1), 3))
  )
  brms_setup("brmsfit-methods:826",
    newdata <- cbind(epilepsy[1:10, ], Exp = rep(1:5, 2), volume = 0)
  )
  brms_setup("brmsfit-methods:827",
    res2 <- residuals(fit1, newdata = newdata)
  )
  brms_port("brmsfit-methods:828", "defect",
    paste0(
      "residuals(newdata =) is refused by name, though newdata ",
      "carries the response brms reads"),
    expect_equal(dim(res2), c(10, 4))
  )
  brms_setup("brmsfit-methods:829",
    newdata$visit <- rep(1:5, 2)
  )
  brms_setup("brmsfit-methods:831",
    res3 <- residuals(fit1, newdata = newdata, allow_new_levels = TRUE)
  )
  brms_port("brmsfit-methods:832", "defect",
    "residuals(newdata =) is refused by name",
    expect_equal(dim(res3), c(10, 4))
  )
  brms_setup("brmsfit-methods:834",
    res4 <- residuals(fit2)
  )
  brms_port("brmsfit-methods:835", "pass",
    "",
    expect_equal(dim(res4), c(nobs(fit2), 4))
  )
  brms_port_own("brmsfit-methods:837",
    "not defined for the .sratio. family, as in brms",
    paste0(
      "brms: Predictive errors are not defined for ordinal or ",
      "categorical models. frmtmb refuses the same call for the ",
      "same reason since lane wt-correct closed item 1 ",
      "(dev/correct-findings.md section 1); the row was a defect ",
      "while this package answered"),
    expect_error(residuals(fit4), "Predictive errors are not defined")
  )
  brms_setup("brmsfit-methods:839",
    res6 <- residuals(fit6)
  )
  brms_port("brmsfit-methods:840", "defect",
    paste0(
      "residuals() exists and refuses the multivariate fit6 as ",
      "'not supported yet'; brms answers (user decision, ",
      "2026-09-17, rule 3; item 2.6f)"),
    expect_equal(dim(res6), c(nobs(fit6), 4, 2))
  )
  brms_port("brmsfit-methods:841", "defect",
    paste0(
      "residuals() exists and refuses the multivariate fit6 as ",
      "'not supported yet'; brms answers (user decision, ",
      "2026-09-17, rule 3; item 2.6f)"),
    expect_equal(dimnames(res6)[[3]], c("volume", "count"))
  )
})

test_that("summary has reasonable outputs", {
  brms_setup("brmsfit-methods:886",
    summary1 <- SW(summary(fit1, priors = TRUE))
  )
  brms_port("brmsfit-methods:887", "pass",
    "",
    expect_true(is.data.frame(summary1$fixed))
  )
  brms_port("brmsfit-methods:888", "pass",
    "",
    expect_equal(rownames(summary1$fixed),
                 c("Intercept", "sigma_Intercept", "Trt1", "Age", "volume",
                   "Trt1:Age", "sigma_Trt1", "sAge_1", "moExp"))
  )
  brms_port("brmsfit-methods:891", "divergence",
    paste0(
      "summary(fit)$fixed carries brms's four columns and then the ",
      "Wald test this package reports, where brms writes Rhat, ",
      "Bulk_ESS and Tail_ESS. Those three describe a SAMPLER and a ",
      "maximum-likelihood fit has none, so the column set cannot ",
      "match (item 2.6f)"),
    expect_equal(colnames(summary1$fixed),
                 c("Estimate", "Est.Error", "l-95% CI",
                   "u-95% CI", "Rhat", "Bulk_ESS", "Tail_ESS"))
  )
  brms_port("brmsfit-methods:894", "pass",
    "",
    expect_equal(rownames(summary1$random$visit),
                 c("sd(Intercept)", "sd(Trt1)", "cor(Intercept,Trt1)"))
  )
  brms_port("brmsfit-methods:896", "pass",
    "",
    expect_output(print(summary1), "Regression Coefficients:")
  )
  brms_port("brmsfit-methods:897", "pass",
    "",
    expect_output(print(summary1), "Priors:")
  )
  brms_setup("brmsfit-methods:899",
    summary5 <- SW(summary(fit5, robust = TRUE))
  )
  brms_port("brmsfit-methods:900", "divergence",
    paste0(
      "summary(robust = TRUE) is refused: a median and MAD need ",
      "draws (D3's reason); past it, print(summary(fit5)) does ",
      "name sigma1"),
    expect_output(print(summary5), "sigma1")
  )
  brms_port("brmsfit-methods:901", "divergence",
    paste0(
      "summary(robust = TRUE) is refused (D3's reason); past it, ",
      "print(summary(fit5)) does name theta1"),
    expect_output(print(summary5), "theta1")
  )
  brms_setup("brmsfit-methods:903",
    summary6 <- SW(summary(fit6))
  )
  brms_port("brmsfit-methods:904", "defect",
    paste0(
      "print(summary(fit6)) labels the GP standard deviation ",
      "'sd(gp)', not sdgp (user decision, 2026-09-17, rule 3; item ",
      "2.6f)"),
    expect_output(print(summary6), "sdgp")
  )
})

test_that("update has reasonable outputs", {
  brms_setup("brmsfit-methods:913",
    up <- update(fit1, testmode = TRUE)
  )
  brms_port("brmsfit-methods:914", "divergence",
    paste0(
      "update() returns a frmtmb_fit, not a brmsfit ; the update ",
      "itself succeeded brms's class name; frmtmb objects must NOT ",
      "carry brms's class names (user decision, 2026-09-17, rule ",
      "2)"),
    expect_true(is(up, "brmsfit"))
  )
  brms_setup("brmsfit-methods:916",
    new_data <- data.frame(
      Age = rnorm(18), visit = rep(c(3, 2, 4), 6),
      Trt = rep(0:1, 9), count = rep(c(5, 17, 28), 6),
      patient = rep(1:6, each = 3), Exp = 4, volume = 0
    )
  )
  brms_setup("brmsfit-methods:921",
    up <- update(fit1, newdata = new_data, save_pars = save_pars(group = FALSE),
                 testmode = TRUE)
  )
  brms_port("brmsfit-methods:923", "divergence",
    paste0(
      "update(newdata =) returns a frmtmb_fit ; save_pars() was ",
      "dropped by the shim (D10) brms's class name; frmtmb objects ",
      "must NOT carry brms's class names (user decision, ",
      "2026-09-17, rule 2)"),
    expect_true(is(up, "brmsfit"))
  )
  brms_port("brmsfit-methods:924", "defect",
    paste0(
      "attr(up$data, 'data_name') is NULL: brms records the name ",
      "of the newdata argument on the frame it stores and frmtmb ",
      "does not. The frame itself is there now. Was fit-data"),
    expect_equal(attr(up$data, "data_name"), "new_data")
  )
  brms_port("brmsfit-methods:927", "defect",
    paste0(
      "update(fit, data = new_data) refits on the new data where ",
      "brms refuses and demands newdata (dev/brms-suite-audit.md ",
      "section 7 contract 15; dev/brmsport-probe4.R)"),
    expect_error(update(fit1, data = new_data), "use argument 'newdata'")
  )
  brms_setup("brmsfit-methods:929",
    up <- update(fit1, formula = ~ . + I(exp(Age)), testmode = TRUE,
                 prior = set_prior("normal(0,10)"))
  )
  brms_port("brmsfit-methods:931", "divergence",
    paste0(
      "update() returns a frmtmb_fit brms's class name; frmtmb ",
      "objects must NOT carry brms's class names (user decision, ",
      "2026-09-17, rule 2)"),
    expect_true(is(up, "brmsfit"))
  )
  brms_setup("brmsfit-methods:932",
    up <- update(fit1, ~ . - Age + factor(Age),  testmode = TRUE)
  )
  brms_port("brmsfit-methods:933", "divergence",
    paste0(
      "update() returns a frmtmb_fit brms's class name; frmtmb ",
      "objects must NOT carry brms's class names (user decision, ",
      "2026-09-17, rule 2)"),
    expect_true(is(up, "brmsfit"))
  )
  brms_setup("brmsfit-methods:935",
    up <- update(fit1, formula = ~ . + I(exp(Age)), newdata = new_data,
                 sample_prior = FALSE, testmode = TRUE)
  )
  brms_port("brmsfit-methods:937", "divergence",
    paste0(
      "update() returns a frmtmb_fit brms's class name; frmtmb ",
      "objects must NOT carry brms's class names (user decision, ",
      "2026-09-17, rule 2)"),
    expect_true(is(up, "brmsfit"))
  )
  brms_port("brmsfit-methods:938", "defect",
    paste0(
      "a formula update naming a variable the data lacks dies with ",
      "R's object 'wrong_var' not found, not 'New variables found'"),
    expect_error(update(fit1, formula. = ~ . + wrong_var),
                 "New variables found: 'wrong_var'")
  )
  brms_setup("brmsfit-methods:941",
    up <- update(fit1, save_pars = save_pars(group = FALSE), testmode = TRUE)
  )
  brms_port("brmsfit-methods:942", "divergence",
    paste0(
      "update() returns a frmtmb_fit brms's class name; frmtmb ",
      "objects must NOT carry brms's class names (user decision, ",
      "2026-09-17, rule 2)"),
    expect_true(is(up, "brmsfit"))
  )
  brms_setup("brmsfit-methods:944",
    up <- update(fit3, save_pars = save_pars(latent = FALSE), testmode = TRUE)
  )
  brms_port("brmsfit-methods:945", "divergence",
    paste0(
      "update() returns a frmtmb_fit brms's class name; frmtmb ",
      "objects must NOT carry brms's class names (user decision, ",
      "2026-09-17, rule 2)"),
    expect_true(is(up, "brmsfit"))
  )
  brms_setup("brmsfit-methods:948",
    up <- update(fit2, algorithm = "fullrank", testmode = TRUE)
  )
  brms_port("brmsfit-methods:949", "divergence",
    paste0(
      "update() returns a frmtmb_fit brms's class name; frmtmb ",
      "objects must NOT carry brms's class names (user decision, ",
      "2026-09-17, rule 2)"),
    expect_true(is(up, "brmsfit"))
  )
  brms_setup("brmsfit-methods:951",
    up <- update(fit2, formula. = bf(. ~ ., a + b ~ 1, nl = TRUE),
                 testmode = TRUE)
  )
  brms_port("brmsfit-methods:953", "defect",
    paste0(
      "update(fit2, formula. = bf(. ~ ., a + b ~ 1, nl = TRUE)) is ",
      "refused: the dot does not carry the old nonlinear body, so ",
      "a and b are 'not used'"),
    expect_true(is(up, "brmsfit"))
  )
  brms_setup("brmsfit-methods:954",
    up <- update(fit2, formula. = bf(count ~ a + b, nl = TRUE), testmode = TRUE)
  )
  brms_port("brmsfit-methods:955", "defect",
    paste0(
      "update(fit2, formula. = bf(count ~ a + b, nl = TRUE)) is ",
      "refused for having no parameter formulas; brms keeps fit2's"),
    expect_true(is(up, "brmsfit"))
  )
  brms_setup("brmsfit-methods:956",
    up <- update(fit3, family = acat(), testmode = TRUE)
  )
  brms_port("brmsfit-methods:957", "divergence",
    paste0(
      "update(family = acat()) returns a frmtmb_fit brms's class ",
      "name; frmtmb objects must NOT carry brms's class names ",
      "(user decision, 2026-09-17, rule 2)"),
    expect_true(is(up, "brmsfit"))
  )
  brms_setup("brmsfit-methods:958",
    up <- update(fit3, bf(~., family = acat()), testmode = TRUE)
  )
  brms_port("brmsfit-methods:959", "defect",
    paste0(
      "update(fit3, bf(~ ., family = acat())) is refused as a ",
      "formula with no response; brms reads the one-sided dot as ",
      "the old formula"),
    expect_true(is(up, "brmsfit"))
  )
})

test_that("variables has reasonable ouputs", {
  brms_port("brmsfit-methods:978", "divergence",
    paste0(
      "variables(fit) lists an ML fit's parameters; simo_, r_ and ",
      "s_ draws and prior_ and lp__ are posterior or Stan ",
      "quantities (D5, D10; dev/brmsnames-findings.md A10)"),
    expect_true(all(
      c("b_Intercept", "bsp_moExp", "ar[1]", "cor_visit__Intercept__Trt1",
        "nu", "simo_moExp1[2]", "r_visit[4,Trt1]", "s_sAge_1[8]",
        "prior_sd_visit", "prior_cor_visit", "lp__") %in%
        variables(fit1)
    ))
  )
  brms_port("brmsfit-methods:984", "divergence",
    paste0(
      "variables(fit2) has brms's b_, sd_ and cor_ names; the r_ ",
      "and prior_ names are posterior or Stan quantities (D5, D10)"),
    expect_true(all(
      c("b_a_Intercept", "b_b_Age", "sd_patient__b_Intercept",
        "cor_patient__a_Intercept__b_Intercept",
        "r_patient__a[1,Intercept]", "r_patient__b[4,Intercept]",
        "prior_b_a") %in%
        variables(fit2)
    ))
  )
  brms_port("brmsfit-methods:991", "cannot transfer",
    paste0(
      "lscale_volume_gpAgeTrt0 needs gp(Age, by = Trt), which ",
      "frmtmb's gp() does not take (D8)"),
    expect_true(all(
      c("lscale_volume_gpAgeTrt0", "lscale_volume_gpAgeTrt1") %in%
        variables(fit6)
    ))
  )
  brms_port("brmsfit-methods:995", "defect",
    paste0(
      "parnames() is brms's live spelling of variables(); ",
      "frmtmb.sample defines parnames() and refuses it, core has ",
      "none (dev/brms-suite-audit.md section 7 contract 14)"),
    expect_equal(variables(fit3), SW(parnames(fit3)))
  )
})

test_that("vcov has reasonable outputs", {
  brms_port("brmsfit-methods:999", "pass",
    "",
    expect_equal(dim(vcov(fit1)), c(9, 9))
  )
  brms_port("brmsfit-methods:1000", "pass",
    "",
    expect_equal(dim(vcov(fit1, cor = TRUE)), c(9, 9))
  )
})

test_that("contrasts of grouping factors are not stored #214", {
  brms_port("brmsfit-methods:1035", "pass",
    "",
    expect_true(is.null(attr(fit1$data$patient, "contrasts")))
  )
})
