# GENERATED by dev/brmsport-gen.R from brms 2.23.0
# tests/testthat/tests.families.R. Do not edit by hand: change
# dev/brmsport-verdicts.tsv or the generator, then regenerate.
# helper-brms-suite.R says what brms_port() asserts.

skip_unless_brms_suite()

test_that("family functions returns expected results", {
  brms_port("families:4", "pass",
    "",
    expect_equal(student(identity)$link, "identity")
  )
  brms_port("families:5", "pass",
    "",
    expect_equal(student()$link, "identity")
  )
  brms_port("families:6", "pass",
    "",
    expect_equal(bernoulli(logit)$link, "logit")
  )
  brms_port("families:7", "pass",
    "",
    expect_error(bernoulli("sqrt"), "bernoulli")
  )
  brms_port("families:8", "pass",
    "",
    expect_equal(negbinomial(sqrt)$link, "sqrt")
  )
  brms_port("families:9", "pass",
    "",
    expect_error(negbinomial(inverse), "inverse")
  )
  brms_port("families:10", "pass",
    "",
    expect_equal(geometric(identity)$link, "identity")
  )
  brms_port("families:11", "pass",
    "",
    expect_error(geometric("inv"), "geometric")
  )
  brms_port("families:12", "pass",
    "",
    expect_equal(exponential(log)$link, "log")
  )
  brms_port("families:13", "pass",
    "",
    expect_error(exponential("cloglog"), "exponential")
  )
  brms_port("families:14", "pass",
    "",
    expect_equal(weibull()$family, "weibull")
  )
  brms_port("families:15", "pass",
    "",
    expect_error(weibull(sqrt), "weibull")
  )
  brms_port("families:16", "pass",
    "",
    expect_equal(Beta("probit")$link, "probit")
  )
  brms_port("families:17", "pass",
    "",
    expect_error(Beta("1/mu^2"), "beta")
  )
  brms_port("families:18", "pass",
    "",
    expect_equal(hurdle_poisson()$link, "log")
  )
  brms_port("families:19", "cannot transfer",
    "frmtmb has no hurdle_negbinomial() (famlink ledger row 16)",
    expect_equal(hurdle_negbinomial(log)$link, "log")
  )
  brms_port("families:20", "cannot transfer",
    paste0(
      "frmtmb has no hurdle_negbinomial(); the expect_error passes ",
      "only on could not find function (famlink ledger row 17)"),
    expect_error(hurdle_negbinomial("inverse"), "hurdle_negbinomial")
  )
  brms_port("families:21", "pass",
    "",
    expect_equal(hurdle_gamma()$family, "hurdle_gamma")
  )
  brms_port("families:22", "pass",
    "",
    expect_error(hurdle_gamma(sqrt), "hurdle_gamma")
  )
  brms_port("families:23", "pass",
    "",
    expect_equal(zero_inflated_poisson(log)$link, "log")
  )
  brms_port("families:24", "pass",
    "",
    expect_error(zero_inflated_poisson(list(1)), "zero_inflated_poisson")
  )
  brms_port("families:25", "pass",
    "",
    expect_equal(zero_inflated_negbinomial("log")$link, "log")
  )
  brms_port("families:26", "pass",
    "",
    expect_error(zero_inflated_negbinomial("logit"),
                 "zero_inflated_negbinomial")
  )
  brms_port("families:28", "pass",
    "",
    expect_equal(zero_inflated_beta(logit)$family,
                 "zero_inflated_beta")
  )
  brms_port("families:30", "pass",
    "",
    expect_equivalent(zero_inflated_binomial()$link_zi, "logit")
  )
  brms_port("families:31", "pass",
    "",
    expect_error(zero_inflated_binomial(y~x), "zero_inflated_binomial")
  )
  brms_port("families:32", "pass",
    "",
    expect_equal(categorical()$link, "logit")
  )
  brms_port("families:33", "pass",
    "",
    expect_error(categorical(probit), "probit")
  )
  brms_port("families:34", "pass",
    "",
    expect_equal(cumulative(cauchit)$family, "cumulative")
  )
  brms_port("families:35", "pass",
    "",
    expect_equal(sratio(probit_approx)$link, "probit_approx")
  )
  brms_port("families:36", "pass",
    "",
    expect_equal(cratio("cloglog")$family, "cratio")
  )
  brms_port("families:37", "divergence",
    paste0(
      "acat() takes the logit link only: off the logit acat is a ",
      "second density frmtmb has not written (?frmtmb-links; ",
      "famlink ledger row 32)"),
    expect_equal(acat(cloglog)$link, "cloglog")
  )
  brms_port("families:38", "pass",
    "",
    expect_equal(brmsfamily("gaussian", inverse)$link, "inverse")
  )
  brms_port("families:39", "pass",
    "",
    expect_equal(brmsfamily("geometric", "identity")$family, "geometric")
  )
  brms_port("families:40", "pass",
    "",
    expect_equal(brmsfamily("zi_poisson")$link_zi, "logit")
  )
  brms_port("families:42", "pass",
    "",
    expect_error(weibull(link_shape = "logit"),
                 "'logit' is not a supported link for parameter 'shape'")
  )
  brms_port_own("families:44",
    "takes a single link name, not a character of length 2",
    "brms: Cannot coerce 'alink' to a single character value",
    expect_error(weibull(link_shape = c("log", "logit")),
                 "Cannot coerce 'alink' to a single character value")
  )
  brms_port("families:47", "pass",
    "",
    expect_equal(beta_binomial()$link, "logit")
  )
  brms_port("families:48", "pass",
    "",
    expect_equal(beta_binomial('probit')$link, "probit")
  )
  brms_port("families:49", "pass",
    "",
    expect_equal(beta_binomial()$link_phi, "log")
  )
  brms_port("families:50", "pass",
    "",
    expect_error(beta_binomial('log'))
  )
  brms_port("families:51", "pass",
    "",
    expect_error(beta_binomial(link_phi = 'logit'))
  )
  brms_port("families:52", "cannot transfer",
    paste0(
      "frmtmb has no zero_inflated_beta_binomial() (famlink ledger ",
      "row 43)"),
    expect_equal(zero_inflated_beta_binomial()$link, "logit")
  )
  brms_port("families:53", "cannot transfer",
    paste0(
      "frmtmb has no zero_inflated_beta_binomial() (famlink ledger ",
      "row 44)"),
    expect_equal(zero_inflated_beta_binomial('probit')$link, "probit")
  )
  brms_port("families:54", "cannot transfer",
    paste0(
      "frmtmb has no zero_inflated_beta_binomial() (famlink ledger ",
      "row 45)"),
    expect_equal(zero_inflated_beta_binomial()$link_phi, "log")
  )
  brms_port("families:55", "cannot transfer",
    paste0(
      "frmtmb has no zero_inflated_beta_binomial() (famlink ledger ",
      "row 46)"),
    expect_equal(zero_inflated_beta_binomial()$link_zi, "logit")
  )
  brms_port("families:56", "cannot transfer",
    paste0(
      "frmtmb has no zero_inflated_beta_binomial() (famlink ledger ",
      "row 47)"),
    expect_equal(zero_inflated_beta_binomial(link_zi = "identity")$link_zi, 
        "identity")
  )
  brms_port("families:57", "cannot transfer",
    paste0(
      "frmtmb has no zero_inflated_beta_binomial(); the ",
      "expect_error passes only on could not find function ",
      "(famlink ledger row 48)"),
    expect_error(zero_inflated_beta_binomial('sqrt'))
  )
  brms_port("families:58", "cannot transfer",
    paste0(
      "frmtmb has no zero_inflated_beta_binomial(); the ",
      "expect_error passes only on could not find function ",
      "(famlink ledger row 49)"),
    expect_error(zero_inflated_beta_binomial(link_phi = 'logit'))
  )
  brms_port("families:59", "cannot transfer",
    paste0(
      "frmtmb has no zero_inflated_beta_binomial(); the ",
      "expect_error passes only on could not find function ",
      "(famlink ledger row 50)"),
    expect_error(zero_inflated_beta_binomial(link_zi = 'log'))
  )
  brms_port("families:60", "cannot transfer",
    "frmtmb has no hurdle_cumulative() (famlink ledger row 51)",
    expect_equal(hurdle_cumulative()$link, "logit")
  )
  brms_port("families:61", "cannot transfer",
    "frmtmb has no hurdle_cumulative() (famlink ledger row 52)",
    expect_equal(hurdle_cumulative('probit')$link, "probit")
  )
  brms_port("families:62", "cannot transfer",
    "frmtmb has no hurdle_cumulative() (famlink ledger row 53)",
    expect_equal(hurdle_cumulative('cauchit')$link, "cauchit")
  )
  brms_port("families:63", "cannot transfer",
    "frmtmb has no hurdle_cumulative() (famlink ledger row 54)",
    expect_equal(hurdle_cumulative()$link_hu, "logit")
  )
  brms_port("families:64", "cannot transfer",
    "frmtmb has no hurdle_cumulative() (famlink ledger row 55)",
    expect_equal(hurdle_cumulative()$link_disc, "log")
  )
  brms_port("families:65", "cannot transfer",
    paste0(
      "frmtmb has no hurdle_cumulative(); the expect_error passes ",
      "only on could not find function (famlink ledger row 56)"),
    expect_error(hurdle_cumulative(link = "log")$link)
  )
  brms_port("families:66", "cannot transfer",
    paste0(
      "frmtmb has no hurdle_cumulative(); the expect_error passes ",
      "only on could not find function (famlink ledger row 57)"),
    expect_error(hurdle_cumulative(link_hu = "probit")$link_hu)
  )
  brms_port("families:67", "cannot transfer",
    paste0(
      "frmtmb has no hurdle_cumulative(); the expect_error passes ",
      "only on could not find function (famlink ledger row 58)"),
    expect_error(hurdle_cumulative(link_disc = "logit")$link_disc)
  )
  brms_port("families:68", "cannot transfer",
    "frmtmb has no xbeta() (famlink ledger row 59)",
    expect_equal(xbeta()$link, "logit")
  )
  brms_port("families:69", "cannot transfer",
    "frmtmb has no xbeta() (famlink ledger row 60)",
    expect_equal(xbeta("probit")$link, "probit")
  )
  brms_port("families:70", "cannot transfer",
    "frmtmb has no xbeta() (famlink ledger row 61)",
    expect_equal(xbeta("cloglog")$link, "cloglog")
  )
  brms_port("families:71", "cannot transfer",
    paste0(
      "frmtmb has no xbeta(); the expect_error passes only on ",
      "could not find function (famlink ledger row 62)"),
    expect_error(xbeta("1/mu"), "xbeta")
  )
  brms_port("families:72", "cannot transfer",
    "frmtmb has no xbeta() (famlink ledger row 63)",
    expect_equal(xbeta(link_phi = "log")$link_phi, "log")
  )
  brms_port("families:73", "cannot transfer",
    "frmtmb has no xbeta() (famlink ledger row 64)",
    expect_equal(xbeta(link_phi = "softplus")$link_phi, "softplus")
  )
  brms_port("families:74", "cannot transfer",
    "frmtmb has no xbeta() (famlink ledger row 65)",
    expect_error(xbeta(link_phi = "sqrt")$link_phi, "sqrt")
  )
  brms_port("families:75", "cannot transfer",
    "frmtmb has no xbeta() (famlink ledger row 66)",
    expect_equal(xbeta(link_kappa = "identity")$link_kappa, "identity")
  )
  brms_port("families:76", "cannot transfer",
    "frmtmb has no xbeta() (famlink ledger row 67)",
    expect_equal(xbeta(link_kappa = "log")$link_kappa, "log")
  )
})

test_that("print brmsfamily works correctly", {
  brms_port("families:80", "pass",
    "",
    expect_output(print(weibull()), "Family: weibull \nLink function: log")
  )
  brms_port("families:81", "cannot transfer",
    "frmtmb has no xbeta() (famlink ledger row 69)",
    expect_output(print(xbeta()), "Family: xbeta \nLink function: logit")
  )
})

test_that("mixture returns expected results and errors", {
  brms_setup("families:85",
    mix <- mixture(gaussian, nmix = 3)
  )
  brms_port_not_run("families:86", "cannot transfer",
    paste0(
      "reads brms:::family_names(), and the mixture it reads is ",
      "built with nmix, which mixture() does not take (famlink ",
      "ledger row 70)"),
    "reaches brms's own namespace"
  )
  # expect_equal(brms:::family_names(mix), rep("gaussian", 3))
  brms_setup("families:87",
    mix <- mixture(gaussian, student, weibull, nmix = 3:1)
  )
  brms_port_not_run("families:88", "cannot transfer",
    paste0(
      "reads brms:::family_names(), and the mixture it reads is ",
      "built with nmix, which mixture() does not take (famlink ",
      "ledger row 71)"),
    "reaches brms's own namespace"
  )
  # expect_equal(
  #     brms:::family_names(mix),
  #     c(rep("gaussian", 3), rep("student", 2), "weibull")
  #   )
  brms_port("families:92", "pass",
    "",
    expect_error(mixture(gaussian, "x"),
                 "x is not a supported family")
  )
  brms_port("families:94", "pass",
    "",
    expect_error(mixture(poisson(), categorical()),
                 "Some of the families are not allowed in mixture models")
  )
  brms_port("families:96", "pass",
    "",
    expect_error(mixture(poisson, "cumulative"),
                 "Cannot mix ordinal and non-ordinal families")
  )
  brms_port("families:98", "pass",
    "",
    expect_error(mixture(lognormal, exgaussian, poisson()),
                 "Cannot mix families with real and integer support")
  )
  brms_port("families:100", "pass",
    "",
    expect_error(mixture(lognormal),
                 "Expecting at least 2 mixture components")
  )
  brms_port("families:102", "defect",
    paste0(
      "mixture() refuses the argument NAME order, where brms ",
      "refuses its value 'x' (famlink ledger row 77, not fixed)"),
    expect_error(mixture(poisson, binomial, order = "x"),
                 "Argument 'order' is invalid")
  )
})

test_that("response interval is defined correctly", {
  brms_port("families:107", "cannot transfer",
    "frmtmb has no xbeta() (famlink ledger row 78)",
    expect_equal(xbeta()$closed, rep(TRUE, 2))
  )
  brms_port("families:108", "cannot transfer",
    "frmtmb has no xbeta() (famlink ledger row 79)",
    expect_equal(xbeta()$ybounds, c(0, 1))
  )
  brms_port("families:109", "cannot transfer",
    "frmtmb has no xbeta() (famlink ledger row 80)",
    expect_equal(xbeta()$type, "real")
  )
})

test_that("distributional parameters are as expected", {
  brms_port("families:113", "cannot transfer",
    "frmtmb has no xbeta() (famlink ledger row 81)",
    expect_identical(xbeta()$dpars, c("mu", "phi", "kappa"))
  )
})

test_that("default priors are as expected", {
  brms_port("families:117", "cannot transfer",
    paste0(
      "frmtmb has no xbeta(); it also reads a Stan prior string ",
      "(famlink ledger row 82)"),
    expect_output(print(xbeta()$prior), "gamma\\(0.01, 0.01\\)")
  )
  brms_port("families:118", "cannot transfer",
    paste0(
      "frmtmb has no xbeta(); it also reads a Stan prior string ",
      "(famlink ledger row 83)"),
    expect_output(print(xbeta()$prior), "student\\_t\\(3, 0, 2.5\\)")
  )
})

test_that("correct STAN code is used", {
  brms_port("families:122", "cannot transfer",
    paste0(
      "frmtmb has no xbeta(), and the assertion reads the Stan ",
      "include file (famlink ledger row 84)"),
    expect_equal(xbeta()$include, "fun_xbeta.stan")
  )
})
