# GENERATED by dev/brmsport-gen.R from brms 2.23.0
# tests/testthat/tests.brmsformula.R. Do not edit by hand: change
# dev/brmsport-verdicts.tsv or the generator, then regenerate.
# helper-brms-suite.R says what brms_port() asserts.

skip_unless_brms_suite()

test_that("brmsformula validates formulas of non-linear parameters", {
  brms_port("brmsformula:4", "pass",
    "",
    expect_error(bf(y ~ a, ~ 1, a ~ 1),
                 "Additional formulas must be named")
  )
  brms_port("brmsformula:6", "pass",
    "",
    expect_error(bf(y ~ a^x, a.b ~ 1),
                 "not contain dots or underscores")
  )
  brms_port("brmsformula:8", "pass",
    "",
    expect_error(bf(y ~ a^(x+b), a_b ~ 1),
                 "not contain dots or underscores")
  )
})

test_that("brmsformula validates formulas of auxiliary parameters", {
  brms_port("brmsformula:13", "pass",
    "",
    expect_error(bf(y ~ a, ~ 1, sigma ~ 1),
                 "Additional formulas must be named")
  )
})

test_that("brmsformula detects use if '~~'", {
  brms_port("brmsformula:19", "pass",
    "",
    expect_error(bf(y~~x), "~~")
  )
})

test_that("brmsformula does not change a 'brmsformula' object", {
  brms_setup("brmsformula:23",
    form <- bf(y ~ a, sigma ~ 1)
  )
  brms_port("brmsformula:24", "pass",
    "",
    expect_identical(form, bf(form))
  )
  brms_setup("brmsformula:25",
    form <- bf(y ~ a, sigma ~ 1, a ~ x, nl = TRUE)
  )
  brms_port("brmsformula:26", "pass",
    "",
    expect_identical(form, bf(form))
  )
})

test_that("brmsformula detects auxiliary parameter equations", {
  brms_port("brmsformula:30", "cannot transfer",
    paste0(
      "frmtmb has no equating of one dpar to another, bf(y ~ x, ",
      "sigma1 = 'sigma2') (priorform ledger F8)"),
    expect_error(bf(y~x, sigma1 = "sigmaa2"),
                 "Can only equate parameters of the same class")
  )
  brms_port("brmsformula:32", "cannot transfer",
    "frmtmb has no dpar equating (priorform ledger F9)",
    expect_error(bf(y~x, mu3 = "mu2"),
                 "Equating parameters of class 'mu' is not allowed")
  )
  brms_port("brmsformula:34", "cannot transfer",
    "frmtmb has no dpar equating (priorform ledger F10)",
    expect_error(bf(y~x, sigma1 = "sigma1"),
                 "Equating 'sigma1' with itself is not meaningful")
  )
  brms_port("brmsformula:36", "cannot transfer",
    "frmtmb has no dpar equating (priorform ledger F11)",
    expect_error(bf(y~x, shape1 ~ x, shape2 = "shape1"),
                 "Cannot use predicted parameters on the right-hand side")
  )
  brms_port("brmsformula:38", "cannot transfer",
    "frmtmb has no dpar equating (priorform ledger F12)",
    expect_error(bf(y~x, shape1 = "shape3", shape2 = "shape1"),
                 "Cannot use fixed parameters on the right-hand side")
  )
})

test_that("update_adterms works correctly", {
  brms_setup("brmsformula:43",
    form <- y | trials(size) ~ x
  )
  brms_port("brmsformula:44", "cannot transfer",
    "frmtmb exports no update_adterms() (priorform ledger F13)",
    expect_equal(
      update_adterms(form, ~ trials(10)),
      y | trials(10) ~ x
    )
  )
  brms_port("brmsformula:48", "cannot transfer",
    "frmtmb exports no update_adterms() (priorform ledger F14)",
    expect_equal(
      update_adterms(form, ~ weights(w)),
      y | trials(size) + weights(w) ~ x
    )
  )
  brms_port("brmsformula:52", "cannot transfer",
    "frmtmb exports no update_adterms() (priorform ledger F15)",
    expect_equal(
      update_adterms(form, ~ weights(w), action = "replace"),
      y | weights(w) ~ x
    )
  )
  brms_port("brmsformula:56", "cannot transfer",
    "frmtmb exports no update_adterms() (priorform ledger F16)",
    expect_equal(
      update_adterms(y ~ x, ~ trials(10)),
      y | trials(10) ~ x
    )
  )
})
