# GENERATED by dev/brmsport-gen.R from brms 2.23.0
# tests/testthat/tests.standata.R. Do not edit by hand: change
# dev/brmsport-verdicts.tsv or the generator, then regenerate.
# helper-brms-suite.R says what brms_port() asserts.

skip_unless_brms_suite()
standata <- brms_shim_standata
SW <- suppressWarnings

test_that("standata accepts correct response variables depending on the family", {
  brms_port("standata:69", "pass",
    "",
    expect_equal(standata(y ~ 1, data = data.frame(y = seq(-9.9,0,0.1)),
                               family = "student")$Y, as.array(seq(-9.9,0,0.1)))
  )
  brms_port("standata:71", "pass",
    "",
    expect_equal(standata(y | trials(10) ~ 1, data = data.frame(y = 1:10),
                               family = "binomial")$Y, as.array(1:10))
  )
  brms_port("standata:73", "pass",
    "",
    expect_equal(standata(y ~ 1, data = data.frame(y = 10:20),
                               family = "poisson")$Y, as.array(10:20))
  )
  brms_port("standata:75", "defect",
    paste0(
      "bernoulli refuses a response with two distinct values -1 ",
      "and -2 ('response must be 0/1'); brms codes them 1 and 0 ",
      "(dev/brmsport-probe3.R)"),
    expect_equal(standata(y ~ 1, data = data.frame(y = rep(-c(1:2),5)),
                               family = "bernoulli")$Y, as.array(rep(1:0,5)))
  )
  brms_port("standata:77", "pass",
    "",
    expect_equal(standata(y ~ 1, data = data.frame(y = rep(c(TRUE, FALSE),5)),
                               family = "bernoulli")$Y, as.array(rep(1:0,5)))
  )
  brms_port("standata:79", "pass",
    "",
    expect_equal(standata(y ~ 1, data = data.frame(y = rep(1,5)),
                               family = "bernoulli")$Y, as.array(rep(1, 5)))
  )
  brms_port("standata:81", "pass",
    "",
    expect_equal(standata(y ~ 1, data = data.frame(y = rep(0,5)),
                               family = "bernoulli")$Y, as.array(rep(0, 5)))
  )
  brms_port("standata:83", "defect",
    paste0(
      "categorical() refuses integer codes 1..10 with the false ",
      "claim 'fewer than two categories'; brms accepts positive ",
      "integers (dev/brmsport-probe3.R)"),
    expect_equal(standata(y ~ 1, data = data.frame(y = rep(1:10,5)),
                               family = "categorical")$Y, as.array(rep(1:10,5)))
  )
  brms_port("standata:85", "defect",
    paste0(
      "categorical() refuses integer codes 11..20 with the false ",
      "claim 'fewer than two categories'; brms accepts them and ",
      "recodes to 1..10"),
    expect_equal(standata(y ~ 1, data = data.frame(y = rep(11:20,5)),
                               family = "categorical")$Y, as.array(rep(1:10,5)))
  )
  brms_port("standata:87", "pass",
    "",
    expect_equal(standata(y ~ 1, data = data.frame(y = factor(rep(11:20,5))),
                               family = "categorical")$Y, as.array(rep(1:10,5)))
  )
  brms_port("standata:89", "pass",
    "",
    expect_equal(standata(y ~ 1, data = data.frame(y = rep(1:10,5)),
                               family = "cumulative")$Y, as.array(rep(1:10,5)))
  )
  brms_setup("standata:91",
    dat <- data.frame(y = factor(rep(-4:5,5), order = TRUE))
  )
  brms_port("standata:92", "pass",
    "",
    expect_equal(standata(y ~ 1, data = dat, family = "acat")$Y,
                 as.array(rep(1:10,5)))
  )
  brms_port("standata:94", "pass",
    "",
    expect_equal(standata(y ~ 1, data = data.frame(y = seq(1, 10, 
        0.1)), family = "exponential")$Y, as.array(seq(1, 10, 0.1)))
  )
  brms_setup("standata:97",
    dat <- data.frame(y1 = 1:10, y2 = 11:20, x = rep(0,10))
  )
  brms_setup("standata:98",
    form <- bf(mvbind(y1, y2) ~ x) + set_rescor(TRUE)
  )
  brms_setup("standata:99",
    sdata <- standata(form, data = dat)
  )
  brms_port("standata:100", "pass",
    "",
    expect_equal(sdata$Y_y1, as.array(1:10))
  )
  brms_port("standata:101", "pass",
    "",
    expect_equal(sdata$Y_y2, as.array(11:20))
  )
})

test_that("standata rejects incorrect response variables depending on the family", {
  brms_port_own("standata:106",
    "Factor responses are only supported for binomial families",
    "brms: Family 'student' requires numeric responses",
    expect_error(standata(y ~ 1, data = data.frame(y = factor(1:10)),
                               family = "student"),
                 "Family 'student' requires numeric responses")
  )
  brms_port_own("standata:109",
    "geometric: response must be non-negative integers",
    paste0(
      "brms: Family 'geometric' requires response greater than or ",
      "equal to 0"),
    expect_error(standata(y ~ 1, data = data.frame(y = -5:5), family = "geometric"), 
        "Family 'geometric' requires response greater than or equal to 0")
  )
  brms_port_own("standata:112",
    "bernoulli: response must be 0/1",
    paste0(
      "brms: contain only two different values. CAVEAT: frmtmb ",
      "gives this message for standata:75's two-valued -1/-2 ",
      "response, which brms accepts"),
    expect_error(standata(y ~ 1, data = data.frame(y = -1:1),
                               family = "bernoulli"),
                 "contain only two different values")
  )
  brms_port("standata:115", "pass",
    "",
    expect_error(standata(y ~ 1, data = data.frame(y = factor(-1:1)), 
        family = "cratio"), "Family 'cratio' requires either positive integers or ordered factors")
  )
  brms_port("standata:118", "pass",
    "",
    expect_error(standata(y ~ 1, data = data.frame(y = rep(0.5:7.5), 
        2), family = "sratio"), "Family 'sratio' requires either positive integers or ordered factors")
  )
  brms_port_own("standata:121",
    "Gamma: response must be strictly positive",
    "brms: Family 'gamma' requires response greater than 0",
    expect_error(standata(y ~ 1, data = data.frame(y = rep(-7.5:7.5), 2),
                               family = "gamma"),
                 "Family 'gamma' requires response greater than 0")
  )
  brms_port_own("standata:124",
    "beta: response must lie strictly in [(]0, 1[)]",
    "brms: Family 'beta' requires response smaller than 1",
    expect_error(standata(y ~ 1, data = data.frame(y = c(0.1, 0.5, 1)),
                               family = Beta()),
                 "Family 'beta' requires response smaller than 1")
  )
  brms_port_own("standata:127",
    "von_mises: response must be angles in radians",
    paste0(
      "brms: Family 'von_mises' requires response smaller than or ",
      "equal to 3.14"),
    expect_error(standata(y ~ 1, data = data.frame(y = c(0, 0.5, 
        4)), family = von_mises()), "Family 'von_mises' requires response smaller than or equal to 3.14")
  )
  brms_port_own("standata:130",
    "hurdle_gamma: response must be non-negative",
    paste0(
      "brms: Family 'hurdle_gamma' requires response greater than ",
      "or equal to 0"),
    expect_error(standata(y ~ 1, data = data.frame(y = c(-1, 2, 5)), 
        family = hurdle_gamma()), "Family 'hurdle_gamma' requires response greater than or equal to 0")
  )
})

test_that("standata suggests using family bernoulli if appropriate", {
  brms_port("standata:136", "pass",
    "",
    expect_message(standata(y | trials(1) ~ 1, data = list(y = rep(0:1,5)),
                                 family = "binomial"),
                   "family 'bernoulli' might be a more efficient choice.")
  )
  brms_port("standata:139", "pass",
    "",
    expect_message(standata(y ~ 1, data = data.frame(y = rep(1:2, 5)),
                                 family = "acat"),
                   "family 'bernoulli' might be a more efficient choice.")
  )
  brms_port("standata:142", "defect",
    paste0(
      "categorical() refuses the two-category integer response ",
      "rep(0:1, 5) with the false claim 'fewer than two ",
      "categories', so brms's bernoulli suggestion is never ",
      "reached"),
    expect_message(standata(y ~ 1, data = data.frame(y = rep(0:1,5)),
                               family = "categorical"),
                  "family 'bernoulli' might be a more efficient choice.")
  )
})

test_that("standata returns correct values for addition terms", {
  brms_setup("standata:148",
    dat <- data.frame(y = rnorm(9), s = 1:9, w = 1:9, c1 = rep(-1:1, 3),
                      c2 = rep(c("left","none","right"), 3),
                      c3 = c(rep(c(TRUE, FALSE), 4), FALSE),
                      c4 = c(sample(-1:1, 5, TRUE), rep(2, 4)),
                      t = 11:19)
  )
  brms_port("standata:153", "pass",
    "",
    expect_equivalent(standata(y | se(s) ~ 1, data = dat)$se,
                      as.array(1:9))
  )
  brms_port("standata:155", "pass",
    "",
    expect_equal(standata(y | weights(w) ~ 1, data = dat)$weights,
                 as.array(1:9))
  )
  brms_port("standata:157", "pass",
    "",
    expect_equal(standata(y | cens(c1) ~ 1, data = dat)$cens,
                 as.array(rep(-1:1, 3)))
  )
  brms_port("standata:159", "pass",
    "",
    expect_equal(standata(y | cens(c2) ~ 1, data = dat)$cens,
                 as.array(rep(-1:1, 3)))
  )
  brms_port("standata:161", "pass",
    "",
    expect_equal(standata(y | cens(c3) ~ 1, data = dat)$cens,
                 as.array(c(rep(1:0, 4), 0)))
  )
  brms_port("standata:163", "pass",
    "",
    expect_equal(standata(y | cens(c4, y + 2) ~ 1, data = dat)$rcens,
                 as.array(c(rep(0, 5), dat$y[6:9] + 2)))
  )
  brms_port("standata:165", "pass",
    "",
    expect_equal(standata(s | trials(10) ~ 1, dat,
                               family = "binomial")$trials,
                 as.array(rep(10, 9)))
  )
  brms_port("standata:168", "pass",
    "",
    expect_equal(standata(s | trials(t) ~ 1, data = dat,
                               family = "binomial")$trials,
                 as.array(11:19))
  )
  brms_port("standata:171", "cannot transfer",
    paste0(
      "frmtmb has no cat() addition term (brms's deprecated ",
      "spelling of thres())"),
    expect_equal(SW(standata(s | cat(19) ~ 1, data = dat,
                        family = "cumulative"))$nthres,
                 18)
  )
})

test_that("standata rejects incorrect addition terms", {
  brms_setup("standata:177",
    dat <- data.frame(y = rnorm(9), s = -(1:9), w = -(1:9),
                      c = rep(-2:0, 3), t = 9:1, z = 1:9)
  )
  brms_port_own("standata:179",
    "se[(][)] values must be positive",
    paste0(
      "brms: Standard errors must be non-negative. CAVEAT: frmtmb ",
      "gives this message for se = 0, which brms accepts"),
    expect_error(standata(y | se(s) ~ 1, data = dat),
                 "Standard errors must be non-negative")
  )
  brms_port_own("standata:181",
    "weights[(][)] must be non-negative",
    "brms: Weights must be non-negative",
    expect_error(standata(y | weights(w) ~ 1, data = dat),
                 "Weights must be non-negative")
  )
  brms_port("standata:183", "pass",
    "",
    expect_error(standata(y | cens(c) ~ 1, data = dat))
  )
  brms_port_own("standata:184",
    paste0(
      "binomial: response must be integer counts in [[]0, ",
      "trials[]]"),
    "brms: Number of trials is smaller than the number of events",
    expect_error(standata(z | trials(t) ~ 1, data = dat,
                               family = "binomial"),
                 "Number of trials is smaller than the number of events")
  )
})

test_that("standata removes NAs correctly", {
  brms_setup("standata:240",
    dat <- data.frame(y = c(rnorm(9), NA))
  )
  brms_setup("standata:241",
    sdata <- suppressWarnings(standata(y ~ 1, dat))
  )
  brms_port("standata:242", "pass",
    "",
    expect_equal(as.numeric(sdata$Y), dat$y[1:9])
  )
})

test_that("standata handles the 'subset' addition argument correctly", {
  brms_setup("standata:246",
    dat1 <- data.frame(
      y1 = rnorm(15), y2 = NA,
      x1 = rnorm(15), x2 = NA, x3 = rnorm(15),
      sub1 = 1, sub2 = 0
    )
  )
  brms_setup("standata:251",
    dat2 <- data.frame(
      y1 = NA, y2 = rnorm(10),
      x1 = NA, x2 = rnorm(10), x3 = NA,
      sub1 = 0, sub2 = 1
    )
  )
  brms_setup("standata:256",
    dat <- rbind(dat1, dat2)
  )
  brms_setup("standata:258",
    bform <-
      bf(y1 | subset(sub1) ~ x1*x3 + sin(x1), family = gaussian()) +
      bf(y2 | subset(sub2) ~ x2, family = gaussian()) +
      set_rescor(FALSE)
  )
  brms_setup("standata:263",
    sdata <- standata(bform, dat)
  )
  brms_setup("standata:264",
    nsub1 <- sum(dat$sub1)
  )
  brms_setup("standata:265",
    nsub2 <- sum(dat$sub2)
  )
  brms_port("standata:266", "cannot transfer",
    "frmtmb has no subset() addition term",
    expect_equal(sdata$N_y1, nsub1)
  )
  brms_port("standata:267", "cannot transfer",
    "frmtmb has no subset() addition term",
    expect_equal(sdata$N_y2, nsub2)
  )
  brms_port("standata:268", "cannot transfer",
    "frmtmb has no subset() addition term",
    expect_equal(length(sdata$Y_y1), nsub1)
  )
  brms_port("standata:269", "cannot transfer",
    "frmtmb has no subset() addition term",
    expect_equal(nrow(sdata$X_y2), nsub2)
  )
})

test_that("standata allows to retrieve the initial data order", {
  brms_setup("standata:305",
    dat <- data.frame(y1 = rnorm(100), y2 = rnorm(100),
                            id = sample(1:10, 100, TRUE),
                            time = sample(1:100, 100))
  )
  brms_setup("standata:309",
    sdata1 <- standata(y1 ~ ar(time, id), data = dat, internal = TRUE)
  )
  brms_port("standata:310", "cannot transfer",
    paste0(
      "reads brms's internal old_order attribute of Stan data, ",
      "which exists because brms sorts rows for its ",
      "autocorrelation code; frmtmb keeps the data order and has ",
      "no such attribute. The setup ar(time, id) runs (brms's cov ",
      "= FALSE form, ?frmtmb-autocor)"),
    expect_equal(dat$y1, as.numeric(sdata1$Y[attr(sdata1, "old_order")]))
  )
  brms_setup("standata:313",
    form <- bf(mvbind(y1, y2) ~ ma(time, id)) + set_rescor(FALSE)
  )
  brms_setup("standata:314",
    sdata2 <- standata(form, data = dat, internal = TRUE)
  )
  brms_port("standata:315", "cannot transfer",
    paste0(
      "reads brms's internal old_order attribute of Stan data; ",
      "frmtmb keeps the data order and has no such attribute. The ",
      "setup ma(time, id) runs (?frmtmb-autocor)"),
    expect_equal(sdata2$Y_y1[attr(sdata2, "old_order")], as.array(dat$y1))
  )
  brms_port("standata:316", "cannot transfer",
    paste0(
      "reads brms's internal old_order attribute of Stan data; ",
      "frmtmb keeps the data order and has no such attribute. The ",
      "setup ma(time, id) runs (?frmtmb-autocor)"),
    expect_equal(sdata2$Y_y2[attr(sdata2, "old_order")], as.array(dat$y2))
  )
})

test_that("standata handles 'mi' terms with 'subset'", {
  brms_setup("standata:610",
    dat <- data.frame(
      y = rnorm(10), x = c(rnorm(9), NA), z = rnorm(10),
      g1 = sample(1:5, 10, TRUE), g2 = 10:1, g3 = 1:10,
      s = c(FALSE, rep(TRUE, 9))
    )
  )
  brms_setup("standata:616",
    bform <- bf(y ~ mi(x, idx = g1)) +
      bf(x | mi() + index(g2) + subset(s)  ~ 1) +
      set_rescor(FALSE)
  )
  brms_setup("standata:619",
    sdata <- standata(bform, dat)
  )
  brms_port("standata:620", "cannot transfer",
    paste0(
      "frmtmb has no mi(x, idx = ) and no subset() or index() ",
      "addition terms"),
    expect_true(all(sdata$idxl_y_x_1 %in% 9:5))
  )
  brms_setup("standata:631",
    bform <- bf(y ~ mi(x, idx = g1)) +
      bf(x | mi() + subset(s) ~ 1) +
      set_rescor(FALSE)
  )
  brms_port("standata:634", "cannot transfer",
    paste0(
      "frmtmb has no mi(x, idx = ); the call is refused on that, ",
      "before the index() check brms asserts"),
    expect_error(standata(bform, dat),
      "Response 'x' needs to have an 'index' addition term"
    )
  )
  brms_setup("standata:638",
    bform <- bf(y ~ mi(x)) +
      bf(x | mi() + subset(s) + index(g2)  ~ 1) +
      set_rescor(FALSE)
  )
  brms_port("standata:641", "cannot transfer",
    "frmtmb has no subset() addition term",
    expect_error(standata(bform, dat),
      "mi() terms of subsetted variables require the 'idx' argument",
      fixed = TRUE
    )
  )
  brms_setup("standata:646",
    bform <- bf(y | mi() ~ mi(x, idx = g1)) +
      bf(x | mi() + subset(s) + index(g2)  ~ mi(y)) +
      set_rescor(FALSE)
  )
  brms_port("standata:649", "cannot transfer",
    "frmtmb has no mi(x, idx = ) and no subset() addition term",
    expect_error(standata(bform, dat),
      "mi() terms in subsetted formulas require the 'idx' argument",
      fixed = TRUE
    )
  )
})

test_that("by variables in grouping terms are handled correctly", {
  brms_setup("standata:691",
    gvar <- c("1A", "1B", "2A", "2B", "3A", "3B", "10", "100", "2", "3")
  )
  brms_setup("standata:692",
    gvar <- rep(gvar, each = 10)
  )
  brms_setup("standata:693",
    g_order <- order(gvar)
  )
  brms_setup("standata:694",
    byvar <- c(0, 4.5, 3, 2, "x 1")
  )
  brms_setup("standata:695",
    byvar <- factor(rep(byvar, each = 20))
  )
  brms_setup("standata:696",
    dat <- data.frame(
      y = rnorm(100), x = rnorm(100),
      g = gvar,
      g2 = gvar[g_order],
      z = byvar,
      z2 = byvar[g_order],
      z3 = factor(1:2)
    )
  )
  brms_setup("standata:704",
    sdata <- standata(y ~ x + (x | gr(g, by = z)), dat)
  )
  brms_port("standata:705", "cannot transfer",
    paste0(
      "frmtmb's gr() takes cov and prec only, not by ",
      "(dev/brms-suite-audit.md section 5); Nby_1 is also Stan ",
      "data"),
    expect_equal(sdata$Nby_1, 5)
  )
  brms_port("standata:706", "cannot transfer",
    paste0(
      "frmtmb's gr() takes cov and prec only, not by; Jby_1 is ",
      "also Stan data"),
    expect_equal(sdata$Jby_1, as.array(c(2, 2, 1, 1, 5, 4, 4, 5, 3, 3)))
  )
  brms_setup("standata:708",
    sdata <- standata(y ~ x + (x | mm(g, g2, by = cbind(z, z2))), dat)
  )
  brms_port("standata:709", "cannot transfer",
    "frmtmb's mm() refuses by = by name",
    expect_equal(sdata$Nby_1, 5)
  )
  brms_port("standata:710", "cannot transfer",
    "frmtmb's mm() refuses by = by name",
    expect_equal(sdata$Jby_1, as.array(c(2, 2, 1, 1, 5, 4, 4, 5, 3, 3)))
  )
  brms_port("standata:712", "cannot transfer",
    paste0(
      "frmtmb's gr() takes no by, so the level check brms asserts ",
      "is never reached"),
    expect_error(standata(y ~ x + (1|gr(g, by = z3)), dat),
                 "Some levels of 'g' correspond to multiple levels of 'z3'")
  )
})

test_that("standata handles calls to the 'poly' function", {
  brms_setup("standata:717",
    dat <- data.frame(y = rnorm(10), x = rnorm(10))
  )
  brms_port("standata:718", "cannot transfer",
    paste0(
      "Stan data column names: brms renames poly(x, 3)1 to polyx31 ",
      "to make a Stan identifier; frmtmb's brms-facing names ",
      "already agree, variables() reads b_polyx31 ",
      "(dev/brmsport-probe3.R)"),
    expect_equal(colnames(standata(y ~ 1 + poly(x, 3), dat)$X),
                 c("Intercept", "polyx31", "polyx32", "polyx33"))
  )
})

test_that("standata allows fixed distributional parameters", {
  brms_setup("standata:723",
    dat <- list(y = 1:10)
  )
  brms_port("standata:724", "cannot transfer",
    paste0(
      "reads the Stan data slot nu; frmtmb accepts bf(y ~ 1, nu = ",
      "3) and keeps the constant in its parameter map, not in a ",
      "data slot"),
    expect_equal(standata(bf(y ~ 1, nu = 3), dat, student())$nu, 3)
  )
  brms_port("standata:725", "cannot transfer",
    paste0(
      "reads the Stan data slot disc, which brms passes as the ",
      "constant 1; frmtmb's acat() has no disc data"),
    expect_equal(standata(y ~ 1, dat, acat())$disc, 1)
  )
  brms_port_own("standata:726",
    "not available for family 'gaussian': bias",
    "brms: Invalid fixed parameters: 'bias'",
    expect_error(standata(bf(y ~ 1, bias = 0.5), dat),
                 "Invalid fixed parameters: 'bias'")
  )
})

test_that("Cell-mean coding can be disabled", {
  brms_setup("standata:731",
    df <- data.frame(y = 1:10, g = rep(c("a", "b"), 5))
  )
  brms_setup("standata:732",
    bform <- bf(y ~ g) +
      lf(disc ~ 0 + g + (0 + g | y), cmc = FALSE) +
      cumulative()
  )
  brms_setup("standata:736",
    sdata <- standata(bform, df)
  )
  brms_setup("standata:737",
    target <- matrix(rep(0:1, 5), dimnames = list(1:10, "gb"))
  )
  brms_port("standata:738", "cannot transfer",
    paste0(
      "lf() takes no cmc argument; frmtmb refuses it with the ",
      "misleading 'lf() takes two-sided formulas', and X_disc and ",
      "Z_1_disc_1 are Stan data"),
    expect_equal(sdata$X_disc, target)
  )
  brms_port("standata:739", "cannot transfer",
    "lf() takes no cmc argument, and Z_1_disc_1 is Stan data",
    expect_equal(unname(sdata$Z_1_disc_1), as.array(rep(0:1, 5)))
  )
  brms_port("standata:740", "cannot transfer",
    "lf() takes no cmc argument",
    expect_true(!"Z_1_disc_2" %in% names(sdata))
  )
  brms_setup("standata:742",
    bform <- bf(y ~ 0 + g + (1 | y), cmc = FALSE)
  )
  brms_setup("standata:743",
    sdata <- standata(bform, df)
  )
  brms_port("standata:744", "cannot transfer",
    "bf() takes no cmc argument",
    expect_equal(sdata$X, target)
  )
  brms_port("standata:745", "cannot transfer",
    "bf() takes no cmc argument, and Z_1_1 is Stan data",
    expect_equal(unname(sdata$Z_1_1), as.array(rep(1, 10)))
  )
})

test_that("dots in formula are correctly expanded", {
  brms_setup("standata:926",
    dat <- data.frame(y = 1:10, x1 = 1:10, x2 = 1:10)
  )
  brms_setup("standata:927",
    sdata <- standata(y ~ ., dat)
  )
  brms_port("standata:928", "defect",
    paste0(
      "y ~ . is not expanded: frm() dies with R's ''.' in formula ",
      "and no data argument' on the fit route and the frame route ",
      "alike, where brms expands the dot against the data ",
      "(dev/brmsport-probe3.R)"),
    expect_equal(colnames(sdata$X), c("Intercept", "x1", "x2"))
  )
})

test_that("reserved variables 'Intercept' is handled correctly", {
  brms_setup("standata:969",
    dat <- data.frame(y = 1:10)
  )
  brms_port("standata:970", "cannot transfer",
    paste0(
      "frmtmb has no reserved Intercept variable, so 0 + intercept ",
      "dies with R's object 'intercept' not found"),
    expect_warning(
      sdata <- standata(y ~ 0 + intercept, dat),
      "Reserved variable name 'intercept' is deprecated."
    )
  )
  brms_port("standata:974", "cannot transfer",
    "frmtmb has no reserved intercept variable",
    expect_true(all(sdata$X[, "intercept"] == 1))
  )
  brms_setup("standata:975",
    sdata <- standata(y ~ 0 + Intercept, dat)
  )
  brms_port("standata:976", "cannot transfer",
    paste0(
      "frmtmb has no reserved Intercept variable: y ~ 0 + ",
      "Intercept dies with R's object 'Intercept' not found"),
    expect_true(all(sdata$X[, "Intercept"] == 1))
  )
})

test_that("standata handles addition term 'rate' is correctly", {
  brms_setup("standata:1045",
    data <- data.frame(y = rpois(10, 1), x = rnorm(10), time = 1:10)
  )
  brms_setup("standata:1046",
    sdata <- standata(y | rate(time) ~ x, data, poisson())
  )
  brms_port("standata:1047", "cannot transfer",
    "frmtmb has no rate() addition term",
    expect_equal(sdata$denom, as.array(data$time))
  )
})

test_that("standata handles grouped ordinal thresholds correctly", {
  brms_setup("standata:1051",
    dat <- data.frame(
      y = c(1:5, 1:4, 4),
      gr = rep(c("a", "b"), each = 5),
      th = rep(5:6, each = 5),
      x = rnorm(10)
    )
  )
  brms_setup("standata:1059",
    sdata <- standata(y ~ x, dat, cumulative())
  )
  brms_port("standata:1060", "pass",
    "",
    expect_equal(sdata$nthres, 4)
  )
  brms_setup("standata:1062",
    sdata <- standata(y | thres(5) ~ x, dat, cumulative())
  )
  brms_port("standata:1063", "cannot transfer",
    paste0(
      "frmtmb has no thres() addition term ",
      "(dev/brms-suite-audit.md section 5)"),
    expect_equal(sdata$nthres, 5)
  )
  brms_port("standata:1065", "cannot transfer",
    "frmtmb has no thres() addition term",
    expect_error(
      standata(y | thres(th) ~ x, dat, cumulative()),
      "Number of thresholds needs to be a single value"
    )
  )
  brms_setup("standata:1071",
    sdata <- standata(y | thres(th, gr) ~ x, dat, cumulative())
  )
  brms_port("standata:1072", "cannot transfer",
    "frmtmb has no thres() addition term",
    expect_equal(sdata$nthres, as.array(c(5, 6)))
  )
  brms_port("standata:1073", "cannot transfer",
    paste0(
      "frmtmb has no thres() addition term; ngrthres is also Stan ",
      "data"),
    expect_equal(sdata$ngrthres, 2)
  )
  brms_port("standata:1074", "cannot transfer",
    paste0(
      "frmtmb has no thres() addition term; Jthres is also Stan ",
      "data"),
    expect_equal(unname(sdata$Jthres[1, ]), c(1, 5))
  )
  brms_port("standata:1075", "cannot transfer",
    paste0(
      "frmtmb has no thres() addition term; Jthres is also Stan ",
      "data"),
    expect_equal(unname(sdata$Jthres[10, ]), c(6, 11))
  )
  brms_setup("standata:1077",
    sdata <- standata(y | thres(gr = gr) ~ x, dat, cumulative())
  )
  brms_port("standata:1078", "cannot transfer",
    "frmtmb has no thres() addition term",
    expect_equal(sdata$nthres, as.array(c(4, 3)))
  )
  brms_port("standata:1079", "cannot transfer",
    paste0(
      "frmtmb has no thres() addition term; ngrthres is also Stan ",
      "data"),
    expect_equal(sdata$ngrthres, 2)
  )
  brms_setup("standata:1081",
    sdata <- standata(y | thres(6, gr = gr) ~ x, dat, cumulative())
  )
  brms_port("standata:1082", "cannot transfer",
    "frmtmb has no thres() addition term",
    expect_equal(sdata$nthres, as.array(c(6, 6)))
  )
  brms_port("standata:1083", "cannot transfer",
    paste0(
      "frmtmb has no thres() addition term; ngrthres is also Stan ",
      "data"),
    expect_equal(sdata$ngrthres, 2)
  )
})

test_that("NAs are allowed in unused interval censoring variables", {
  brms_setup("standata:1110",
    dat <- data.frame(y = rnorm(10), ce = c(1, rep(2, 9)))
  )
  brms_setup("standata:1111",
    dat$y2 <- dat$y + 2
  )
  brms_setup("standata:1112",
    dat$y2[1] <- NA
  )
  brms_setup("standata:1113",
    sdata <- standata(y | cens(ce, y2 = y2) ~ 1, data = dat)
  )
  brms_port("standata:1114", "pass",
    "",
    expect_equal(sdata$N, 10L)
  )
  brms_port("standata:1115", "pass",
    "",
    expect_equal(sdata$rcens[1], 0)
  )
  brms_setup("standata:1117",
    dat$ce[1] <- 2
  )
  brms_port_own("standata:1118",
    paste0(
      "cens[(][)] upper bounds must not be NA on interval-censored ",
      "rows"),
    paste0(
      "brms: 'y2' should not be NA for interval censored ",
      "observations"),
    expect_error(
      standata(y | cens(ce, y2 = y2) ~ 1, data = dat),
      "'y2' should not be NA for interval censored observations"
    )
  )
})

test_that("drop_unused_factor levels works correctly", {
  brms_setup("standata:1125",
    dat <- data.frame(y = rnorm(10), x = factor(c("a", "b"), levels = c("a", 
        "b", "c")))
  )
  brms_setup("standata:1128",
    sdata <- standata(y ~ x, data = dat)
  )
  brms_port("standata:1129", "pass",
    "",
    expect_equal(colnames(sdata$X), c("Intercept", "xb"))
  )
  brms_setup("standata:1132",
    sdata <- standata(y ~ x, data = dat, drop_unused_levels = FALSE)
  )
  brms_port("standata:1133", "cannot transfer",
    paste0(
      "frm() takes no drop_unused_levels argument; the unused ",
      "level is always dropped"),
    expect_equal(colnames(sdata$X), c("Intercept", "xb", "xc"))
  )
})
