# GENERATED by dev/brmsport-gen.R from brms 2.23.0
# tests/testthat/tests.priors.R. Do not edit by hand: change
# dev/brmsport-verdicts.tsv or the generator, then regenerate.
# helper-brms-suite.R says what brms_port() asserts.

skip_unless_brms_suite()
epilepsy <- brms::epilepsy
inhaler <- brms::inhaler

test_that("default_prior finds all classes for which priors can be specified", {
  brms_port("priors:5", "divergence",
    paste0(
      "frmtmb lists 5 class theta rows (its covariance parameters) ",
      "and no per-coefficient sd rows, since its class sd ",
      "addresses a block and refuses coef (priorform ledger P1)"),
    expect_equal(
      sort(
        default_prior(
          count ~ zBase * Trt + (1|patient) + (1+Trt|visit),
          data = epilepsy, family = "poisson"
        )$class
      ),
      sort(c(rep("b", 4), c("cor", "cor"), "Intercept", rep("sd", 6)))
    )
  )
  brms_port("priors:14", "cannot transfer",
    paste0(
      "sratio() takes no threshold = 'equidistant' and there is no ",
      "cse() alias (priorform ledger P2)"),
    expect_equal(
      sort(
        default_prior(
          rating ~ treat + period + cse(carry), data = inhaler,
          family = sratio(threshold = "equidistant")
        )$class
      ),
      sort(c(rep("b", 4), "delta", rep("Intercept", 1)))
    )
  )
})

test_that("set_prior allows arguments to be vectors", {
  brms_setup("priors:26",
    bprior <- set_prior("normal(0, 2)", class = c("b", "sd"))
  )
  brms_port("priors:27", "divergence",
    paste0(
      "expect_is(bprior, 'brmsprior'): the object is a ",
      "frmtmb_priorlist; brms's class name; frmtmb objects must ",
      "NOT carry brms's class names (user decision, 2026-09-17, ",
      "rule 2)"),
    expect_is(bprior, "brmsprior")
  )
  brms_port("priors:28", "pass",
    "",
    expect_equal(bprior$prior, rep("normal(0, 2)", 2))
  )
  brms_port("priors:29", "pass",
    "",
    expect_equal(bprior$class, c("b", "sd"))
  )
})

test_that("print for class brmsprior works correctly", {
  brms_port("priors:33", "pass",
    "",
    expect_output(print(set_prior("normal(0,1)")), fixed = TRUE,
                  "b ~ normal(0,1)")
  )
  brms_port("priors:35", "pass",
    "",
    expect_output(print(set_prior("normal(0,1)", coef = "x")),
                  "b_x ~ normal(0,1)", fixed = TRUE)
  )
  brms_port("priors:37", "pass",
    "",
    expect_output(print(set_prior("cauchy(0,1)", class = "sd", group = "x")),
                  "sd_x ~ cauchy(0,1)", fixed = TRUE)
  )
  brms_port("priors:39", "cannot transfer",
    paste0(
      "set_prior(check = FALSE) passes Stan code through, and ",
      "frmtmb builds no Stan program (priorform ledger P9)"),
    expect_output(print(set_prior("target += normal_lpdf(x | 0,1))", 
        check = FALSE)), "target += normal_lpdf(x | 0,1))", fixed = TRUE)
  )
})

test_that("default_prior returns correct nlpar names for random effects pars", {
  brms_setup("priors:45",
    dat <- data.frame(y = rnorm(10), x = rnorm(10), g = rep(1:2, 5))
  )
  brms_setup("priors:46",
    bform <- bf(y ~ a - b^x, a + b ~ (1+x|g), nl = TRUE)
  )
  brms_setup("priors:47",
    gp <- default_prior(bform, data = dat)
  )
  brms_port("priors:48", "pass",
    "",
    expect_equal(sort(unique(gp$nlpar)), c("", "a", "b"))
  )
})

test_that("default_prior returns correct fixed effect names for GAMMs", {
  brms_setup("priors:52",
    dat <- data.frame(y = rnorm(10), x = rnorm(10),
                      z = rnorm(10), g = rep(1:2, 5))
  )
  brms_setup("priors:54",
    prior <- default_prior(y ~ z + s(x) + (1|g), data = dat)
  )
  brms_port("priors:55", "defect",
    paste0(
      "the prior table names a smooth's unpenalized column ",
      "s(x).fx1 where brms writes sx_1, and variables() already ",
      "writes bs_sx_1; priorform P11/P12 deferred to brmsnames and ",
      "brmsnames deferred back, so no document decides it"),
    expect_equal(prior[prior$class == "b", ]$coef,
                 c("", "sx_1", "z"))
  )
  brms_setup("priors:57",
    prior <- default_prior(bf(y ~ lp, lp ~ z + s(x) + (1|g), nl = TRUE),
                       data = dat)
  )
  brms_port("priors:59", "defect",
    paste0(
      "the prior table names a smooth's unpenalized column ",
      "s(x).fx1 where brms writes sx_1, and variables() already ",
      "writes bs_sx_1; priorform P11/P12 deferred to brmsnames and ",
      "brmsnames deferred back, so no document decides it"),
    expect_equal(prior[prior$class == "b", ]$coef,
                 c("", "Intercept", "sx_1", "z"))
  )
})

test_that("default_prior returns correct prior names for auxiliary parameters", {
  brms_setup("priors:64",
    dat <- data.frame(y = rnorm(10), x = rnorm(10),
                      z = rnorm(10), g = rep(1:2, 5))
  )
  brms_setup("priors:66",
    bform <- bf(y ~ 1, phi ~ z + (1|g), family = Beta())
  )
  brms_setup("priors:67",
    prior <- default_prior(bform, data = dat)
  )
  brms_setup("priors:68",
    prior <- prior[prior$dpar == "phi", ]
  )
  brms_setup("priors:69",
    pdata <- data.frame(class = c("b", "b", "Intercept", rep("sd", 3)),
                        coef = c("", "z", "", "", "", "Intercept"),
                        group = c(rep("", 4), "g", "g"),
                        stringsAsFactors = FALSE)
  )
  brms_setup("priors:73",
    pdata <- pdata[with(pdata, order(class, group, coef)), ]
  )
  brms_port("priors:74", "defect",
    paste0(
      "default_prior() and get_prior() validate the response ",
      "against the family and refuse brms's rnorm response under ",
      "Beta(); brms returns 7 rows. PRE-EXISTING: refused at every ",
      "commit back to base 0.58.0 (dev/brmsport-rev-regress.R). ",
      "priorform's P13 showed a table only because ",
      "dev/priorform-ledger.R replaced brms's y with runif(10)"),
    expect_equivalent(prior[, c("class", "coef", "group")], pdata)
  )
})

test_that("default_prior returns correct priors for multivariate models", {
  brms_setup("priors:78",
    dat <- data.frame(y1 = rnorm(10), y2 = c(1, rep(1:3, 3)),
                      x = rnorm(10), g = rep(1:2, 5))
  )
  brms_setup("priors:80",
    bform <- bf(mvbind(y1, y2) ~ x + (x|ID1|g)) + set_rescor(TRUE)
  )
  brms_setup("priors:83",
    prior <- default_prior(bform, dat, family = gaussian())
  )
  brms_port("priors:84", "pass",
    "",
    expect_equal(prior[prior$resp == "y1" & prior$class == "b", "coef"], 
        c("", "x"))
  )
  brms_port("priors:85", "divergence",
    paste0(
      "default_prior() describes frm(), which is flat in every ",
      "slot; the sampling route's flat rescor is a filed ",
      "frmtmb.sample defect (priorform ledger P15, ",
      "dev/priorform-findings.md section 6)"),
    expect_equal(prior[prior$class == "rescor", "prior"], "lkj(1)")
  )
  brms_setup("priors:88",
    family <- list(gaussian, Beta())
  )
  brms_setup("priors:89",
    bform <- bf(y1 ~ x + (x|ID1|g) + ar()) + bf(y2 ~ 1)
  )
  brms_setup("priors:90",
    prior <- default_prior(bform, dat, family = family)
  )
  brms_port("priors:91", "cannot transfer",
    paste0(
      "frmtmb takes no list of families as family (priorform ",
      "ledger P16); the object read is the previous model's table"),
    expect_true(any(with(prior, class == "sigma" & resp == "y1")))
  )
  brms_port("priors:92", "cannot transfer",
    paste0(
      "frmtmb takes no list of families as family (priorform ",
      "ledger P17)"),
    expect_true(any(with(prior, class == "ar" & resp == "y1")))
  )
  brms_port("priors:93", "cannot transfer",
    paste0(
      "frmtmb takes no list of families as family (priorform ",
      "ledger P18)"),
    expect_true(any(with(prior, class == "phi" & resp == "y2")))
  )
  brms_port("priors:94", "cannot transfer",
    paste0(
      "frmtmb takes no list of families as family (priorform ",
      "ledger P19); the object read is the previous model's table"),
    expect_true(!any(with(prior, class == "ar" & resp == "y2")))
  )
})

test_that("default_prior returns correct priors for categorical models", {
  brms_setup("priors:99",
    dat <- data.frame(y2 = c(1, rep(1:3, 3)), x = rnorm(10), g = rep(1:2, 5))
  )
  brms_setup("priors:100",
    prior <- default_prior(y2 ~ x + (x | ID1 | g), data = dat, family = categorical())
  )
  brms_port("priors:101", "defect",
    paste0(
      "categorical() refuses the integer response c(1, rep(1:3, ",
      "3)) with the false claim 'fewer than two categories'; ",
      "priorform ledger P20 deferred it to famlink as cannot ",
      "transfer, and it is the defect of standata:83"),
    expect_equal(prior[prior$dpar == "mu2" & prior$class == "b", 
        "coef"], c("", "x"))
  )
})

test_that("set_prior alias functions produce equivalent results", {
  brms_port("priors:105", "pass",
    "",
    expect_equal(set_prior("normal(0, 1)", class = "sd"),
                 prior(normal(0, 1), class = sd))
  )
  brms_port("priors:107", "pass",
    "",
    expect_equal(set_prior("normal(0, 1)", class = "sd", nlpar = "a"),
                 prior(normal(0, 1), class = "sd", nlpar = a))
  )
  brms_port("priors:109", "pass",
    "",
    expect_equal(set_prior("normal(0, 1)", class = "sd", nlpar = "a"),
                 prior_(~normal(0, 1), class = ~sd, nlpar = quote(a)))
  )
  brms_port("priors:111", "pass",
    "",
    expect_equal(set_prior("normal(0, 1)", class = "sd"),
                 prior_string("normal(0, 1)", class = "sd"))
  )
})

test_that("external interface of validate_prior works correctly", {
  brms_setup("priors:116",
    prior1 <- prior(normal(0,10), class = b) +
      prior(cauchy(0,2), class = sd)
  )
  brms_setup("priors:118",
    prior1 <- validate_prior(
      prior1, count ~ zAge + zBase * Trt + (1|patient),
      data = epilepsy, family = poisson()
    )
  )
  brms_port("priors:122", "pass",
    "",
    expect_true(all(c("b", "Intercept", "sd") %in% prior1$class))
  )
  brms_port("priors:123", "divergence",
    paste0(
      "10 rows against brms's 9: two class theta rows added, one ",
      "per-coefficient sd row absent (priorform ledger P26)"),
    expect_equal(nrow(prior1), 9)
  )
})

test_that("as.brmsprior works correctly", {
  brms_setup("priors:134",
    dat <- data.frame(prior = "normal(0,1)", x = "test", coef = c("a", "b"))
  )
  brms_setup("priors:135",
    bprior <- as.brmsprior(dat)
  )
  brms_port("priors:136", "pass",
    "",
    expect_equal(bprior$prior, rep("normal(0,1)", 2))
  )
  brms_port("priors:137", "pass",
    "",
    expect_equal(bprior$class, rep("b", 2))
  )
  brms_port("priors:138", "pass",
    "",
    expect_equal(bprior$coef, c("a", "b"))
  )
  brms_port("priors:139", "pass",
    "",
    expect_equal(bprior$x, NULL)
  )
  brms_port("priors:140", "pass",
    "",
    expect_equal(bprior$lb, rep(NA_character_, 2))
  )
})

test_that("prior tags are correctly applied", {
  brms_setup("priors:145",
    prior1 <- prior(normal(0, 1), class = sd, tag = "prior_tag1")
  )
  brms_setup("priors:146",
    prior2 <- prior(normal(0, 5), class = b, tag = "prior_tag2")
  )
  brms_setup("priors:147",
    prior3 <- prior(normal(0, 0.5), coef = "Trt1", tag = "prior_tag3")
  )
  brms_setup("priors:148",
    prior4 <- prior(normal(0, 10), class = "Intercept", tag = "prior_tag4")
  )
  brms_setup("priors:149",
    prior5 <- prior(lkj_corr_cholesky(3), class = "L", group = "visit", 
        tag = "prior_tag5")
  )
  brms_setup("priors:151",
    v <- validate_prior(
      c(prior1, prior2, prior3, prior4, prior5),
      formula = count ~ zBase * Trt + (1 | patient) + (1 + Trt | visit),
      data = epilepsy, family = poisson())
  )
  brms_port("priors:156", "cannot transfer",
    paste0(
      "set_prior() takes no tag: a tag names a prior inside a Stan ",
      "program (priorform ledger P33)"),
    expect_equal(v[which(v$class == "sd"),]$tag[[1]], "prior_tag1")
  )
  brms_port("priors:157", "cannot transfer",
    "set_prior() takes no tag (priorform ledger P34)",
    expect_equal(v[which(v$class == "b" & v$coef != "Trt1"), ]$tag[[1]], 
        "prior_tag2")
  )
  brms_port("priors:158", "cannot transfer",
    "set_prior() takes no tag (priorform ledger P35)",
    expect_equal(v[which(v$class == "b" & v$coef == "Trt1"),]$tag, "prior_tag3")
  )
  brms_port("priors:159", "cannot transfer",
    "set_prior() takes no tag (priorform ledger P36)",
    expect_equal(v[which(v$class == "Intercept"),]$tag, "prior_tag4")
  )
  brms_port("priors:160", "cannot transfer",
    "set_prior() takes no tag (priorform ledger P37)",
    expect_equal(v[which(v$class == "L"),]$tag[[2]], "prior_tag5")
  )
})
