# GENERATED by dev/brmsport-gen.R from brms 2.23.0
# tests/testthat/tests.emmeans.R. Do not edit by hand: change
# dev/brmsport-verdicts.tsv or the generator, then regenerate.
# helper-brms-suite.R says what brms_port() asserts.

skip_unless_brms_suite()
skip_if_not_installed("emmeans")
library(emmeans)
SW <- suppressWarnings
rename_pars <- brms_shim_rename_pars
fit1 <- brms_fixture(1)
fit2 <- brms_fixture(2)
fit4 <- brms_fixture(4)
fit6 <- brms_fixture(6)

test_that("emmeans returns expected output structure", {
  brms_setup("emmeans:14",
    em <- summary(emmeans(fit1, "Age", by = "Trt"))
  )
  brms_port("emmeans:15", "pass",
    "",
    expect_equal(nrow(em), 2)
  )
  brms_setup("emmeans:17",
    em <- summary(emmeans(fit1, "Trt", dpar = "sigma"))
  )
  brms_port("emmeans:18", "pass",
    "",
    expect_equal(nrow(em), 2)
  )
  brms_setup("emmeans:20",
    em <- summary(emmeans(fit1, "Age", by = "Exp"))
  )
  brms_port("emmeans:21", "defect",
    paste0(
      "emmeans(fit1, 'Age', by = 'Exp') is refused, 'No variable ",
      "named Exp in the reference grid': the mo(Exp) variable is ",
      "not in frmtmb's recover_data()"),
    expect_equal(nrow(em), 5)
  )
  brms_setup("emmeans:23",
    em <- summary(emmeans(fit1, "Exp"))
  )
  brms_port("emmeans:24", "defect",
    paste0(
      "emmeans(fit1, 'Exp') is refused: the mo(Exp) variable is ",
      "not in the reference grid"),
    expect_equal(nrow(em), 5)
  )
  brms_setup("emmeans:26",
    em <- SW(summary(emmeans(fit2, "Age", nlpar = "a")))
  )
  brms_port("emmeans:27", "cannot transfer",
    paste0(
      "frmtmb's emmeans support is declared refused for a ",
      "nonlinear mu ('needs a linear mu predictor', ",
      "R/compat.R:1612, enforced by emm_mu_linpred()); the reason ",
      "is hidden by emmeans, a separate defect"),
    expect_equal(nrow(em), 1)
  )
  brms_setup("emmeans:29",
    em <- SW(summary(emmeans(fit4, "x1", dpar = "mu")))
  )
  brms_port("emmeans:30", "pass",
    "",
    expect_equal(nrow(em), 1)
  )
})

test_that("emmeans supports 'epred' predictions", {
  brms_setup("emmeans:34",
    em <- summary(emmeans(fit2, "Age", epred = TRUE))
  )
  brms_port("emmeans:35", "cannot transfer",
    paste0(
      "frmtmb's emmeans support is declared refused for a ",
      "nonlinear mu ('needs a linear mu predictor', ",
      "R/compat.R:1612, enforced by emm_mu_linpred()); the reason ",
      "is hidden by emmeans, a separate defect"),
    expect_equal(nrow(em), 1)
  )
  brms_setup("emmeans:37",
    em <- summary(emmeans(fit2, "Age", by = "Trt", epred = TRUE))
  )
  brms_port("emmeans:38", "cannot transfer",
    paste0(
      "frmtmb's emmeans support is declared refused for a ",
      "nonlinear mu ('needs a linear mu predictor', ",
      "R/compat.R:1612, enforced by emm_mu_linpred()); the reason ",
      "is hidden by emmeans, a separate defect"),
    expect_equal(nrow(em), 2)
  )
  brms_setup("emmeans:41",
    em <- summary(emmeans(fit6, "Age", by = "Trt", epred = TRUE))
  )
  brms_port("emmeans:42", "cannot transfer",
    paste0(
      "frmtmb's emmeans support is declared univariate only ",
      "(R/compat.R:1356); the reason is hidden by emmeans, a ",
      "separate defect"),
    expect_equal(nrow(em), 2)
  )
})

test_that("emmeans supports multilevel terms", {
  brms_setup("emmeans:46",
    em <- summary(emmeans(fit1, "Age", by = "Trt", re_formula = NULL))
  )
  brms_port("emmeans:47", "pass",
    "",
    expect_equal(nrow(em), 2)
  )
  brms_setup("emmeans:49",
    em <- SW(summary(emmeans(fit2, "Age", nlpar = "a", re_formula = NULL)))
  )
  brms_port("emmeans:50", "cannot transfer",
    paste0(
      "frmtmb's emmeans support is declared refused for a ",
      "nonlinear mu ('needs a linear mu predictor', ",
      "R/compat.R:1612, enforced by emm_mu_linpred()); the reason ",
      "is hidden by emmeans, a separate defect"),
    expect_equal(nrow(em), 1)
  )
})
