# GENERATED by dev/brmsport-gen.R from brms 2.23.0
# tests/testthat/tests.brm.R. Do not edit by hand: change
# dev/brmsport-verdicts.tsv or the generator, then regenerate.
# helper-brms-suite.R says what brms_port() asserts.

skip_unless_brms_suite()
brm <- brms_shim_brm
inhaler <- brms::inhaler

test_that("brm produces expected errors", {
  brms_setup("brm:72",
    dat <- data.frame(y = rnorm(10), x = rnorm(10), g = rep(1:5, 2))
  )
  brms_port_own("brm:75",
    "needs a response [(]left-hand side[)]",
    "brms: Response variable is missing",
    expect_error(brm(~ x + (1|g), dat, file = "test"),
                 "Response variable is missing")
  )
  brms_port_own("brm:77",
    paste0(
      "nonlinear formula needs at least one nonlinear-parameter ",
      "formula"),
    "brms: No non-linear parameters specified",
    expect_error(brm(bf(y ~ a, nl = TRUE)),
                 "No non-linear parameters specified")
  )
  brms_port_own("brm:79",
    "se[(][)] without sigma = TRUE replaces the residual scale",
    "brms: Cannot predict or fix 'sigma' in this model",
    expect_error(brm(bf(y | se(sei) ~ x, sigma ~ x), dat),
                 "Cannot predict or fix 'sigma' in this model")
  )
  brms_port("brm:81", "defect",
    paste0(
      "not the same refusal: frmtmb validates the data first and ",
      "refuses the missing column by name, 'The model uses `sei`, ",
      "which is not a column of `data`', where brms refuses se() ",
      "for weibull from the formula alone; with sei present frmtmb ",
      "does refuse se() for weibull (dev/brmsport-probe3.R). The ",
      "message is frmtmb's own, not base R's 'object not found', ",
      "which is what this reason used to say"),
    expect_error(brm(y | se(sei) ~ x, dat, family = weibull()),
                 "Argument 'se' is not supported for family")
  )
  brms_port_own("brm:83",
    "Duplicated addition term `se[(][)]`",
    "brms: Each addition argument may only be defined once",
    expect_error(brm(y | se(sei) + se(sei2) ~ x, dat, family = gaussian()),
                 "Each addition argument may only be defined once")
  )
  brms_port_own("brm:85",
    "Addition term `abc[(][)]` is not supported",
    "brms: The following addition terms are invalid",
    expect_error(brm(y | abc(sei) ~ x, family = gaussian()),
                 "The following addition terms are invalid:\n'abc(sei)'",
                 fixed = TRUE)
  )
  brms_port_own("brm:88",
    "Addition term `disp[(][)]` is not supported",
    "brms: The following addition terms are invalid",
    expect_error(brm(y | disp(sei) ~ x, dat, family = gaussian()),
                 "The following addition terms are invalid:")
  )
  brms_port_own("brm:90",
    "not available for family 'gaussian': shape",
    "brms: The parameter 'shape' is not a valid distributional",
    expect_error(brm(bf(y ~ x, shape ~ x), family = gaussian()),
                 "The parameter 'shape' is not a valid distributional")
  )
  brms_port_own("brm:92",
    paste0(
      "The [|]abc[|] key is used over more than one grouping ",
      "specification"),
    "brms: Can only combine group-level terms",
    expect_error(brm(y ~ x + (1|abc|g/x), dat),
                 "Can only combine group-level terms")
  )
  brms_port("brm:94", "pass",
    "",
    expect_error(brm(y ~ x + (1|g) + (x|g), dat),
                 "Duplicated group-level effects are not allowed")
  )
  brms_port("brm:96", "pass",
    "",
    expect_error(brm(y~mo(g)*t2(x), dat), fixed = TRUE,
                 "The term 'mo(g):t2(x)' is invalid")
  )
  brms_port("brm:98", "pass",
    "",
    expect_error(brm(y~x*cs(g), dat), fixed = TRUE,
                 "The term 'x:cs(g)' is invalid")
  )
  brms_port("brm:100", "pass",
    "",
    expect_error(brm(y~me(x, 2 * g)*me(x, g), dat),
                 "Variable 'x' is used in different calls to 'me'")
  )
  brms_port("brm:102", "defect",
    paste0(
      "set_rescor() on the right-hand side reaches model.frame and ",
      "dies with R's 'invalid type (list) for variable', not a ",
      "designed refusal (dev/brmsport-probe3.R)"),
    expect_error(brm(y ~ 1 + set_rescor(TRUE), data = dat),
                 "Function 'set_rescor' should not be part")
  )
  brms_port_own("brm:106",
    "the time index must be ONE variable name",
    paste0(
      "brms: Cannot coerce 'x + y' to a single variable name. The ",
      "grammar check runs before the cov = TRUE one, so the ported ",
      "call, which omits cov, reaches it ",
      "(dev/adefects-log/evidence.txt)"),
    expect_error(brm(y ~ ar(x+y, g), dat),
                 "Cannot coerce 'x \\+ y' to a single variable name")
  )
  brms_port_own("brm:108",
    "grouping term must be variable names combined by",
    paste0(
      "brms: Illegal grouping term 'g1/g2'. The grammar check runs ",
      "before the cov = TRUE one, so the ported call reaches it"),
    expect_error(brm(y ~ ar(gr = g1/g2), dat),
                 "Illegal grouping term 'g1/g2'")
  )
  brms_port_own("brm:110",
    paste0(
      "ma[(][)]: only the residual-covariance formulation is ",
      "implemented, so the call needs cov = TRUE"),
    paste0(
      "brms: Please set cov = TRUE. CAVEAT: frmtmb gives this ",
      "message for ma(x) on every family, including gaussian, ",
      "which brms fits (defect filed)"),
    expect_error(brm(y ~ ma(x), dat, poisson()),
                 "Please set cov = TRUE")
  )
  brms_port("brm:112", "cannot transfer",
    paste0(
      "frmtmb has no arma() function object to add to a formula; ",
      "the term exists only inside a formula"),
    expect_error(brm(bf(y ~ 1) + arma(x), dat),
                 "Autocorrelation terms can only be specified")
  )
  brms_port("brm:116", "defect",
    paste0(
      "categorical() refuses the integer response inhaler$rating ",
      "(4 categories) with the FALSE claim 'fewer than two ",
      "categories', before reaching the cs() check brms asserts; a ",
      "factor response is accepted (dev/brmsport-probe3.R; ",
      "priorform ledger P20 deferred it to famlink)"),
    expect_error(brm(rating ~ treat + (cs(period)|subject),
                     data = inhaler, family = categorical()),
                 "Category specific effects are not supported")
  )
  brms_port("brm:121", "pass",
    "",
    expect_error(brm(y ~ x, dat, family = poisson("inverse")),
                 "'inverse' is not a supported link for family 'poisson'")
  )
  brms_port("brm:123", "pass",
    "",
    expect_error(brm(y ~ x, dat, family = c("weibull", "sqrt")),
                 "'sqrt' is not a supported link for family 'weibull'")
  )
  brms_port("brm:125", "pass",
    "",
    expect_error(brm(y ~ x, dat, family = c("categorical", "probit")),
                 "'probit' is not a supported link for family 'categorical'")
  )
  brms_port("brm:127", "pass",
    "",
    expect_error(brm(y ~ x, dat, family = "ordinal"),
                "ordinal is not a supported family")
  )
})
