# The agreement tier: every family's simulator against that family's OWN
# log-density.
#
# WHY this file exists, and why it is the one place that breaks the
# suite's usual rule. Everywhere else the reference is generated by
# hand, deliberately: a validation test that drew its data from the
# package could not see a convention error the simulator and the
# density SHARE, such as a shape/scale swap, a variance-for-sd slip or
# a zero-inflation gate read the wrong way round, because the round trip
# cancels it. That argument makes the hand-written reference necessary
# there, and it also leaves frm_simulate() untested AS A GENERATIVE
# PROCESS: nothing said the draws came from the distribution the
# likelihood scores.
#
# This file closes that loop, in the only direction where closing it
# proves something. The draws come from the family's `sim` slot; every
# number they are tested against is computed FROM `fam$lpdf`
# numerically, never from a closed form written out beside it. A
# convention the two halves share is exactly what fails here, because
# the two halves are compared against each other instead of against a
# third thing both were copied from.
#
# Two statistics per family, at a fixed parameter point on a fixed
# two-cell design:
#
#   1. a chi-square goodness of fit over cells whose probabilities are
#      summed (discrete) or integrated (continuous) from `fam$lpdf`;
#   2. the first two moments, taken from the same numeric measure,
#      against the sample mean and variance.
#
# The design carries two cells so that a simulator which ignores the
# per-row distributional parameters, reading `dpars[["mu"]][1]` and
# recycling it, fails rather than passing on the first cell's
# parameters.

skip_on_cran()

# --- tolerances -------------------------------------------------------
#
# One false-alarm rate drives every threshold in the file, and it is
# small for a reason that is about maintenance rather than statistics.
# The seed is fixed, so a false alarm here would not be flaky: it would
# be PERMANENT, and somebody would have to work out whether a correct
# simulator or a real defect was on the other end of it.
#
# Buying that costs almost no detection. On SIM_CELLS cells the
# chi-square critical value at this alpha is about 41 on 7 degrees of
# freedom, while a simulator that genuinely draws from another
# distribution misses the cell probabilities by whole percentage points
# and lands a statistic in the hundreds at SIM_N draws. The margin
# between 41 and "hundreds" is what the small alpha buys, and it is why
# the number is one constant rather than a value tuned per family.
#
# The trade depends on the COUNT, so it is written down here: 251 of
# this file's assertions are statistical (87 chi-square, 77 mean, 77
# variance, 10 P(Y = 0)). At this alpha that is a 0.0003 chance that
# any reseed raises a permanent false alarm somewhere in the file; at
# 1e-3 it would be 0.22, and at a conventional 0.05 it would be a
# near-certainty. Re-check the arithmetic if the tier grows by an
# order of magnitude.
SIM_ALPHA <- 1e-6
SIM_N <- 4000L        # draws PER CELL: two cells, 8000 rows per family
SIM_CELLS <- 8L
SIM_Z <- stats::qnorm(1 - SIM_ALPHA / 2)   # two-sided, same alpha
SIM_SEED <- 20250905L

# --- reading the density numerically ----------------------------------

#' Evaluate a family's log-density off the tape. RTMB's `d*` functions
#' are numeric on numeric input, so this is the same code the objective
#' tapes, run in plain doubles. The ordinal families take their
#' thresholds as a fourth argument; the rowwise contract is three.
dens_lp <- function(fam, y, dp, at = list(), extra = NULL) {
  n <- if (is.matrix(y)) nrow(y) else length(y)
  rec <- function(v) if (is.numeric(v) && length(v) == 1L) rep(v, n) else v
  dp <- lapply(dp, rec)
  at <- lapply(at, rec)
  out <- if (length(formals(fam[["lpdf"]])) >= 4L) {
    fam[["lpdf"]](y, dp, at, extra)
  } else {
    fam[["lpdf"]](y, dp, at)
  }
  as.numeric(out)
}

#' The density as a discrete measure, its points and the probability at
#' each, so that one set of cell and moment code serves every support.
#'
#' `kind` is "disc" (integer support 0..hi, the exact pmf), "ord"
#' (categories 1..hi), or "cont" (a bracket, discretized on a fine grid
#' with trapezoid weights). A family with an atom at zero passes
#' "cont" for its continuous part and tests the atom separately, which
#' keeps both statistics sharp instead of burying the atom in a cell.
dens_points <- function(fam, dp, at, kind, lo, hi, extra = NULL,
                        m = 4001L) {
  if (identical(kind, "ord")) {
    y <- seq_len(hi)
    return(list(y = y, p = exp(dens_lp(fam, y, dp, at, extra))))
  }
  if (identical(kind, "disc")) {
    y <- seq.int(0L, hi)
    return(list(y = y, p = exp(dens_lp(fam, y, dp, at, extra))))
  }
  y <- seq(lo, hi, length.out = m)
  # a family with an atom at zero returns log P(Y = 0) there, which is
  # not a density value and must not enter the quadrature
  y[y == 0] <- .Machine$double.eps
  d <- exp(dens_lp(fam, y, dp, at, extra))
  h <- diff(y)
  w <- c(h[1L], h[-1L] + h[-length(h)], h[length(h)]) / 2
  list(y = y, p = d * w)
}

#' Mean, variance and fourth central moment of a discrete measure. The
#' fourth is what gives the variance check its standard error.
dens_moments <- function(dz) {
  p <- dz[["p"]] / sum(dz[["p"]])
  m1 <- sum(p * dz[["y"]])
  cy <- dz[["y"]] - m1
  list(mean = m1, var = sum(p * cy^2), m4 = sum(p * cy^4))
}

#' Merge two measures (an atom at zero and a continuous part) into one,
#' for the moments of a zero-inflated or hurdle family.
dens_mix0 <- function(dz, p0) {
  p <- dz[["p"]] / sum(dz[["p"]]) * (1 - p0)
  list(y = c(0, dz[["y"]]), p = c(p0, p))
}

#' Cut a measure into at most `B` cells of roughly equal probability,
#' returning the cut points and each cell's exact probability under the
#' density. A support with fewer distinct points than cells (bernoulli)
#' keeps one cell per point; an integer support cuts at half-integers so
#' a draw can never land on a boundary.
dens_cells <- function(dz, B, integer_support) {
  p <- dz[["p"]] / sum(dz[["p"]])
  y <- dz[["y"]]
  pos <- which(p > 1e-12)
  if (length(pos) <= B) {
    yk <- y[pos]
    cuts <- if (length(yk) < 2L) numeric(0) else {
      (yk[-1L] + yk[-length(yk)]) / 2
    }
  } else {
    cp <- cumsum(p)
    idx <- unique(pmin(findInterval(seq_len(B - 1L) / B, cp) + 1L,
                       length(y) - 1L))
    cuts <- unique(if (integer_support) y[idx] + 0.5 else y[idx])
  }
  cell <- findInterval(y, cuts) + 1L
  nb <- length(cuts) + 1L
  list(cuts = cuts,
       p = as.numeric(tapply(p, factor(cell, levels = seq_len(nb)),
                             sum, default = 0)))
}

# --- the two statistics -----------------------------------------------

#' Chi-square goodness of fit of `draws` against cell probabilities read
#' off the density. Cells the density puts almost nothing in are folded
#' into one tail cell rather than inflating the statistic on a single
#' draw.
expect_gof <- function(draws, cells, label) {
  n <- length(draws)
  obs <- tabulate(findInterval(draws, cells[["cuts"]]) + 1L,
                  length(cells[["p"]]))
  ex <- cells[["p"]] * n
  ok <- !is.na(ex) & ex >= 5
  testthat::expect_gte(sum(ok), 2L, label = paste0(label, ": usable cells"))
  obs <- c(obs[ok], sum(obs[!ok]))
  ex <- c(ex[ok], sum(ex[!ok]))
  if (!any(!ok)) {
    obs <- obs[-length(obs)]
    ex <- ex[-length(ex)]
  }
  df <- length(obs) - 1L
  testthat::expect_lt(sum((obs - ex)^2 / ex),
                      stats::qchisq(1 - SIM_ALPHA, df),
                      label = paste0(label, " chi-square (df ", df, ")"))
}

#' Sample mean and variance against the density's own, each within
#' SIM_Z standard errors of it. `moments` says how many of the two the
#' family has at these parameters: a heavy-tailed member has no finite
#' variance to compare against.
expect_moments <- function(draws, mom, moments, label) {
  n <- length(draws)
  if (moments >= 1L) {
    testthat::expect_lt(abs(mean(draws) - mom[["mean"]]),
                        SIM_Z * sqrt(mom[["var"]] / n),
                        label = paste0(label, " mean"))
  }
  if (moments >= 2L) {
    # var(sample variance) = (mu4 - sigma^4) / n to first order
    sev <- sqrt(max(mom[["m4"]] - mom[["var"]]^2, 0) / n)
    testthat::expect_lt(abs(stats::var(draws) - mom[["var"]]), SIM_Z * sev,
                        label = paste0(label, " variance"))
  }
}

#' The share of exact zeros against the atom the density declares, as a
#' binomial deviate. This is the statistic that would catch a
#' zero-inflation gate read the wrong way round, which the cell test
#' can dilute.
expect_atom0 <- function(draws, p0, label) {
  n <- length(draws)
  testthat::expect_lt(abs(mean(draws == 0) - p0),
                      SIM_Z * sqrt(p0 * (1 - p0) / n),
                      label = paste0(label, " P(Y = 0)"))
}

# --- the fixed design -------------------------------------------------

#' The two-cell design every family draws on: SIM_N rows in cell "a" and
#' SIM_N in cell "b", so `y ~ 0 + g` gives each cell its own predictor.
sim_data <- function(ydummy, extra_cols = list()) {
  n <- 2L * SIM_N
  dd <- data.frame(g = factor(rep(c("a", "b"), each = SIM_N)))
  dd[["y"]] <- rep(ydummy, length.out = n)
  for (nm in names(extra_cols)) dd[[nm]] <- rep(extra_cols[[nm]], length.out = n)
  dd
}

sim_formula <- function(aterm) {
  stats::as.formula(if (is.null(aterm)) "y ~ 0 + g" else {
    paste0("y | ", aterm, " ~ 0 + g")
  })
}

#' Set named entries of a par_template by name, so a test never depends
#' on the order the template happens to lay parameters out in.
set_pars <- function(tpl, vals) {
  for (comp in names(vals)) {
    v <- vals[[comp]]
    if (is.null(names(v))) {
      tpl[[comp]][] <- v
      next
    }
    for (nm in names(v)) {
      i <- match(nm, names(tpl[[comp]]))
      if (is.na(i)) {
        stop("test design error: no '", nm, "' in par_template$", comp,
             " (have: ", paste(names(tpl[[comp]]), collapse = ", "), ")",
             call. = FALSE)
      }
      tpl[[comp]][i] <- v[[nm]]
    }
  }
  tpl
}

#' Draw one column through frm_simulate() and split it by design cell.
sim_cells <- function(form, dd, fam, newparams) {
  s <- frmtmb::frm_simulate(form, dd, family = fam, newparams = newparams,
                            nsim = 1L, seed = SIM_SEED)
  v <- s[["sim_1"]]
  if (is.factor(v)) v <- as.integer(v)
  if (is.matrix(v)) {
    return(list(a = v[seq_len(SIM_N), , drop = FALSE],
                b = v[-seq_len(SIM_N), , drop = FALSE]))
  }
  list(a = v[seq_len(SIM_N)], b = v[-seq_len(SIM_N)])
}

# ======================================================================
# The rowwise families
# ======================================================================

# One row per family: the family object, the two cells' linear
# predictors for mu, the remaining distributional parameters on the
# RESPONSE scale (which is the spelling frm_simulate's natural
# newparams takes, so the same numbers serve the call and the density),
# the support, and how many moments are finite there.
#
# The support brackets are a quadrature detail, not a claim about the
# distribution: every continuous family asserts that its density
# integrates to one over the bracket, which is what makes a bracket that
# clips real mass a failure rather than a silent bias.
sim_specs <- list(
  list(nm = "gaussian", fam = quote(stats::gaussian()),
       eta = c(-0.5, 1.2), dp = list(sigma = 0.8), kind = "cont",
       lo = function(mu, d) mu - 9 * d[["sigma"]],
       hi = function(mu, d) mu + 9 * d[["sigma"]]),
  list(nm = "student", fam = quote(student()),
       eta = c(-0.5, 1.0), dp = list(sigma = 0.8, nu = 8), kind = "cont",
       lo = function(mu, d) mu - 60 * d[["sigma"]],
       hi = function(mu, d) mu + 60 * d[["sigma"]]),
  list(nm = "huber", fam = quote(huber()),
       eta = c(-0.4, 0.9), dp = list(sigma = 0.8), kind = "cont",
       lo = function(mu, d) mu - 25 * d[["sigma"]],
       hi = function(mu, d) mu + 25 * d[["sigma"]]),
  list(nm = "skew_normal", fam = quote(skew_normal()),
       eta = c(-0.5, 1.0), dp = list(sigma = 0.9, alpha = 2),
       kind = "cont",
       lo = function(mu, d) mu - 12 * d[["sigma"]],
       hi = function(mu, d) mu + 12 * d[["sigma"]]),
  list(nm = "exgaussian", fam = quote(exgaussian()),
       eta = c(0.2, 1.0), dp = list(sigma = 0.5, beta = 0.8),
       kind = "cont",
       lo = function(mu, d) mu - 10 * d[["sigma"]],
       hi = function(mu, d) mu + 10 * d[["sigma"]] + 25 * d[["beta"]]),
  list(nm = "asym_laplace", fam = quote(asym_laplace()),
       eta = c(-0.3, 0.8), dp = list(sigma = 0.7, quantile = 0.35),
       kind = "cont",
       lo = function(mu, d) mu - 90 * d[["sigma"]],
       hi = function(mu, d) mu + 90 * d[["sigma"]]),
  list(nm = "lognormal", fam = quote(lognormal()),
       eta = c(-0.3, 0.4), dp = list(sigma = 0.5), kind = "cont",
       lo = function(mu, d) 0, hi = function(mu, d) exp(mu + 9 * d[["sigma"]])),
  # stats::Gamma()'s default inverse link sends eta = 0 to an infinite
  # mean; the family is reached under the log link frmtmb defaults to
  list(nm = "Gamma", fam = quote(stats::Gamma(link = "log")),
       eta = c(0, 0.8), dp = list(shape = 3), kind = "cont",
       lo = function(mu, d) 0, hi = function(mu, d) mu * 12),
  list(nm = "exponential", fam = quote(exponential()),
       eta = c(0, 0.7), dp = list(), kind = "cont",
       lo = function(mu, d) 0, hi = function(mu, d) mu * 30),
  list(nm = "weibull", fam = quote(weibull()),
       eta = c(0, 0.5), dp = list(shape = 2), kind = "cont",
       lo = function(mu, d) 0, hi = function(mu, d) mu * 8),
  # stats::inverse.gaussian()'s default 1/mu^2 link is not one frmtmb
  # implements; the family is reached under the log link it does
  list(nm = "inverse.gaussian",
       fam = quote(stats::inverse.gaussian(link = "log")),
       eta = c(0, 0.5), dp = list(shape = 3), kind = "cont",
       lo = function(mu, d) 0, hi = function(mu, d) mu * 25),
  list(nm = "shifted_lognormal", fam = quote(shifted_lognormal()),
       eta = c(-0.3, 0.3), dp = list(sigma = 0.4, ndt = 0.2),
       kind = "cont", ydummy = 1.5,
       # the density is exactly zero at the shift and its log is -Inf
       # there, so the quadrature starts just above it
       lo = function(mu, d) d[["ndt"]] * (1 + 1e-9),
       hi = function(mu, d) d[["ndt"]] + exp(mu + 9 * d[["sigma"]])),
  list(nm = "von_mises", fam = quote(von_mises()),
       eta = c(-0.6, 0.5), dp = list(kappa = 2), kind = "cont",
       ydummy = 0.2,
       lo = function(mu, d) -pi, hi = function(mu, d) pi),
  list(nm = "Beta", fam = quote(Beta()),
       eta = c(-0.5, 0.5), dp = list(phi = 6), kind = "cont",
       ydummy = 0.5,
       lo = function(mu, d) 0, hi = function(mu, d) 1),

  list(nm = "poisson", fam = quote(stats::poisson()),
       eta = c(0.5, 1.4), dp = list(), kind = "disc", hi = 45,
       ydummy = 1L),
  list(nm = "negbinomial", fam = quote(negbinomial()),
       eta = c(0.5, 1.4), dp = list(shape = 3), kind = "disc", hi = 120,
       ydummy = 1L),
  list(nm = "nbinom1", fam = quote(nbinom1()),
       eta = c(0.5, 1.4), dp = list(phi = 2), kind = "disc", hi = 150,
       ydummy = 1L),
  list(nm = "geometric", fam = quote(geometric()),
       eta = c(0.4, 1.2), dp = list(), kind = "disc", hi = 400,
       ydummy = 1L),
  list(nm = "bernoulli", fam = quote(bernoulli()),
       eta = c(-0.5, 0.7), dp = list(), kind = "disc", hi = 1,
       ydummy = c(0L, 1L)),
  list(nm = "binomial", fam = quote(stats::binomial()),
       eta = c(-0.5, 0.7), dp = list(), kind = "disc", hi = 12,
       ydummy = 1L, aterm = "trials(k)", cols = list(k = 12L),
       at = list(trials = 12)),
  list(nm = "beta_binomial", fam = quote(beta_binomial()),
       eta = c(-0.4, 0.6), dp = list(phi = 4), kind = "disc", hi = 12,
       ydummy = 1L, aterm = "trials(k)", cols = list(k = 12L),
       at = list(trials = 12)),

  list(nm = "zero_inflated_poisson", fam = quote(zero_inflated_poisson()),
       eta = c(0.6, 1.5), dp = list(zi = 0.3), kind = "disc", hi = 45,
       ydummy = 1L),
  list(nm = "zero_inflated_negbinomial",
       fam = quote(zero_inflated_negbinomial()),
       eta = c(0.6, 1.5), dp = list(shape = 3, zi = 0.25), kind = "disc",
       hi = 130, ydummy = 1L),
  list(nm = "zero_inflated_binomial", fam = quote(zero_inflated_binomial()),
       eta = c(-0.3, 0.8), dp = list(zi = 0.25), kind = "disc", hi = 12,
       ydummy = 1L, aterm = "trials(k)", cols = list(k = 12L),
       at = list(trials = 12)),
  list(nm = "hurdle_poisson", fam = quote(hurdle_poisson()),
       eta = c(0.6, 1.4), dp = list(hu = 0.3), kind = "disc", hi = 45,
       ydummy = 1L),
  list(nm = "compois", fam = quote(compois()),
       eta = c(0.6, 1.4), dp = list(nu = 1.5), kind = "disc", hi = 60,
       ydummy = 1L),

  # the atom families: the cell test runs on the continuous part alone
  # and the atom gets its own binomial check
  list(nm = "zero_inflated_beta", fam = quote(zero_inflated_beta()),
       eta = c(-0.4, 0.5), dp = list(phi = 6, zi = 0.3), kind = "cont",
       atom0 = TRUE, ydummy = c(0, 0.5),
       lo = function(mu, d) 0, hi = function(mu, d) 1),
  list(nm = "zero_inflated_asym_laplace",
       fam = quote(zero_inflated_asym_laplace()),
       eta = c(-0.3, 0.8), dp = list(sigma = 0.7, quantile = 0.4,
                                     zi = 0.3),
       kind = "cont", atom0 = TRUE, ydummy = c(0, 1),
       lo = function(mu, d) mu - 90 * d[["sigma"]],
       hi = function(mu, d) mu + 90 * d[["sigma"]]),
  list(nm = "hurdle_gamma", fam = quote(hurdle_gamma()),
       eta = c(0, 0.6), dp = list(shape = 3, hu = 0.3), kind = "cont",
       atom0 = TRUE, ydummy = c(0, 1),
       lo = function(mu, d) 0, hi = function(mu, d) mu * 12),
  list(nm = "hurdle_lognormal", fam = quote(hurdle_lognormal()),
       eta = c(-0.2, 0.4), dp = list(sigma = 0.5, hu = 0.3),
       kind = "cont", atom0 = TRUE, ydummy = c(0, 1),
       lo = function(mu, d) 0, hi = function(mu, d) exp(mu + 9 * d[["sigma"]])),
  list(nm = "tweedie", fam = quote(tweedie()),
       eta = c(0.2, 0.9), dp = list(phi = 1.2, power = 1.5),
       kind = "cont", atom0 = TRUE, ydummy = c(0, 1),
       lo = function(mu, d) 0, hi = function(mu, d) mu * 25)
)

for (sp in sim_specs) {
  local({
    sp <- sp
    testthat::test_that(paste0(sp[["nm"]], ": draws agree with the ",
                               "family's own density"), {
      fam <- eval(sp[["fam"]])
      ffam <- frmtmb::as_frmtmb_family(fam)
      dd <- sim_data(if (is.null(sp[["ydummy"]])) 1 else sp[["ydummy"]],
                     if (is.null(sp[["cols"]])) list() else sp[["cols"]])
      form <- sim_formula(sp[["aterm"]])
      np <- c(list(ga = sp[["eta"]][1L], gb = sp[["eta"]][2L]), sp[["dp"]])
      draws <- sim_cells(form, dd, fam, np)
      at <- if (is.null(sp[["at"]])) list() else sp[["at"]]
      linv <- ffam[["links"]][["mu"]][["linkinv"]]
      atom <- isTRUE(sp[["atom0"]])
      for (cell in c("a", "b")) {
        mu <- linv(sp[["eta"]][if (identical(cell, "a")) 1L else 2L])
        dp <- c(list(mu = mu), sp[["dp"]])
        lab <- paste0(sp[["nm"]], "[", cell, "]")
        disc <- sp[["kind"]] %in% c("disc", "ord")
        dz <- dens_points(ffam, dp, at, sp[["kind"]],
                          if (disc) NA else sp[["lo"]](mu, sp[["dp"]]),
                          if (disc) sp[["hi"]] else sp[["hi"]](mu, sp[["dp"]]))
        mass <- sum(dz[["p"]])
        d <- draws[[cell]]
        if (atom) {
          # the continuous part carries 1 - P(0); a bracket that clipped
          # real mass would show up here first
          p0 <- exp(dens_lp(ffam, 0, dp, at))
          testthat::expect_equal(mass, 1 - p0, tolerance = 1e-3,
                                 label = paste0(lab, " continuous mass"))
          expect_atom0(d, p0, lab)
          expect_gof(d[d != 0], dens_cells(dz, SIM_CELLS, FALSE), lab)
          expect_moments(d, dens_moments(dens_mix0(dz, p0)), 2L, lab)
        } else {
          testthat::expect_equal(mass, 1, tolerance = 1e-3,
                                 label = paste0(lab, " total mass"))
          expect_gof(d, dens_cells(dz, SIM_CELLS, disc), lab)
          expect_moments(d, dens_moments(dz), 2L, lab)
        }
      }
    })
  })
}

# ======================================================================
# Ordinal, categorical, multinomial, mixture
# ======================================================================
#
# These take the internal newparams spelling, because their thresholds
# (`tau_raw`) and their per-category coefficients have no single
# natural-scale name. Entries are set BY NAME off par_template(), so a
# change in layout is an error here rather than a silently wrong test.

ord_specs <- list(
  # cumulative and sratio store thresholds as (tau_1, log increments);
  # cratio and acat store them raw. Passing tau_raw straight through to
  # the density means this test never has to know which.
  list(nm = "cumulative", fam = quote(cumulative()), raw = c(-1, 0, 0)),
  list(nm = "sratio", fam = quote(sratio()), raw = c(-1, 0, 0)),
  list(nm = "cratio", fam = quote(cratio()), raw = c(-1, 0, 1)),
  list(nm = "acat", fam = quote(acat()), raw = c(-1, 0, 1))
)

for (sp in ord_specs) {
  local({
    sp <- sp
    testthat::test_that(paste0(sp[["nm"]], ": category draws agree with ",
                               "the family's own density"), {
      fam <- eval(sp[["fam"]])
      K <- 4L
      dd <- sim_data(factor(seq_len(K), ordered = TRUE))
      form <- sim_formula(NULL)
      eta <- c(-0.4, 0.9)
      tpl <- frmtmb::par_template(form, dd, family = fam)
      np <- set_pars(tpl, list(beta = c(ga = eta[1L], gb = eta[2L]),
                               tau_raw = sp[["raw"]]))
      draws <- sim_cells(form, dd, fam, unclass(np)[c("beta", "tau_raw")])
      ex <- list(tau_raw = sp[["raw"]])
      for (cell in c("a", "b")) {
        e <- eta[if (identical(cell, "a")) 1L else 2L]
        lab <- paste0(sp[["nm"]], "[", cell, "]")
        dz <- dens_points(fam, list(mu = e), list(), "ord", NA, K,
                          extra = ex)
        testthat::expect_equal(sum(dz[["p"]]), 1, tolerance = 1e-8,
                               label = paste0(lab, " category mass"))
        expect_gof(draws[[cell]], dens_cells(dz, K, TRUE), lab)
        expect_moments(draws[[cell]], dens_moments(dz), 2L, lab)
      }
    })
  })
}

test_that("categorical: category draws agree with the family's own density", {
  lv <- c("a", "b", "c")
  fam <- categorical(levels = lv)
  dd <- sim_data(factor(lv, levels = lv))
  form <- sim_formula(NULL)
  eta <- list(a = c(mub = 0.4, muc = -0.6), b = c(mub = -0.5, muc = 0.8))
  tpl <- frmtmb::par_template(form, dd, family = fam)
  np <- set_pars(tpl, list(beta = c(
    mub_ga = eta[["a"]][["mub"]], mub_gb = eta[["b"]][["mub"]],
    muc_ga = eta[["a"]][["muc"]], muc_gb = eta[["b"]][["muc"]])))
  draws <- sim_cells(form, dd, fam, unclass(np)["beta"])
  for (cell in c("a", "b")) {
    e <- eta[[cell]]
    lab <- paste0("categorical[", cell, "]")
    dz <- dens_points(fam, list(mub = e[["mub"]], muc = e[["muc"]]),
                      list(), "ord", NA, 3L)
    expect_equal(sum(dz[["p"]]), 1, tolerance = 1e-8,
                 label = paste0(lab, " category mass"))
    expect_gof(draws[[cell]], dens_cells(dz, 3L, TRUE), lab)
  }
})

test_that("multinomial: count-vector draws agree with the family's own density", {
  K <- 3L
  size <- 5L
  fam <- multinomial(K)
  n <- 2L * SIM_N
  Y <- matrix(0L, n, K)
  Y[, 1L] <- size
  colnames(Y) <- paste0("c", seq_len(K))
  dd <- data.frame(g = factor(rep(c("a", "b"), each = SIM_N)),
                   k = rep(size, n))
  dd[["y"]] <- Y
  form <- Y | trials(k) ~ 0 + g
  eta <- list(a = c(mu2 = 0.5, mu3 = -0.4), b = c(mu2 = -0.6, mu3 = 0.7))
  tpl <- frmtmb::par_template(form, `names<-`(dd, c("g", "k", "Y")),
                              family = fam)
  d2 <- dd
  names(d2) <- c("g", "k", "Y")
  np <- set_pars(tpl, list(beta = c(
    mu2_ga = eta[["a"]][["mu2"]], mu2_gb = eta[["b"]][["mu2"]],
    mu3_ga = eta[["a"]][["mu3"]], mu3_gb = eta[["b"]][["mu3"]])))
  s <- frmtmb::frm_simulate(form, d2, family = fam,
                            newparams = unclass(np)["beta"],
                            nsim = 1L, seed = SIM_SEED)
  v <- s[["sim_1"]]
  # the support is every composition of `size` into K parts; each one's
  # probability comes from the family's own lpdf, so this is the same
  # agreement test the scalar families get, on the true support
  supp <- as.matrix(expand.grid(rep(list(seq.int(0L, size)), K)))
  supp <- supp[rowSums(supp) == size, , drop = FALSE]
  colnames(supp) <- colnames(Y)
  for (cell in c("a", "b")) {
    idx <- if (identical(cell, "a")) seq_len(SIM_N) else -seq_len(SIM_N)
    d <- v[idx, , drop = FALSE]
    e <- eta[[cell]]
    lab <- paste0("multinomial[", cell, "]")
    p <- exp(dens_lp(fam, supp, list(mu2 = e[["mu2"]], mu3 = e[["mu3"]]),
                     list(trials = size)))
    expect_equal(sum(p), 1, tolerance = 1e-8,
                 label = paste0(lab, " support mass"))
    expect_true(all(rowSums(d) == size),
                label = paste0(lab, " rows sum to trials()"))
    key <- function(M) apply(M, 1L, paste, collapse = ",")
    obs <- tabulate(match(key(d), key(supp)), nrow(supp))
    expect_gof(rep(seq_along(obs), obs),
               list(cuts = seq_along(obs)[-length(obs)] + 0.5, p = p), lab)
  }
})

test_that("mixture: draws agree with the mixture's own density", {
  fam <- mixture(stats::gaussian(), stats::gaussian())
  dd <- sim_data(1)
  form <- sim_formula(NULL)
  # theta1 is the identity-link mixing predictor for component 1; the
  # weights are its softmax against an implicit zero for component 2
  mu1 <- c(a = -1.5, b = -0.5)
  mu2 <- c(a = 1.5, b = 2.5)
  sd1 <- 0.6
  sd2 <- 0.9
  th1 <- 0.4
  tpl <- frmtmb::par_template(form, dd, family = fam)
  np <- set_pars(tpl, list(
    beta = c(mu1_ga = mu1[["a"]], mu1_gb = mu1[["b"]],
             mu2_ga = mu2[["a"]], mu2_gb = mu2[["b"]]),
    betad = c(`sigma1_(Intercept)` = log(sd1),
              `sigma2_(Intercept)` = log(sd2),
              `theta1_(Intercept)` = th1)))
  draws <- sim_cells(form, dd, fam, unclass(np)[c("beta", "betad")])
  for (cell in c("a", "b")) {
    lab <- paste0("mixture[", cell, "]")
    dp <- list(mu1 = mu1[[cell]], sigma1 = sd1, mu2 = mu2[[cell]],
               sigma2 = sd2, theta1 = th1)
    lo <- min(mu1[[cell]], mu2[[cell]]) - 12 * max(sd1, sd2)
    hi <- max(mu1[[cell]], mu2[[cell]]) + 12 * max(sd1, sd2)
    dz <- dens_points(fam, dp, list(), "cont", lo, hi)
    expect_equal(sum(dz[["p"]]), 1, tolerance = 1e-3,
                 label = paste0(lab, " total mass"))
    expect_gof(draws[[cell]], dens_cells(dz, SIM_CELLS, FALSE), lab)
    expect_moments(draws[[cell]], dens_moments(dz), 2L, lab)
  }
})

# ======================================================================
# The addition terms that change what is drawn, and the ones that must
# not
# ======================================================================

test_that("trunc(): draws stay inside the bounds and follow the truncated density", {
  lb <- -0.5
  hi_b <- 2.0
  fam <- stats::gaussian()
  ffam <- frmtmb::as_frmtmb_family(fam)
  dd <- sim_data(0.5)
  form <- stats::as.formula(paste0("y | trunc(lb = ", lb, ", ub = ", hi_b,
                                   ") ~ 0 + g"))
  eta <- c(-0.2, 1.0)
  sg <- 0.9
  draws <- sim_cells(form, dd, fam,
                     list(ga = eta[1L], gb = eta[2L], sigma = sg))
  for (cell in c("a", "b")) {
    d <- draws[[cell]]
    lab <- paste0("gaussian/trunc[", cell, "]")
    expect_true(all(d >= lb & d <= hi_b),
                label = paste0(lab, " inside the bounds"))
    # rejection sampling should give the density renormalized on
    # [lb, ub], which is exactly what dens_points on that bracket is
    dz <- dens_points(ffam, list(mu = eta[if (cell == "a") 1L else 2L],
                                 sigma = sg), list(), "cont", lb, hi_b)
    expect_gof(d, dens_cells(dz, SIM_CELLS, FALSE), lab)
  }
})

test_that("se(): the known standard error enters the draw's spread", {
  se_val <- 0.6
  fam <- stats::gaussian()
  ffam <- frmtmb::as_frmtmb_family(fam)
  dd <- sim_data(0.5, list(s = se_val))
  eta <- c(-0.3, 1.1)
  # se() alone REPLACES sigma, so sigma is not a parameter of this model
  # at all: the frame offers only the two cell means, and the drawn
  # spread has to be se
  draws <- sim_cells(y | se(s) ~ 0 + g, dd, fam,
                     list(ga = eta[1L], gb = eta[2L]))
  for (cell in c("a", "b")) {
    lab <- paste0("gaussian/se[", cell, "]")
    # the sigma passed here is the one resid_sd() must ignore
    dp <- list(mu = eta[if (cell == "a") 1L else 2L], sigma = 5)
    at <- list(se = se_val)
    dz <- dens_points(ffam, dp, at, "cont",
                      dp[["mu"]] - 9 * se_val, dp[["mu"]] + 9 * se_val)
    expect_equal(sum(dz[["p"]]), 1, tolerance = 1e-3,
                 label = paste0(lab, " total mass"))
    expect_gof(draws[[cell]], dens_cells(dz, SIM_CELLS, FALSE), lab)
    expect_moments(draws[[cell]], dens_moments(dz), 2L, lab)
  }
})

test_that("se(sigma = TRUE): the two spreads add in quadrature", {
  se_val <- 0.6
  sg <- 0.8
  fam <- stats::gaussian()
  ffam <- frmtmb::as_frmtmb_family(fam)
  dd <- sim_data(0.5, list(s = se_val))
  eta <- c(-0.3, 1.1)
  draws <- sim_cells(y | se(s, sigma = TRUE) ~ 0 + g, dd, fam,
                     list(ga = eta[1L], gb = eta[2L], sigma = sg))
  tot <- sqrt(sg^2 + se_val^2)
  for (cell in c("a", "b")) {
    lab <- paste0("gaussian/se+sigma[", cell, "]")
    dp <- list(mu = eta[if (cell == "a") 1L else 2L], sigma = sg)
    at <- list(se = se_val, se_sigma = TRUE)
    dz <- dens_points(ffam, dp, at, "cont", dp[["mu"]] - 9 * tot,
                      dp[["mu"]] + 9 * tot)
    expect_gof(draws[[cell]], dens_cells(dz, SIM_CELLS, FALSE), lab)
    expect_moments(draws[[cell]], dens_moments(dz), 2L, lab)
  }
})

test_that("weights() and cens() do not change what is drawn", {
  # a likelihood weight says how much a row counts, not what it is; a
  # cens() code says what was OBSERVED about the draw, not how the draw
  # was generated. Either changing the draws would mean simulate() was
  # sampling from something other than the family.
  fam <- stats::gaussian()
  np <- list(ga = -0.2, gb = 0.9, sigma = 0.7)
  base <- sim_cells(y ~ 0 + g, sim_data(0.5), fam, np)
  dw <- sim_data(0.5, list(w = c(1, 3, 7)))
  wt <- sim_cells(y | weights(w) ~ 0 + g, dw, fam, np)
  expect_identical(base[["a"]], wt[["a"]])
  expect_identical(base[["b"]], wt[["b"]])

  dc <- sim_data(0.5, list(cc = c(0L, 1L)))
  cn <- sim_cells(y | cens(cc) ~ 0 + g, dc, fam, np)
  expect_identical(base[["a"]], cn[["a"]])
  expect_identical(base[["b"]], cn[["b"]])
})

test_that("mi(): a response with missing values still simulates from the family", {
  fam <- stats::gaussian()
  ffam <- frmtmb::as_frmtmb_family(fam)
  dd <- sim_data(c(0.5, NA))
  eta <- c(-0.2, 1.0)
  sg <- 0.8
  # the imputed values are themselves parameters (`miss`), so this model
  # has no complete natural-scale spelling and takes the internal one
  tpl <- frmtmb::par_template(y | mi() ~ 0 + g, dd, family = fam)
  np <- unclass(tpl)[c("beta", "betad", "miss")]
  np[["beta"]] <- eta
  np[["betad"]] <- log(sg)
  np[["miss"]][] <- 0
  s <- frmtmb::frm_simulate(y | mi() ~ 0 + g, dd, family = fam,
                            newparams = np, nsim = 1L, seed = SIM_SEED)
  v <- s[["sim_1"]]
  expect_equal(length(v), 2L * SIM_N)
  # every row is drawn, including the ones whose response was missing:
  # that is what makes frm_simulate() usable for an imputation check
  expect_true(all(is.finite(v)))
  for (cell in c("a", "b")) {
    d <- if (identical(cell, "a")) v[seq_len(SIM_N)] else v[-seq_len(SIM_N)]
    lab <- paste0("gaussian/mi[", cell, "]")
    dp <- list(mu = eta[if (cell == "a") 1L else 2L], sigma = sg)
    dz <- dens_points(ffam, dp, list(), "cont", dp[["mu"]] - 9 * sg,
                      dp[["mu"]] + 9 * sg)
    expect_gof(d, dens_cells(dz, SIM_CELLS, FALSE), lab)
  }
})

# ======================================================================
# The same implementation through simulate()
# ======================================================================

test_that("simulate() on a fit draws from the fitted family's density", {
  set.seed(3)
  n <- 600L
  dd <- data.frame(x = stats::rnorm(n))
  dd$y <- 0.4 + 0.8 * dd$x + stats::rnorm(n, 0, 0.7)
  fit <- frmtmb::frm(y ~ x, family = stats::gaussian(), data = dd)
  ffam <- frmtmb::as_frmtmb_family(stats::gaussian())
  # the fit's own dpars, through the exported accessors
  mu <- stats::fitted(fit)
  sg <- stats::sigma(fit)
  sims <- stats::simulate(fit, nsim = 40L, seed = SIM_SEED)
  # standardized residuals of the draws are one iid sample from the
  # density at sigma = 1, mu = 0, which is the same agreement test
  z <- as.numeric(as.matrix(sims) - mu) / sg
  dz <- dens_points(ffam, list(mu = 0, sigma = 1), list(), "cont", -9, 9)
  expect_gof(z, dens_cells(dz, SIM_CELLS, FALSE), "simulate/gaussian")
  expect_moments(z, dens_moments(dz), 2L, "simulate/gaussian")
})

test_that("simulate() and frm_simulate() are the same implementation", {
  # simulate() reads the fit's estimates and frm_simulate() reads
  # newparams, but the draw itself must come from one place. Feeding the
  # fit's own estimate vector back in under the same seed makes that an
  # exact identity rather than a distributional claim.
  set.seed(5)
  n <- 200L
  dd <- data.frame(x = stats::rnorm(n), g = factor(rep(1:20, 10)))
  dd$y <- stats::rpois(n, exp(0.2 + 0.5 * dd$x))
  fit <- frmtmb::frm(bf(y ~ x + (1 | g)), family = stats::poisson(),
                     data = dd)
  est <- fit[["estimates"]]
  ref <- stats::simulate(fit, nsim = 2L, seed = 99L)
  new <- frmtmb::frm_simulate(bf(y ~ x + (1 | g)), dd,
                              family = stats::poisson(),
                              newparams = est[c("beta", "theta", "b")],
                              nsim = 2L, seed = 99L)
  expect_equal(unname(as.matrix(new)), unname(as.matrix(ref)))
})

test_that("a family that installs its simulator in family_finalize can be simulated", {
  # A family that derives itself from the data has NO simulator until
  # assembly has run. frm_simulate() read the family as written and
  # refused it for having none, while simulate() on a fit of the same
  # model worked, because a fit carries the finalized family. The
  # asymmetry was invisible until an extension put its simulator in
  # that slot (frmtmb.ddm's gddm() does).
  fam <- frmtmb::custom_family(
    "late_sim", dpars = c("mu", "sigma"),
    links = list(mu = "identity", sigma = "log"),
    lpdf = function(y, dpars, aterms) {
      stop("late_sim: the density is installed by family_finalize()",
           call. = FALSE)
    },
    family_finalize = function(f, y, aterms) {
      f[["lpdf"]] <- function(y, dpars, aterms) {
        stats::dnorm(y, dpars[["mu"]], dpars[["sigma"]], log = TRUE)
      }
      f[["sim"]] <- function(dpars, aterms, n) {
        stats::rnorm(n, dpars[["mu"]], dpars[["sigma"]])
      }
      f
    })
  expect_null(fam[["sim"]])

  eta <- c(-0.4, 1.1)
  sg <- 0.7
  dd <- sim_data(0.5)
  draws <- sim_cells(y ~ 0 + g, dd, fam,
                     list(ga = eta[1L], gb = eta[2L], sigma = sg))
  # the density to test against is the finalized one, reached the same
  # way assembly reaches it
  fin <- fam[["family_finalize"]](fam, dd[["y"]], list())
  for (cell in c("a", "b")) {
    dp <- list(mu = eta[if (identical(cell, "a")) 1L else 2L], sigma = sg)
    dz <- dens_points(fin, dp, list(), "cont", dp[["mu"]] - 9 * sg,
                      dp[["mu"]] + 9 * sg)
    expect_gof(draws[[cell]], dens_cells(dz, SIM_CELLS, FALSE),
               paste0("late_sim[", cell, "]"))
  }
})

# ======================================================================
# Families that declare no simulator are refused BY NAME
# ======================================================================

#' Registry families that declare no simulator, read off the registry
#' rather than listed by hand, so a family that loses or gains one
#' changes this file's answer instead of drifting away from it.
#'
#' A DEFERRED family (`categorical()` before its categories are known)
#' is not a gap: every entry point resolves it against the data before
#' asking whether it can simulate, and the resolved family can.
sim_gap_families <- function() {
  reg <- frmtmb:::family_registry
  Filter(function(nm) {
    fam <- tryCatch(reg[[nm]](), error = function(e) NULL)
    !is.null(fam) && is.null(fam[["defer"]]) && !frmtmb:::sim_can(fam)
  }, names(reg))
}

test_that("a family with no simulator is refused by name at both entry points", {
  gaps <- sim_gap_families()
  # cox() is the one deliberate refusal: inverting a cumulative baseline
  # hazard identified only on the observed window has no answer
  expect_identical(sort(gaps), "cox")

  set.seed(11)
  n <- 60L
  dd <- data.frame(x = rep(c(0, 1), length.out = n))
  dd$y <- stats::rexp(n, rate = exp(-0.2 + 0.5 * dd$x))
  for (nm in gaps) {
    fam <- frmtmb:::family_registry[[nm]]()
    expect_error(
      frmtmb::frm_simulate(y ~ x, dd, family = fam,
                           newparams = list(Intercept = 0, x = 0.5),
                           nsim = 1L),
      paste0("family '", nm, "' has no simulator"), fixed = TRUE)
    fit <- frmtmb::frm(y ~ x, family = fam, data = dd)
    expect_error(stats::simulate(fit, nsim = 1L),
                 paste0("family '", nm, "' has no simulator"), fixed = TRUE)
  }
})

test_that("cox() states why it has no simulator rather than only that it has none", {
  # a refusal that gives the reason is the difference between a gap and
  # a decision, and cox()'s is a decision
  set.seed(12)
  dd <- data.frame(x = rep(c(0, 1), length.out = 40L))
  dd$y <- stats::rexp(40L, rate = exp(-0.2 + 0.5 * dd$x))
  expect_error(
    frmtmb::frm_simulate(y ~ x, dd, family = cox(),
                         newparams = list(Intercept = 0, x = 0.5),
                         nsim = 1L),
    "cumulative baseline hazard")
})

test_that("the deferred categorical() resolves to a family that simulates", {
  # the registry entry has no `sim`; the family the data resolves it to
  # does, and that is the one every entry point actually reaches
  lv <- c("a", "b", "c")
  dd <- sim_data(factor(lv, levels = lv))
  s <- frmtmb::frm_simulate(y ~ 0 + g, dd, family = categorical(),
                            newparams = list(mub_ga = 0.3, mub_gb = -0.4,
                                             muc_ga = -0.2, muc_gb = 0.6),
                            nsim = 1L, seed = SIM_SEED)
  expect_true(is.factor(s[["sim_1"]]))
  expect_identical(levels(s[["sim_1"]]), lv)
})

test_that("every registry family is either in the agreement tier or a declared gap", {
  # the tier is only worth what it covers: a family added without a
  # simulator and without an entry here would otherwise slip through
  covered <- c(vapply(sim_specs, function(s) s[["nm"]], ""),
               vapply(ord_specs, function(s) s[["nm"]], ""),
               "categorical", "multinomial")
  # nbinom2 and beta are registry aliases of negbinomial and Beta: the
  # same constructor under a second spelling, so covering one covers both
  aliases <- c(nbinom2 = "negbinomial", beta = "Beta")
  reg <- names(frmtmb:::family_registry)
  reg[reg %in% names(aliases)] <- aliases[reg[reg %in% names(aliases)]]
  expect_setequal(unique(reg), union(covered, sim_gap_families()))
})
