# GENERATED by dev/brmsport-gen.R from brms 2.23.0
# tests/testthat/tests.data-helpers.R. Do not edit by hand: change
# dev/brmsport-verdicts.tsv or the generator, then regenerate.
# helper-brms-suite.R says what brms_port() asserts.

skip_unless_brms_suite()

test_that("validate_newdata handles factors correctly", {
  brms_setup("data-helpers:4",
    fit <- brms_fixture(1)
  )
  brms_setup("data-helpers:5",
    fit$data$fac <- factor(sample(1:3, nrow(fit$data), TRUE))
  )
  brms_setup("data-helpers:6",
    newdata <- fit$data[1:5, ]
  )
  brms_port("data-helpers:7", "defect",
    paste0(
      "newdata is fit$data[1:5, ], and fit$data partial-matches ",
      "fit$data2 (the fit has no data element); on ",
      "model.frame(fit) rows fitted() works, with a spurious ",
      "'contrasts dropped from factor Trt' warning ",
      "(dev/brmsport-probe4.R) [fit$data is the $ partial match of ",
      "fit$data2, dev/brmsport-rev-silent.R R8]"),
    expect_silent(brms_shim_validate_newdata(newdata, fit))
  )
  brms_setup("data-helpers:8",
    newdata$visit <- 1:5
  )
  brms_port("data-helpers:9", "defect",
    paste0(
      "blocked by fit$data; on model.frame(fit) rows frmtmb ",
      "refuses the new visit level in its own words, 'New levels ",
      "in grouping factor visit: 5' (dev/brmsport-probe4.R) ",
      "[fit$data is the $ partial match of fit$data2, ",
      "dev/brmsport-rev-silent.R R8]"),
    expect_error(brms_shim_validate_newdata(newdata, fit),
                 "Levels '5' of grouping factor 'visit' cannot")
  )
  brms_setup("data-helpers:11",
    newdata$fac <- 1:5
  )
  brms_port("data-helpers:12", "defect",
    paste0(
      "blocked by fit$data; the factor fac brms checks is a data ",
      "column the model does not use [fit$data is the $ partial ",
      "match of fit$data2, dev/brmsport-rev-silent.R R8]"),
    expect_error(brms_shim_validate_newdata(newdata, fit),
                 "New factor levels are not allowed")
  )
})

test_that("validate_data returns correct model.frames", {
  brms_setup("data-helpers:17",
    dat <- data.frame(y = 1:5, x = 1:5, z = 6:10, g = 5:1)
  )
  brms_setup("data-helpers:19",
    bterms <- brmsterms(y ~ as.numeric(x) + (as.factor(z) | g),
                        family = gaussian())
  )
  brms_setup_not_run("data-helpers:21", "mf")
  # mf <- brms:::validate_data(dat, bterms = bterms)
  brms_port("data-helpers:22", "cannot transfer",
    paste0(
      "reads brms:::validate_data() and brms's internal ",
      "brmsterms()"),
    expect_true(all(c("x", "z") %in% names(mf)))
  )
  brms_setup("data-helpers:24",
    bterms <- brmsterms(y ~ 1 + (1|g/x/z), family = gaussian())
  )
  brms_setup_not_run("data-helpers:25", "mf")
  # mf <- brms:::validate_data(dat, bterms = bterms)
  brms_port("data-helpers:26", "cannot transfer",
    paste0(
      "reads brms:::validate_data() and brms's internal ",
      "brmsterms()"),
    expect_equal(mf[["g:x"]], paste0(dat$g, "_", dat$x))
  )
  brms_port("data-helpers:27", "cannot transfer",
    paste0(
      "reads brms:::validate_data() and brms's internal ",
      "brmsterms()"),
    expect_equal(mf[["g:x:z"]], paste0(dat$g, "_", dat$x, "_", dat$z))
  )
})
