# GENERATED by dev/brmsport-gen.R from brms 2.23.0
# tests/testthat/tests.data-helpers.R. Do not edit by hand: change
# dev/brmsport-verdicts.tsv or the generator, then regenerate.
# helper-brms-suite.R says what brms_port() asserts.

skip_unless_brms_suite()

test_that("validate_newdata handles factors correctly", {
  withr::local_seed(3L)
  brms_setup("data-helpers:4",
    fit <- brms_fixture(1)
  )
  brms_setup("data-helpers:5",
    fit$data$fac <- factor(sample(1:3, nrow(fit$data), TRUE))
  )
  brms_setup("data-helpers:6",
    newdata <- fit$data[1:5, ]
  )
  brms_port("data-helpers:7", "pass",
    "",
    expect_silent(brms_shim_validate_newdata(newdata, fit))
  )
  brms_setup("data-helpers:8",
    newdata$visit <- 1:5
  )
  brms_port_own("data-helpers:9",
    "New levels in grouping factor .visit.: 5",
    paste0(
      "brms: Levels '5' of grouping factor 'visit' cannot be used. ",
      "The same refusal of the same case in frmtmb's words"),
    expect_error(brms_shim_validate_newdata(newdata, fit),
                 "Levels '5' of grouping factor 'visit' cannot")
  )
  brms_setup("data-helpers:11",
    newdata$fac <- 1:5
  )
  brms_port("data-helpers:12", "divergence",
    paste0(
      "brms refuses the integer codes of `fac`, a factor column of ",
      "the data that no term of the model reads; frmtmb never ",
      "checks such a column, since no value in it can change the ",
      "prediction, and refuses this call for the new `visit` level ",
      "set the line before"),
    expect_error(brms_shim_validate_newdata(newdata, fit),
                 "New factor levels are not allowed")
  )
})

test_that("validate_data returns correct model.frames", {
  withr::local_seed(16L)
  brms_setup("data-helpers:17",
    dat <- data.frame(y = 1:5, x = 1:5, z = 6:10, g = 5:1)
  )
  brms_setup("data-helpers:19",
    bterms <- brmsterms(y ~ as.numeric(x) + (as.factor(z) | g),
                        family = gaussian())
  )
  brms_setup_not_run("data-helpers:21", "mf")
  # mf <- brms:::validate_data(dat, bterms = bterms)
  brms_port("data-helpers:22", "cannot transfer",
    paste0(
      "reads brms:::validate_data() and brms's internal ",
      "brmsterms()"),
    expect_true(all(c("x", "z") %in% names(mf)))
  )
  brms_setup("data-helpers:24",
    bterms <- brmsterms(y ~ 1 + (1|g/x/z), family = gaussian())
  )
  brms_setup_not_run("data-helpers:25", "mf")
  # mf <- brms:::validate_data(dat, bterms = bterms)
  brms_port("data-helpers:26", "cannot transfer",
    paste0(
      "reads brms:::validate_data() and brms's internal ",
      "brmsterms()"),
    expect_equal(mf[["g:x"]], paste0(dat$g, "_", dat$x))
  )
  brms_port("data-helpers:27", "cannot transfer",
    paste0(
      "reads brms:::validate_data() and brms's internal ",
      "brmsterms()"),
    expect_equal(mf[["g:x:z"]], paste0(dat$g, "_", dat$x, "_", dat$z))
  )
})
