# GENERATED by dev/brmsport-gen.R from brms 2.23.0
# tests/testthat/tests.brmsterms.R. Do not edit by hand: change
# dev/brmsport-verdicts.tsv or the generator, then regenerate.
# helper-brms-suite.R says what brms_port() asserts.

skip_unless_brms_suite()

test_that("brmsterms correctly check fixed auxiliary parameters", {
  brms_setup("brmsterms:39",
    bform <- bf(y~1, sigma = 4, family = gaussian)
  )
  brms_port("brmsterms:40", "cannot transfer",
    paste0(
      "is.brmsterms() and brmsterms() are brms internals; frm() ",
      "accepts bf(y ~ 1, sigma = 4) (dev/brmsport-probe3.R)"),
    expect_true(is.brmsterms(brmsterms(bform)))
  )
  brms_setup("brmsterms:41",
    bform <- bf(y~1, zi = 0.5, family = zero_inflated_beta())
  )
  brms_port("brmsterms:42", "cannot transfer",
    paste0(
      "is.brmsterms() and brmsterms() are brms internals; frm() ",
      "accepts bf(y ~ 1, zi = 0.5) under zero_inflated_beta() ",
      "(dev/brmsport-probe3.R)"),
    expect_true(is.brmsterms(brmsterms(bform)))
  )
  brms_setup("brmsterms:43",
    bform <- bf(y~1, shape = -2, family = Gamma())
  )
  brms_port("brmsterms:44", "cannot transfer",
    paste0(
      "brmsterms() is a brms internal; frm() refuses shape = -2 in ",
      "its own words, 'not in the range of the log link' ",
      "(dev/brmsport-probe3.R)"),
    expect_error(brmsterms(bform), "Parameter 'shape' must be positive")
  )
  brms_setup("brmsterms:45",
    bform <- bf(y~1, quantile = 1.5, family = asym_laplace())
  )
  brms_port("brmsterms:46", "cannot transfer",
    paste0(
      "brmsterms() is a brms internal; frm() refuses quantile = ",
      "1.5 in its own words, 'not in the range of the logit link' ",
      "(dev/brmsport-probe3.R)"),
    expect_error(brmsterms(bform), "Parameter 'quantile' must be between 0 and 1")
  )
})

test_that("unused variables are correctly incorporated", {
  brms_setup("brmsterms:88",
    bterms <- brmsterms(bf(y ~ 1, unused = ~ x))
  )
  brms_port("brmsterms:89", "cannot transfer",
    paste0(
      "brmsterms() is a brms internal, and frm() has no unused = ~ ",
      "x: it is refused as an unavailable dpar ",
      "(dev/brmsport-probe3.R)"),
    expect_true("x" %in% all.vars(bterms$allvars))
  )
})
