# brms's own assertions about bf(), the formula grammar and the prior
# surface, ported from brms 2.23.0's tests.brmsformula.R, tests.priors.R
# and tests.brm.R, and the frmtmb behavior around each one. The ledger
# of every brms assertion in those blocks, with the ones that do not
# transfer and why, is dev/priorform-findings.md, generated by
# dev/priorform-ledger.R.

pf_epilepsy <- local({
  set.seed(4)
  n <- 120
  data.frame(count = stats::rpois(n, 4), zAge = stats::rnorm(n),
             zBase = stats::rnorm(n),
             Trt = factor(rep(0:1, each = n / 2)),
             patient = factor(rep(1:30, 4)),
             visit = factor(rep(1:4, each = 30)))
})

# ---- bf() ------------------------------------------------------------------

test_that("bf() returns a formula it already built unchanged (brms)", {
  form <- bf(y ~ a, sigma ~ 1)
  expect_identical(form, bf(form))
  form <- bf(y ~ a, sigma ~ 1, a ~ x, nl = TRUE)
  expect_identical(form, bf(form))
  # the family and the nonlinear flag survive, rather than being reset
  # to bf()'s defaults
  form <- bf(y ~ a * exp(b * x), a ~ 1, b ~ 1, nl = TRUE) + poisson()
  expect_identical(form, bf(form))
  expect_true(bf(form)$nl)
})

test_that("bf() on a built formula adds to it and refuses a repeat", {
  form <- bf(y ~ x)
  more <- bf(form, sigma ~ z)
  expect_identical(names(more$pforms), "sigma")
  expect_identical(more$formula, form$formula)
  expect_identical(bf(form, family = poisson())$family$family, "poisson")
  # nl reaches every response of an mvbind() formula; the base commit
  # built linear formulas there
  mv <- bf(mvbind(y1, y2) ~ a, a ~ 1, nl = TRUE)
  expect_true(mv$forms[[1L]]$nl)
  expect_true(mv$forms[[2L]]$nl)
  expect_true(bf(bf(y ~ a, a ~ 1), nl = TRUE)$nl)
  expect_error(bf(bf(y ~ x, sigma ~ z), sigma ~ w),
               "Duplicated dpar formula: 'sigma'", fixed = TRUE)
  expect_error(bf(bf(y ~ x, sigma = 1), sigma = 2),
               "Duplicated dpar constant: 'sigma'", fixed = TRUE)
  # the guard cannot pass by returning the input: something was added
  expect_false(identical(more, form))
})

test_that("a doubled tilde is refused by name (brms #749)", {
  expect_error(bf(y ~ ~x), "~~", fixed = TRUE)
  expect_error(bf(~ ~x), "~~", fixed = TRUE)
  expect_error(bf(y ~ x, sigma ~ ~z), "~~", fixed = TRUE)
  expect_error(bf(y ~ x) + lf(sigma ~ ~z), "~~", fixed = TRUE)
  expect_error(nlf(sigma ~ ~z), "~~", fixed = TRUE)
  # frm() on a plain formula reaches the same refusal; before it, this
  # fitted y ~ x without a word
  expect_error(frm(y ~ ~x, data.frame(y = 1:5, x = 1:5)), "~~",
               fixed = TRUE)
  # brms checks the top level only, and so does this: a parenthesized
  # formula is an ordinary call there
  expect_s3_class(bf(y ~ x + (1 | g)), "frmtmb_formula")
})

test_that("parameter formulas name their parameter (brms)", {
  expect_error(bf(y ~ a, ~ 1, a ~ 1), "Additional formulas must be named")
  expect_error(bf(y ~ a^x, a.b ~ 1), "not contain dots or underscores")
  expect_error(bf(y ~ a^(x+b), a_b ~ 1), "not contain dots or underscores")
  expect_error(bf(y ~ a, ~ 1, sigma ~ 1),
               "Additional formulas must be named")
  # the named one-sided spelling brms accepts is the same formula
  expect_identical(bf(y ~ x, sigma = ~ z), bf(y ~ x, sigma ~ z))
  expect_identical(bf(y ~ x) + lf(sigma = ~ z), bf(y ~ x, sigma ~ z))
  expect_error(lf(~x), "two-sided")
})

# ---- the formula grammar -----------------------------------------------------

test_that("exact twin terms are one block, as brms reads them", {
  set.seed(11)
  dat <- data.frame(y = stats::rnorm(60), x = stats::rnorm(60),
                    g = factor(rep(1:6, 10)), h = factor(rep(1:5, 12)))
  blocks <- function(f, ...) {
    length(frm(f, dat, dry_run = "frame", ...)[["re_blocks"]])
  }
  # base fitted two blocks for each twin, with the one variance split
  # between them at will; brms's terms() keeps one copy
  expect_identical(blocks(y ~ x + (1 | g) + (1 | g)), 1L)
  expect_identical(blocks(y ~ x + (x | g) + (x | g)), 1L)
  expect_identical(blocks(y ~ x + (x || g) + (x || g)), 2L)
  expect_identical(blocks(y ~ x + (1 | mm(g, h)) + (1 | mm(g, h))), 1L)
  expect_identical(blocks(bf(y ~ a + x, a ~ 1 + (1 | g) + (1 | g),
                             nl = TRUE)), 1L)
  expect_identical(
    frmtmb:::drop_twin_bar_terms(y ~ x + (1 | g) + ((1 | g))),
    y ~ x + (1 | g))
  # twins are compared as written, so a repeat that only appears after
  # an expansion is a duplicated effect, as it is in brms
  expect_error(blocks(y ~ x + (x || g) + (1 | g)), "Duplicated")
  expect_error(blocks(y ~ (1 | g/h) + (1 | g)), "Duplicated")
  # grouping factors compare as brms writes them: g/h is g and g:h
  expect_error(blocks(y ~ (1 | g:h) + (1 | g/h)), "group 'g:h'",
               fixed = TRUE)
  expect_identical(blocks(y ~ (1 | g:h) + (1 | h:g)), 2L)
  expect_identical(blocks(y ~ (1 | h:g) + (1 | g/h)), 3L)
  # the fits of a twin and of the single term are one model
  set.seed(12)
  dat$y <- stats::rnorm(6, 0, 0.7)[dat$g] + stats::rnorm(60)
  expect_identical(as.numeric(logLik(frm(y ~ (1 | g) + (1 | g), dat))),
                   as.numeric(logLik(frm(y ~ (1 | g), dat))))
})

test_that("multi-membership and smooth twins read as brms reads them", {
  set.seed(14)
  n <- 120
  dat <- data.frame(y = stats::rnorm(n), x = stats::rnorm(n),
                    z = stats::runif(n, -2, 2),
                    g1 = factor(sample(1:6, n, TRUE)),
                    g2 = factor(sample(1:6, n, TRUE)),
                    wt1 = stats::runif(n), wt2 = stats::runif(n))
  dat$y <- sin(dat$z) + stats::rnorm(n, 0, 0.3)
  # brms names the group mmg1g2 whatever the weights, so these repeat
  # the intercept; the base commit fitted two blocks
  expect_error(frm(y ~ (1 | mm(g1, g2)) +
                     (1 | mm(g1, g2, weights = cbind(wt1, wt2))),
                   dat, dry_run = "frame"),
               "group 'mmg1g2'", fixed = TRUE)
  # s(z) + s(z) built two smooths with one column name; brms keeps one
  two <- frm(y ~ x + s(z) + s(z), dat)
  one <- frm(y ~ x + s(z), dat)
  expect_length(two$frame[["linpreds"]][[1L]][["smooths"]], 1L)
  expect_identical(as.numeric(logLik(two)), as.numeric(logLik(one)))
})

test_that("frmtmb-only structures on one factor are held to the rule", {
  set.seed(13)
  dat <- data.frame(y = stats::rnorm(80), x = stats::rnorm(80),
                    z = stats::rnorm(80), g = factor(rep(1:8, 10)))
  frame <- function(f) frm(f, dat, dry_run = "frame")
  expect_error(frame(y ~ rr(0 + x + z | g, d = 1) + diag(0 + x + z | g)),
               "Duplicated")
  expect_error(frame(y ~ us(1 + x | g) + diag(1 + x | g)), "Duplicated")
  # and the message keeps the structure and gr() the terms were written
  # with
  expect_error(frame(y ~ us(1 + x | g) + diag(1 + x | g)),
               "diag(1 + x | g)", fixed = TRUE)
  expect_error(frame(y ~ (1 | gr(g, dist = "student")) + (1 | g)),
               "(1 | gr(g, dist = \"student\"))", fixed = TRUE)
})

test_that("duplicated group-level effects are refused (brms)", {
  set.seed(1)
  dat <- data.frame(y = stats::rnorm(60), x = stats::rnorm(60),
                    z = stats::rnorm(60),
                    g = factor(rep(1:6, 10)), h = factor(rep(1:5, 12)))
  frame <- function(f) frm(f, dat, dry_run = "frame")
  expect_error(frame(y ~ x + (1 | g) + (x | g)),
               "Duplicated group-level effects are not allowed")
  expect_error(frame(y ~ x + (1 | g) + (x || g)),
               "coefficient '(Intercept)' of group 'g'", fixed = TRUE)
  expect_error(frame(y ~ x + (x | g) + (0 + x | g)),
               "coefficient 'x' of group 'g'", fixed = TRUE)
  expect_error(frame(y ~ (1 | g:h) + (1 | g/h)),
               "Duplicated group-level effects")
  # the animal model is refused as brms refuses it, and the message
  # names brms's spelling, a copy of the column
  A <- diag(6)
  dimnames(A) <- list(levels(dat$g), levels(dat$g))
  expect_error(frm(y ~ (1 | gr(g, cov = A)) + (1 | g), dat,
                   data2 = list(A = A), dry_run = "frame"),
               "copy of the column")
  dat$g2 <- dat$g
  expect_silent(frm(y ~ (1 | gr(g, cov = A)) + (1 | g2), dat,
                    data2 = list(A = A), dry_run = "frame"))
  expect_error(frame(y ~ x + (1 | mm(g, h)) + (x | mm(g, h))),
               "Duplicated group-level effects")
  # what brms accepts is accepted: a split that repeats no coefficient,
  # the same coefficient on two factors, and the same term in two
  # predictors
  expect_silent(frame(y ~ x + (1 | g) + (0 + x | g)))
  expect_silent(frame(y ~ x + (x || g)))
  expect_silent(frame(y ~ x + (1 | g) + (1 | h)))
  expect_silent(frame(y ~ x + (1 | g) + (1 | g:h)))
  expect_silent(frm(bf(y ~ x + (1 | g), sigma ~ (1 | g)), dat,
                    dry_run = "frame"))
})

test_that("a split that repeats no coefficient fits; a repeat is refused", {
  # the base commit fitted the refused model and split the intercept
  # variance between the two blocks at will, 0.56151 and 0.56093 on this
  # construction (dev/priorform-base-behaviour.R); the split that
  # repeats nothing is a different, identified model
  set.seed(20260916)
  n <- 240
  d <- data.frame(x = stats::rnorm(n), z = stats::rnorm(n),
                  g = factor(rep(1:12, 20)))
  d$y <- 1 + 0.5 * d$x + stats::rnorm(12, 0, 0.8)[d$g] +
    stats::rnorm(12, 0, 0.5)[d$g] * d$x + stats::rnorm(n)
  one <- frm(y ~ x + (1 | g) + (0 + x | g), d)
  expect_error(frm(y ~ x + (1 | g) + (x | g), d), "Duplicated")
  expect_s3_class(one, "frmtmb_fit")
})

test_that("a smooth or gp() inside an interaction is refused (brms)", {
  set.seed(20260916)
  n <- 200
  d <- data.frame(x = stats::rnorm(n), z = stats::runif(n, -3, 3),
                  g = factor(rep(1:4, 50)))
  d$y <- 1 + d$x * sin(d$z) + stats::rnorm(n, 0, 0.3)
  frame <- function(f) frm(f, d, dry_run = "frame")
  # every one of these fitted y ~ x, the smooth dropped without a word
  expect_error(frame(y ~ x:s(z)), "The term 'x:s(z)' is invalid",
               fixed = TRUE)
  expect_error(frame(y ~ x * s(z)), "The term 'x:s(z)' is invalid",
               fixed = TRUE)
  expect_error(frame(y ~ I(s(z))), "The term 'I(s(z))' is invalid",
               fixed = TRUE)
  expect_error(frame(y ~ x:t2(z, x)), "is invalid", fixed = TRUE)
  expect_error(frame(y ~ x:gp(z)), "The term 'x:gp(z)' is invalid",
               fixed = TRUE)
  # what brms accepts still fits: a varying-coefficient smooth, and a
  # repeat terms() collapses to one smooth
  smooths <- function(f) length(frame(f)[["linpreds"]][[1L]][["smooths"]])
  expect_identical(smooths(y ~ s(z, by = x)), 1L)
  expect_identical(smooths(y ~ x + s(z) * s(z)), smooths(y ~ x + s(z)))
})

test_that("the whole-term specials are brms's own list", {
  skip_if_not_installed("brms")
  rx <- vapply(c("cs", "sm", "gp", "ac", "mmc"),
               function(t) brms:::regex_sp(t), "")
  body <- sub("^[(]\\^[(](.*)[)]\\\\[(].*$", "\\1", rx)
  names_of <- function(b) {
    b <- gsub("[()]", "", b)
    parts <- strsplit(b, "|", fixed = TRUE)[[1L]]
    unlist(lapply(parts, function(p) {
      if (endsWith(p, "?")) {
        stem <- substr(p, 1L, nchar(p) - 2L)
        c(stem, substr(p, 1L, nchar(p) - 1L))
      } else {
        p
      }
    }))
  }
  from_brms <- unique(unlist(lapply(body, names_of)))
  expect_gt(length(from_brms), 10L)
  expect_setequal(frmtmb:::brms_whole_term_specials, from_brms)
})

test_that("cs() inside an interaction is refused by name (brms)", {
  set.seed(1)
  dat <- data.frame(y = stats::rnorm(10), x = stats::rnorm(10),
                    g = rep(1:5, 2))
  expect_error(frm(y ~ x * cs(g), dat, dry_run = "frame"), fixed = TRUE,
               "The term 'x:cs(g)' is invalid")
  expect_error(frm(y ~ x + I(cs(g)), dat, dry_run = "frame"),
               "The term 'I(cs(g))' is invalid", fixed = TRUE)
  # a repeat terms() collapses is the one cs() term, as brms reads it
  d3 <- data.frame(y = factor(rep(1:3, 20), ordered = TRUE),
                   x = stats::rnorm(60), z = stats::rnorm(60))
  cs_labels <- function(f) {
    fr <- frm(f, d3, family = sratio(), dry_run = "frame")
    unname(unlist(lapply(fr[["linpreds"]], function(lp) {
      vapply(lp[["cs"]], `[[`, "", "label")
    })))
  }
  expect_identical(cs_labels(y ~ x + cs(z) * cs(z)), cs_labels(y ~ x + cs(z)))
  expect_identical(cs_labels(y ~ x + cs(z)), "csz")
  # the base commit dropped cs(z) from this model without a word
  expect_error(cs_labels(y ~ x * cs(z)), "x:cs(z)", fixed = TRUE)
  # the bar form is a compound-symmetry covariance and is not this
  expect_null(frmtmb:::special_term_refusal(quote(cs(0 + x | g))))
})

# ---- set_prior() and the prior object -------------------------------------

test_that("set_prior allows arguments to be vectors (brms)", {
  bprior <- set_prior("normal(0, 2)", class = c("b", "sd"))
  expect_s3_class(bprior, "frmtmb_priorlist")
  expect_equal(bprior$prior, rep("normal(0, 2)", 2))
  expect_equal(bprior$class, c("b", "sd"))
  # every argument is a column, recycled as data.frame() recycles
  v <- set_prior(c("normal(0,1)", "normal(0,2)"), coef = c("a", "b", "c", "d"))
  expect_equal(v$prior, rep(c("normal(0,1)", "normal(0,2)"), 2))
  expect_equal(v$coef, c("a", "b", "c", "d"))
  expect_equal(set_prior("", lb = c(0, 1))$lb, c("0", "1"))
  expect_equal(length(unclass(set_prior("normal(0, 1)",
                                        dpar = c("mu2", "mu3")))), 2L)
  expect_error(set_prior("normal(0,1)", coef = c("a", "b", "c"),
                         class = c("b", "sd")),
               "divides the longest")
  expect_error(set_prior("normal(0,1)", class = character(0)),
               "divides the longest")
  # a prior object is one value, not a vector of its fields
  expect_equal(length(unclass(set_prior(prior_normal(0, 1),
                                        class = c("b", "sd")))), 2L)
  # each row is checked as a call of its own would be
  expect_error(set_prior("normal(0, 1)", class = c("b", "sds")), "sds")
})

test_that("print for a prior object prints brms's layout (brms)", {
  expect_output(print(set_prior("normal(0,1)")), fixed = TRUE,
                "b ~ normal(0,1)")
  expect_output(print(set_prior("normal(0,1)", coef = "x")),
                "b_x ~ normal(0,1)", fixed = TRUE)
  expect_output(print(set_prior("cauchy(0,1)", class = "sd", group = "x")),
                "sd_x ~ cauchy(0,1)", fixed = TRUE)
  # the rest of brms's .print_prior(): bounds in front, a group before a
  # coefficient, and a bounds-only row reads (flat)
  expect_identical(capture.output(print(set_prior("", lb = 0, ub = 1))),
                   "<lower=0,upper=1> b ~ (flat)")
  expect_identical(capture.output(print(set_prior(
    "normal(0, 1)", class = "b", nlpar = "a", coef = "x"))),
    "b_a_x ~ normal(0, 1)")
  expect_identical(capture.output(print(set_prior("student_t(3, 0, 2.5)",
                                                  class = "sigma"))),
                   "sigma ~ student_t(3, 0, 2.5)")
  # several print as a table, one row each
  out <- capture.output(print(set_prior("normal(0, 2)",
                                        class = c("b", "sd"))))
  expect_length(out, 3L)
  expect_match(out[1L], "prior +class", perl = TRUE)
  expect_identical(capture.output(print(set_prior("normal(0, 2)",
                                                  class = c("b", "sd")),
                                        show_df = FALSE)),
                   c("b ~ normal(0, 2)", "sd ~ normal(0, 2)"))
  # an empty prior prints nothing, and a row with no density of its own
  # shows its class row's as "(vectorized)", both as brms prints them
  expect_identical(capture.output(print(empty_prior())), character(0))
  tab <- capture.output(print(as.brmsprior(data.frame(
    prior = c("normal(0,1)", ""), coef = c("", "x"), lb = c(NA, "0")))))
  expect_match(tab[3L], "normal(0,1)", fixed = TRUE)
  expect_match(tab[3L], "(vectorized)", fixed = TRUE)
})

test_that("set_prior alias functions produce equivalent results (brms)", {
  expect_equal(set_prior("normal(0, 1)", class = "sd"),
               prior(normal(0, 1), class = sd))
  expect_equal(set_prior("normal(0, 1)", class = "sd", nlpar = "a"),
               prior(normal(0, 1), class = "sd", nlpar = a))
  expect_equal(set_prior("normal(0, 1)", class = "sd", nlpar = "a"),
               prior_(~normal(0, 1), class = ~sd, nlpar = quote(a)))
  expect_equal(set_prior("normal(0, 1)", class = "sd"),
               prior_string("normal(0, 1)", class = "sd"))
})

test_that("a column of a prior object can be edited in place", {
  pr <- set_prior("normal(0, 2)", class = c("b", "sd"))
  pr$prior[2] <- "exponential(1)"
  expect_s3_class(pr, "frmtmb_priorlist")
  expect_equal(pr$prior, c("normal(0, 2)", "exponential(1)"))
  expect_identical(unclass(pr)[[2L]]$dist,
                   unclass(set_prior("exponential(1)",
                                     class = "sd"))[[1L]]$dist)
  # an edit is checked as a new call is
  expect_error({
    pr$class[1] <- "sds"
  }, "row 1")
  expect_error({
    pr$nonsense <- "x"
  }, "no column 'nonsense'")
  expect_null(pr$nonsense)
})

test_that("empty_prior() is a prior object with nothing in it", {
  e <- empty_prior()
  expect_s3_class(e, "frmtmb_priorlist")
  expect_length(unclass(e), 0L)
  expect_identical(nrow(as.data.frame(e)), 0L)
  pr <- e + set_prior("normal(0, 1)", class = "b")
  expect_identical(pr, set_prior("normal(0, 1)", class = "b"))
  # and frm() given it fits with no prior
  set.seed(2)
  d <- data.frame(x = stats::rnorm(40))
  d$y <- 1 + d$x + stats::rnorm(40)
  expect_identical(fixef(frm(y ~ x, d, prior = empty_prior())),
                   fixef(frm(y ~ x, d)))
})

test_that("as.brmsprior works correctly (brms)", {
  dat <- data.frame(prior = "normal(0,1)", x = "test", coef = c("a", "b"))
  bprior <- as.brmsprior(dat)
  expect_equal(bprior$prior, rep("normal(0,1)", 2))
  expect_equal(bprior$class, rep("b", 2))
  expect_equal(bprior$coef, c("a", "b"))
  expect_equal(bprior$x, NULL)
  expect_equal(bprior$lb, rep(NA_character_, 2))
  # a prior object passes through, and a table without a prior column
  # has nothing to read
  pr <- set_prior("normal(0, 1)")
  expect_identical(as.brmsprior(pr), pr)
  expect_error(as.brmsprior(data.frame(class = "b")), "`prior` column")
  expect_error(as.brmsprior(data.frame(prior = "normal(0,1)", tag = "t")),
               "tag")
  # a flat row applies nothing and is left out
  expect_length(unclass(as.brmsprior(data.frame(
    prior = c("", "(flat)", "normal(0, 1)")))), 1L)
})

# ---- default_prior() and validate_prior() ---------------------------------

test_that("default_prior() and get_prior() are one function (brms)", {
  f <- count ~ zBase * Trt + (1 | patient) + (1 + Trt | visit)
  gp <- get_prior(f, data = pf_epilepsy, family = poisson())
  dp <- default_prior(f, data = pf_epilepsy, family = poisson())
  expect_identical(gp, dp)
  expect_identical(names(dp), c("prior", "class", "coef", "group", "resp",
                                "dpar", "nlpar", "lb", "ub", "source"))
  # brms's classes are all here; theta is frmtmb's own
  expect_setequal(unique(dp$class),
                  c("b", "cor", "Intercept", "sd", "theta"))
  expect_equal(sum(dp$class == "b"), 4L)
  expect_equal(sum(dp$class == "cor"), 2L)
})

test_that("default_prior gives random effects their nlpar names (brms)", {
  set.seed(1)
  dat <- data.frame(y = rnorm(10), x = rnorm(10), g = rep(1:2, 5))
  bform <- bf(y ~ a - b^x, a + b ~ (1+x|g), nl = TRUE)
  gp <- default_prior(bform, data = dat)
  expect_equal(sort(unique(gp$nlpar)), c("", "a", "b"))
})

test_that("default_prior lists multivariate priors per response (brms)", {
  set.seed(1)
  dat <- data.frame(y1 = rnorm(10), y2 = c(1, rep(1:3, 3)),
                    x = rnorm(10), g = rep(1:2, 5))
  bform <- bf(mvbind(y1, y2) ~ x + (x|ID1|g)) + set_rescor(TRUE)
  prior <- default_prior(bform, dat, family = gaussian())
  expect_equal(prior[prior$resp == "y1" & prior$class == "b", "coef"],
               c("", "x"))
})

test_that("a block of a distributional parameter lists its dpar", {
  set.seed(1)
  dat <- data.frame(y = stats::runif(40), z = stats::rnorm(40),
                    g = factor(rep(1:4, 10)))
  p <- default_prior(bf(y ~ 1 + (1 | g), phi ~ z + (1 | g)) + Beta(),
                     data = dat)
  sd_g <- p[p$class == "sd" & p$group == "g", ]
  # two blocks on one factor in two predictors are two rows, where they
  # used to collapse into one
  expect_identical(sort(sd_g$dpar), c("", "phi"))
  # and the row's spelling addresses that block alone
  fit_frame <- frm(bf(y ~ 1 + (1 | g), phi ~ z + (1 | g)) + Beta(),
                   data = dat, dry_run = "frame")
  spec <- frm(bf(y ~ 1 + (1 | g), phi ~ z + (1 | g)) + Beta(),
              data = dat, dry_run = "spec")
  ent <- frmtmb:::resolve_priorlist(
    list(frame = fit_frame, spec = spec),
    set_prior("exponential(1)", class = "sd", group = "g", dpar = "phi"))
  expect_length(ent$entries, 1L)
})

test_that("external interface of validate_prior works correctly (brms)", {
  prior1 <- prior(normal(0,10), class = b) + prior(cauchy(0,2), class = sd)
  prior1 <- validate_prior(prior1, count ~ zAge + zBase * Trt + (1|patient),
                           data = pf_epilepsy, family = poisson())
  expect_true(all(c("b", "Intercept", "sd") %in% prior1$class))
  expect_s3_class(prior1, "frmtmb_prior_rows")
  # the rows the prior set, and the rows under them, as brms marks them
  expect_identical(prior1$source[prior1$class == "b" & prior1$coef == ""],
                   "user")
  expect_true(all(prior1$source[prior1$class == "b" &
                                  nzchar(prior1$coef)] == "(vectorized)"))
  expect_true(all(prior1$prior[prior1$class == "b"] == "normal(0, 10)"))
  expect_identical(prior1$source[prior1$class == "Intercept"], "default")
  expect_identical(prior1$prior[prior1$class == "sd" &
                                  prior1$group == "patient"],
                   "cauchy(0, 2)")
})

test_that("validate_prior() refuses what frm() refuses, with its message", {
  f <- count ~ zAge + (1 | patient)
  bad <- prior(normal(0, 1), coef = "nothere")
  msg_v <- tryCatch(validate_prior(bad, f, data = pf_epilepsy,
                                   family = poisson()),
                    error = conditionMessage)
  msg_f <- tryCatch(frm(f, pf_epilepsy, family = poisson(), prior = bad),
                    error = conditionMessage)
  expect_match(msg_v, "Prior target not found", fixed = TRUE)
  expect_identical(msg_v, msg_f)
  expect_error(validate_prior(list(1), f, data = pf_epilepsy),
               "takes a prior built by set_prior")
})

test_that("a validate_prior() table fits the model its prior fits", {
  set.seed(5)
  d <- data.frame(x = stats::rnorm(80), z = stats::rnorm(80),
                  g = factor(rep(1:8, 10)), h = factor(rep(1:5, 16)))
  d$y <- 1 + 0.4 * d$x + stats::rnorm(8, 0, 0.5)[d$g] +
    stats::rnorm(5, 0, 0.5)[d$h] + stats::rnorm(80)
  f <- y ~ x + z + (1 | g) + (1 | h)
  cls_b <- set_prior("normal(0, 0.01)", class = "b")
  coef_z <- set_prior("normal(3, 0.01)", class = "b", coef = "z")
  cls_sd <- set_prior("normal(0, 0.05)", class = "sd", lb = 0.01)
  grp_sd <- set_prior("normal(0, 5)", class = "sd", group = "g")
  # both orders of each nesting: the more specific specification wins
  # whatever the order, as in brms, and the table shows what the fit
  # applies. Before, the later one won in the fit and the earlier one in
  # the table
  orders <- list(cls_b + coef_z + cls_sd + grp_sd,
                 coef_z + cls_b + grp_sd + cls_sd)
  fits <- lapply(orders, function(pr) {
    tab <- validate_prior(pr, f, data = d)
    a <- frm(f, d, prior = pr)
    b <- frm(f, d, prior = tab)
    expect_identical(fixef(a), fixef(b))
    expect_identical(as.numeric(logLik(a)), as.numeric(logLik(b)))
    expect_identical(tab$prior[tab$class == "b" & tab$coef == "z"],
                     "normal(3, 0.01)")
    expect_identical(tab$prior[tab$class == "b" & tab$coef == "x"],
                     "normal(0, 0.01)")
    expect_identical(tab$source[tab$class == "b" & tab$coef == "x"],
                     "(vectorized)")
    expect_identical(tab$prior[tab$class == "sd" & tab$group == "g"],
                     "normal(0, 5)")
    expect_identical(tab$prior[tab$class == "sd" & tab$group == "h"],
                     "normal(0, 0.05)")
    expect_identical(tab$lb[tab$class == "sd" & tab$group == ""], 0.01)
    a
  })
  # the two orders are one model
  expect_identical(fixef(fits[[1]]), fixef(fits[[2]]))
  # the coefficient prior bites: z sits at 3, x at 0
  expect_lt(abs(fixef(fits[[1]])$mu[["z"]] - 3), 0.1)
  # and the table is not simply ignored: without the prior the fit moves
  expect_false(identical(fixef(fits[[1]]), fixef(frm(f, d))))
})

# Every row of a validate_prior() table that names parameters no other
# row of its class narrows, compared with what the resolver applies to
# those parameters. The table is a display of the fit, so a row that
# shows a density the fit does not apply is the defect this reads.
pf_table_matches_fit <- function(pr, f, data) {
  tab <- validate_prior(pr, f, data = data)
  fr <- frm(f, data, dry_run = "frame")
  sp <- frm(f, data, dry_run = "spec")
  design <- list(frame = fr, spec = sp)
  applied <- frmtmb:::resolve_priorlist(design, pr)$entries
  dist_at <- list()
  for (e in applied) {
    for (k in e$idx) {
      dist_at[[paste0(e$comp, ".", k)]] <- if (identical(e$dist$kind, "lkj")) {
        paste0("lkj(", format(e$dist$eta), ")")
      } else {
        frmtmb:::prior_dist_string(e$dist)
      }
    }
  }
  block_of <- function(idx) {
    Filter(function(bk) idx %in% bk$theta_idx, fr$re_blocks)[[1L]]
  }
  checked <- 0L
  for (i in seq_len(nrow(tab))) {
    r <- tab[i, ]
    if (!r$class %in% c("b", "Intercept", "sd", "cor")) next
    kids <- tab$class == r$class & tab$resp == r$resp &
      tab$dpar == r$dpar & tab$nlpar == r$nlpar & seq_len(nrow(tab)) != i &
      ((nzchar(tab$coef) & !nzchar(r$coef)) |
         (nzchar(tab$group) & !nzchar(r$group)))
    if (any(kids)) next
    probe <- set_prior(if (r$class == "cor") "lkj(1)" else "normal(0, 1)",
                       class = r$class, coef = r$coef, group = r$group,
                       resp = r$resp, dpar = r$dpar, nlpar = r$nlpar)
    pos <- frmtmb:::resolve_priorlist(design, probe)$entries
    keys <- unlist(lapply(pos, function(e) {
      idx <- e$idx
      if (r$class %in% c("sd", "cor")) {
        # a block row names one predictor's block; the probe's empty
        # dpar reaches the others too
        idx <- idx[vapply(idx, function(k) {
          identical(frmtmb:::block_dpar(sp, fr, block_of(k)), r$dpar)
        }, TRUE)]
      }
      if (length(idx)) paste0(e$comp, ".", idx) else character(0)
    }))
    shown <- if (identical(r$prior, "(flat)")) NA_character_ else
      frmtmb:::prior_dist_string(frmtmb:::parse_prior_dist(r$prior))
    got <- unique(vapply(keys, function(k) dist_at[[k]] %||% NA_character_,
                         ""))
    testthat::expect_identical(got, shown,
                               info = paste(unlist(r[1:7]), collapse = "/"))
    checked <- checked + 1L
  }
  checked
}

test_that("every leaf row of a validate_prior() table is what the fit applies", {
  set.seed(20260916)
  n <- 200
  d <- data.frame(g = factor(rep(1:10, 20)), h = factor(rep(1:8, 25)),
                  x = stats::rnorm(n), z = stats::rnorm(n))
  d$yb <- pmin(pmax(stats::plogis(d$x / 3 + stats::rnorm(n, 0, 0.5)),
                    0.01), 0.99)
  d$y <- 1 + d$x + stats::rnorm(10, 0, 0.5)[d$g] + stats::rnorm(n)
  beta_f <- bf(yb ~ x + (1 | g), phi ~ z + (1 | g)) + Beta()
  cls_sd <- set_prior("normal(0, 1)", class = "sd")
  phi_sd <- set_prior("normal(0, 5)", class = "sd", dpar = "phi")
  grp_sd <- set_prior("normal(0, 2)", class = "sd", group = "g")
  cases <- list(
    # the recheck's R2: the phi block showed normal(0, 1)
    list(beta_f, cls_sd + phi_sd),
    list(beta_f, phi_sd + cls_sd),
    list(beta_f, grp_sd + phi_sd + cls_sd),
    list(beta_f, set_prior("normal(0, 3)", class = "b", dpar = "phi") +
           set_prior("normal(0, 0.5)", class = "b")),
    list(y ~ x + z + (x | g) + (1 | h),
         set_prior("normal(0, 1)", coef = "z") +
           set_prior("normal(0, 5)", class = "b") +
           set_prior("lkj(3)", class = "cor") + grp_sd + cls_sd))
  checked <- 0L
  for (cs in cases) {
    checked <- checked + pf_table_matches_fit(cs[[2]], cs[[1]], d)
  }
  # the check reads rows, not zero of them
  expect_gt(checked, 15L)
  # and it sees the defect when the table is wrong
  tab <- validate_prior(cls_sd + phi_sd, beta_f, data = d)
  expect_identical(tab$prior[tab$class == "sd" & tab$group == "g" &
                               tab$dpar == "phi"], "normal(0, 5)")
})

test_that("a group-specific cor prior wins over the class-wide one", {
  set.seed(8)
  d <- data.frame(x = stats::rnorm(160), g = factor(rep(1:16, 10)),
                  h = factor(rep(1:10, 16)))
  d$y <- 1 + 0.4 * d$x + stats::rnorm(16, 0, 0.6)[d$g] + stats::rnorm(160)
  f <- y ~ x + (x | g) + (x | h)
  kinds <- function(pr) {
    fr <- frm(f, d, dry_run = "frame")
    sp <- frm(f, d, dry_run = "spec")
    e <- frmtmb:::resolve_priorlist(list(frame = fr, spec = sp), pr)
    sort(vapply(e$entries, function(z) z$dist$eta, 0))
  }
  a <- set_prior("lkj(1)", class = "cor")
  b <- set_prior("lkj(9)", class = "cor", group = "g")
  expect_identical(kinds(a + b), c(1, 9))
  expect_identical(kinds(b + a), c(1, 9))
  tab <- validate_prior(b + a, f, data = d)
  expect_identical(tab$prior[tab$class == "cor" & tab$group == "g"],
                   "lkj(9)")
  expect_identical(tab$prior[tab$class == "cor" & tab$group == "h"],
                   "lkj(1)")
})

test_that("two specifications for one slot are refused (brms)", {
  set.seed(9)
  d <- data.frame(x = stats::rnorm(40))
  d$y <- 1 + d$x + stats::rnorm(40)
  msg <- "Duplicated prior specifications are not allowed"
  one <- set_prior("normal(0, 1)", class = "b")
  expect_error(frm(y ~ x, d, prior = one + one), msg)
  expect_error(frm(y ~ x, d, prior = one +
                     set_prior("normal(0, 2)", class = "b")), msg)
  expect_error(frm(y ~ x, d, prior = one +
                     set_prior("", class = "b", lb = 0)), msg)
  expect_error(validate_prior(one + one, y ~ x, data = d), msg)
  expect_error(frm_simulate(bf(y ~ x) + gaussian(), d, nsim = 1,
                            prior = one + one), msg)
  # the coefficient spelled with or without parentheses is one slot
  expect_error(frm(y ~ x, d,
                   prior = set_prior("normal(0, 1)", coef = "(Intercept)") +
                     set_prior("normal(0, 2)", coef = "Intercept")), msg)
  # different slots are not duplicates, whatever they reach
  expect_s3_class(frm(y ~ x, d, prior = one +
                        set_prior("", class = "b", coef = "x", lb = 0)),
                  "frmtmb_fit")
  # the slot is the fields, not the name brms prints: b with
  # dpar = "sigma" and b with coef = "sigma" both print b_sigma and are
  # two slots, which brms accepts. inputs.Rmd fits a covariate named
  # sigma
  d$sigma <- stats::rnorm(40)
  expect_s3_class(
    frm(bf(y ~ sigma, sigma ~ x), d,
        prior = set_prior("normal(0, 1)", class = "b", dpar = "sigma") +
          set_prior("normal(0, 2)", class = "b", coef = "sigma")),
    "frmtmb_fit")
  expect_silent(frmtmb:::check_prior_slots(
    set_prior("normal(0, 1)", class = "b", nlpar = "a") +
      set_prior("normal(0, 1)", class = "b", coef = "a")))
  # the message names the slot as brms prints it
  expect_error(frm(y ~ x, d, prior = set_prior("normal(0, 1)", coef = "x") +
                     set_prior("normal(0, 2)", coef = "x")),
               "'b_x' is given 2 times", fixed = TRUE)
})

test_that("class theta rows name real parameters of the fit", {
  # the extra rows default_prior() lists beside brms's: a theta prior
  # moves the fit, so the rows advertise a slot that exists
  set.seed(6)
  d <- data.frame(x = stats::rnorm(90), g = factor(rep(1:9, 10)))
  d$y <- 1 + stats::rnorm(9, 0, 0.8)[d$g] + stats::rnorm(90)
  f <- y ~ x + (1 | g)
  tab <- default_prior(f, data = d)
  expect_true("theta_1" %in% tab$coef[tab$class == "theta"])
  free <- frm(f, d)
  pinned <- frm(f, d, prior = set_prior("normal(-3, 0.05)",
                                        class = "theta", coef = "theta_1"))
  sd_of <- function(fit) sqrt(unclass(VarCorr(fit))[[1L]][1L, 1L])
  expect_lt(sd_of(pinned), sd_of(free) / 2)
})
