# Review: wt-priors2

Branch `wt-priors2`, base `68d6782`. Reviewer environment: R 4.6.1, frmtmb 0.52.0
installed from the worktree into a private library, brms 2.23.0, rstan 2.32.7,
StanHeaders 2.39.1. Every figure below was measured, not taken from the lane's
report.

## Verdict

**Final: MERGE**, at the re-check of 2026-09-06. Two merge-time wording edits, no
blockers. Read the "Re-check, 2026-09-06" section at the end for the current
state; everything between here and there is the first pass of 2026-09-05, kept
because the punch list and the measurements behind it are the record of what was
fixed.

First pass, 2026-09-05: PUNCH.

The core of the round is right and I can confirm it: the natural-scale class
places the density on the parameter itself with the correct log-Jacobian, the
two routes are genuinely one rule, and the shape gate reproduces brms's
accept/refuse split on 33 of 33 dpar-class cells I tested. Two defects block a
merge as it stands, both introduced by this round, both user-facing.

## Diff hygiene

21 paths, exactly as claimed: 20 modified, 1 untracked (`dev/priors2-findings.md`).
No `dev/*.log`, no `.Rcheck`, no stray artifacts.

No file owned by wt-protocol was touched: `R/families.R`, `R/compat.R` and
`R/objective.R` are all clean.

`R/sampling-api.R` IS touched, 14 lines in 4 hunks, none of them in the
conditional-effects section:

- `:59-64` roxygen prose describing `spec_spelling()`
- `:190` one `@aliases spec_spelling` line
- `:228-231` the `@rawNamespace export(...)` list gains `spec_spelling`
- `:332-338` `registered_prior_defaults()` keys by `spec_spelling(s)` instead of
  the raw `s$class`/`s$dpar`

Only the last is executable. The merge with wt-sample-ce should be textually
clean unless that lane also edits the export block.

`extensions/frmtmb.sample/tests/testthat/test-prior-route.R` is touched (5 lines).
That path is inside wt-sample-ce's territory. It is a test-only edit that follows
the class rename, so it is defensible, but it needs to be called out in the merge
plan rather than discovered.

## What I verified and can confirm

### The placement and the log-Jacobian are exactly right (c, d)

`prior_logdens()` (`R/priors.R:2049-2053`) applies `jac <- log(abs(link$mu_eta(x)))`
and `x <- link$linkinv(x)`, which is the correct change of variables. I checked
the resulting penalty against a hand-written
`-[log p(theta) + log|dtheta/deta|]` at a fixed parameter vector, for every link
a natural class can reach. The coordinate the penalty depends on was found by
perturbation rather than assumed:

| link | family, dpar | eta | frmtmb penalty | hand-written | abs diff |
| --- | --- | --- | --- | --- | --- |
| log | gaussian, sigma | 0.71284052 | 2.938019234302 | 2.938019234302 | 4.0e-15 |
| logit | zero_inflated_poisson, zi | -2.39789527 | 3.182084110375 | 3.182084110375 | 4.4e-15 |
| logm1 | student, nu | 1.09861229 | 13.433039055700 | 13.433039055700 | 2.3e-14 |
| power12 | tweedie, power | 0.00000000 | 3.417945705488 | 3.417945705488 | 2.0e-14 |
| identity | skew_normal, alpha | 2.02143441 | 3.586076279746 | 3.586076279746 | 1.3e-15 |

All well inside 1e-10. The identity case carries `log|1| = 0`, so no Jacobian, and
the number confirms it. The six `mu_eta` entries in `R/links.R:25-84` are each the
correct derivative of their own `linkinv`, `inverse` included (its negative
derivative is handled by the `abs()`).

`tan_half` is unreachable by a natural class by construction, not by omission: it
is only ever a `mu` link (`R/families.R:3656`, `:4732`), and `mu` always carries
the main formula, so `dpar_has_predictor()` is always TRUE there and the natural
spelling is refused before a Jacobian is needed. Nothing to fix; worth one line in
the docs so the next reader does not go looking.

A modeled dpar's Intercept carries NO Jacobian, as it must: on `bf(y ~ x, sigma ~ 1)`,
`set_prior("normal(0.3, 0.7)", class = "Intercept", dpar = "sigma")` adds exactly
`-dnorm(eta, 0.3, 0.7, log = TRUE)`, diff 4.9e-15.

This matches brms. `brms::make_stancode()` on `y ~ x` with
`prior(normal(0, 0.5), class = "sigma")` declares `real<lower=0> sigma;` and writes
`lprior += normal_lpdf(sigma | 0, 0.5)`. The density is on sigma itself and the
`<lower=0>` declaration is what supplies Stan's own `target += log(sigma)`. frmtmb's
penalty is `-[log p(sigma) + log sigma]`, so frmtmb's objective IS Stan's target in
unconstrained coordinates, up to constants. With `sigma ~ 1` brms writes
`real Intercept_sigma;` (unconstrained) and `normal_lpdf(Intercept_sigma | 0.3, 0.7)`,
link scale, no Jacobian. Both sides agree.

### The two routes really are one rule (c)

On gaussian `y ~ x`, n = 120: ML sigma 1.980522534,
`set_prior("normal(0, 0.5)", class = "sigma")` 1.880243585,
`brms::prior(normal(0, 0.5), class = "sigma")` 1.880243585. Equal to 1e-12, and the
objectives agree at a common parameter vector to 1e-12. I could not reproduce the
lane's 1.942946001 literally because the data that produced it is not in the tree
(`dev/priors2-findings.md:78` cites `p2-after.R`, which is not committed); the
invariant it stands for reproduces exactly on my own data.

I did NOT compile a brms model and compare against `optimizing()`. The comparison
it would give is available analytically and more tightly: brms's generated Stan
program declares `real<lower=0> sigma;` and adds `normal_lpdf(sigma | 0, 0.5)`, so
Stan's target in unconstrained coordinates is
`log p(y|sigma) + log p(sigma) + log sigma`, and F4 below shows frmtmb's optimum
is the maximizer of exactly that, to 6 significant figures against a
one-dimensional profile computed by hand. A compiled `optimizing()` run would add
Stan's own optimizer error on top and settle nothing the profile does not. It is
worth doing once at re-check if the cache makes it cheap.

### The sample route honors the natural placement (g)

`frm_sample(y ~ x, prior = set_prior("normal(0.5, 0.005)", class = "sigma"))`,
n = 150 whose ML sigma is about 2.0: sampled `sigma_Intercept` mean -0.543776, so
sigma 0.5805674. `frm()`'s penalized ML on the same prior gives 0.5805759. The
draws sit near 0.5, not near `exp(0.5) = 1.649`, so the density reached the sampler
on sigma rather than on log sigma. Correct.

### Deleted assertions are justified (e)

Every deleted assertion in the test diff is the old `link` arm that measured the
divergence this round removes: `bp_dpar_link_prior()` and the
`r$link$...` expectations could not survive a spelling that is now refused by name.
They are replaced, not dropped. `helper-brms-priors.R` swaps in
`bp_dpar_link_refusal()`; `extensions/frmtmb.eam/tests/testthat/test-surface.R:150-163`
adds a natural-class shrink assertion AND an `expect_error()` on the link spelling;
`tests/testthat/test-get-prior-route.R:93-94` adds `expect_false()` on the old
row alongside the new one. Coverage went up.

### print() and get_prior() are unambiguous (f)

`get_prior(yg ~ x, data = d)` against `brms::get_prior()` on the same model,
gaussian, matches row for row on `class`, `coef`, `dpar` and `nlpar`:

| | frmtmb | brms |
| --- | --- | --- |
| rows | Intercept; b; b/x; **sigma** | b; b/x; Intercept; **sigma** |
| bounds on the sigma row | `lb` NA, `ub` NA | `lb` 0 |
| prior column | all `(flat)` | brms's own defaults |

The four class/coef pairs are identical and `sigma` is listed under its own class
on both sides, which is the round's change. Row ORDER differs, which is cosmetic.
The two real differences are both correct and both documented: frmtmb's `lb` is NA
because a `lb = 0` on a log-linked dispersion is no constraint rather than a floor
(`?set_prior`, and `vignettes/brms-migration.Rmd`), and frmtmb applies no default
priors on the fit route because it is maximum likelihood, so every row is `(flat)`.
frmtmb has no `source` column; brms does.

A mixed table prints unambiguously. The natural rows carry an explicit
`scale=natural` marker and the link-scale ones do not, and each row prints the
class it was WRITTEN with, so every line can be pasted back into `set_prior()`:

```
normal(0, 2) class=b
student_t(3, 0, 2.5) class=sigma scale=natural
normal(0, 1) class=Intercept

normal(0, 2) class=b
normal(0, 1) class=Intercept dpar=sigma
normal(0, 3) class=b dpar=sigma
```

That paste-back promise is exactly what F1 breaks for `get_prior()`, which is why
F1 is ranked first: `print()` keeps the promise, and the table does not.

## Findings, ranked

### F1 (HIGH, blocks merge). `get_prior()` advertises class `theta1`, and every spelling of it is refused. New this round.

The new branch at `R/priors.R:1144-1148` routes ANY predictor-free dpar to its own
class. A mixture proportion is a predictor-free dpar, so a plain mixture now lists
`class = "theta1"`. But `check_dpar_prior_class()` (`R/priors.R:479`, via
`brms_prior_class_refusal()` at `R/priors.R:828`) refuses every class beginning
with `theta`. The refusal tells the user to write `class = "Intercept", dpar =`;
the new shape gate `dpar_shape_refusal()` (`R/priors.R:1921`) refuses THAT because
theta1 has no predictor, and tells the user to write `class = "theta1"`. The two
messages name each other. A mixture proportion is advertised by `get_prior()` and
reachable by nothing.

Before this round the same model listed `class = "Intercept", dpar = "theta1"`,
which was also refused, but `get_prior()` was not naming a class of its own that
does not exist. The round made the table worse, not better, on this row.

```r
d <- data.frame(x = rnorm(60)); d$yg <- 1 + .5*d$x + rnorm(60)
m <- frmtmb::bf(yg ~ x) + mixture(gaussian(), gaussian())
get_prior(m, data = d)$class
#> "Intercept" "b" "b" "sigma1" "sigma2" "theta1"

set_prior("normal(0, 1)", class = "theta1")
#> Error: class = "theta1" has no faithful frmtmb spelling. brms's "theta1" is a
#>   mixture proportion ... addressed as class = "Intercept" with dpar = that
#>   proportion's name ... and get_prior() lists the ones this model has.

frm(m, data = d, dry_run = "objective",
    prior = set_prior("normal(0, 1)", class = "Intercept", dpar = "theta1"))
#> Error: class = "Intercept", dpar = "theta1" is a density on the identity-scale
#>   intercept of theta1's linear predictor, which brms accepts only where theta1
#>   has one. This model writes no theta1 formula, so the prior brms takes there
#>   is class = "theta1", a density on theta1 itself.
```

For comparison, brms honors `class = "theta"` (a Dirichlet) on the same model, so
brms users have a working spelling and frmtmb has none. That part is the
documented, deliberate refusal and I am not asking for it to change. What has to
change is that `get_prior()` stops naming a class the package refuses.

Fix: exclude a class that `brms_prior_class_refusal()` refuses from the
own-class branch at `R/priors.R:1144-1148`, so a mixture proportion falls back to
the previous `Intercept` + `dpar` row (or is dropped, as the flat `simo` row
already is). Either way `get_prior()` must not print `theta1` in the `class`
column while `set_prior()` refuses it by name.

### F2 (MEDIUM-HIGH, blocks merge). `class = "b", dpar = X` on a `X ~ 1` model is accepted and does exactly nothing. brms refuses it.

The shape gate covers `natural && predictor` and `!natural && !predictor`
(`R/priors.R:1955-1985`) but not the third case brms rejects: class `"b"` on a
distributional parameter whose predictor is an intercept only, so it has no
population-level slopes for `b` to address. `dpar_has_predictor()` answers TRUE for
`sigma ~ 1` by design (`R/priors.R:1896-1907`, and that is correct for choosing
between the other two spellings), so the gate returns NULL and the prior is
accepted against an empty coefficient set.

This is not a near miss. The penalty is bit-identical to no prior at all, with no
message and no warning:

```r
f0 <- frm(bf(yg ~ x, sigma ~ 1), data = d, dry_run = "objective")
f1 <- frm(bf(yg ~ x, sigma ~ 1), data = d, dry_run = "objective",
          prior = set_prior("normal(0, 1e-6)", class = "b", dpar = "sigma"))
# objective difference at 40 random parameter vectors: max |diff| = 0, exactly
# messages: 0   warnings: 0
```

brms refuses the same row outright:
`The following priors do not correspond to any model parameter: b_sigma ~ normal(0, 3)`.

The machinery to refuse it already exists and fires for a named coefficient:
`set_prior("normal(0,1)", class = "b", coef = "nope", dpar = "sigma")` gives
`Prior target not found (class=b, coef=nope, dpar=sigma)`. Only the empty-`coef`
case slips through, because an empty `coef` matches the whole (empty) slope set
and an empty match is tolerated.

I measured this on 9 of the 11 family/dpar pairs in the table below: gaussian
sigma, student sigma, student nu, negbinomial shape, beta phi,
zero_inflated_poisson zi, hurdle_gamma hu, hurdle_gamma shape, von_mises kappa.
Same result every time. It is the ONLY residual disagreement with brms in the
whole sweep.

A tight prior a user believes is doing work and which provably does none is worse
than a refusal, and it is precisely the failure mode the lane's own docstring at
`R/priors.R:1909-1919` argues against.

### F3 (MEDIUM). `frm_sample()` announces a spelling that `set_prior()` now refuses on that very model.

`announce_default_priors()` (`extensions/frmtmb.sample/R/sample.R:728-731`) builds
its label as `paste0(s$class, " (", s$dpar, ")")` from the STORED pair, so a
natural sigma default prints `Intercept (sigma)`. The same default is listed by
`get_prior(route = "sample")` as class `sigma`, because `registered_prior_defaults()`
was changed this round to key by `spec_spelling()` (`R/sampling-api.R:332-338`).
One package, one default, two names, and the announced one errors:

```r
get_prior(y ~ x, data = d, route = "sample")$class
#> "Intercept" "b" "b" "sigma"

# what frm_sample() prints:
#>   Intercept          student_t(3, 1.2, 2.5)
#>   Intercept (sigma)  student_t(3, 0, 2.5)  [natural scale]

frm(y ~ x, data = d, prior = set_prior("student_t(3, 0, 2.5)",
                                       class = "Intercept", dpar = "sigma"))
#> Error: class = "Intercept", dpar = "sigma" is a density on the log-scale
#>   intercept of sigma's linear predictor, which brms accepts only where ...
```

The lane lists this as left out and owned by another lane. I do not accept the
second half: the inconsistency did not exist before this round, this round created
it by changing `get_prior()`, and the fix is to call `spec_spelling()` (which this
lane wrote and exported) in the one `lab <- ` line. One line, in a function whose
only job is to name what the table names. It should go in with the change that
broke it rather than be handed to wt-sample-ce as a mystery.

### F4 (LOW-MEDIUM). The substantive-differences list says "MAP" where it means "the mode in the internal coordinates".

The list's first item is "penalty is MAP not posterior", and `vignettes/inputs.Rmd`
says the fit is "penalized (MAP)". Both are true and neither says which mode.
Because the log-Jacobian is added, frmtmb maximizes
`L + log p(sigma) + log|dsigma/deta|` over eta, whose maximizer is the mode in
LOG-sigma coordinates. It is NOT the maximizer of `L + log p(sigma)` over sigma,
which is what a reader of "a density on sigma itself, MAP" will expect. On
gaussian `y ~ x`, n = 150, with `normal(2.5, 0.4)` on sigma:

| quantity | value |
| --- | --- |
| frmtmb penalized sigma | 2.170587365 |
| mode of L x p in sigma coordinates | 2.163706616 |
| mode of L x p in log-sigma coordinates | 2.170589175 |

frmtmb matches the third row. This is the right choice, because it is exactly
Stan's target in unconstrained coordinates and so keeps the two packages'
objectives equal, which is the property the whole round is built on. But it is a
substantive difference from the plain reading of "MAP", the user asked to be told
about substantive differences, and it is told nowhere. One sentence in the priors
section of `vignettes/brms-migration.Rmd`, next to the existing `log(2)` sentence
which is exactly the same kind of remark.

### F5 (LOW). `attr(frm_simulate(...), "pars")$sigma_Intercept` now means two different scales under one name.

Whether that column holds sigma or log sigma is decided by whether the model
writes a `sigma` formula, which is not visible in the column name:

```r
frm_simulate(y ~ x + (1|g), d, prior = ... + set_prior("normal(0.6,1e-9)", class = "sigma"))
#> sigma_Intercept = 0.6      -> simulated residual sd 0.6048
frm_simulate(bf(y ~ x + (1|g), sigma ~ 1), d,
             prior = ... + set_prior("normal(0.6,1e-9)", class = "Intercept", dpar = "sigma"))
#> sigma_Intercept = 0.6      -> simulated residual sd 1.8367  (= exp(0.6))
```

The numbers are right in both cases, so this is a labeling problem, not a bug: the
draw is used on the scale it was drawn on. It was reachable before via the brms
route, but this round makes the natural spelling the ONLY one on the commonest
model, so it goes from a corner to the default path.
`tests/testthat/test-simulate-ergonomics.R:118-127` pins the new value with a good
comment but does not address the collision. Worth a line in `?frm_simulate`.

### F6 (LOW, informational). `cumulative`'s `disc` has no frmtmb dpar at all.

brms models `disc` and accepts `class = "Intercept", dpar = "disc"` and
`class = "b", dpar = "disc"` once `disc` is given a formula. frmtmb refuses at the
parse step, before the new gate is reached:
`dpar(s) not available for family 'cumulative': disc (available: )`. On the
unmodeled shape both packages refuse `class = "disc"`, so they agree there by
coincidence rather than by rule. This is a pre-existing family gap, not something
this round introduced, and I am not asking the lane to implement `disc`. It is
listed because the round's claim is that the acceptance rule now follows brms, and
this is the one family where the rule is not reached at all.

### F7 (LOW-MEDIUM). `coef` and `group` on a natural class are silently dropped, which is the defect the round just fixed for `sd` and `cor`.

`unhonored_coef_refusal()` (`R/priors.R:737-738`) guards `cls %in% c("sd", "cor")`
only, and it is called at `R/priors.R:444` while `class` still holds the natural
name, before the rewrite to `Intercept` + `dpar`. So a `coef` or `group` on
`class = "sigma"` reaches the spec, is never read, and vanishes:

```r
frm(y1 ~ x, data = d, prior = set_prior("normal(0, 0.3)", class = "sigma"))
#> sigma = 0.9592549394
frm(y1 ~ x, data = d, prior = set_prior("normal(0, 0.3)", class = "sigma", coef = "x"))
#> sigma = 0.9592549394     identical: the coef was discarded, the prior applied anyway
```

brms refuses it:
`The following priors do not correspond to any model parameter: sigma_x ~ normal(0, 0.3)`.
`group = "g"` behaves the same way.

The lane's own NEWS bullet 4 says a `coef` that cannot be honored is now refused
rather than "accepted, printed, and then applied to the whole block". That
reasoning applies verbatim to the class family this round introduced, and the fix
is to extend the same guard: a natural class reads neither `coef` nor `group`, so
both should be refused there. Cheap, and it closes the rule the lane opened.

### F8 (LOW). A resp-less natural class broadcasts across a multivariate model; brms refuses the row.

```r
mv <- frmtmb::bf(y1 ~ x) + frmtmb::bf(y2 ~ x) + gaussian()
frm(mv, data = d)                                              # sigma 1.0130527 1.5136688
frm(mv, data = d, prior = set_prior("normal(0, 0.3)", class = "sigma"))
#>                                                              # sigma 0.9592519 1.3574421
```

Both responses move. brms refuses the same row outright because a dpar class on a
multivariate model needs `resp`. With `resp = "y1"` both packages accept, so this
is only the resp-less case. It is consistent with frmtmb's own broadcast
convention for class-wide priors, so I would not change the behavior, but it is a
brms difference that became reachable this round (before, `class = "sigma"` was a
`match.arg()` error and a brms table always carries `resp`), and it is documented
nowhere.

### F9 (INFO). Cross-lane paths, for the merge plan.

`R/sampling-api.R`: 4 hunks, listed above under Diff hygiene. Only
`registered_prior_defaults()` at `:332-338` is executable. No overlap with the
conditional-effects section.

`extensions/frmtmb.sample/tests/testthat/test-prior-route.R`: a 5-line test edit
inside wt-sample-ce's package, following the `get_prior()` class rename. Correct
and necessary, but it belongs in the merge plan explicitly.

## The brms acceptance comparison (b)

11 family/dpar pairs x 3 model shapes x 3 spellings = 99 cells. brms's verdict is
`brms::validate_prior()` under brms 2.23.0; frmtmb's is `frm(dry_run = "objective")`,
which reaches `resolve_priorlist()` and so the new gate. Shapes: `none` = the dpar
is unwritten, `int` = `dpar ~ 1`, `cov` = `dpar ~ z`. Spellings: `own` =
`class = <dpar>`, `int` = `class = "Intercept", dpar = <dpar>`, `b` =
`class = "b", dpar = <dpar>`.

`a` = both accept, `r` = both refuse, `B` = brms refuses and frmtmb accepts,
`F` = brms accepts and frmtmb refuses.

| family | dpar | none/own | none/int | none/b | int/own | int/int | int/b | cov/own | cov/int | cov/b |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| gaussian | sigma | a | r | r | r | a | **B** | r | a | a |
| student | sigma | a | r | r | r | a | **B** | r | a | a |
| student | nu | a | r | r | r | a | **B** | r | a | a |
| negbinomial | shape | a | r | r | r | a | **B** | r | a | a |
| Beta | phi | a | r | r | r | a | **B** | r | a | a |
| zero_inflated_poisson | zi | a | r | r | r | a | **B** | r | a | a |
| hurdle_gamma | hu | a | r | r | r | a | **B** | r | a | a |
| hurdle_gamma | shape | a | r | r | r | a | **B** | r | a | a |
| von_mises | kappa | a | r | r | r | a | **B** | r | a | a |
| mixture(gaussian, gaussian) | sigma1 | a | r | r | r | a | **B** | r | a | a |
| cumulative | disc | r | r | r | r | **F** | r | r | **F** | **F** |

Totals: 86 of 99 agree. 10 disagreements are F2, all the same rule in the `int/b`
column. 3 are F6, the `cumulative` `disc` family gap.

The result that matters most: on the two spellings this round is actually about,
`own` and `int`, across the 10 families frmtmb implements and all 3 shapes, that
is 60 of 60 cells in exact agreement with brms. The acceptance rule the lane
built is correct. What is missing is a gate on the third spelling.

A note on method: my first pass flagged 4 extra mixture disagreements. Those were
my harness error, not the lane's. `mixture()` must be attached with
`bf(...) + mixture(...)`; passing it through `family =` reaches a different
dispatch and errors with `Unsupported family object: 'mixture'`. Re-run with the
`+` idiom, mixture agrees with brms on 8 of 9 cells, the exception being the same
`int/b` rule. The table above is the corrected run.

## Behavior changes against NEWS (e)

Every spelling whose result moved, and whether `NEWS.md` states it:

| spelling | before | after | NEWS |
| --- | --- | --- | --- |
| `set_prior(class = "sigma")` and every other dpar name | error from `match.arg()` | accepted on a predictor-free dpar, density on the parameter | YES, bullet 1, with the 2.0103 / 1.9965 / 1.9429 numbers |
| `set_prior(class = "Intercept", dpar = "sigma")`, no sigma formula | accepted, density on LOG sigma | refused by name | YES, bullet 1, and the escape hatch (`sigma ~ 1`, or `prior = list(betad = )`) is given |
| the same, with `sigma ~ 1` or `sigma ~ x` | accepted, link scale | unchanged | YES, stated as unaffected |
| `brms::prior(..., class = "sigma")` | density on sigma | unchanged number | YES, pass-through bullet |
| `get_prior()` class column for a predictor-free dpar | `Intercept` + `dpar` | the dpar's own class | YES, bullet 2 |
| `set_prior(class = "sd", coef = )` | accepted, applied to the whole block | refused | YES, bullet 4 |
| `set_prior(class = "sds" / "simo" / "car" / "theta1" / ...)` | generic `match.arg()` error | named refusal saying where the quantity lives | YES, bullet 5 |
| `print()` and `spec_target()` on a brms-routed dpar row | `class=Intercept dpar=sigma scale=natural` | `class=sigma scale=natural` | NO |

The last row is the only omission and it is minor: the printed text of a
translated prior list, and of the error messages `spec_target()` builds, changed
for every dpar row. It follows from bullet 1 and nobody will be surprised, but the
round's own standard is that a visible change gets a line.

Not covered anywhere, because the lane did not know about them: F1, F2, F3.

## Documentation completeness (i)

The user asked to be told about anything substantively different. The lane's list
has four items. Three are documented well:

- the `log(2)` per lower-bounded priored `sd` element: `vignettes/brms-migration.Rmd:77-79`, correct and quantified.
- `cor`/`ar`/`ma`/`cosy` as coordinate changes: carried in `?set_prior`'s class list and the `"trans"` branch of `prior_logdens()`.
- structural classes refused by name from both routes: `?set_prior`, `NEWS.md` bullet 5, `vignettes/brms-migration.Rmd`.

The fourth, "penalty is MAP not posterior", is under-specified: see F4.

The list is also incomplete. Every one of F1, F2, F3, F6, F7 and F8 is a place
where frmtmb and brms differ in what they accept or in what they do with it, and
none is stated anywhere a user will read. The user asked to be told about
substantive differences; six went unreported. F1, F2 and F3 have to be fixed
rather than documented, but F6, F7 and F8 are the kind of thing the existing
`log(2)` sentence handles well, and they belong beside it.

The main behavior change itself is documented unusually well.
`vignettes/brms-migration.Rmd:80-101` gives the two-spelling table, the before and
after numbers, and both escape hatches. `?set_prior` gains a whole
"A distributional parameter's own class" section. `SPEC.md:433-444` and
`vignettes/inputs.Rmd:194` agree with it. I have no complaint about any of this.

One doc nit: `vignettes/brms-migration.Rmd` says "a script written before 0.53.0"
while `DESCRIPTION` still says 0.52.0 and `NEWS.md` heads the section
"development version". Fine if 0.53.0 is the release this lands in; wrong if the
version is bumped differently. Worth one check at merge.

## Counts I measured

Named test files, one `test_file()` per fresh process, frmtmb 0.52.0 loaded from
the private library in every one (printed and checked, so none of these ran
against the stale 0.50.0 in the user library):

| file | pass | fail | error | warn | skip |
| --- | --- | --- | --- | --- | --- |
| `tests/testthat/test-brms-priors.R` (gated on) | 103 | 0 | 0 | 0 | 0 |
| `tests/testthat/test-prior-compat.R` | 185 | 0 | 0 | 1 | 0 |
| `tests/testthat/test-setprior.R` | 27 | 0 | 0 | 0 | 0 |
| `tests/testthat/test-get-prior-route.R` | 37 | 0 | 0 | 0 | 0 |
| `tests/testthat/test-priors-autocor-classes.R` | 63 | 0 | 0 | 0 | 0 |
| `tests/testthat/test-priors-bounds-grcov.R` | 49 | 0 | 0 | 0 | 0 |
| `tests/testthat/test-simulate-ergonomics.R` | 50 | 0 | 0 | 0 | 0 |
| `tests/testthat/test-message-uniqueness.R` | 6 | 0 | 0 | 0 | 0 |
| `tests/testthat/test-bracket-access.R` | 8 | 0 | 0 | 0 | 0 |
| `extensions/frmtmb.sample/.../test-sample-direct.R` | 136 | 0 | 0 | 0 | 0 |
| `extensions/frmtmb.sample/.../test-prior-route.R` | 9 | 0 | 0 | 0 | 0 |
| `extensions/frmtmb.eam/.../test-surface.R` | 50 | 0 | 0 | 0 | 0 |

`test-brms-priors.R` at 103 confirms the lane's claim exactly (it was 83).

The one warning is not a failure and not new to this round:
`test-prior-compat.R:505:3`, "Optimizer did not report convergence: singular
convergence (7)" in "coef and group narrow the classes that read them".

Full suites, CRAN gating left ON (`NOT_CRAN` unset):

| suite | files | pass | fail | error | warn | skip |
| --- | --- | --- | --- | --- | --- | --- |
| frmtmb core | 97 of 117 | 4259 | 0 | 0 | 1 | 179 |
| frmtmb.eam | 16 | 1129 | 0 | 0 | 0 | 20 |
| frmtmb.sample | 5 | 265 | 0 | 0 | 0 | 5 |

These are BELOW the lane's reported 6562 / 1292 / 899 because I left CRAN gating
on for this pass: 20 of the 117 core files skip entirely under `skip_on_cran`. The
re-run with `NOT_CRAN=true`, which is the comparable number, did not finish before
my turn ended and I am not restarting it per the coordinator. Nothing in the
partial output contradicted the lane; treat the lane's three totals as UNVERIFIED
and re-measure them on the corrected tree.

### as-cran, partial

Run with the consolidation invocation (`_R_CHECK_CRAN_INCOMING_=false`,
`_R_CHECK_FORCE_SUGGESTS_=false`, `--as-cran`, `--no-manual`, pandoc on PATH). It
reached 52 check steps and was cut off at "checking re-building of vignette
outputs", so there is no final `Status` line and any NOTE past that point is
unknown. What it got through:

| step | result |
| --- | --- |
| `checking examples` | OK, 47s |
| `checking examples with --run-donttest` | OK, 76s |
| `checking for unstated dependencies in 'tests'` | OK |
| `checking tests` | **OK, 344s** |
| `checking files in 'vignettes'` | WARNING |
| `checking package vignettes` | WARNING |

The two WARNINGs are MY artifact, not the lane's: I built the tarball with
`R CMD build --no-build-vignettes`, so `inst/doc` does not exist and check
correctly complains that eight vignettes have no built output. They say nothing
about this branch. Rebuild the tarball without that flag to clear them.

The substantive line is `checking tests ... [344s] OK`: the whole suite passes
under `--as-cran`. I could not confirm or refute the lane's claim that the
remaining ERROR/WARNING/NOTEs are only pdflatex and V8, because the run did not
reach them. Note that `frmtmb-Ex.pdf` was produced, so pdflatex IS available in
this environment and the lane's pdflatex explanation is doubtful; it needs
re-measuring rather than accepting.

## Verdict (first pass): PUNCH

The design is right and most of the execution is right. The natural-scale class,
the Jacobian, the one-rule pass-through and the shape gate for the two spellings
that matter are all correct and I verified each independently rather than reading
the lane's numbers back. But F1 and F2 are both user-facing, both new or newly
reachable, and both are the exact failure mode the round set out to remove: a
spelling that the package advertises and refuses, and a prior that is accepted and
does nothing.

### Punch list

1. **F1.** Stop `get_prior()` naming a class that `set_prior()` refuses. At
   `R/priors.R:1144-1148`, exclude any dpar for which
   `brms_prior_class_refusal()` returns non-NULL from the own-class branch, so a
   mixture proportion falls back to the `Intercept` + `dpar` row or is dropped the
   way the flat `simo` row already is. Add a test that every `class` value
   `get_prior()` emits is a class `set_prior()` accepts, for a mixture and for at
   least one ordinary model. That test is what stops this recurring.

2. **F2.** Refuse `class = "b", dpar = X` where X's predictor has no
   population-level slopes. In `dpar_shape_refusal()` (`R/priors.R:1921`), add the
   third case: `s$class == "b"`, `pred` TRUE, and the dpar's design has no column
   beyond the intercept, naming `class = "Intercept", dpar = X` as the spelling
   that applies. Test it on `bf(y ~ x, sigma ~ 1)` and assert brms refuses the
   same row.

3. **F3.** One line in `announce_default_priors()`
   (`extensions/frmtmb.sample/R/sample.R:728-731`): build `lab` from
   `spec_spelling(s)` rather than `s$class`/`s$dpar`, so `frm_sample()` announces
   the same word `get_prior(route = "sample")` prints and `set_prior()` accepts.
   Coordinate with wt-sample-ce, but it belongs with the change that broke it.

4. **F7.** Extend `unhonored_coef_refusal()` (`R/priors.R:737`) to refuse `coef`
   and `group` on a natural class, and move the call at `R/priors.R:444` so it
   sees the natural name. Same rule the round already adopted for `sd` and `cor`.

5. **F4.** One sentence in the priors section of `vignettes/brms-migration.Rmd`
   saying the penalized optimum is the mode in the internal coordinates, equal to
   Stan's target in unconstrained space, not the mode of the parameter's own
   density. Put it beside the existing `log(2)` sentence and give the
   2.170587 / 2.163707 pair.

6. **F8 and F6**, in the same documentation pass: a resp-less natural class
   broadcasts across a multivariate model where brms refuses the row; `cumulative`
   has no `disc` dpar at all, so the acceptance rule is never reached for it.

7. **F5**, optional: a line in `?frm_simulate` saying the `pars` column for a dpar
   is on the scale the prior was written on.

8. **NEWS**, minor: a line for the changed `print()` and `spec_target()` text on a
   translated dpar row.

9. **Re-measure at re-check**, since my runs were cut off: the three suite totals
   with `NOT_CRAN=true` (lane claims 6562 / 1292 / 899), and a complete as-cran on
   a tarball built WITH vignettes, to settle what the residual NOTEs actually are.
   Do not carry the lane's pdflatex explanation forward without evidence.

Items 1 and 2 are the merge blockers. 3 through 8 are cheap and should ride along.

---

# Re-check, 2026-09-06

Machine restarted between rounds, so core, `frmtmb.sample` and `frmtmb.eam` were
rebuilt from the worktree into `rvp2-lib` before anything was measured; every
script prints its `packageVersion("frmtmb")` and its library path, and all of them
report 0.52.0 out of `rvp2-lib`, not the 0.50.0 in the user library.

## Verdict (final): MERGE

All nine punch items are on disk and all nine verify by running. The two blockers
are fixed properly rather than papered over, and the fixes do not over-refuse. The
one residual acceptance disagreement with brms is the `cumulative` `disc` family
gap, which is now documented rather than silent.

## Item by item

**1. F1, `get_prior()` no longer advertises an unusable class. FIXED.**
`R/priors.R:1190` skips a predictor-free dpar whose class
`brms_prior_class_refusal()` rejects. Verified by round-tripping EVERY row of
`get_prior()` back through `set_prior()` across seven shapes:

| shape | rows | classes emitted | round trip |
| --- | --- | --- | --- |
| gaussian `y ~ x` | 4 | Intercept, b, sigma | all accepted |
| gaussian `+ (1|g)` | 8 | Intercept, b, sigma, sd, theta | all accepted |
| `sigma ~ z` | 6 | Intercept, b | all accepted |
| student | 5 | Intercept, b, sigma, nu | all accepted |
| negbinomial | 4 | Intercept, b, shape | all accepted |
| cumulative | 3 | Intercept, b | all accepted |
| mixture(gaussian, gaussian) | 5 | Intercept, b, sigma1, sigma2 | all accepted |

No `theta1` row anywhere, and no row that `set_prior()` refuses. brms still lists
`theta` (a Dirichlet) for the mixture where frmtmb lists nothing; that is the
deliberate documented refusal, and staying silent about a class the package
cannot honor is the right call.

**2. F2, `class = "b", dpar = X` on an intercept-only predictor. FIXED.**
The third case is at `R/priors.R` inside `dpar_shape_refusal()`, testing
`s$class == "b" && pred && !length(setdiff(colnames(lp[["X"]]), "(Intercept)"))`.
Using the column names rather than a count is the better choice: it also catches
`sigma ~ 1 + (1|g)`, where a random effect makes `pred` TRUE but there is still no
`b_sigma`.

Re-ran the changed cells on all 10 family/dpar pairs: **10 of 10 now agree with
brms**, every one a refusal on both sides, where all 10 previously disagreed.

Checked for over-refusal, which is the obvious way to get this wrong.
`class = "b", dpar = "sigma"` is still ACCEPTED on `sigma ~ z`, `sigma ~ 1 + z`
and `sigma ~ z + I(z^2)`. It is refused on `sigma ~ 1 + (1|g)`, and brms refuses
that one too.

**3. F3, the `frm_sample()` announcement. FIXED.**
`extensions/frmtmb.sample/R/sample.R:725-735` builds the label from
`spec_spelling()`. The announcement and the table now agree:

```
get_prior(route = "sample") classes:  Intercept, b, b, sigma
frm_sample() announces:
  Intercept          student_t(3, 1.5, 2.5)
  sigma              student_t(3, 0, 2.5)  [natural scale]
  b                  (flat), as brms leaves slopes
```

No `Intercept (sigma)` anywhere, and `sigma` is a word `set_prior()` accepts on
that model.

**4. F7, `coef`/`group` on a natural class. FIXED, and it does not over-refuse.**
`unhonored_coef_refusal()` gained a `group` argument and a `nat` branch, called at
`R/priors.R:444` with the class the user wrote.

| spelling | result |
| --- | --- |
| `class = "sigma", coef = "x"` | refused, "which is one parameter, so coef = "x" names nothing it can narrow to" |
| `class = "sigma", group = "g"` | refused, same shape of message |
| `class = "shape", coef = "x"` | refused |
| `class = "b", coef = "x"` | ACCEPTED |
| `class = "sd", group = "g"` | ACCEPTED |
| `class = "sigma"` bare | ACCEPTED |

And a legitimate narrowed prior still bites end to end: `class = "b", coef = "x"`
with `normal(0, 0.01)` moves the slope from 0.5083211 to 0.003897806. brms refuses
`class = "sigma", coef = "x"` as well.

**5. F4, which mode. DOCUMENTED, with one wording defect.**
`vignettes/brms-migration.Rmd:80-91` now has a "Which mode" paragraph saying the
optimum is the mode in internal coordinates, which is Stan's target in
unconstrained space. The substance is right and I re-measured it: frmtmb 2.170587,
log-sigma mode 2.170587 (gap 3.2e-07), sigma-coordinate mode 2.163703 (gap
6.9e-03).

Two notes. First, the vignette's literal figures (2.133344 / 2.133358 / 2.126533)
do not reproduce on my data, because the paragraph states `n = 150` and
`normal(2.5, 0.4)` but not the seed or the data-generating process. The STRUCTURE
reproduces exactly, including the gap to the sigma-coordinate mode (6.8e-03 in the
vignette, 6.9e-03 here), so I am satisfied the numbers are real; they are just not
reproducible from what is written. Stating the seed would fix that.

Second, a real wording defect: the paragraph ends "frmtmb matches the second,
deliberately". The preceding sentence names two modes, log-sigma coordinates first
and sigma coordinates second, so "the second" reads as the sigma-coordinate mode,
which is the one frmtmb does NOT match. Read as the second of the three numbers it
happens to be right. In a paragraph whose whole purpose is to say precisely which
mode, that sentence must not be ambiguous. Name it: "frmtmb matches the log-sigma
mode".

**6. F8 and F6, the two rows frmtmb accepts and brms refuses. DOCUMENTED, and I
accept the convention argument.**
`vignettes/brms-migration.Rmd:93-101` keeps the multivariate broadcast and argues
it follows frmtmb's own convention. I tested the premise rather than taking it:

- a `class = "sd"` prior with no `group` on `y ~ x + (1|g) + (1|h)` moves BOTH blocks (theta -0.0666258, -0.3175069 becomes -1.29323, -1.94302).
- a `class = "b"` prior with no `coef` moves every slope (0.469816, 0.059039 becomes 0.00317818, 0.00032409).
- and, decisively, **brms does the same thing**: `make_stancode()` for a groupless `class = "sd"` prior emits `lprior += normal_lpdf(sd_1 | 0, 0.05)` AND `lprior += normal_lpdf(sd_2 | 0, 0.05)`.

So "a class-wide prior with no qualifier covers every instance of that class" is
not merely frmtmb's house style, it is brms's behavior on the other qualifiers.
brms's insistence on `resp` for a dpar class on a multivariate model is the
inconsistency, not frmtmb's broadcast. The argument is sound and I accept it. The
behavior is documented and `resp = "y1"` correctly narrows to one response
(verified: only y1's sigma moves, 1.013053 to 0.9592563, y2 unchanged at 1.5136666).

`cumulative` having no `disc` is documented in the same paragraph.

**7. F5, the `pars` column scale. DOCUMENTED.**
`R/simulate-new.R:494-506` states which scale the column holds under each
spelling, and adds the point that settles it: only one of the two spellings is
accepted on any one model, so a table cannot mix them and the draw is always used
on the scale it was taken on.

**8. NEWS. DONE.** `NEWS.md:30-56` covers the `get_prior()` omission, the
`class = "b"` refusal, the `coef`/`group` refusal, and the changed `print()` and
error-message text, each stating what used to happen.

**9. as-cran and the pdflatex question.** See below.

## Re-check counts

Named files, one `test_file()` per fresh process, `test-brms-priors.R` gated on
with `FRMTMB_BRMS_FIT_TESTS=true`, `NOT_CRAN=true` and `FRMTMB_STAN_CACHE` on my
own copy of the cache:

| file | pass | fail | error | warn | skip | lane claimed |
| --- | --- | --- | --- | --- | --- | --- |
| `test-brms-priors.R` (gated) | 103 | 0 | 0 | 0 | 0 | 103 |
| `test-prior-compat.R` | 195 | 0 | 0 | 1 | 0 | 195 (was 185) |
| `test-setprior.R` | 27 | 0 | 0 | 0 | 0 | 27 |
| `test-get-prior-route.R` | 75 | 0 | 0 | 0 | 0 | 75 (was 37) |
| `test-priors-autocor-classes.R` | 63 | 0 | 0 | 0 | 0 | 63 |
| `test-priors-bounds-grcov.R` | 49 | 0 | 0 | 0 | 0 | 49 |
| `test-simulate-ergonomics.R` | 50 | 0 | 0 | 0 | 0 | 50 |
| `test-message-uniqueness.R` | 6 | 0 | 0 | 0 | 0 | |
| `test-bracket-access.R` | 8 | 0 | 0 | 0 | 0 | |
| `frmtmb.sample` `test-sample-direct.R` | 136 | 0 | 0 | 0 | 0 | |
| `frmtmb.sample` `test-prior-route.R` | 9 | 0 | 0 | 0 | 0 | |
| `frmtmb.eam` `test-surface.R` | 50 | 0 | 0 | 0 | 0 | |

Every count the lane reported matches what I measured. 0 failures and 0 errors
across all twelve. The single warning is the same pre-existing one as last round,
`test-prior-compat.R:505:3`, "Optimizer did not report convergence: singular
convergence (7)"; it is not new and not a failure.

`test-get-prior-route.R` going 37 to 75 is the per-row usability loop the lane
describes, and it is the right test to have added: it is the assertion that would
have caught F1 before I did.

Roxygen is still idempotent after the changes: NAMESPACE and `man/` regenerate
byte-identical from a scratchpad copy.

## The acceptance sweep, re-run

Same 99 cells as last round.

| | first pass | re-check |
| --- | --- | --- |
| disagreements | 16 | 7 |
| of which my mixture harness artifact | 4 | 4 |
| of which F2, `class = "b"` on `X ~ 1` | 10 | **0** |
| of which `cumulative` `disc` (F6) | 3 | 3 |
| genuine disagreements | 13 | **3** |

Excluding `cumulative`, which frmtmb does not implement `disc` for at all: 90
cells, 90 in agreement with brms. The three remaining are the documented family
gap. Every F2 cell is fixed and none of the previously agreeing cells regressed.

## Cross-lane footprint: clean

`extensions/frmtmb.sample/R/sample.R` is modified by this lane, which is package
source rather than a test and sits in what was wt-sample-ce's territory. That hunk
exists because I asked for it (F3). It is settled: wt-sample-ce has already merged
into main and did NOT touch `extensions/frmtmb.sample/R/sample.R`, so there is no
conflict and nothing to sequence. The hunk is 8 lines confined to
`announce_default_priors()`, nowhere near the conditional-effects work.

`R/sampling-api.R` is likewise clean: 4 hunks, three of them roxygen and export
lines, one executable change in `registered_prior_defaults()`, none in the
conditional-effects section.

No file owned by wt-protocol (`R/families.R`, `R/compat.R`, `R/objective.R`) is
touched in either round.

## Two wording items: MERGE-TIME, not blocking

Neither changes behavior, neither is worth another round trip. Both are one-line
edits to `vignettes/brms-migration.Rmd` and should be made as the branch goes in.

1. **Name the mode explicitly.** The "Which mode" paragraph ends "frmtmb matches
   the second, deliberately". The sentence before it names two modes, log-sigma
   first and sigma second, so "the second" reads as the sigma-coordinate mode,
   which is the one frmtmb does not match. Counting the three numbers instead
   makes it correct, which is exactly the ambiguity a paragraph about precision
   cannot afford. Replace with "frmtmb matches the log-sigma mode, deliberately".

2. **State the seed and the DGP for the figures.** The paragraph gives
   2.133344 / 2.133358 / 2.126533 for "a gaussian `y ~ x` with 150 rows and
   `normal(2.5, 0.4)` on `sigma`" but not the seed or how `y` was generated, so
   the numbers cannot be reproduced from what is written. I satisfied myself they
   are real by reproducing the structure and the gap size (6.8e-03 in the
   vignette, 6.9e-03 on my data), but a reader should not have to do that. One
   clause naming the seed fixes it.

## as-cran, complete this time

Invocation, recorded because it decides what the result means: `R CMD build` WITH
vignettes (no `--no-build-vignettes`, which is what produced my two spurious
vignette WARNINGs last round), then
`R CMD check --as-cran --no-manual` with `_R_CHECK_CRAN_INCOMING_=false`,
`_R_CHECK_FORCE_SUGGESTS_=false`, pandoc on PATH, and TinyTeX's
`C:/Users/adf44/AppData/Roaming/TinyTeX/bin/windows` PREPENDED to PATH so a
missing pdflatex could not mask anything else. That is consolidation's invocation
plus the PATH entry.

**`Status: OK`. 56 check steps. Zero ERRORs, zero WARNINGs, zero NOTEs.**

| step | result |
| --- | --- |
| `checking files in 'vignettes'` | OK |
| `checking examples` | OK, 43s |
| `checking examples with --run-donttest` | OK, 50s |
| `checking for unstated dependencies in 'tests'` | OK |
| `checking tests` | OK, 327s |
| `checking package vignettes` | OK |
| `checking re-building of vignette outputs` | OK, 290s |
| `checking installed files from 'inst/doc'` | OK |

There is nothing to name, because nothing was flagged.

On the two attributions the lane made and I was asked to settle:

- **pdflatex.** Confirmed, and the cause is now nailed down. `Sys.which("pdflatex")` is empty from a plain `Rscript`, yet `C:/Users/adf44/AppData/Roaming/TinyTeX/bin/windows/pdflatex.exe` exists. The binary is present and the directory is simply not on the PATH these shells inherit. So the lane's manual-building ERROR and WARNING are environmental and its attribution holds. Under `--no-manual`, which is what consolidation runs, the manual is never built and the question does not arise.
- **V8.** V8 is NOT installed in this library, and my check still produced zero NOTEs. `_R_CHECK_FORCE_SUGGESTS_=false` is part of consolidation's invocation and is what keeps an absent Suggests package from raising one. So the lane's V8 NOTE also does not appear under the invocation consolidation actually uses.

The practical conclusion for consolidation: this branch checks clean. The lane's
reported ERROR, WARNING and two NOTEs were artifacts of building the manual on a
machine whose PATH lacks TinyTeX, and none of them survives the invocation
consolidation runs.

## Final verdict: MERGE

Everything that blocked the first pass is fixed and verified by running, not by
reading. The acceptance rule now matches brms on every cell except the three that
belong to a family gap frmtmb does not implement and now documents. All twelve
named test files pass with the counts the lane reported. Roxygen is idempotent,
the cross-lane footprint is clean, and as-cran is `Status: OK` with nothing
flagged.

Take the two wording edits to `vignettes/brms-migration.Rmd` as the branch goes
in. They are merge-time, not blocking, and neither touches behavior:

1. "frmtmb matches the second" becomes "frmtmb matches the log-sigma mode".
2. Name the seed and the data-generating process behind the 2.133344 / 2.133358 / 2.126533 figures so a reader can reproduce them.

One thing worth carrying forward beyond this branch: the per-row usability loop
added to `tests/testthat/test-get-prior-route.R`, which asserts that every class
`get_prior()` emits is a class `set_prior()` accepts, is the test that would have
caught F1 before review. That pattern, an invariant tying the two halves of a
public API together rather than pinning one more number, is worth reusing whenever
a lane adds a class vocabulary.
