# Review: wt-xspec, extensions/frmtmb.coupling 0.1.0

Reviewer lane: rvxs. Target: branch `wt-xspec` in
`C:/Users/adf44/source/r/frmtmb-wt-xspec`, uncommitted diff against
`c18253e` plus untracked files. Core and extension installed into a
private library; no shared library touched. Neither tree modified except
this file.

**Verdict: PUNCH.** The likelihood itself is right, and better verified
than the lane claimed: it matches an independent complex-matrix
implementation to 1.6e-12 and its normalizing constant survives an
importance-sampling mass test across differing degrees of freedom. Three
things block a merge. The positive definiteness guarantee the package
advertises three times is false in floating point and produces a
zero-width confidence interval and a reachable NaN. The stated reason for
refusing more than two channels is a false claim about core. The
`fit_check` hook, which the lane rates among its top three findings,
fires on correctly specified models and stays silent on the misspecified
ones in the common regime.

---

## Findings, by severity

### S1. BLOCKER. `1 - ch` is catastrophic cancellation, and the docs say it is safe

`extensions/frmtmb.coupling/R/cross-wishart.R:151`

```r
cmp <- 1 - ch
```

`ch` arrives as `plogis(eta)`. The complement is then formed by
subtraction from 1, which throws away every digit below the leading one
of `1 - ch`. The stable form is `plogis(-eta)`.

Measured on one legal row at `n = 16`, shipped expression against the
same formula with `cmp = plogis(-eta)`:

| eta_coh | coherence | shipped log density | stable log density | relative error |
| --- | --- | --- | --- | --- |
| 10 | 0.9999546 | -4299.993882 | -4299.993882 | 9.9e-13 |
| 20 | 0.999999998 | -97032770.3 | -97032773.78 | 3.6e-08 |
| 25 | 1 - 1.4e-11 | -14400919385 | -14400979522 | 4.2e-06 |
| 30 | 1 - 9.4e-14 | -2139477257233 | -2137294915880 | 1.0e-03 |
| 36 | 1 - 2.2e-16 | -900719925473580 | -862246309422520 | 4.5e-02 |
| 36.74 | 1 | **NaN** | -1.807e+15 | undefined |
| 40 | 1 | **NaN** | -4.708e+16 | undefined |

`1 - plogis(eta)` reaches exactly 0 just above `eta = 36.736800569677101`,
the last value at which it still returns 2.22e-16, so from there up
`log(cmp)` is `-Inf` and `tr` divides by zero. The RTMB tape returns NaN
for both the value and the derivative there.

The region is reachable from an ordinary fit. Nine groups, a random
effect on `coh`, eight groups at true coherence 0.3 and one group at a
true coherence approaching 1:

| top group true C | min row determinant | fitted eta | returned SE |
| --- | --- | --- | --- |
| 0.99 | 1.7e+00 | 4.613 | 0.108 |
| 1 - 1e-06 | 1.8e-04 | 13.812 | 0.106 |
| 1 - 1e-10 | 1.6e-08 | 23.191 | 0.108 |
| 1 - 1e-13 | 1.1e-11 | 29.325 | 0.148 |
| 1 - 1e-15 | 1.5e-13 | 34.031 | **NaN** |

`valid_y()` passes every one of these rows, because each row's own
determinant is positive. One further decade of coherence and the
objective itself is NaN.

Worse, and reachable without any random effect. Two signals differing by
noise of 1e-5, `segments = 16`, intercept-only:

```
eta       = 18.699822832179027
.se       = 0            exactly zero
.estimate = 0.99999999243567606
.lower    = 0.99999999243567606
.upper    = 0.99999999243567606
```

`frm_coherence()` returns a 95 percent confidence interval of width
zero. `cp_link_se()` at `R/coupling.R:97` guards only against a NULL
`se.fit`, so a zero or NaN standard error passes through and becomes a
point.

The shipped documentation asserts the opposite in three places:

* `R/cross-wishart.R:76-80`: "Here it cannot fail to be. ... no value of
  any linear predictor can produce an invalid matrix. There is no
  eigenvalue floor and no projection step."
* `R/cross-wishart.R:143-144`: "`1 - ch` is safe without a floor because
  `ch` arrives through a logit link and cannot reach 1."
* `DESCRIPTION` and `vignettes/coherence.Rmd`: "The parameterization
  cannot leave the positive definite cone, because a logit link on
  coherence IS the constraint."

The mathematics is right. The arithmetic is not, and the code comment
names the unstable line and blesses it.

Nothing tests it. `tests/testthat/test-coherence.R:41` loops over
`eta` in `c(-3, 0, 3)`, a top coherence of 0.953;
`tests/testthat/test-cross-wishart.R:57` tops out at `coh = 0.75`.

Reproduction:

```r
lp <- frmtmb.coupling:::cw_lpdf
lp(10, list(mu = 1.25, pow2 = 1.25, coh = plogis(40), phase = 0),
   list(vint1 = 8, vreal1 = 10, vreal2 = 9.99, vreal3 = 0))
#> NaN
```

Note the fix probably cannot live inside the family as written, because
`cw_lpdf` receives `dpars$coh` already through the link and never sees
`eta`. **That** is a genuine core seam worth recording: the family needs
the link-scale predictor, or a link that supplies its own complement. A
`pmax()` floor would remove the NaN but not the precision loss, and would
cost exactly the "no eigenvalue floor" property the package sells.

### S2. MAJOR. The p > 2 refusal blames core for a limitation core does not have

`extensions/frmtmb.coupling/R/cross-wishart.R:85-86` and
`extensions/frmtmb.coupling/vignettes/coherence.Rmd:229`:

> a `p`-channel response needs `p^2` linear predictors and a Hermitian
> response the frame does not carry.

Core's frame does carry a matrix-valued response. `R/frame.R:241-247`
preserves it explicitly:

```r
if (is.matrix(y) && ncol(y) == 1L) {
  y <- drop(y)
}
if (is.matrix(y)) {
  storage.mode(y) <- "double"
} else {
  y <- as.numeric(as.vector(y))
```

Both of these fit:

```r
d <- data.frame(x = rnorm(60)); d$Y <- cbind(rnorm(60, 1), rnorm(60, 5))
frm(Y ~ x, family = gaussian(), data = d)
#> fits. nobs 60, logLik -262.0422

cf <- custom_family("hermitianish", dpars = c("mu", "s2"),
  links = list(mu = "identity", s2 = "log"),
  lpdf = function(y, dpars, aterms)
    -0.5 * ((y[, 1] - dpars$mu)^2 + (y[, 2] - dpars$s2)^2),
  type = "continuous")
frm(bf(Y ~ x, s2 ~ 1), family = cf, data = d)
#> fits. logLik -55.52872; y reaches the lpdf as an n x 2 matrix
```

Refusing p > 2 is a defensible scope decision: p^2 predictors, no complex
determinant on the tape, and a much less pleasant Cholesky
parameterization. Say that. Do not say the frame blocks it, and above all
do not record it as a core seam, which sends whoever owns items 1 to 4 in
core after a gap that is not there.

There is also no code path to refuse. `cross_wishart()` takes no
arguments and `frm_cross_spectrum()` takes exactly two signals, so
"refused by name" is documentation only. That is honest enough, but a
three-column matrix pair is silently read as three UNITS rather than
three channels, which is the shape a user with a three-channel recording
will actually reach for.

### S3. MAJOR. `cw_fit_check` fires on the wrong statistic

`extensions/frmtmb.coupling/R/cross-wishart.R:212-235`. The hook compares
`var(log(W11 / (n S11)))` against `trigamma(n)` and warns above a ratio
of 2. That measures residual spread in the POWER model. It is not
monotone in the thing the user is warned about, which is displacement of
the COHERENCE.

Two-band design, 400 frequencies, `n = 8`, true coherences 0.35 and 0.05,
`coh ~ band`, fitted with the constant power model `mu ~ 1, pow2 ~ 1`,
varying the spectral slope:

| power spread | high-band coherence reported | truth | overstatement | hook | ratio |
| --- | --- | --- | --- | --- | --- |
| 54830x | 0.989 | 0.05 | 19.8x | FIRES | 76.2 |
| 385x | 0.874 | 0.05 | 17.5x | FIRES | 23.3 |
| 19.6x | 0.470 | 0.05 | 9.4x | FIRES | 6.60 |
| 7.3x | 0.229 | 0.05 | 4.6x | FIRES | 3.52 |
| 4.4x | 0.141 | 0.05 | 2.8x | FIRES | 2.46 |
| **2.7x** | **0.092** | **0.05** | **1.8x** | **SILENT** | below 2 |
| **1.6x** | **0.067** | **0.05** | **1.3x** | **SILENT** | below 2 |

A 2.7-fold power spread across a band is unremarkable in any real
recording, and there the reported coherence is nearly double the truth
with no warning at all.

The other direction is worse, because it trains users to ignore it. With
the CORRECT power model `mu ~ band, pow2 ~ band`, which recovers the
coherences accurately, the hook still fires:

| power spread | low band (true 0.35) | high band (true 0.05) | hook | ratio |
| --- | --- | --- | --- | --- |
| 54830x | 0.368 | 0.042 | FIRES | 20.5 |
| 385x | 0.356 | 0.047 | FIRES | 6.99 |
| 19.6x | 0.347 | 0.050 | FIRES | 2.65 |

So the hook fires loudly on a model whose coherences are right and stays
quiet on one whose coherences are doubled. The threshold of 2 is tuned to
the single 236-fold example in the docstring. The manual
(`R/cross-wishart.R:67-71`) presents it as the thing that catches the
trap; it does not.

The vignette's own trap chunk emits the warning at ratio 25.2, so the
narrative example works. It is the surrounding claim that does not
generalize.

### S4. MINOR. A shipped degrees-of-freedom number does not reproduce

`extensions/frmtmb.coupling/R/cross-spectrum.R:84-85`:

> On an AR(1) spectrum with `phi = 0.9`, `smooth = 16` delivers 15.13
> rather than 16.

Measured at true coherence 0, where the naive estimate has mean exactly
`1/n`:

| series length | smooth | nominal | measured | bins |
| --- | --- | --- | --- | --- |
| 1024, the length `dev/xspec-findings.md` states | 8 | 8 | 7.961 | 25200 |
| 1024 | 16 | 16 | **15.909** | 12400 |
| 4096 | 8 | 8 | 7.987 | 102000 |
| 4096 | 16 | 16 | **15.991** | 50800 |

The documented loss of "about 5 percent" is about 0.6 percent. The source
table at `dev/xspec-findings.md:222-231` also reports white-noise
smoothing at nominal 16 as 15.62, which cannot be right: for white
Gaussian noise the periodogram ordinates at distinct Fourier frequencies
are exactly independent, so smoothing 16 of them buys 16. That table
looks under-replicated, and one of its numbers was promoted into the
manual.

### S5. MINOR. Vignette prose does not match what the vignette prints

`extensions/frmtmb.coupling/vignettes/coherence.Rmd:161`. The trap chunk
emits two warnings, in this order:

```
#> Warning: Large maximum absolute gradient at the optimum (0.0028); the fit may
#>   not have converged. ...
#> Warning: the fitted power model leaves 25.2 times the residual spread ...
```

The next line of prose reads "That warning is the family's `fit_check`
hook." The reader sees two and is told about one, and the first one says
the fit did not converge, which the prose never addresses.

### S6. TRIVIAL. Stale counts in the workflow comment

`.github/workflows/check-frmtmb-coupling.yaml:90-98` says "337
expectations in 113 s with NOT_CRAN, and 322 with 5 skips in 34 s
without it." Measured now: 341 with `NOT_CRAN=true`, 328 with 5 skips
without, 318 with 6 skips inside `R CMD check`. The structure of the
claim is right and the extra in-check skip is real; the numbers drifted.

### S7. TRIVIAL. The WARNING has three causes, not two

The lane named "new submission plus a 404". The check names a third:
`Strong dependencies not in the CRAN or BioC software repositories:
frmtmb`. Inherent to every extension in this repo, but it belongs in the
accounting.

---

## What was verified and holds

### (a) Diff hygiene: clean

`git diff --name-only c18253e` returns exactly `README.md`,
`_pkgdown.yml`, `dev/build-docs.R`; 8 insertions, 3 deletions, the 3
being comment rewording in `build-docs.R` ("seven" to "eight", "six" to
"seven"). Untracked: the workflow, `dev/xspec-findings.md`, and 22 files
under `extensions/frmtmb.coupling`, exactly as claimed. **No core file
changed.** Core `DESCRIPTION` lists `frmtmb.coupling` in neither
`Imports` nor `Suggests`. No `dev/*.log`, no scratch scripts, no build
products; the built tarball carries no `dev/`, no `_pkgdown.yml`, no
`.Rproj.user`. `.github/workflows/check-frmtmb-coupling.yaml` is a
faithful line-by-line adaptation of `check-frmtmb-spline.yaml`, with the
comments rewritten honestly rather than copied. README row and Extensions
menu entry follow house style; the menu insertion is alphabetical.

### (c) The likelihood: correct, and verified harder than claimed

Derived independently. For `CW_2(n, S)`, `CGamma_2(n) = pi * Gamma(n) *
Gamma(n-1)`, `det S = S11 S22 (1 - C)`, and
`tr(S^-1 W) = (S22 w11 + S11 w22 - 2 sqrt(C S11 S22)(cos(phi) w12r +
sin(phi) w12i)) / (S11 S22 (1-C))`. All three match
`R/cross-wishart.R:152-157` exactly. The `cw_dev` closed form at the
saturated `S = W/n` is also algebraically correct.

| check | result |
| --- | --- |
| lpdf vs independent complex implementation, `eigen` for det and `solve` for inverse, 200 random rows | max abs 1.6e-12, max rel 1.5e-12 |
| total mass by importance sampling, n0 = 10 to n1 = 9, 400000 draws | 0.99899, MCSE 0.00079 |
| same, n0 = 6 to n1 = 5 | 1.00101, MCSE 0.00106 |
| same, n0 = 3 to n1 = 3, S shifted | 0.99996, MCSE 0.00061 |
| same with `lgamma(n-1)` deleted, to show the test bites | 5032 |
| channel-order invariance, (S11,S22,C,phi) to (S22,S11,C,-phi) | max abs 1.6e-13 |
| parameterization identities: log power, log power, logit C, phase | 0 to 5.6e-16 |
| gradient vs numDeriv on the link scale, 3 parameter points | 2.9e-08 to 3.9e-05 |
| Hessian vs numDeriv, same points | 5.8e-09 to 5.5e-07 |

The importance-sampling test is the one that matters, because it varies
`n` between proposal and target and so tests the normalizing constant's
degrees-of-freedom dependence rather than letting it cancel.

The lane's claim that base R has no complex determinant is correct:
`det()` on a complex matrix errors with "'determinant' not currently
defined for complex matrices".

Positive definiteness at the extremes is where it fails; see S1.

### (b) The bias, reproduced

My own draw routine, 2000 replicates, 20 homogeneous subjects, true phase
0.7. "naive 1" is one subject's own coherence, "naive mean 20" is the
mean over subjects, "pooled 20" is the coherence of the summed matrix.

| true C | n | naive, 1 subject | naive mean of 20 | pooled 20 |
| --- | --- | --- | --- | --- |
| 0.0 | 2 | 0.5082 | 0.4983 | 0.0249 |
| 0.0 | 4 | 0.2512 | 0.2515 | 0.0130 |
| 0.0 | 8 | 0.1247 | 0.1252 | 0.0060 |
| 0.0 | 16 | 0.0613 | 0.0623 | 0.0032 |
| 0.0 | 32 | 0.0312 | 0.0314 | 0.0015 |
| **0.2** | **4** | **0.3646** | **0.3719** | **0.2055** |
| 0.2 | 8 | 0.2822 | 0.2834 | 0.2037 |
| 0.2 | 16 | 0.2374 | 0.2410 | 0.2022 |
| 0.5 | 4 | 0.5854 | 0.5797 | 0.5047 |
| **0.9** | **4** | **0.9007** | **0.9033** | **0.8997** |
| 0.9 | 16 | 0.9006 | 0.9010 | 0.9004 |

Confirmed, in the lane's favor:

* The headline reproduces. At true 0.2 with 4 segments the naive answer
  averages 0.372, the lane said 0.375, and the pooled model gives 0.206,
  the lane said 0.209.
* **Averaging over subjects does not help.** Bias of one subject 0.1646,
  bias of the mean of 20 subjects 0.1719. Identical within noise, exactly
  as claimed.
* At true C = 0 the naive mean is `1/n` to three digits: 0.508, 0.251,
  0.125, 0.0613, 0.0312 against 0.5, 0.25, 0.125, 0.0625, 0.03125. The
  pooled value is `1/(N n)`.
* The taped fit IS the closed-form pooled estimator, which the lane
  asserted and I confirmed: over 40 replicates, `max|frm fit - closed
  form|` was 2.9e-15 at (0.2, n=4), 8.4e-15 at (0.2, n=16), 1.1e-06 at
  (0.9, n=4), 8.5e-07 at (0.0, n=8), with no failures. True coherence 0
  does not break the optimizer, because the pooled sample coherence stays
  strictly positive.

One qualification the lane's summary should carry: **at a true coherence
of 0.9 the naive estimator is already unbiased**, +0.0007 at n = 4. The
package buys almost nothing at high coherence. The whole argument lives
at low to moderate coherence, which the lane's own findings table shows
at C = 0.8 but the summary does not say out loud.

Heterogeneous subjects, 40 subjects, `eta ~ N(0, 0.4^2)`, per-subject
powers `~ N(0, 0.3^2)`, 40 replicates, true median coherence 0.500,
random effects on all four dpars:

| sd_phi | n | naive mean | pooled / concatenated | hierarchical |
| --- | --- | --- | --- | --- |
| 0.0 | 4 | 0.5897 (+0.090) | 0.4894 (-0.011) | 0.5154 (+0.015) |
| 0.0 | 16 | 0.5141 (+0.014) | 0.4722 (-0.028) | 0.4986 (-0.001) |
| 0.8 | 4 | 0.5878 (+0.088) | **0.2632 (-0.237)** | 0.5051 (+0.005) |
| 0.8 | 16 | 0.5232 (+0.023) | **0.2729 (-0.227)** | 0.5065 (+0.007) |

**Concatenation is worse, confirmed.** With a spread of phases, pooling
reads 0.26 against a truth of 0.50, and does not improve from n = 4 to
n = 16, because it is cancellation and not variance. The hierarchical fit
with random effects on every dpar is the best of the three at every cell,
and its bias does not grow at n = 4.

### (d) Degrees of freedom, reproduced

White noise, true coherence 0, `n_eff = 1 / mean(coherence)`, 250 series
of 4096 samples each.

| configuration | nominal | measured | MCSE |
| --- | --- | --- | --- |
| `segments = 8` | 8 | 7.979 | 0.028 |
| `segments = 4, smooth = 2` | 8 | 7.993 | 0.028 |
| `segments = 2, smooth = 4` | 8 | 7.977 | 0.028 |
| `segments = 1, smooth = 8` | 8 | 7.971 | 0.028 |
| `segments = 4, tapers = 2` | 8 | 7.996 | 0.020 |
| `segments = 2, tapers = 4` | 8 | 7.982 | 0.014 |
| `segments = 1, tapers = 8` | 8 | 7.982 | 0.010 |

Every accepted route delivers its nominal count within about one MCSE.
My numbers are tighter than the lane's table, which reports 7.76 for
`segments = 2, tapers = 4`; that cell is fine.

The refused combination, computed by hand outside the guard:

| configuration | nominal | measured |
| --- | --- | --- |
| `tapers = 4, smooth = 4` | 16 | **5.770**, lane said 5.80 |
| `tapers = 2, smooth = 2` | 4 | **2.693**, lane said 2.70 |
| `segments = 2, tapers = 2, smooth = 2` | 8 | 5.220 |
| `tapers = 2, smooth = 4` | 8 | 4.133 |

The refusal at `R/cross-spectrum.R:139-146` is correct and the numbers in
its message are right.

**`tapers = 1` really is no taper.** `cp_taper_basis(N, 1)` returns a
single column of ones, `R/cross-spectrum.R:226`, and the package output
equals a plain segmented FFT to **exactly 0** across all four columns.

**The bug the lane says it fixed is real, and the 15 percent is right.**
Reintroducing "tapers = 1 means the first sine taper":

| configuration | claimed n | current code | first-sine-taper version | SE understated by |
| --- | --- | --- | --- | --- |
| `segments = 2, smooth = 4` | 8 | 7.977 | **6.035** | **15.1%** |
| `segments = 4, smooth = 2` | 8 | 7.993 | 6.646 | 9.7% |
| `segments = 8` | 8 | 7.979 | 7.999 | 0.0% |

The lane's account is exact: only in combination with smoothing does the
taper correlate neighboring bins, and nothing but an effective
degrees-of-freedom measurement would have seen it.

Refusals fire where they should: `tapers` with `smooth`, one total degree
of freedom, `segments = 0`, `tapers >= seglen`, `smooth` wider than the
band, `n < 2` in `valid_y()`, a non-positive-definite row, and a warning
below `n = 4`. Frequency zero and Nyquist are dropped: `segments = 4` on
1024 samples gives bins 1 to 127 of 256.

### (g) Suites and checks, fresh processes

Test suite, one fresh `Rscript` per run, against the source directory:

| file | expectations | fail | error | skip |
| --- | --- | --- | --- | --- |
| `test-coherence.R` | 49 | 0 | 0 | 0 |
| `test-cross-spectrum.R` | 61 | 0 | 0 | 0 |
| `test-cross-wishart.R` | 169 | 0 | 0 | 0 |
| `test-message-uniqueness.R` | 4 | 0 | 0 | 0 |
| `test-surface.R` | 58 | 0 | 0 | 0 |
| **total, `NOT_CRAN=true`** | **341** | **0** | **0** | **0** |
| total, without `NOT_CRAN` | 328 | 0 | 0 | 5 |

41 `test_that` blocks. The five `skip_on_cran()` gates guard the
simulation-heavy claims, which is house practice: spline has 13, eam 21.
Inside `R CMD check`: `FAIL 0 | WARN 1 | SKIP 6 | PASS 318`, the extra
skip being `test-message-uniqueness.R` finding no sources, exactly as the
workflow comment says.

Roxygen is idempotent: `roxygenise(clean = TRUE)` on a copy leaves `man/`
and `NAMESPACE` byte-identical to the worktree. The multi-argument
`importFrom` is genuinely what roxygen2 8.1.0 emits here, and matches the
sibling extensions.

`R CMD check --as-cran` with the manual, TinyTeX and pandoc on PATH:

```
Status: 1 WARNING
```

0 ERRORs, 0 NOTEs. `checking PDF version of manual ... OK` and
`checking HTML version of manual ... OK`, so the manual really built.
The single WARNING is `checking CRAN incoming feasibility`, with three
causes:

1. `New submission`. Expected at 0.1.0.
2. `Strong dependencies not in the CRAN or BioC software repositories:
   frmtmb`. Inherent; shared by every extension.
3. `Found the following (possibly) invalid URLs:
   https://aforren1.github.io/frmtmb/frmtmb.coupling ... Status: 404`.

**The 404 is genuinely structural, not a broken link.** Fetched live:

| URL | status |
| --- | --- |
| `.../frmtmb.learn` | 200 |
| `.../frmtmb.learn/` | 200 |
| `.../frmtmb.spline` | 200 |
| `.../frmtmb.coupling` | 404 |
| `.../frmtmb.coupling/` | 404 |

Siblings resolve with or without a trailing slash, so the trailing slash
is not the cause; the subsite simply has not been published. The URL form
in `DESCRIPTION` matches five of the six siblings. It clears when
`dev/build-docs.R` runs and gh-pages deploys.

### (h) Docs

The vignette knits and its numeric claims match its own rendered output:
naive coherence at n = 4 prints 0.393 against prose "about 0.39";
pooling prints 0.298 against a truth of 0.5; the flat power fit prints
0.468 and 0.422 against prose "calls the two bands nearly equal" while
the smooth fit prints 0.335 and 0.029; the coherence spectrum's interval
stays inside (0, 1) with `range(.lower)` 0.0024 to 0.9055 and
`range(.upper)` 0.0415 to 0.9509; every simulated draw is positive
definite. The only mismatch is S5.

23 compat rows, matching the claim: 17 for `cross_wishart`, 4 for
`frm_coherence`, 2 for `frm_cross_simulate`. Six are marked `untested`,
which is the honest third state, and `residuals_osa` names itself as the
row most likely to be wrong. `test-message-uniqueness.R` is exact house
form.

---

## Punch list

1. **S1.** Stop computing the coherence complement by subtraction.
   `R/cross-wishart.R:151` and `:172`. If core cannot hand the family the
   link-scale predictor, record THAT as the core seam and say so. Then:
   * Delete or correct the three safety claims at
     `R/cross-wishart.R:76-80`, `R/cross-wishart.R:143-144`, and in
     `DESCRIPTION` plus `vignettes/coherence.Rmd`. If a floor is added,
     the "no eigenvalue floor and no projection step" sentence goes.
   * Make `cp_link_se()`, `R/coupling.R:97`, reject a standard error that
     is zero or non-finite, not only NULL. A zero-width 95 percent
     interval must not be returned.
   * Extend the loop at `tests/testthat/test-coherence.R:41` to include
     `eta = 19`. The existing assertion `co$.estimate > co$.lower`
     already fails there, so this costs one number.
   * Add a density test at `eta_coh` of 20, 30 and 40 asserting finite
     value and finite gradient.

2. **S2.** Rewrite the p > 2 refusal at `R/cross-wishart.R:85-86` and
   `vignettes/coherence.Rmd:229` to give the real reason: p^2 predictors,
   no complex determinant on the tape, the parameterization does not
   stay this clean. Remove the core-seam record. Optionally refuse a
   matrix pair with more than one column pair by name in
   `frm_cross_spectrum()`, or say plainly in its `@param` that columns
   are units and never channels.

3. **S3.** Either re-base `cw_fit_check` on a statistic that tracks
   coherence displacement rather than power residual spread, or downgrade
   what the manual claims for it. As it stands it must not be described
   as the thing that catches the trap. At minimum, document that it is
   silent below roughly a 3-fold power spread and fires on correctly
   specified models above roughly a 20-fold one, and stop the hook firing
   when the power model already carries a frequency term.

4. **S4.** Re-measure the AR(1) smoothing loss and correct
   `R/cross-spectrum.R:84-85`, or drop the number. Re-run the
   `dev/xspec-findings.md:222-231` table with enough replicates that
   white-noise smoothing at nominal 16 returns 16.

5. **S5.** Fix the vignette prose at `vignettes/coherence.Rmd:161` to
   account for both warnings, and either silence or explain the
   convergence warning on the flat fit.

6. **S6, S7.** Refresh the counts in the workflow comment, 341 / 328 /
   318, and add the third WARNING cause to the lane's accounting.

Items 1 to 3 block. Items 4 to 6 can ride along.

---

# Re-check, 2026-09-08

Second round after the lane reported all three blockers fixed. Everything
below was re-measured by running, in fresh processes, against a
reinstalled core and extension. Neither tree modified except this file.

**Verdict: MERGE**, subject to one single-line deletion in a dev-only
document, R1 below, that does not need another review round.

## S1, the complement: FIXED

`cw_complement()` at `R/cross-wishart.R:210` reads core's `.eta_coh` and
returns `log(1 - C)` as `-logspace_add(0, eta)`. No floor was added, so
the "no eigenvalue floor and no projection step" property survives.

Re-ran my own round-1 reproductions against an independently written
stable reference, `log(1-C) = -(eta + log1p(exp(-eta)))`:

| eta_coh | `cw_lpdf` on the tape | stable reference | relative error |
| --- | --- | --- | --- |
| 20 | -7762521 | -7762521 | **0.00e+00** |
| 30 | -1.70984e+11 | -1.70984e+11 | **0.00e+00** |
| 36.74 | -1.44577e+14 | -1.44577e+14 | **0.00e+00** |
| 40 | -3.76616e+15 | -3.76616e+15 | **0.00e+00** |
| 100 | -4.30099e+41 | -4.30099e+41 | **0.00e+00** |
| 700 | -1.62277e+302 | -1.62277e+302 | **0.00e+00** |
| 708 | -4.83741e+305 | -4.83741e+305 | **0.00e+00** |

Not merely finite: bit-exact against the reference at every point, where
round 1 was NaN from 36.74 up and wrong in the second digit at 36. The
RTMB tape returns a finite derivative at all of them, including 700.

The zero-width interval is now impossible. The exact round-1 case, two
signals differing by 1e-5 of noise, which previously returned
`.se = 0` and `.lower == .estimate == .upper`:

```
noise=1e-05 eta=20.7170  frm_coherence REFUSED:
  the standard error of `coh` is zero or negative in 1 of 1 rows,
  so no interval exists for them.
```

`cp_link_se()` at `R/coupling.R:108` now tests
`!is.finite(p$se.fit) | p$se.fit <= 0` and stops by name. At noise 1e-3 a
real interval of width 1.8e-07 still comes back, so the guard refuses
degeneracy rather than refusing the tail.

My round-1 nine-group near-unit-coherence ladder, re-run and pushed
harder:

| top group true C | fitted eta | logLik | interval | residuals finite |
| --- | --- | --- | --- | --- |
| 0.99 | 4.613 | -489.8719 | 0.987893 to 0.992027 | yes |
| 1 - 1e-06 | 13.812 | -393.3402 | positive width | yes |
| 1 - 1e-10 | 23.191 | -286.5924 | positive width | yes |
| 1 - 1e-13 | 29.325 | -660.9267 | positive width | yes |
| 1 - 1e-15 | n/a | optimizer error, named | n/a | n/a |

Round 1 returned NaN standard errors silently at eta 34.03. The last row
now fails loudly instead: "The optimizer failed on this model
(cross_wishart, ML, nlminb): NA/NaN". A genuinely degenerate model
failing by name is the right outcome and a clear improvement.

**One residual, not a blocker.** The off-tape fallback branch at
`R/cross-wishart.R:214` still forms `inv = 1 / (1 - ch)` by subtraction,
and `log1p(-ch)` carries the same cancellation as `log(1 - ch)` when `ch`
is near 1, because `log1p` only helps for small arguments. Measured on
that branch: relative error 1.0e-03 at eta 30, 4.5e-02 at eta 36, and
**NaN at eta 36.74 and above** for both `cw_lpdf` and `cw_dev`.

It is not reachable in practice, which I checked rather than assumed:
`logLik`, `AIC`, `fitted`, `residuals` and `predict` all return finite
values on a fitted model, `simulate` refuses with its stated message, and
the optimizer errors out before a fit can land past 36.74. The lane
documents the branch and its 36.74 ceiling honestly at
`R/cross-wishart.R:203-207`. Worth tightening one day; not worth holding
the merge.

## The lane's pushback on my `eta = 19` item: ACCEPTED, and it is right

The lane says its `cp_units()` draw helper loses the matrix determinant
to rounding above about eta 17, so the fit-level loop stops at 16. That is
correct about the helper. It is not correct that such a fit is
unconstructible, and I checked: the signal route reaches it with every
row determinant strictly positive.

| noise | min row determinant | all determinants > 0 | fitted eta | residuals finite |
| --- | --- | --- | --- | --- |
| 3e-05 | 1.50e-07 | yes | 20.1285 | yes |
| 1e-05 | 1.96e-08 | yes | 20.7170 | yes |
| 5e-06 | 3.86e-09 | yes | 18.9803 | yes |

But the lane already covers this. `test-coherence.R:72`, "an interval
near a coherence of 1 has positive width", builds its data with
`frm_cross_spectrum(src, src + rnorm(4096, 0, 1e-5))`, which is the same
route, and asserts the right invariant: either a positive-width interval
inside (0, 1) or a refusal naming "no interval exists", never a point.
That is a better test than the one I asked for, in a better place. My
punch item is satisfied; my suggested location was the wrong one.

## S2, the false blame on core: FIXED, with one survivor

Withdrawn in the shipped documentation. `R/cross-wishart.R:124` now says
"**core is not the obstacle**: `frm()` carries a matrix-valued response,
and both a gaussian fit and a custom family indexing `y[, 1]` and
`y[, 2]` work today. What is missing is here rather than there", and
names the real reasons. `vignettes/coherence.Rmd:285-291` says the same.
Section 7 of `dev/xspec-findings.md` withdraws the seam explicitly.

The replacement seam is real, and I verified it in core rather than
taking it on trust:

* `R/objective.R:327` and `R/objective.R:357` store
  `dparv[[resp]][[paste0(".eta_", dpar)]] <- eta`.
* `R/families.R:426-465` carries four accessors built on it:
  `robust_logit()`, `robust_logmu()`, `log_dpar()`, `gate_logs()`.
* All four are `@noRd`. None appears in core's `NAMESPACE`.
* `gate_logs()` at `R/families.R:458` returns `l1m = log1m_inv_logit(e)`
  at `R/families.R:464`, which is exactly what `cw_complement()` needed
  and had to reimplement.
* Core's own comment at `R/families.R:409-418` names the identical
  hazard: "plogis(40) is exactly 1, so `1 - mu` is exactly 0 and a
  binomial log-density is -Inf where the truth is -40, with a gradient of
  NaN."

So core solved this problem for its own families and never exposed the
solution. The seam record is well founded and the recommendation to make
a promise is right.

### R1. The only thing still to fix

`dev/xspec-findings.md:581-583`, in section 8, still reads:

> * **More than two channels.** The arithmetic is checked at `p = 4`; the
>   frame is what blocks it. Recorded as a core seam above rather than
>   worked around.

That is the withdrawn claim, still asserted, and it points at section 7
for a seam record section 7 now retracts. It is the one sentence left in
the repository that would still send a lane after a core gap that does
not exist. It is dev-only and `.Rbuildignore`d, so it ships to nobody,
but recording seams for sibling lanes is precisely what this file is for.
Delete or restate those three lines. No other survivor: a grep for
"frame is what blocks", "frame does not carry" and "does not carry"
across `dev/xspec-findings.md` and the whole extension returns this line
and nothing else.

## S3, the hook: WITHDRAWN, and the replacement verified at slopes I chose

`cross_wishart()$post$fit_check` is NULL and `cw_fit_check` no longer
exists in the namespace. The docstring at `R/cross-wishart.R:56-86`
explains the withdrawal using my round-1 numbers and says a check that
punishes correct models teaches users to ignore it.

I picked my own slopes rather than re-running theirs. Truth: low band
0.35, high band 0.05.

| power spread | flat powers report | smooth powers report | delta AIC | AIC picks |
| --- | --- | --- | --- | --- |
| 1.0x | 0.341, 0.053 | 0.339, 0.054 | -7.5 | flat, correct |
| 1.2x | 0.328, 0.056 | 0.339, 0.054 | -1.1 | tie |
| 1.5x | 0.308, 0.063 | 0.339, 0.054 | 57.0 | rejects flat |
| 2.2x | 0.283, 0.080 | 0.339, 0.054 | 273.9 | rejects flat |
| **2.7x** | **0.273, 0.092** | 0.339, 0.054 | **438.9** | **rejects flat** |
| 3.7x | 0.260, 0.117 | 0.339, 0.054 | 754.5 | rejects flat |
| 12.1x | 0.236, 0.349 | 0.339, 0.054 | 2701.8 | rejects flat |
| 88.4x | 0.231, 0.737 | 0.339, 0.054 | 7387.8 | rejects flat |
| 2887x | 0.236, 0.953 | 0.339, 0.054 | 17897.4 | rejects flat |

**AIC catches both spreads where the withdrawn hook was silent**: 2.7x by
438.9 and 1.6x by 97.0. That was the specific failure I punched for.

**And it stays quiet on a correct model**, which is the half that matters
more. True spectrum flat, six seeds:

| seed | flat model reports | delta AIC | outcome |
| --- | --- | --- | --- |
| 1 | 0.344, 0.052 | +3.00 | prefers smooth |
| 2 | 0.369, 0.042 | -7.33 | keeps flat |
| 3 | 0.340, 0.057 | -7.97 | keeps flat |
| 4 | 0.363, 0.041 | -4.36 | keeps flat |
| 5 | 0.341, 0.053 | -7.55 | keeps flat |
| 6 | 0.349, 0.066 | -6.85 | keeps flat |

Five of six keep the flat model. The sixth prefers the smooth one by 3.0,
which is ordinary AIC behavior near the null with a penalized smooth, and
the consequence is benign: following the guidance there reads 0.339 and
0.054 off the smooth fit instead of 0.344 and 0.052 off the flat one, and
both are right. That is the decisive difference from the hook, whose
false alarms told users their correct model was too simple.

## S4, the AR(1) degrees-of-freedom number: FIXED, re-measured independently

A wrong number reached the manual once, so I re-measured rather than
reading the correction. 400 replicates of 4096 samples, every bin pooled,
true coherence 0, with a Monte Carlo standard error:

| configuration | nominal | measured | MCSE | bins |
| --- | --- | --- | --- | --- |
| white, `smooth = 16` | 16 | 15.863 | 0.066 | 50800 |
| **AR(1) 0.9, `smooth = 16`** | 16 | **16.014** | 0.067 | 50800 |
| white, `smooth = 8` | 8 | 7.977 | 0.022 | 102000 |
| AR(1) 0.9, `smooth = 8` | 8 | 8.019 | 0.022 | 102000 |
| white, `segments = 16` | 16 | 15.894 | 0.066 | 50800 |
| AR(1) 0.9, `segments = 16` | 16 | 15.921 | 0.066 | 50800 |

The AR(1) figure is not below the white one; if anything it sits a hair
above. There is no systematic smoothing penalty on a sloped spectrum at
this configuration, so the withdrawn "about 5 percent" was noise, exactly
as the lane now says. My 16.014 and their 16.069 agree within one MCSE.
The lane states plainly in the findings doc that the old wrong number had
reached the manual, which is the right way to record it.

## S5, S6, S7

S5 is moot: the hook is gone, so the vignette's "That warning is the
family's `fit_check` hook" is gone with it, replaced by an AIC comparison
whose output the prose matches. The hook survives in the vignette only in
the past tense, as a withdrawn draft. S6 and S7 are folded into the
counts below.

## Counts, re-measured

| measurement | result |
| --- | --- |
| suite, `NOT_CRAN=true`, fresh process | **388 expectations, 0 failures, 0 errors, 0 skipped**, 46 blocks |
| by file | coherence 61, cross-spectrum 61, cross-wishart 203, message-uniqueness 4, surface 59 |
| inside `R CMD check` | FAIL 0, WARN 1, SKIP 6, PASS 365 |
| roxygen idempotent | `man/` and `NAMESPACE` byte-identical after `roxygenise(clean = TRUE)` on a copy |
| `R CMD check --as-cran`, with manual | **1 WARNING, 0 NOTEs, 0 ERRORs** |
| PDF and HTML manual | both OK |
| vignette rebuild inside check | OK |
| RTMB genuinely used | `RTMB::logspace_add` at `R/cross-wishart.R:216`, plus `importFrom(RTMB,logspace_add)` |
| core files touched | none; core `DESCRIPTION` still lists the extension nowhere |
| files under `extensions/frmtmb.coupling` | 22 |

The lane reported 384 expectations; I measure 388, the same small drift as
round 1 and of no consequence. The single WARNING is unchanged and still
has the three causes named in round 1: new submission, `frmtmb` not on
CRAN, and the structural 404 on the unpublished pkgdown subsite.

## Verdict

**MERGE.** All three blockers are genuinely fixed, and I confirmed each by
running rather than by reading. S1's fix is exact rather than merely
finite and adds no floor. S2's retraction is unambiguous in every shipped
file, and the seam it puts in place of the false one is real, verified in
core, and worth acting on. S3 was withdrawn rather than retuned, and its
replacement passes both halves of the test at slopes I chose myself,
including the half the hook failed. S4 was re-measured from scratch and
holds.

One item outstanding: delete or restate `dev/xspec-findings.md:581-583`,
which still asserts the retracted claim in a document whose purpose is
recording seams. One line, no re-review needed.
