# GENERATED by dev/conditions-ext-tests.R in the frmtmb repository.
#
# brms raises every refusal as a `brms_error`; frmtmb keeps the same
# contract with `frmtmb_error` (?frmtmb::frmtmb-conditions). A refusal
# that this package raises also carries its own subclass,
# `frmtmb_ode_error`, so a caller can catch every frmtmb refusal or
# only the refusals of this package. The census in
# test-conditions-census.R keeps every call site on the helpers; this
# asserts that a real refusal arrives with the classes.

test_that("a frmtmb.ode refusal is caught as a frmtmb_error", {
  ev <- data.frame(time = 2, state = "depot", value = 100,
                   method = "replace")
  refuse <- function() {
    frm_lincmt(parms = list(ka = 1.1, ke = 0.2, V = 10),
               times = c(0, 1, 2, 4), ncmt = 1,
               depot = TRUE, events = ev)
  }
  e <- tryCatch(refuse(), frmtmb_error = function(e) e)
  expect_identical(class(e), c("frmtmb_ode_error", "frmtmb_error", "error",
                               "condition"))
  expect_match(conditionMessage(e), "replace rows", fixed = TRUE)
  # and by its own subclass alone
  expect_s3_class(tryCatch(refuse(), frmtmb_ode_error = function(e) e),
                  "frmtmb_ode_error")
})

test_that("the refusals classed in punch round 1 carry the subclass", {
  # an argument refused by frm_match_arg(), and a refusal this package
  # wrote that another package raises, which is the case the subclass
  # used to miss
  cases <- list(
    output = quote(frm_lincmt(parms = list(ke = 0.2, V = 10), times = 1:5,
               output = "bogus")),
    on_error = quote(frm_ode(function(t, y, p) list(-y[[1]]), init = list(1),
            times = 1:3, on_error = "bogus")))
  n <- 0L
  for (nm in names(cases)) {
    e <- tryCatch(eval(cases[[nm]]), error = identity)
    expect_identical(class(e)[1:3], c("frmtmb_ode_error", "frmtmb_error",
                                      "error"), label = nm)
    n <- n + 1L
  }
  # the loop asserted once per case, not over nothing
  expect_identical(n, 2L)
})

