# GENERATED by dev/brmsport-gen.R from brms 2.23.0
# tests/testthat/tests.brmsfit-methods.R. Do not edit by hand: change
# dev/brmsport-verdicts.tsv or the generator, then regenerate.
# helper-brms-suite.R says what brms_port() asserts.

skip_unless_brms_suite()
skip_sampler()
expect_range <- function(object, lower = -Inf, upper = Inf, ...) {
  testthat::expect_true(all(object >= lower & object <= upper), ...)
}
expect_ggplot <- function(object, ...) {
  testthat::expect_true(is(object, "ggplot"), ...)
}
SM <- suppressMessages
SW <- suppressWarnings
epilepsy <- brms::epilepsy
rename_pars <- brms_shim_rename_pars
update <- brms_shim_update
nobs <- 40
npatients <- 10
nsubjects <- 8
nvisits <- 4
fit1 <- brms_fixture_draws(1)
fit2 <- brms_fixture_draws(2)
fit3 <- brms_fixture_draws(3)
fit5 <- brms_fixture_draws(5)

test_that("as_draws and friends have resonable outputs", {
  brms_setup("brmsfit-methods:31",
    draws <- as_draws(fit1, variable = "b_Intercept")
  )
  brms_port("brmsfit-methods:32", "pass",
    "",
    expect_s3_class(draws, "draws_list")
  )
  brms_port("brmsfit-methods:33", "pass",
    "",
    expect_equal(variables(draws), "b_Intercept")
  )
  brms_port("brmsfit-methods:34", "pass",
    "",
    expect_equal(ndraws(draws), ndraws(fit1))
  )
  brms_setup("brmsfit-methods:36",
    draws <- SM(as_draws_matrix(fit1))
  )
  brms_port("brmsfit-methods:37", "pass",
    "",
    expect_s3_class(draws, "draws_matrix")
  )
  brms_port("brmsfit-methods:38", "pass",
    "",
    expect_equal(ndraws(draws), ndraws(fit1))
  )
  brms_setup("brmsfit-methods:40",
    draws <- as_draws_array(fit2)
  )
  brms_port("brmsfit-methods:41", "pass",
    "",
    expect_s3_class(draws, "draws_array")
  )
  brms_port("brmsfit-methods:42", "pass",
    "",
    expect_equal(niterations(draws), ndraws(fit2))
  )
  brms_setup("brmsfit-methods:44",
    draws <- as_draws_df(fit2, variable = "^b_", regex = TRUE)
  )
  brms_port("brmsfit-methods:45", "pass",
    "",
    expect_s3_class(draws, "draws_df")
  )
  brms_port("brmsfit-methods:46", "pass",
    "",
    expect_true(all(grepl("^b_", variables(draws))))
  )
  brms_setup("brmsfit-methods:48",
    draws <- as_draws_list(fit2)
  )
  brms_port("brmsfit-methods:49", "pass",
    "",
    expect_s3_class(draws, "draws_list")
  )
  brms_port("brmsfit-methods:50", "pass",
    "",
    expect_equal(nchains(draws), nchains(fit2))
  )
  brms_setup("brmsfit-methods:52",
    draws <- as_draws_rvars(fit3)
  )
  brms_port("brmsfit-methods:53", "pass",
    "",
    expect_s3_class(draws, "draws_rvars")
  )
  brms_port("brmsfit-methods:54", "pass",
    "",
    expect_equal(ndraws(draws), ndraws(fit3))
  )
  brms_port("brmsfit-methods:55", "pass",
    "",
    expect_true(length(variables(draws)) > 0)
  )
})

test_that("as.data.frame has reasonable ouputs", {
  brms_setup("brmsfit-methods:59",
    draws <- as.data.frame(fit1)
  )
  brms_port("brmsfit-methods:60", "pass",
    "",
    expect_true(is(draws, "data.frame"))
  )
  brms_port("brmsfit-methods:61", "pass",
    "",
    expect_equal(dim(draws), c(ndraws(fit1), length(variables(fit1))))
  )
  brms_port("brmsfit-methods:64", "pass",
    "",
    expect_warning(
      draws <- as.data.frame(fit1, pars = "^b_"),
      "'pars' is deprecated"
    )
  )
  brms_port("brmsfit-methods:68", "pass",
    "",
    expect_s3_class(draws, "data.frame")
  )
  brms_port("brmsfit-methods:69", "pass",
    "",
    expect_true(ncol(draws) > 0)
  )
  brms_port("brmsfit-methods:72", "pass",
    "",
    expect_warning(
      draws <- as.data.frame(fit1, subset = 10:20),
      "'subset' is deprecated"
    )
  )
  brms_port("brmsfit-methods:76", "pass",
    "",
    expect_s3_class(draws, "data.frame")
  )
  brms_port("brmsfit-methods:77", "pass",
    "",
    expect_equal(nrow(draws), 11)
  )
})

test_that("as.matrix has reasonable ouputs", {
  brms_setup("brmsfit-methods:81",
    draws <- as.matrix(fit1, iteration = 1:10)
  )
  brms_port("brmsfit-methods:82", "defect",
    paste0(
      "as.matrix() of draws refuses brms's iteration argument by ",
      "name"),
    expect_true(is(draws, "matrix"))
  )
  brms_port("brmsfit-methods:83", "defect",
    paste0(
      "as.matrix() of draws refuses brms's iteration argument by ",
      "name"),
    expect_equal(dim(draws), c(10, length(variables(fit1))))
  )
})

test_that("as.array has reasonable ouputs", {
  brms_setup("brmsfit-methods:87",
    draws <- as.array(fit1)
  )
  brms_port("brmsfit-methods:88", "pass",
    "",
    expect_true(is.array(draws))
  )
  brms_setup("brmsfit-methods:89",
    chains <- fit1$fit@sim$chains
  )
  brms_setup("brmsfit-methods:90",
    ps_dim <- c(niterations(fit1), chains, length(variables(fit1)))
  )
  brms_port("brmsfit-methods:91", "cannot transfer",
    paste0(
      "reads fit1$fit@sim$chains, the stanfit slot (D10); ",
      "frmtmb.sample keeps it in x$stanfit"),
    expect_equal(dim(draws), ps_dim)
  )
  brms_setup("brmsfit-methods:93",
    draws <- as.array(fit1, chain = 1)
  )
  brms_port("brmsfit-methods:94", "defect",
    "as.array() of draws refuses brms's chain argument by name",
    expect_true(is.array(draws))
  )
  brms_setup("brmsfit-methods:95",
    ps_dim <- c(niterations(fit1), 1, length(variables(fit1)))
  )
  brms_port("brmsfit-methods:96", "defect",
    "as.array() of draws refuses brms's chain argument by name",
    expect_equal(dim(draws), ps_dim)
  )
})

test_that("as.mcmc has reasonable ouputs", {
  brms_setup("brmsfit-methods:100",
    chains <- fit1$fit@sim$chains
  )
  brms_setup("brmsfit-methods:101",
    mc <- SW(as.mcmc(fit1))
  )
  brms_port("brmsfit-methods:102", "cannot transfer",
    "reads fit1$fit@sim$chains, the stanfit slot (D10)",
    expect_equal(length(mc), chains)
  )
  brms_port("brmsfit-methods:103", "cannot transfer",
    "reads fit1$fit@sim$chains, the stanfit slot (D10)",
    expect_equal(dim(mc[[1]]), c(ndraws(fit1)/chains, length(variables(fit1))))
  )
  brms_setup("brmsfit-methods:104",
    mc <- SW(as.mcmc(fit1, combine_chains = TRUE))
  )
  brms_port("brmsfit-methods:105", "pass",
    "",
    expect_equal(dim(mc), c(ndraws(fit1), length(variables(fit1))))
  )
  brms_port("brmsfit-methods:107", "cannot transfer",
    paste0(
      "as.mcmc(inc_warmup = TRUE): frm_sample() stores no warmup, ",
      "a recorded gap (dev/brms-api-diff.md (c), 'Blocked, not ",
      "small'), not a decision"),
    expect_equal(dim(SW(as.mcmc(fit1, inc_warmup = TRUE)[[1]])),
                 c(fit1$fit@sim$iter, length(variables(fit1))))
  )
})

test_that("ndraws and friends have reasonable ouputs", {
  brms_port("brmsfit-methods:578", "pass",
    "",
    expect_equal(ndraws(fit1), 25)
  )
  brms_port("brmsfit-methods:579", "pass",
    "",
    expect_equal(nchains(fit1), 1)
  )
  brms_port("brmsfit-methods:580", "pass",
    "",
    expect_equal(niterations(fit1), 25)
  )
})

test_that("nsamples has reasonable ouputs", {
  brms_port("brmsfit-methods:593", "defect",
    paste0(
      "nsamples() is refused as a deprecated spelling (frmtmb ",
      "NEWS, ?frmtmb-draws-refusals); brms keeps it live, and that ",
      "refusal predates the user's 2026-09-15 rule that ",
      "frmtmb.sample matches brms"),
    expect_equal(SW(nsamples(fit1)), 25)
  )
  brms_port("brmsfit-methods:594", "defect",
    paste0(
      "nsamples() is refused as a deprecated spelling (see ",
      "brmsfit-methods:593)"),
    expect_equal(SW(nsamples(fit1, subset = 10:1)), 10)
  )
  brms_port("brmsfit-methods:595", "defect",
    paste0(
      "nsamples() is refused as a deprecated spelling; incl_warmup ",
      "would also meet D6"),
    expect_equal(SW(nsamples(fit1, incl_warmup = TRUE)), 75)
  )
})

test_that("pairs has reasonable outputs", {
  brms_port("brmsfit-methods:599", "pass",
    "",
    expect_s3_class(SW(pairs(fit1, variable = variables(fit1)[1:3])),
                    "bayesplot_grid")
  )
})

test_that("posterior_average has reasonable outputs", {
  brms_setup("brmsfit-methods:617",
    pnames <- c("b_Age", "nu")
  )
  brms_setup("brmsfit-methods:618",
    draws <- posterior_average(fit1, fit1, variable = pnames, weights = c(0.3, 
        0.7))
  )
  brms_port("brmsfit-methods:619", "cannot transfer",
    "frmtmb.sample has no posterior_average()",
    expect_equal(dim(draws), c(ndraws(fit1), 2))
  )
  brms_port("brmsfit-methods:620", "cannot transfer",
    "frmtmb.sample has no posterior_average()",
    expect_equal(names(draws), pnames)
  )
  brms_setup("brmsfit-methods:622",
    weights <- rexp(3)
  )
  brms_setup_not_run("brmsfit-methods:623", "draws")
  # draws <- brms:::SW(posterior_average(
  #     fit1, fit2, fit3, variable = "nu", weights = rexp(3),
  #     missing = 1, ndraws = 10
  #   ))
  brms_port("brmsfit-methods:627", "cannot transfer",
    paste0(
      "frmtmb.sample has no posterior_average(), and brms wraps ",
      "the call in brms:::SW"),
    expect_equal(dim(draws), c(10, 1))
  )
  brms_port("brmsfit-methods:628", "cannot transfer",
    "frmtmb.sample has no posterior_average()",
    expect_equal(names(draws), "nu")
  )
})

test_that("posterior_samples has reasonable outputs", {
  brms_setup("brmsfit-methods:632",
    draws <- SW(posterior_samples(fit1))
  )
  brms_port("brmsfit-methods:633", "defect",
    paste0(
      "posterior_samples() is refused as a deprecated spelling ",
      "(see brmsfit-methods:593)"),
    expect_equal(dim(draws), c(ndraws(fit1), length(variables(fit1))))
  )
  brms_port("brmsfit-methods:634", "defect",
    "posterior_samples() is refused as a deprecated spelling",
    expect_equal(names(draws), variables(fit1))
  )
  brms_port("brmsfit-methods:635", "defect",
    "posterior_samples() is refused as a deprecated spelling",
    expect_equal(names(SW(posterior_samples(fit1, pars = "^b_"))),
                 c("b_Intercept", "b_sigma_Intercept", "b_Trt1",
                   "b_Age", "b_volume", "b_Trt1:Age", "b_sigma_Trt1"))
  )
  brms_setup("brmsfit-methods:640",
    draws <- SW(posterior_samples(fit1$fit, "^b_Intercept$"))
  )
  brms_port("brmsfit-methods:641", "cannot transfer",
    "posterior_samples() on fit1$fit, the stanfit (D10)",
    expect_equal(dim(draws), c(ndraws(fit1), 1))
  )
})

test_that("posterior_summary has reasonable outputs", {
  brms_setup("brmsfit-methods:645",
    draws <- posterior_summary(fit1, variable = "^b_", regex = TRUE)
  )
  brms_port("brmsfit-methods:646", "pass",
    "",
    expect_equal(dim(draws), c(7, 4))
  )
})

test_that("posterior_interval has reasonable outputs", {
  brms_port("brmsfit-methods:650", "pass",
    "",
    expect_equal(dim(posterior_interval(fit1)),
                 c(length(variables(fit1)), 2))
  )
})

test_that("posterior_predict has reasonable outputs", {
  brms_port("brmsfit-methods:655", "pass",
    "",
    expect_equal(dim(posterior_predict(fit1)),
                 c(ndraws(fit1), nobs(fit1)))
  )
})

test_that("posterior_linpred has reasonable outputs", {
  brms_port("brmsfit-methods:660", "pass",
    "",
    expect_equal(dim(posterior_linpred(fit1)),
                 c(ndraws(fit1), nobs(fit1)))
  )
})

test_that("posterior_epred has reasonable outputs", {
  brms_port("brmsfit-methods:708", "pass",
    "",
    expect_equal(dim(posterior_epred(fit1)), c(ndraws(fit1), nobs(fit1)))
  )
  brms_setup("brmsfit-methods:711",
    pe <- posterior_epred(fit1, point_estimate = "median",
                          ndraws_point_estimate = 2)
  )
  brms_port("brmsfit-methods:713", "defect",
    paste0(
      "posterior_epred() ignores brms's point_estimate = 'median' ",
      "and ndraws_point_estimate = 2 and returns all 25 draws, 25 ",
      "x 40, where brms returns 2 x 40. Ignoring an UNKNOWN ",
      "argument is brms parity: brms also returns 25 x 40 for ",
      "not_an_argument = 2 (dev/brmsport-defects.R S1)"),
    expect_equal(nrow(pe), 2)
  )
  brms_port("brmsfit-methods:714", "defect",
    paste0(
      "as brmsfit-methods:713: the point estimate brms repeats is ",
      "never computed, so the rows differ"),
    expect_true(all(pe[1, ] == pe[2, ]))
  )
})

test_that("pp_mixture has reasonable outputs", {
  brms_port("brmsfit-methods:718", "pass",
    "",
    expect_equal(dim(pp_mixture(fit5)), c(nobs(fit5), 4, 2))
  )
  brms_port_own("brmsfit-methods:719",
    "needs a mixture[(][)] family fit",
    paste0(
      "brms: Method 'pp_mixture' can only be applied to mixture ",
      "models"),
    expect_error(pp_mixture(fit1),
                 "Method 'pp_mixture' can only be applied to mixture models"
    )
  )
})

test_that("predictive_error has reasonable outputs", {
  brms_port("brmsfit-methods:779", "pass",
    "",
    expect_equal(dim(predictive_error(fit1)),
                 c(ndraws(fit1), nobs(fit1)))
  )
})

test_that("prior_draws has reasonable outputs", {
  brms_setup("brmsfit-methods:788",
    prs1 <- prior_draws(fit1)
  )
  brms_setup("brmsfit-methods:789",
    prior_names <- c(
      "Intercept", "b", paste0("simo_moExp1[", 1:4, "]"), "bsp",
      "bs", "sds_sAge", "b_sigma", "Intercept_sigma", "nu",
      "sd_visit", "cor_visit"
    )
  )
  brms_port("brmsfit-methods:794", "cannot transfer",
    paste0(
      "frmtmb.sample stores no prior draws, brms's sample_prior ",
      "(D10)"),
    expect_equal(colnames(prs1), prior_names)
  )
  brms_setup("brmsfit-methods:796",
    prs2 <- prior_draws(fit1, variable = "b_Trt1")
  )
  brms_port("brmsfit-methods:797", "cannot transfer",
    "frmtmb.sample stores no prior draws (D10)",
    expect_equal(dimnames(prs2), list(as.character(1:ndraws(fit1)), "b_Trt1"))
  )
  brms_port("brmsfit-methods:798", "cannot transfer",
    "frmtmb.sample stores no prior draws (D10)",
    expect_equal(sort(prs1$b), sort(prs2$b_Trt))
  )
  brms_setup("brmsfit-methods:801",
    prs <- prior_draws(fit1$fit, variable = "^sd_visit", regex = TRUE)
  )
  brms_port("brmsfit-methods:802", "cannot transfer",
    paste0(
      "prior_draws() on fit1$fit, the stanfit, and no prior draws ",
      "(D10)"),
    expect_equal(names(prs), "prior_sd_visit")
  )
})
