# GENERATED by dev/conditions-ext-tests.R in the frmtmb repository.
#
# brms raises every refusal as a `brms_error`; frmtmb keeps the same
# contract with `frmtmb_error` (?frmtmb::frmtmb-conditions). A refusal
# that this package raises also carries its own subclass,
# `frmtmb_eam_error`, so a caller can catch every frmtmb refusal or
# only the refusals of this package. The census in
# test-conditions-census.R keeps every call site on the helpers; this
# asserts that a real refusal arrives with the classes.

test_that("a frmtmb.eam refusal is caught as a frmtmb_error", {
  refuse <- function() {
    wiener()$links[["ndt"]]$linkinv(0)
  }
  e <- tryCatch(refuse(), frmtmb_error = function(e) e)
  expect_identical(class(e), c("frmtmb_eam_error", "frmtmb_error", "error",
                               "condition"))
  expect_match(conditionMessage(e), "bound is not set yet", fixed = TRUE)
  # and by its own subclass alone
  expect_s3_class(tryCatch(refuse(), frmtmb_eam_error = function(e) e),
                  "frmtmb_eam_error")
})

test_that("the refusals classed in punch round 1 carry the subclass", {
  # an argument refused by frm_match_arg(), and a refusal this package
  # wrote that another package raises, which is the case the subclass
  # used to miss
  cases <- list(
    tridiagonal = quote(gddm_control(tridiagonal = "bogus")),
    lapse = quote(gddm(lapse = "bogus")),
    lapse_simulate = quote(gddm_simulate(10, lapse = "bogus")),
    dec_needed = quote(frm(bf(rt ~ 1, bias = 0.5), family = wiener(),
        data = data.frame(rt = c(0.4, 0.5, 0.6)))))
  n <- 0L
  for (nm in names(cases)) {
    e <- tryCatch(eval(cases[[nm]]), error = identity)
    expect_identical(class(e)[1:3], c("frmtmb_eam_error", "frmtmb_error",
                                      "error"), label = nm)
    n <- n + 1L
  }
  # the loop asserted once per case, not over nothing
  expect_identical(n, 4L)
})

