.libPaths(c('C:/Users/adf44/source/r/rellib-r3', 'C:/Users/adf44/source/r/pinlib', 'C:/Users/adf44/AppData/Local/R/win-library/4.6'))

suppressPackageStartupMessages({
  library(frmtmb); library(frmtmb.eam); library(frmtmb.ode)
  library(frmtmb.spline); library(frmtmb.latent); library(frmtmb.learn)
  library(frmtmb.coupling); library(frmtmb.sample)
})
options(frmtmb.notices = TRUE, width = 80)
set.seed(20260917)
d <- data.frame(y = rnorm(60), x = rnorm(60), z = rnorm(60),
                g = factor(rep(1:10, each = 6)),
                one = factor(rep("a", 60)), obs = factor(1:60))
d$n <- rep(10L, 60); d$k <- rbinom(60, 10, 0.4)
d$yb <- rbinom(60, 1, 0.5)
d$day <- as.Date("2020-01-01") + 0:59
d$w <- ifelse(seq_len(60) %% 7 == 0, NA, d$x)
fg <- frm(y ~ x, data = d, family = gaussian())
fb <- frm(k | trials(n) ~ x, data = d, family = binomial())
fm <- frm(y ~ x + (1 | g), data = d, family = gaussian())
fsig <- frm(bf(y ~ x, sigma ~ z), data = d, family = gaussian())
dat_rt <- data.frame(rt = 0.5 + rexp(40), upper = rbinom(40, 1, 0.5))
p64x <- rnorm(64); p64y <- rnorm(64)

cat('\n#### frm_family_unknown\n', file = stderr()); cat('\n#### frm_family_unknown\n')
print(tryCatch({frm(y ~ x, data = d, family = "not_a_family"); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm(y ~ x, data = d, family = "not_a_family"), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### frm_missing_var\n', file = stderr()); cat('\n#### frm_missing_var\n')
print(tryCatch({frm(y ~ nope, data = d, family = gaussian()); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm(y ~ nope, data = d, family = gaussian()), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### frm_start_unknown\n', file = stderr()); cat('\n#### frm_start_unknown\n')
print(tryCatch({frm(y ~ x, data = d, start = list(bogus = 1)); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm(y ~ x, data = d, start = list(bogus = 1)), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### frm_start_len\n', file = stderr()); cat('\n#### frm_start_len\n')
print(tryCatch({frm(y ~ x, data = d, start = list(beta = 1:5)); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm(y ~ x, data = d, start = list(beta = 1:5)), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### frm_trials_missing\n', file = stderr()); cat('\n#### frm_trials_missing\n')
print(tryCatch({frm(k ~ x, data = d, family = binomial()); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm(k ~ x, data = d, family = binomial()), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### frm_empty_data\n', file = stderr()); cat('\n#### frm_empty_data\n')
print(tryCatch({frm(y ~ x, data = d[0, ], family = gaussian()); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm(y ~ x, data = d[0, ], family = gaussian()), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### frm_reml_nl\n', file = stderr()); cat('\n#### frm_reml_nl\n')
print(tryCatch({frm(bf(y ~ a * x, a ~ 1, nl = TRUE), data = d, REML = TRUE); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm(bf(y ~ a * x, a ~ 1, nl = TRUE), data = d, REML = TRUE), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### frm_optimizer_fn\n', file = stderr()); cat('\n#### frm_optimizer_fn\n')
print(tryCatch({frm(y ~ x, data = d, control = frmtmb_control(optimizer = function(...) stop("inner optimizer broke"))); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm(y ~ x, data = d, control = frmtmb_control(optimizer = function(...) stop("inner optimizer broke"))), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### frm_optimizer_name\n', file = stderr()); cat('\n#### frm_optimizer_name\n')
print(tryCatch({frm(y ~ x, data = d, control = frmtmb_control(optimizer = "nosuch")); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm(y ~ x, data = d, control = frmtmb_control(optimizer = "nosuch")), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### bf_bad_dpar\n', file = stderr()); cat('\n#### bf_bad_dpar\n')
print(tryCatch({bf(y ~ x, nosuchdpar ~ 1); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(bf(y ~ x, nosuchdpar ~ 1), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### set_prior_class\n', file = stderr()); cat('\n#### set_prior_class\n')
print(tryCatch({frm(y ~ x, data = d, prior = set_prior("normal(0, 1)", class = "nosuch")); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm(y ~ x, data = d, prior = set_prior("normal(0, 1)", class = "nosuch")), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### set_prior_bad_dist\n', file = stderr()); cat('\n#### set_prior_bad_dist\n')
print(tryCatch({set_prior("nosuchdist(1, 2)"); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(set_prior("nosuchdist(1, 2)"), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### predict_newdata_missing\n', file = stderr()); cat('\n#### predict_newdata_missing\n')
print(tryCatch({predict(fg, newdata = data.frame(z = 1)); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(predict(fg, newdata = data.frame(z = 1)), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### predict_bad_arg\n', file = stderr()); cat('\n#### predict_bad_arg\n')
print(tryCatch({predict(fg, re_frmula = NA); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(predict(fg, re_frmula = NA), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### fitted_typo\n', file = stderr()); cat('\n#### fitted_typo\n')
print(tryCatch({fitted(fg, re_frmula = NA); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(fitted(fg, re_frmula = NA), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### coef_typo\n', file = stderr()); cat('\n#### coef_typo\n')
print(tryCatch({coef(fg, robst = TRUE); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(coef(fg, robst = TRUE), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### nobs_extra\n', file = stderr()); cat('\n#### nobs_extra\n')
print(tryCatch({nobs(fg, 7); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(nobs(fg, 7), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### print_digits\n', file = stderr()); cat('\n#### print_digits\n')
print(tryCatch({print(fg, digits = 3); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(print(fg, digits = 3), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### anova_mix\n', file = stderr()); cat('\n#### anova_mix\n')
print(tryCatch({anova(fg, frm(y ~ x, data = d, REML = TRUE)); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(anova(fg, frm(y ~ x, data = d, REML = TRUE)), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### anova_space\n', file = stderr()); cat('\n#### anova_space\n')
print(tryCatch({anova(fg, frm(y ~ z, data = d)); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(anova(fg, frm(y ~ z, data = d)), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### confint_parm\n', file = stderr()); cat('\n#### confint_parm\n')
print(tryCatch({confint(fg, parm = "nosuchparm"); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(confint(fg, parm = "nosuchparm"), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### hypothesis_bad\n', file = stderr()); cat('\n#### hypothesis_bad\n')
print(tryCatch({hypothesis(fg, "nosuchpar = 0"); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(hypothesis(fg, "nosuchpar = 0"), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### ranef_fixed\n', file = stderr()); cat('\n#### ranef_fixed\n')
print(tryCatch({ranef(fg); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(ranef(fg), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### vcov_cluster_len\n', file = stderr()); cat('\n#### vcov_cluster_len\n')
print(tryCatch({vcov_cluster(fg, cluster = 1:3); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(vcov_cluster(fg, cluster = 1:3), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### simulate_nsim\n', file = stderr()); cat('\n#### simulate_nsim\n')
print(tryCatch({simulate(fg, nsim = -1); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(simulate(fg, nsim = -1), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### cond_eff_bad\n', file = stderr()); cat('\n#### cond_eff_bad\n')
print(tryCatch({conditional_effects(fg, effects = "nosuch"); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(conditional_effects(fg, effects = "nosuch"), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### bf_bad_dpar2\n', file = stderr()); cat('\n#### bf_bad_dpar2\n')
print(tryCatch({frm(bf(y ~ x, nosuch ~ 1), data = d); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm(bf(y ~ x, nosuch ~ 1), data = d), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### confint_level\n', file = stderr()); cat('\n#### confint_level\n')
print(tryCatch({confint(fg, level = 2); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(confint(fg, level = 2), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### frm_data_chr\n', file = stderr()); cat('\n#### frm_data_chr\n')
print(tryCatch({frm(y ~ x, data = "notdf"); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm(y ~ x, data = "notdf"), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### prior_coef\n', file = stderr()); cat('\n#### prior_coef\n')
print(tryCatch({frm(y ~ x, data = d, prior = set_prior("normal(0, 1)", class = "b", coef = "nosuch")); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm(y ~ x, data = d, prior = set_prior("normal(0, 1)", class = "b", coef = "nosuch")), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### predict_type_matcharg\n', file = stderr()); cat('\n#### predict_type_matcharg\n')
print(tryCatch({predict(fg, type = "bogus"); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(predict(fg, type = "bogus"), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### control_matcharg\n', file = stderr()); cat('\n#### control_matcharg\n')
print(tryCatch({frmtmb_control(check_nlev_1 = "bogus"); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frmtmb_control(check_nlev_1 = "bogus"), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### set_prior_stopifnot\n', file = stderr()); cat('\n#### set_prior_stopifnot\n')
print(tryCatch({set_prior("normal(0)"); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(set_prior("normal(0)"), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### spline_deriv_newdata\n', file = stderr()); cat('\n#### spline_deriv_newdata\n')
print(tryCatch({frm_curve_deriv(fg, var = "x"); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm_curve_deriv(fg, var = "x"), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### coupling_sfreq\n', file = stderr()); cat('\n#### coupling_sfreq\n')
print(tryCatch({frm_cross_spectrum(p64x, p64y, sfreq = -1); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm_cross_spectrum(p64x, p64y, sfreq = -1), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### ode_lincmt_both\n', file = stderr()); cat('\n#### ode_lincmt_both\n')
print(tryCatch({frm_lincmt(parms = list(ka = 1, CL = 2, ke = 0.2, V = 10), times = 1:5, ncmt = 1, depot = TRUE); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm_lincmt(parms = list(ka = 1, CL = 2, ke = 0.2, V = 10), times = 1:5, ncmt = 1, depot = TRUE), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### coupling_frange\n', file = stderr()); cat('\n#### coupling_frange\n')
print(tryCatch({frm_cross_spectrum(p64x, p64y, frange = c(1, 0)); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm_cross_spectrum(p64x, p64y, frange = c(1, 0)), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### spline_curve_empty\n', file = stderr()); cat('\n#### spline_curve_empty\n')
print(tryCatch({frm_curve(fg, newdata = data.frame()); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm_curve(fg, newdata = data.frame()), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### getME_mv_Zt\n', file = stderr()); cat('\n#### getME_mv_Zt\n')
print(tryCatch({lme4::getME(frm(mvbf(bf(y ~ x + (1 | g)), bf(z ~ x + (1 | g))), data = d), "Zt"); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(lme4::getME(frm(mvbf(bf(y ~ x + (1 | g)), bf(z ~ x + (1 | g))), data = d), "Zt"), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### frm_periodogram_short\n', file = stderr()); cat('\n#### frm_periodogram_short\n')
print(tryCatch({frm_periodogram(1); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm_periodogram(1), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### eam_wiener_linkinv\n', file = stderr()); cat('\n#### eam_wiener_linkinv\n')
print(tryCatch({wiener()$links[["ndt"]]$linkinv(0); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(wiener()$links[["ndt"]]$linkinv(0), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### eam_wiener_lpdf\n', file = stderr()); cat('\n#### eam_wiener_lpdf\n')
print(tryCatch({wiener_lpdf(0.5, 1, 1.5, 0.5, 2); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(wiener_lpdf(0.5, 1, 1.5, 0.5, 2), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### eam_wiener_nodec\n', file = stderr()); cat('\n#### eam_wiener_nodec\n')
print(tryCatch({frm(bf(rt ~ 1, bias = 0.5), family = wiener(), data = dat_rt); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm(bf(rt ~ 1, bias = 0.5), family = wiener(), data = dat_rt), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### eam_wiener_badcol\n', file = stderr()); cat('\n#### eam_wiener_badcol\n')
print(tryCatch({frm(bf(rt | dec(one) ~ 1, bias = 0.5), family = wiener(), data = dat_rt); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm(bf(rt | dec(one) ~ 1, bias = 0.5), family = wiener(), data = dat_rt), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### ode_lincmt_parms\n', file = stderr()); cat('\n#### ode_lincmt_parms\n')
print(tryCatch({frm_lincmt(parms = list(1, 0.2, 10), times = 1:5, ncmt = 1, depot = TRUE); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm_lincmt(parms = list(1, 0.2, 10), times = 1:5, ncmt = 1, depot = TRUE), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### ode_lincmt_missing\n', file = stderr()); cat('\n#### ode_lincmt_missing\n')
print(tryCatch({frm_lincmt(parms = list(ka = 1, ke = 0.2), times = 1:5, ncmt = 1, depot = TRUE); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm_lincmt(parms = list(ka = 1, ke = 0.2), times = 1:5, ncmt = 1, depot = TRUE), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### spline_curve_nonfit\n', file = stderr()); cat('\n#### spline_curve_nonfit\n')
print(tryCatch({frm_curve(d, newdata = d); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm_curve(d, newdata = d), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### spline_curve_level\n', file = stderr()); cat('\n#### spline_curve_level\n')
print(tryCatch({frm_curve(fg, newdata = d, level = 1.5); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm_curve(fg, newdata = d, level = 1.5), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### latent_hmm_reml\n', file = stderr()); cat('\n#### latent_hmm_reml\n')
print(tryCatch({frm(bf(y ~ 1), family = hmm(K = 2, gaussian(), time = x, group = g), data = d, REML = TRUE); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm(bf(y ~ 1), family = hmm(K = 2, gaussian(), time = x, group = g), data = d, REML = TRUE), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### latent_hmm_weights\n', file = stderr()); cat('\n#### latent_hmm_weights\n')
print(tryCatch({frm(bf(y | weights(z) ~ 1), family = hmm(K = 2, gaussian(), time = x, group = g), data = d); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm(bf(y | weights(z) ~ 1), family = hmm(K = 2, gaussian(), time = x, group = g), data = d), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### coupling_len\n', file = stderr()); cat('\n#### coupling_len\n')
print(tryCatch({frm_cross_spectrum(p64x, p64y[1:10]); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm_cross_spectrum(p64x, p64y[1:10]), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### coupling_segments\n', file = stderr()); cat('\n#### coupling_segments\n')
print(tryCatch({frm_cross_spectrum(p64x, p64y, segments = 0); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm_cross_spectrum(p64x, p64y, segments = 0), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### coupling_whole\n', file = stderr()); cat('\n#### coupling_whole\n')
print(tryCatch({frm_cross_spectrum(p64x, p64y, segments = 2.5); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm_cross_spectrum(p64x, p64y, segments = 2.5), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### coupling_coherence\n', file = stderr()); cat('\n#### coupling_coherence\n')
print(tryCatch({frm_coherence(fg); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm_coherence(fg), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### learn_ctprobe\n', file = stderr()); cat('\n#### learn_ctprobe\n')
print(tryCatch({frm_task_simulate(1, d); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm_task_simulate(1, d), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### sample_loglik\n', file = stderr()); cat('\n#### sample_loglik\n')
print(tryCatch({log_lik(fg, pointwise = TRUE); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(log_lik(fg, pointwise = TRUE), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### sample_nonfit\n', file = stderr()); cat('\n#### sample_nonfit\n')
print(tryCatch({frm_sample(1); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frm_sample(1), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### w_single_level\n', file = stderr()); cat('\n#### w_single_level\n')
print(tryCatch({invisible(frm(y ~ x + (1 | one), data = d, family = gaussian())); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(invisible(frm(y ~ x + (1 | one), data = d, family = gaussian())), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### w_obs_level\n', file = stderr()); cat('\n#### w_obs_level\n')
print(tryCatch({invisible(frm(y ~ x + (1 | obs), data = d, family = gaussian())); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(invisible(frm(y ~ x + (1 | obs), data = d, family = gaussian())), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### w_sigma_varies\n', file = stderr()); cat('\n#### w_sigma_varies\n')
print(tryCatch({sigma(fsig); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(sigma(fsig), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### w_nonfinite_cov\n', file = stderr()); cat('\n#### w_nonfinite_cov\n')
print(tryCatch({frmtmb:::solve_joint_precision(matrix(0, 2, 2)); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(frmtmb:::solve_joint_precision(matrix(0, 2, 2)), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### w_structure\n', file = stderr()); cat('\n#### w_structure\n')
print(tryCatch({invisible(frmtmb_structure(loglik = function(y, dpars, aterms, block, extra) 1)); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(invisible(frmtmb_structure(loglik = function(y, dpars, aterms, block, extra) 1)), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### w_ps_span\n', file = stderr()); cat('\n#### w_ps_span\n')
print(tryCatch({invisible(predict(frm(y ~ ps(x, k = 6), data = d), newdata = data.frame(x = c(-50, 0, 50)))); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(invisible(predict(frm(y ~ ps(x, k = 6), data = d), newdata = data.frame(x = c(-50, 0, 50)))), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### w_two_in_call\n', file = stderr()); cat('\n#### w_two_in_call\n')
print(tryCatch({{ invisible(frm(y ~ x + (1 | one), data = d)); sigma(fsig) }; "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers({ invisible(frm(y ~ x + (1 | one), data = d)); sigma(fsig) }, warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### w_lapply\n', file = stderr()); cat('\n#### w_lapply\n')
print(tryCatch({invisible(lapply(1:2, function(i) sigma(fsig))); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(invisible(lapply(1:2, function(i) sigma(fsig))), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### w_ode_states\n', file = stderr()); cat('\n#### w_ode_states\n')
print(tryCatch({invisible(frm_ode(function(t, y, p) lapply(y, function(v) -p[[1]] * v), init = as.list(rep(1, 8)), times = c(0.5, 1), parms = list(0.3), output = 1L)); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(invisible(frm_ode(function(t, y, p) lapply(y, function(v) -p[[1]] * v), init = as.list(rep(1, 8)), times = c(0.5, 1), parms = list(0.3), output = 1L)), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### w_sample_probs\n', file = stderr()); cat('\n#### w_sample_probs\n')
print(tryCatch({NULL; "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(NULL, warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### w_ar_levels\n', file = stderr()); cat('\n#### w_ar_levels\n')
print(tryCatch({invisible(frm(bf(y ~ x + ar(x, g, cov = TRUE)) + gaussian(), data = d, dry_run = "frame")); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(invisible(frm(bf(y ~ x + ar(x, g, cov = TRUE)) + gaussian(), data = d, dry_run = "frame")), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### w_coupling_df\n', file = stderr()); cat('\n#### w_coupling_df\n')
print(tryCatch({NULL; "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(NULL, warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### w_under_warn2\n', file = stderr()); cat('\n#### w_under_warn2\n')
print(tryCatch({local({ op <- options(warn = 2); on.exit(options(op)); sigma(fsig) }); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(local({ op <- options(warn = 2); on.exit(options(op)); sigma(fsig) }), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### m_na_rows\n', file = stderr()); cat('\n#### m_na_rows\n')
print(tryCatch({invisible(frm(y ~ w, data = d, family = gaussian())); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(invisible(frm(y ~ w, data = d, family = gaussian())), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### m_dates\n', file = stderr()); cat('\n#### m_dates\n')
print(tryCatch({invisible(frm(bf(y ~ day) + gaussian(), data = d, dry_run = "frame")); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(invisible(frm(bf(y ~ day) + gaussian(), data = d, dry_run = "frame")), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### m_rank_def\n', file = stderr()); cat('\n#### m_rank_def\n')
print(tryCatch({invisible(frm(y ~ x + I(2 * x), data = d)); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(invisible(frm(y ~ x + I(2 * x), data = d)), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### m_bernoulli\n', file = stderr()); cat('\n#### m_bernoulli\n')
print(tryCatch({invisible(frm(k | trials(n) ~ x, d, family = mixture(binomial, binomial), dry_run = "frame")); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(invisible(frm(k | trials(n) ~ x, d, family = mixture(binomial, binomial), dry_run = "frame")), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### m_categorical\n', file = stderr()); cat('\n#### m_categorical\n')
print(tryCatch({invisible(frm(bf(ych ~ x), family = categorical(), data = transform(d, ych = sample(c("a", "b", "c"), 60, TRUE)))); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(invisible(frm(bf(ych ~ x), family = categorical(), data = transform(d, ych = sample(c("a", "b", "c"), 60, TRUE)))), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### m_anova_refit\n', file = stderr()); cat('\n#### m_anova_refit\n')
print(tryCatch({invisible(anova(frm(y ~ x + (1 | g), data = d, REML = TRUE), frm(y ~ 1 + (1 | g), data = d, REML = TRUE), refit = TRUE)); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(invisible(anova(frm(y ~ x + (1 | g), data = d, REML = TRUE), frm(y ~ 1 + (1 | g), data = d, REML = TRUE), refit = TRUE)), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### m_confint_internal\n', file = stderr()); cat('\n#### m_confint_internal\n')
print(tryCatch({invisible(confint(fm, "sd_g__Intercept")); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(invisible(confint(fm, "sd_g__Intercept")), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### m_in_trycatch\n', file = stderr()); cat('\n#### m_in_trycatch\n')
print(tryCatch({tryCatch(invisible(frm(y ~ w, data = d)), error = function(e) "no"); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(tryCatch(invisible(frm(y ~ w, data = d)), error = function(e) "no"), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
cat('\n#### m_nolf_notice\n', file = stderr()); cat('\n#### m_nolf_notice\n')
print(tryCatch({invisible(frm(y ~ x + (1 | g), data = d, family = gaussian())); "none"}, error = function(c) paste("E", class(c)[1L]), warning = function(c) paste("W", conditionMessage(c)), message = function(c) paste("M", conditionMessage(c))))
try(withCallingHandlers(invisible(frm(y ~ x + (1 | g), data = d, family = gaussian())), warning = function(w) { cat("WCH-W:", conditionMessage(w), "\n"); invokeRestart("muffleWarning") }, message = function(m) { cat("WCH-M:", conditionMessage(m)); invokeRestart("muffleMessage") }))
