.libPaths(c('C:/Users/adf44/source/r/conditions-lib', 'C:/Users/adf44/source/r/pinlib', 'C:/Users/adf44/AppData/Local/R/win-library/4.6'))

suppressPackageStartupMessages({
  library(frmtmb); library(frmtmb.eam); library(frmtmb.ode)
  library(frmtmb.spline); library(frmtmb.latent); library(frmtmb.learn)
  library(frmtmb.coupling); library(frmtmb.sample)
})
options(frmtmb.notices = TRUE, width = 80)
set.seed(20260917)
d <- data.frame(y = rnorm(60), x = rnorm(60), z = rnorm(60),
                g = factor(rep(1:10, each = 6)),
                one = factor(rep("a", 60)), obs = factor(1:60))
d$n <- rep(10L, 60); d$k <- rbinom(60, 10, 0.4)
d$yb <- rbinom(60, 1, 0.5)
d$day <- as.Date("2020-01-01") + 0:59
d$w <- ifelse(seq_len(60) %% 7 == 0, NA, d$x)
fg <- frm(y ~ x, data = d, family = gaussian())
fb <- frm(k | trials(n) ~ x, data = d, family = binomial())
fm <- frm(y ~ x + (1 | g), data = d, family = gaussian())
fsig <- frm(bf(y ~ x, sigma ~ z), data = d, family = gaussian())
dat_rt <- data.frame(rt = 0.5 + rexp(40), upper = rbinom(40, 1, 0.5))
p64x <- rnorm(64); p64y <- rnorm(64)

cat('\n#### frm_family_unknown\n', file = stderr()); cat('\n#### frm_family_unknown\n')
suppressWarnings(suppressMessages(try(frm(y ~ x, data = d, family = "not_a_family"))))
cat('\n#### frm_missing_var\n', file = stderr()); cat('\n#### frm_missing_var\n')
suppressWarnings(suppressMessages(try(frm(y ~ nope, data = d, family = gaussian()))))
cat('\n#### frm_start_unknown\n', file = stderr()); cat('\n#### frm_start_unknown\n')
suppressWarnings(suppressMessages(try(frm(y ~ x, data = d, start = list(bogus = 1)))))
cat('\n#### frm_start_len\n', file = stderr()); cat('\n#### frm_start_len\n')
suppressWarnings(suppressMessages(try(frm(y ~ x, data = d, start = list(beta = 1:5)))))
cat('\n#### frm_trials_missing\n', file = stderr()); cat('\n#### frm_trials_missing\n')
suppressWarnings(suppressMessages(try(frm(k ~ x, data = d, family = binomial()))))
cat('\n#### frm_empty_data\n', file = stderr()); cat('\n#### frm_empty_data\n')
suppressWarnings(suppressMessages(try(frm(y ~ x, data = d[0, ], family = gaussian()))))
cat('\n#### frm_reml_nl\n', file = stderr()); cat('\n#### frm_reml_nl\n')
suppressWarnings(suppressMessages(try(frm(bf(y ~ a * x, a ~ 1, nl = TRUE), data = d, REML = TRUE))))
cat('\n#### frm_optimizer_fn\n', file = stderr()); cat('\n#### frm_optimizer_fn\n')
suppressWarnings(suppressMessages(try(frm(y ~ x, data = d, control = frmtmb_control(optimizer = function(...) stop("inner optimizer broke"))))))
cat('\n#### frm_optimizer_name\n', file = stderr()); cat('\n#### frm_optimizer_name\n')
suppressWarnings(suppressMessages(try(frm(y ~ x, data = d, control = frmtmb_control(optimizer = "nosuch")))))
cat('\n#### bf_bad_dpar\n', file = stderr()); cat('\n#### bf_bad_dpar\n')
suppressWarnings(suppressMessages(try(bf(y ~ x, nosuchdpar ~ 1))))
cat('\n#### set_prior_class\n', file = stderr()); cat('\n#### set_prior_class\n')
suppressWarnings(suppressMessages(try(frm(y ~ x, data = d, prior = set_prior("normal(0, 1)", class = "nosuch")))))
cat('\n#### set_prior_bad_dist\n', file = stderr()); cat('\n#### set_prior_bad_dist\n')
suppressWarnings(suppressMessages(try(set_prior("nosuchdist(1, 2)"))))
cat('\n#### predict_newdata_missing\n', file = stderr()); cat('\n#### predict_newdata_missing\n')
suppressWarnings(suppressMessages(try(predict(fg, newdata = data.frame(z = 1)))))
cat('\n#### predict_bad_arg\n', file = stderr()); cat('\n#### predict_bad_arg\n')
suppressWarnings(suppressMessages(try(predict(fg, re_frmula = NA))))
cat('\n#### fitted_typo\n', file = stderr()); cat('\n#### fitted_typo\n')
suppressWarnings(suppressMessages(try(fitted(fg, re_frmula = NA))))
cat('\n#### coef_typo\n', file = stderr()); cat('\n#### coef_typo\n')
suppressWarnings(suppressMessages(try(coef(fg, robst = TRUE))))
cat('\n#### nobs_extra\n', file = stderr()); cat('\n#### nobs_extra\n')
suppressWarnings(suppressMessages(try(nobs(fg, 7))))
cat('\n#### print_digits\n', file = stderr()); cat('\n#### print_digits\n')
suppressWarnings(suppressMessages(try(print(fg, digits = 3))))
cat('\n#### anova_mix\n', file = stderr()); cat('\n#### anova_mix\n')
suppressWarnings(suppressMessages(try(anova(fg, frm(y ~ x, data = d, REML = TRUE)))))
cat('\n#### anova_space\n', file = stderr()); cat('\n#### anova_space\n')
suppressWarnings(suppressMessages(try(anova(fg, frm(y ~ z, data = d)))))
cat('\n#### confint_parm\n', file = stderr()); cat('\n#### confint_parm\n')
suppressWarnings(suppressMessages(try(confint(fg, parm = "nosuchparm"))))
cat('\n#### hypothesis_bad\n', file = stderr()); cat('\n#### hypothesis_bad\n')
suppressWarnings(suppressMessages(try(hypothesis(fg, "nosuchpar = 0"))))
cat('\n#### ranef_fixed\n', file = stderr()); cat('\n#### ranef_fixed\n')
suppressWarnings(suppressMessages(try(ranef(fg))))
cat('\n#### vcov_cluster_len\n', file = stderr()); cat('\n#### vcov_cluster_len\n')
suppressWarnings(suppressMessages(try(vcov_cluster(fg, cluster = 1:3))))
cat('\n#### simulate_nsim\n', file = stderr()); cat('\n#### simulate_nsim\n')
suppressWarnings(suppressMessages(try(simulate(fg, nsim = -1))))
cat('\n#### cond_eff_bad\n', file = stderr()); cat('\n#### cond_eff_bad\n')
suppressWarnings(suppressMessages(try(conditional_effects(fg, effects = "nosuch"))))
cat('\n#### bf_bad_dpar2\n', file = stderr()); cat('\n#### bf_bad_dpar2\n')
suppressWarnings(suppressMessages(try(frm(bf(y ~ x, nosuch ~ 1), data = d))))
cat('\n#### confint_level\n', file = stderr()); cat('\n#### confint_level\n')
suppressWarnings(suppressMessages(try(confint(fg, level = 2))))
cat('\n#### frm_data_chr\n', file = stderr()); cat('\n#### frm_data_chr\n')
suppressWarnings(suppressMessages(try(frm(y ~ x, data = "notdf"))))
cat('\n#### prior_coef\n', file = stderr()); cat('\n#### prior_coef\n')
suppressWarnings(suppressMessages(try(frm(y ~ x, data = d, prior = set_prior("normal(0, 1)", class = "b", coef = "nosuch")))))
cat('\n#### predict_type_matcharg\n', file = stderr()); cat('\n#### predict_type_matcharg\n')
suppressWarnings(suppressMessages(try(predict(fg, type = "bogus"))))
cat('\n#### control_matcharg\n', file = stderr()); cat('\n#### control_matcharg\n')
suppressWarnings(suppressMessages(try(frmtmb_control(check_nlev_1 = "bogus"))))
cat('\n#### set_prior_stopifnot\n', file = stderr()); cat('\n#### set_prior_stopifnot\n')
suppressWarnings(suppressMessages(try(set_prior("normal(0)"))))
cat('\n#### spline_deriv_newdata\n', file = stderr()); cat('\n#### spline_deriv_newdata\n')
suppressWarnings(suppressMessages(try(frm_curve_deriv(fg, var = "x"))))
cat('\n#### coupling_sfreq\n', file = stderr()); cat('\n#### coupling_sfreq\n')
suppressWarnings(suppressMessages(try(frm_cross_spectrum(p64x, p64y, sfreq = -1))))
cat('\n#### ode_lincmt_both\n', file = stderr()); cat('\n#### ode_lincmt_both\n')
suppressWarnings(suppressMessages(try(frm_lincmt(parms = list(ka = 1, CL = 2, ke = 0.2, V = 10), times = 1:5, ncmt = 1, depot = TRUE))))
cat('\n#### coupling_frange\n', file = stderr()); cat('\n#### coupling_frange\n')
suppressWarnings(suppressMessages(try(frm_cross_spectrum(p64x, p64y, frange = c(1, 0)))))
cat('\n#### spline_curve_empty\n', file = stderr()); cat('\n#### spline_curve_empty\n')
suppressWarnings(suppressMessages(try(frm_curve(fg, newdata = data.frame()))))
cat('\n#### getME_mv_Zt\n', file = stderr()); cat('\n#### getME_mv_Zt\n')
suppressWarnings(suppressMessages(try(lme4::getME(frm(mvbf(bf(y ~ x + (1 | g)), bf(z ~ x + (1 | g))), data = d), "Zt"))))
cat('\n#### frm_periodogram_short\n', file = stderr()); cat('\n#### frm_periodogram_short\n')
suppressWarnings(suppressMessages(try(frm_periodogram(1))))
cat('\n#### eam_wiener_linkinv\n', file = stderr()); cat('\n#### eam_wiener_linkinv\n')
suppressWarnings(suppressMessages(try(wiener()$links[["ndt"]]$linkinv(0))))
cat('\n#### eam_wiener_lpdf\n', file = stderr()); cat('\n#### eam_wiener_lpdf\n')
suppressWarnings(suppressMessages(try(wiener_lpdf(0.5, 1, 1.5, 0.5, 2))))
cat('\n#### eam_wiener_nodec\n', file = stderr()); cat('\n#### eam_wiener_nodec\n')
suppressWarnings(suppressMessages(try(frm(bf(rt ~ 1, bias = 0.5), family = wiener(), data = dat_rt))))
cat('\n#### eam_wiener_badcol\n', file = stderr()); cat('\n#### eam_wiener_badcol\n')
suppressWarnings(suppressMessages(try(frm(bf(rt | dec(one) ~ 1, bias = 0.5), family = wiener(), data = dat_rt))))
cat('\n#### ode_lincmt_parms\n', file = stderr()); cat('\n#### ode_lincmt_parms\n')
suppressWarnings(suppressMessages(try(frm_lincmt(parms = list(1, 0.2, 10), times = 1:5, ncmt = 1, depot = TRUE))))
cat('\n#### ode_lincmt_missing\n', file = stderr()); cat('\n#### ode_lincmt_missing\n')
suppressWarnings(suppressMessages(try(frm_lincmt(parms = list(ka = 1, ke = 0.2), times = 1:5, ncmt = 1, depot = TRUE))))
cat('\n#### spline_curve_nonfit\n', file = stderr()); cat('\n#### spline_curve_nonfit\n')
suppressWarnings(suppressMessages(try(frm_curve(d, newdata = d))))
cat('\n#### spline_curve_level\n', file = stderr()); cat('\n#### spline_curve_level\n')
suppressWarnings(suppressMessages(try(frm_curve(fg, newdata = d, level = 1.5))))
cat('\n#### latent_hmm_reml\n', file = stderr()); cat('\n#### latent_hmm_reml\n')
suppressWarnings(suppressMessages(try(frm(bf(y ~ 1), family = hmm(K = 2, gaussian(), time = x, group = g), data = d, REML = TRUE))))
cat('\n#### latent_hmm_weights\n', file = stderr()); cat('\n#### latent_hmm_weights\n')
suppressWarnings(suppressMessages(try(frm(bf(y | weights(z) ~ 1), family = hmm(K = 2, gaussian(), time = x, group = g), data = d))))
cat('\n#### coupling_len\n', file = stderr()); cat('\n#### coupling_len\n')
suppressWarnings(suppressMessages(try(frm_cross_spectrum(p64x, p64y[1:10]))))
cat('\n#### coupling_segments\n', file = stderr()); cat('\n#### coupling_segments\n')
suppressWarnings(suppressMessages(try(frm_cross_spectrum(p64x, p64y, segments = 0))))
cat('\n#### coupling_whole\n', file = stderr()); cat('\n#### coupling_whole\n')
suppressWarnings(suppressMessages(try(frm_cross_spectrum(p64x, p64y, segments = 2.5))))
cat('\n#### coupling_coherence\n', file = stderr()); cat('\n#### coupling_coherence\n')
suppressWarnings(suppressMessages(try(frm_coherence(fg))))
cat('\n#### learn_ctprobe\n', file = stderr()); cat('\n#### learn_ctprobe\n')
suppressWarnings(suppressMessages(try(frm_task_simulate(1, d))))
cat('\n#### sample_loglik\n', file = stderr()); cat('\n#### sample_loglik\n')
suppressWarnings(suppressMessages(try(log_lik(fg, pointwise = TRUE))))
cat('\n#### sample_nonfit\n', file = stderr()); cat('\n#### sample_nonfit\n')
suppressWarnings(suppressMessages(try(frm_sample(1))))
cat('\n#### w_single_level\n', file = stderr()); cat('\n#### w_single_level\n')
suppressWarnings(suppressMessages(try(invisible(frm(y ~ x + (1 | one), data = d, family = gaussian())))))
cat('\n#### w_obs_level\n', file = stderr()); cat('\n#### w_obs_level\n')
suppressWarnings(suppressMessages(try(invisible(frm(y ~ x + (1 | obs), data = d, family = gaussian())))))
cat('\n#### w_sigma_varies\n', file = stderr()); cat('\n#### w_sigma_varies\n')
suppressWarnings(suppressMessages(try(sigma(fsig))))
cat('\n#### w_nonfinite_cov\n', file = stderr()); cat('\n#### w_nonfinite_cov\n')
suppressWarnings(suppressMessages(try(frmtmb:::solve_joint_precision(matrix(0, 2, 2)))))
cat('\n#### w_structure\n', file = stderr()); cat('\n#### w_structure\n')
suppressWarnings(suppressMessages(try(invisible(frmtmb_structure(loglik = function(y, dpars, aterms, block, extra) 1)))))
cat('\n#### w_ps_span\n', file = stderr()); cat('\n#### w_ps_span\n')
suppressWarnings(suppressMessages(try(invisible(predict(frm(y ~ ps(x, k = 6), data = d), newdata = data.frame(x = c(-50, 0, 50)))))))
cat('\n#### w_two_in_call\n', file = stderr()); cat('\n#### w_two_in_call\n')
suppressWarnings(suppressMessages(try({ invisible(frm(y ~ x + (1 | one), data = d)); sigma(fsig) })))
cat('\n#### w_lapply\n', file = stderr()); cat('\n#### w_lapply\n')
suppressWarnings(suppressMessages(try(invisible(lapply(1:2, function(i) sigma(fsig))))))
cat('\n#### w_ode_states\n', file = stderr()); cat('\n#### w_ode_states\n')
suppressWarnings(suppressMessages(try(invisible(frm_ode(function(t, y, p) lapply(y, function(v) -p[[1]] * v), init = as.list(rep(1, 8)), times = c(0.5, 1), parms = list(0.3), output = 1L)))))
cat('\n#### w_sample_probs\n', file = stderr()); cat('\n#### w_sample_probs\n')
suppressWarnings(suppressMessages(try(NULL)))
cat('\n#### w_ar_levels\n', file = stderr()); cat('\n#### w_ar_levels\n')
suppressWarnings(suppressMessages(try(invisible(frm(bf(y ~ x + ar(x, g, cov = TRUE)) + gaussian(), data = d, dry_run = "frame")))))
cat('\n#### w_coupling_df\n', file = stderr()); cat('\n#### w_coupling_df\n')
suppressWarnings(suppressMessages(try(NULL)))
cat('\n#### w_under_warn2\n', file = stderr()); cat('\n#### w_under_warn2\n')
suppressWarnings(suppressMessages(try(local({ op <- options(warn = 2); on.exit(options(op)); sigma(fsig) }))))
cat('\n#### m_na_rows\n', file = stderr()); cat('\n#### m_na_rows\n')
suppressWarnings(suppressMessages(try(invisible(frm(y ~ w, data = d, family = gaussian())))))
cat('\n#### m_dates\n', file = stderr()); cat('\n#### m_dates\n')
suppressWarnings(suppressMessages(try(invisible(frm(bf(y ~ day) + gaussian(), data = d, dry_run = "frame")))))
cat('\n#### m_rank_def\n', file = stderr()); cat('\n#### m_rank_def\n')
suppressWarnings(suppressMessages(try(invisible(frm(y ~ x + I(2 * x), data = d)))))
cat('\n#### m_bernoulli\n', file = stderr()); cat('\n#### m_bernoulli\n')
suppressWarnings(suppressMessages(try(invisible(frm(k | trials(n) ~ x, d, family = mixture(binomial, binomial), dry_run = "frame")))))
cat('\n#### m_categorical\n', file = stderr()); cat('\n#### m_categorical\n')
suppressWarnings(suppressMessages(try(invisible(frm(bf(ych ~ x), family = categorical(), data = transform(d, ych = sample(c("a", "b", "c"), 60, TRUE)))))))
cat('\n#### m_anova_refit\n', file = stderr()); cat('\n#### m_anova_refit\n')
suppressWarnings(suppressMessages(try(invisible(anova(frm(y ~ x + (1 | g), data = d, REML = TRUE), frm(y ~ 1 + (1 | g), data = d, REML = TRUE), refit = TRUE)))))
cat('\n#### m_confint_internal\n', file = stderr()); cat('\n#### m_confint_internal\n')
suppressWarnings(suppressMessages(try(invisible(confint(fm, "sd_g__Intercept")))))
cat('\n#### m_in_trycatch\n', file = stderr()); cat('\n#### m_in_trycatch\n')
suppressWarnings(suppressMessages(try(tryCatch(invisible(frm(y ~ w, data = d)), error = function(e) "no"))))
cat('\n#### m_nolf_notice\n', file = stderr()); cat('\n#### m_nolf_notice\n')
suppressWarnings(suppressMessages(try(invisible(frm(y ~ x + (1 | g), data = d, family = gaussian())))))
