#' Null-coalescing operator: `y` when `x` is `NULL`, else `x`.
#'
#' Defined here rather than imported so the package keeps working on the
#' oldest supported R, where base does not export it.
#'
#' @noRd
`%||%` <- function(x, y) if (is.null(x)) y else x

# --- argument checks shared by the whole export surface ---------------
#
# These exist because the idioms they replace fail SILENTLY. `isTRUE(x)`
# reads a length-2 logical, a string, an integer and `NA` all as FALSE,
# so a flag set by mistake used to fit the OTHER model and report it as
# the user's. A length-2 `level` recycles against the parameter vector
# and puts DIFFERENT coverages on different rows of one table, with no
# column heading to record it. Each check turns one of those into a
# refusal that names the argument and says what it had to be.
#
# Every check raises exactly one message, so the whole family adds a
# handful of condition messages rather than one per call site, and the
# argument name that varies at run time comes from the caller.

#' What a rejected argument actually was, as a phrase a message can end
#' with. Deliberately short: the caller's message has already said what
#' the argument had to be, so this only has to identify what arrived.
#'
#' @noRd
arg_desc <- function(x) {
  if (is.null(x)) return("NULL")
  cls <- class(x)[1L]
  if (is.atomic(x) && length(x) == 1L) {
    if (is.na(x)) return(paste0(cls, " NA"))
    return(paste0(cls, " ", encodeString(format(x), quote = "\"")))
  }
  art <- if (substr(cls, 1L, 1L) %in% c("a", "e", "i", "o", "u")) "an" else "a"
  paste0(art, " ", cls, " of length ", length(x))
}

# --- refusing an argument that fell into `...` ------------------------
#
# A method whose `...` is never read accepts EVERY name, so a misspelled
# argument and an unsupported one both change nothing and say nothing.
# That is how `fitted(fit, re_formula = NA)` returned the conditional
# fit: 1.291651 at the first row of the fixture in
# tests/testthat/test-arg-refusal.R, identical to `fitted(fit)`, where
# the population answer is 1.954262, measured by dev/argspell-defect.R
# against frmtmb 0.57.0. Refusing the dots is what stops the
# class rather than that one instance, because a swallowing method takes
# every argument brms adds in future the same way.
#
# The refusal is NOT applied to a method of a generic another package
# owns and calls itself (emmeans, insight, marginaleffects): those
# callers pass arguments of their own choosing, so accepting them is the
# contract. `dev/argspell-findings.md` lists the exclusions by name.

# --- what R's S3 contract obliges a method to tolerate ------------
#
# The refusal's rule was "refuse what the METHOD does not have". R's S3
# contract is different: a method must tolerate the arguments its
# GENERIC is documented to carry, which is why every `stats` default
# method declares `use.fallback`, `env`, `data`, `na.rm` or `trace` and
# then ignores them. The two rules collide wherever base R hands a model
# to a generic with an extra name, and three rounds of one-off `.allow`
# patches each uncovered the next hop: `nobs(use.fallback =)` from
# `step()`, then `drop1(scale =, trace =)` from the same call, then
# `formula(env =)` from `as.formula()`, then `terms(data =)` from
# `model.matrix.default()` and four more.
#
# One table, consulted by `frm_check_dots()` for every method at once.
# `dev/argspell-contract.R` derives it by walking the ASTs of R's own
# packages for calls to these generics, and
# `tests/testthat/test-arg-refusal.R` runs the same scan and fails if a
# name turns up that is not here, so the NEXT hop is found by the suite
# rather than by a user.
#
# Everything not named here is still refused: `drop1(fit, re.form = NA)`
# and `nobs(fit, nosucharg = 1)` error as before, and an `.unsupported`
# entry still wins, so `print(fit, digits = 3)` keeps its reason.

#' Graphical arguments, for the `plot` row below.
#'
#' `plot()`'s contract IS the graphical parameters: a plot method that
#' refuses `col` is broken, whatever it does with it. Generated by
#' `dev/argspell-plotset.R` as the union of `par()`,
#' `plot.default()`'s own formals and the names R's other plot methods
#' pass, rather than typed. Used for the "did you mean" search only;
#' the refusal message lists the method's own arguments, because
#' printing 95 graphical parameters would bury the answer.
#'
#' @noRd
s3_plot_args <- c(
  "add", "adj", "angle", "ann", "ask", "asp", "axes", "bg", "border",
  "bty", "cex", "cex.axis", "cex.lab", "cex.main", "cex.sub", "ci",
  "col", "col.axis", "col.lab", "col.main", "col.sub", "crt",
  "density", "err", "family", "fg", "fig", "fin", "font",
  "font.axis", "font.lab", "font.main", "font.sub", "frame.plot",
  "freq", "horiz", "lab", "labels", "las", "leaflab", "lend",
  "lheight", "lim2", "ljoin", "lmitre", "log", "lty", "lwd", "mai",
  "main", "mar", "mex", "mfcol", "mfg", "mfrow", "mgp", "mkh", "new",
  "oma", "omd", "omi", "panel.first", "panel.last", "pch", "pin",
  "plt", "ps", "pty", "smo", "srt", "sub", "tck", "tcl", "type",
  "usr", "verticals", "xaxp", "xaxs", "xaxt", "xgap.axis", "xlab",
  "xlim", "xlog", "xpd", "xy.labels", "xy.lines", "y", "yaxp",
  "yaxs", "yaxt", "ygap.axis", "ylab", "ylbias", "ylim", "ylog"
)

#' Generic to the argument names R's own code passes through it.
#'
#' @noRd
s3_contract_args <- list(
  add1 = c("scale", "test", "k", "trace"),
  as.data.frame = c("row.names", "optional", "stringsAsFactors",
                    "check.names", "fix.empty.names"),
  as.matrix = "rownames.force",
  coef = "complete",
  confint = c("trace", "test", "type"),
  drop1 = c("scale", "test", "k", "trace"),
  formula = "env",
  influence = "do.coef",
  model.frame = c("data", "subset", "na.action", "xlev",
                  "drop.unused.levels"),
  model.matrix = c("data", "contrasts.arg", "xlev"),
  nobs = "use.fallback",
  plot = s3_plot_args,
  predict = "terms",
  print = c("quote", "useS4", "steps"),
  residuals = "na.rm",
  summary = "dispersion",
  terms = c("data", "specials", "allowDotAsName"),
  weights = "type"
)

#' The display name of the function that called the checker.
#'
#' A method reached through `UseMethod()` reports its own name, so
#' `fitted.frmtmb_fit` has to be cut back to `fitted()`: the caller
#' typed the generic, and a message naming the method sends them looking
#' for a function they never wrote. `print.summary.frmtmb_fit` is the
#' case that needs the optional `summary.` in the pattern; without it
#' the message named `print.summary()`, which is not a function.
#'
#' @noRd
calling_fun_name <- function(which) {
  nm <- tryCatch(deparse(sys.call(which)[[1L]]), error = function(e) NA)
  if (length(nm) != 1L || is.na(nm)) return(NA_character_)
  sub(paste0("[.](summary[.])?",
             "(frmtmb|ranef_frmtmb|VarCorr_frmtmb|default)",
             "[.A-Za-z0-9_]*$"),
      "", nm)
}

#' The formal this caller most likely meant, or `NULL`.
#'
#' A single-edit typo is worth naming; anything further apart is a guess
#' dressed as help, so the threshold grows with the name's length.
#'
#' @noRd
nearest_formal <- function(bad, known) {
  known <- setdiff(known, "...")
  if (!length(known) || !nzchar(bad)) return(NULL)
  d <- utils::adist(bad, known, ignore.case = TRUE)[1L, ]
  i <- which.min(d)
  if (d[i] > max(1L, floor(nchar(bad) / 4))) return(NULL)
  known[i]
}

#' Refuse every argument that landed in `...`.
#'
#' Called as `frm_check_dots(...)` from a method that does not read its
#' dots. The function's own name and formals come from the calling
#' frame, so the call site is the same one line everywhere and cannot
#' drift out of step with a renamed argument.
#'
#' @param ... The caller's dots, forwarded.
#' @param .unsupported Named character vector: argument name to the
#'   reason it is refused. Use it for an argument that is REAL in brms
#'   and simply cannot be honored here, so that the refusal says why
#'   instead of reporting the name as unknown.
#' @param .allow Character vector of names this call really does
#'   forward, for a method that passes its dots on from ONE branch, or
#'   `TRUE` for a method that forwards ALL of them to a function with
#'   dots of its own. `.unsupported` is checked first either way, so a
#'   retired spelling is still refused by a method that forwards.
#' @noRd
frm_check_dots <- function(..., .unsupported = NULL, .allow = NULL) {
  n <- ...length()
  if (n == 0L) return(invisible(NULL))
  w <- sys.parent()
  gen <- calling_fun_name(w)
  what <- if (is.na(gen)) "this function" else paste0(gen, "()")
  known <- tryCatch(names(formals(sys.function(w))), error = function(e) NULL)
  # what R's own machinery passes through this generic, which a method
  # has to tolerate whatever its own formals say
  contract <- if (!is.na(gen)) s3_contract_args[[gen]]
  nms <- ...names()
  if (is.null(nms)) nms <- rep("", n)
  nms[is.na(nms)] <- ""
  bad <- nms[nzchar(nms)]
  # first, and before the catch-all below: a name that was a real
  # spelling of a real setting until the rename has to be refused even
  # by a method that forwards its dots, or it goes on meaning nothing
  hit <- intersect(bad, names(.unsupported))
  if (length(hit)) {
    stop(what, " cannot honor `", hit[1L], "`: ", .unsupported[[hit[1L]]],
         call. = FALSE)
  }
  if (isTRUE(.allow)) return(invisible(NULL))
  bad <- setdiff(bad, contract)
  unnamed <- sum(!nzchar(nms))
  if (unnamed > 0L) {
    stop(what, " was given ", unnamed, " argument",
         if (unnamed > 1L) "s" else "", " with no name, which it has ",
         "nowhere to put. It takes: ",
         paste(setdiff(known, "..."), collapse = ", "), call. = FALSE)
  }
  bad <- setdiff(bad, .allow)
  if (!length(bad)) return(invisible(NULL))
  # the nearest name is looked for among everything the call really
  # accepts, but only the method's OWN arguments are listed back: for
  # `plot()` the contract is 95 graphical parameters and printing them
  # would bury the answer
  guess <- nearest_formal(bad[1L], c(known, .allow, contract))
  stop(what, " has no argument `", bad[1L], "`",
       if (length(bad) > 1L) {
         paste0(" (and ", length(bad) - 1L, " more: ",
                paste(bad[-1L], collapse = ", "), ")")
       } else "",
       if (is.null(guess)) "" else paste0(". Did you mean `", guess, "`?"),
       ". It takes: ",
       paste(setdiff(c(known, .allow), "..."), collapse = ", "),
       call. = FALSE)
}

# --- one setting under two spellings ----------------------------------
#
# The naming rule: brms is the TIEBREAKER. Where lme4 or glmmTMB and
# brms disagree on a name, the brms spelling is the one this package
# takes and the lme4 one is DROPPED, not deprecated.
# `predict()` and `simulate()` therefore take `re_formula` and no longer
# take `re.form`, and `predict()` no longer accepts `allow.new.levels`.
#
# Two spellings of one setting survive in exactly one place: where brms
# ITSELF carries both. `posterior_epred.brmsfit()` and
# `posterior_predict.brmsfit()` take `re_formula` and `re.form` side by
# side, so the frmtmb.sample methods of those generics do too. That is
# matching brms, not preserving history. Supplying both at once is
# refused rather than resolved: two names for one setting given together
# is a question about what the caller meant, not a preference to guess
# at.

#' The "argument was not supplied" marker for a dual-spelled argument.
#'
#' A sentinel is needed rather than a plain default because `NULL` and
#' `NA` are both REAL settings for a random-effect formula (keep the
#' random effects; drop them), so neither can double as "unset". Its
#' class is the whole implementation: nothing a caller can pass carries
#' it.
#'
#' @noRd
arg_unset <- function() structure(list(), class = "frmtmb_arg_unset")

#' @noRd
is_arg_unset <- function(x) inherits(x, "frmtmb_arg_unset")

#' One value out of two spellings of one argument.
#'
#' `primary` is the spelling the function is named after (brms's),
#' `alias` the accepted historical one; `default` is what the function
#' does when neither is given, which is by construction the default it
#' had before the alias existed.
#'
#' @noRd
dual_arg <- function(primary, alias, primary_name, alias_name, what,
                     default = NULL) {
  set_primary <- !is_arg_unset(primary)
  set_alias <- !is_arg_unset(alias)
  if (set_primary && set_alias) {
    stop(what, " was given both `", primary_name, "` and `", alias_name,
         "`, which are two spellings of ONE setting, so it cannot tell ",
         "which was meant. `", primary_name, "` is the spelling this ",
         "function takes (it is brms's, and this is a brms function); `",
         alias_name, "` is accepted as an alias. Pass one of them",
         call. = FALSE)
  }
  if (set_primary) return(primary)
  if (set_alias) return(alias)
  default
}

#' The random-effect formula of a brms-named draws method, from either
#' spelling. Kept as its own wrapper so that every call site names the
#' same two spellings and only the function name and the default vary.
#'
#' @noRd
re_form_arg <- function(re_formula, re.form, what, default = NULL) {
  dual_arg(re_formula, re.form, "re_formula", "re.form", what,
           default = default)
}

#' The one refusal every TRUE/FALSE argument in the package shares.
#'
#' @noRd
check_flag <- function(x, arg, what = NULL) {
  if (!is.logical(x) || length(x) != 1L || is.na(x)) {
    stop("`", arg, "` must be TRUE or FALSE, not ", arg_desc(x),
         if (is.null(what)) "" else paste0(". ", what), call. = FALSE)
  }
  invisible(x)
}

#' A single whole number at or above `min`: counts of draws, restarts
#' and grid points. A length-2 or fractional count otherwise reaches
#' `seq_len()` or `numeric()` as a size, where the message names neither
#' the argument nor the function the user called.
#'
#' @noRd
check_count <- function(x, arg, min = 0L) {
  ok <- is.numeric(x) && length(x) == 1L && is.finite(x) &&
    x == round(x) && x >= min
  if (!ok) {
    stop("`", arg, "` must be a single whole number of at least ", min,
         ", not ", arg_desc(x), call. = FALSE)
  }
  invisible(as.integer(x))
}

#' A single number strictly inside (0, 1): every coverage argument
#' (`level`, `prob`).
#'
#' @noRd
check_probability <- function(x, arg) {
  if (!is.numeric(x) || length(x) != 1L || !is.finite(x) ||
        x <= 0 || x >= 1) {
    stop("`", arg, "` must be a single number strictly between 0 and 1, ",
         "not ", arg_desc(x), call. = FALSE)
  }
  invisible(as.numeric(x))
}

#' A single finite positive number: scale parameters and tolerances.
#'
#' @noRd
check_positive <- function(x, arg) {
  if (!is.numeric(x) || length(x) != 1L || !is.finite(x) || x <= 0) {
    stop("`", arg, "` must be a single finite positive number, not ",
         arg_desc(x), call. = FALSE)
  }
  invisible(as.numeric(x))
}

#' A single finite number with no sign constraint: the location
#' arguments of the prior constructors.
#'
#' @noRd
check_number <- function(x, arg) {
  if (!is.numeric(x) || length(x) != 1L || !is.finite(x)) {
    stop("`", arg, "` must be a single finite number, not ", arg_desc(x),
         call. = FALSE)
  }
  invisible(as.numeric(x))
}

#' A named list, for the argument slots keyed by parameter name. An
#' unnamed value used to be iterated over an empty `names()` and so
#' ignored in silence, and the fit then ran from the default and
#' reported it as the user's.
#'
#' @noRd
check_named_list <- function(x, arg, example) {
  # every element must carry a name: a PARTIALLY named list would have
  # its unnamed elements silently dropped by the by-name consumers
  if (!is.list(x) ||
        (length(x) && (is.null(names(x)) || !all(nzchar(names(x)))))) {
    stop("`", arg, "` must be a named list, e.g. ", example, ", not ",
         arg_desc(x), call. = FALSE)
  }
  invisible(x)
}

#' A single string drawn from a fixed set. `match.arg()` covers the
#' arguments whose default IS the set; this covers the ones whose
#' default is one value of it, where `match.arg()` has nothing to match
#' against and any string is accepted.
#'
#' @noRd
check_string_choice <- function(x, arg, choices) {
  if (!is.character(x) || length(x) != 1L || is.na(x) ||
        !x %in% choices) {
    stop("`", arg, "` must be one of ",
         paste0("\"", choices, "\"", collapse = ", "), ", not ",
         arg_desc(x), call. = FALSE)
  }
  invisible(x)
}

#' Split `a + b + c` into list(a, b, c), left-associatively.
#'
#' @noRd
split_plus <- function(expr) {
  if (is.call(expr) && identical(expr[[1]], as.name("+"))) {
    c(split_plus(expr[[2]]), list(expr[[3]]))
  } else {
    list(expr)
  }
}

#' The `"response.dpar"` key that names one linear predictor throughout
#' the package. Written once so every table that is indexed by linear
#' predictor agrees on the separator.
#'
#' @noRd
linpred_key <- function(resp, dpar) paste(resp, dpar, sep = ".")

#' Factor with numeric-coded levels for coordinate covariance structures
#'
#' `ou()` and the spatial structures (`exp()`, `gau()`, `mat()`) need
#' the positions of the term levels. `num_factor(x)` (one dimension) or
#' `num_factor(x, y)` (planar coordinates) encodes them in the level
#' labels the same way `glmmTMB::numFactor()` does, so factors created
#' by either function work.
#'
#' @param x Numeric positions (times, coordinates).
#' @param y Optional second coordinate.
#' @return A factor whose levels encode the unique positions.
#' @examples
#' # unequally spaced observation times, kept as distances
#' num_factor(c(0, 1.5, 4))
#'
#' # planar coordinates for a spatial covariance
#' levels(num_factor(rep(1:3, 3), rep(1:3, each = 3)))
#'
#' # ou() reads the distances out of the level labels; a plain factor
#' # would only give it an ordering
#' set.seed(1)
#' tim <- c(0, 1, 1.5, 3)
#' n_g <- 40
#' S <- 0.9^2 * exp(-1.2 * abs(outer(tim, tim, "-")))
#' u <- matrix(rnorm(n_g * length(tim)), n_g) %*% chol(S)
#' dd <- data.frame(
#'   y = 1 + as.vector(t(u)) + rnorm(n_g * length(tim), 0, 0.4),
#'   g = factor(rep(seq_len(n_g), each = length(tim))),
#'   tim = num_factor(rep(tim, n_g))
#' )
#' fit <- frm(bf(y ~ 1 + ou(tim + 0 | g)) + gaussian(), data = dd)
#' round(VarCorr(fit)$g$cor[, "Estimate", ], 3)
#' @export
num_factor <- function(x, y = NULL) {
  if (is.null(y)) {
    ux <- sort(unique(as.numeric(x)))
    return(factor(sprintf("(%g)", as.numeric(x)),
                  levels = sprintf("(%g)", ux)))
  }
  lab <- sprintf("(%g,%g)", as.numeric(x), as.numeric(y))
  ord <- order(as.numeric(x), as.numeric(y))
  factor(lab, levels = unique(lab[ord]))
}

#' Recover coordinates from num_factor / glmmTMB::numFactor levels
#' (vector for 1-D, matrix for 2-D), or from plainly numeric labels.
#' Errors when a level does not encode a position.
#'
#' @noRd
parse_num_levels <- function(lv) {
  s <- gsub("[()]", "", lv)
  if (any(grepl(",", s, fixed = TRUE))) {
    parts <- strsplit(s, ",", fixed = TRUE)
    out <- t(vapply(parts, function(p) suppressWarnings(as.numeric(p)),
                    numeric(length(parts[[1]]))))
    if (anyNA(out)) {
      stop("Levels must encode numeric coordinates like '(1,2)'; build ",
           "the factor with num_factor(x, y)", call. = FALSE)
    }
    return(out)
  }
  out <- suppressWarnings(as.numeric(s))
  if (anyNA(out)) {
    stop("Levels must encode numeric positions on one axis; build the ",
         "factor with num_factor(x)", call. = FALSE)
  }
  out
}

#' The verdict both covariance paths give when the standard errors come
#' back non-finite. It is a separate verdict from "the Hessian is not
#' positive definite", because the two do not coincide: sdreport reports
#' pdHess from a Cholesky, which succeeds on a matrix LAPACK's solver
#' then refuses as computationally singular (reciprocal condition number
#' below its tolerance), and cov.fixed comes back filled with NaN on a
#' fit that converged with a small gradient and a positive definite
#' Hessian. diagnose() names the parameters; nothing else did.
#'
#' The verdict is a property of the FIT, not of the call, so it is worth
#' saying once per fit: vcov(), summary(), confint() and predict() all
#' reach it on the same degenerate object, and frm_multiple() and
#' influence() loop over those. The flag lives on the fit's cache
#' environment, which is replaced whenever the fit is re-estimated, so a
#' refit that is still degenerate warns again.
#'
#' @noRd
warn_nonfinite_cov <- function(cache = NULL, fit = NULL) {
  if (is.environment(cache)) {
    if (isTRUE(cache$warned_nonfinite_cov)) return(invisible(NULL))
    cache$warned_nonfinite_cov <- TRUE
  }
  # "probably overparameterized" is a guess, and the wrong one when the
  # likelihood is flat in a direction. Given the fit, measure instead.
  note <- if (is.null(fit)) "" else flat_par_note(fit)
  warning("Some standard errors are not finite, so vcov() and ",
          "summary() report NaN: the covariance could not be recovered ",
          "from the Hessian",
          if (nzchar(note)) note else {
            " and the model is probably overparameterized"
          },
          ". diagnose() names the offending ",
          "parameters; see the 'Convergence problems' section of ",
          "vignette('diagnostics')", call. = FALSE)
}

#' Invert the joint precision of a REML / profile fit.
#'
#' The ML branch of vcov() reads an already-inverted cov.fixed, which
#' sdreport fills with NaN when the Hessian is singular; inverting by
#' hand here would instead throw a raw LAPACK message that names neither
#' the model nor the remedy. Degrade the same way ML does: NaN entries
#' plus one warning pointing at diagnose().
#'
#' @noRd
solve_joint_precision <- function(Q, cache = NULL, fit = NULL) {
  # Matrix::solve, not base solve: the joint precision of a GLMM is
  # sparse and often badly conditioned, and base's dense LAPACK path
  # refuses it on a reciprocal-condition-number test that the sparse
  # Cholesky has no reason to apply. Rejecting an invertible precision
  # would turn every standard error on such a fit into NaN.
  # CHOLMOD narrates a failed factorization from C before the error
  # reaches R; the message below is the one that names the remedy
  V <- try(suppressWarnings(Matrix::solve(Q)), silent = TRUE)
  if (!inherits(V, "try-error")) {
    # A precision matrix can factor and still invert into non-finite
    # entries. That is the same verdict as a failed solve() from the
    # user's side - NaN standard errors - so it earns the same warning,
    # or a profile fit reports NaN as quietly as the ML branch used to.
    # The x slot is the stored values of a Matrix; a base matrix has no
    # such slot and is read whole.
    xs <- tryCatch(V@x, error = function(e) as.numeric(as.matrix(V)))
    if (any(!is.finite(xs))) warn_nonfinite_cov(cache, fit)
    return(V)
  }
  if (is.environment(cache)) {
    # same once-per-fit rule as warn_nonfinite_cov(): a singular joint
    # precision stays singular for every caller that asks
    if (isTRUE(cache$warned_singular_precision)) {
      return(matrix(NaN, nrow(Q), ncol(Q), dimnames = dimnames(Q)))
    }
    cache$warned_singular_precision <- TRUE
  }
  note <- if (is.null(fit)) "" else flat_par_note(fit)
  warning("The joint precision matrix is singular, so standard errors ",
          "are NaN",
          if (nzchar(note)) note else {
            "; the model is probably overparameterized"
          },
          ". diagnose() names the offending parameter; see the ",
          "'Convergence problems' section of vignette('diagnostics')",
          call. = FALSE)
  matrix(NaN, nrow(Q), ncol(Q), dimnames = dimnames(Q))
}

#' One string key per coordinate row, used to match gp() prediction
#' positions against fitted positions. Defined once so frame assembly
#' and kriging can never disagree on the separator.
#'
#' @noRd
pos_rowkey <- function(M) {
  do.call(paste, c(as.data.frame(M), sep = "\r"))
}
